package com.instagram.quickpromotion.intf;

import kotlin.enums.EnumEntries;
import p000X.C22T;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes2.dex */
public final class QPTooltipAnchor {
    public static final /* synthetic */ EnumEntries A01;
    public static final /* synthetic */ QPTooltipAnchor[] A02;
    public static final QPTooltipAnchor A03;
    public static final QPTooltipAnchor A04;
    public static final QPTooltipAnchor A05;
    public static final QPTooltipAnchor A06;
    public static final QPTooltipAnchor A07;
    public static final QPTooltipAnchor A08;
    public static final QPTooltipAnchor A09;
    public static final QPTooltipAnchor A0A;
    public static final QPTooltipAnchor A0B;
    public static final QPTooltipAnchor A0C;
    public static final QPTooltipAnchor A0D;
    public static final QPTooltipAnchor A0E;
    public static final QPTooltipAnchor A0F;
    public static final QPTooltipAnchor A0G;
    public static final QPTooltipAnchor A0H;
    public static final QPTooltipAnchor A0I;
    public static final QPTooltipAnchor A0J;
    public static final QPTooltipAnchor A0K;
    public static final QPTooltipAnchor A0L;
    public static final QPTooltipAnchor A0M;
    public static final QPTooltipAnchor A0N;
    public static final QPTooltipAnchor A0O;
    public static final QPTooltipAnchor A0P;
    public static final QPTooltipAnchor A0Q;
    public static final QPTooltipAnchor A0R;
    public static final QPTooltipAnchor A0S;
    public static final QPTooltipAnchor A0T;
    public static final QPTooltipAnchor A0U;
    public static final QPTooltipAnchor A0V;
    public static final QPTooltipAnchor A0W;
    public static final QPTooltipAnchor A0X;
    public static final QPTooltipAnchor A0Y;
    public static final QPTooltipAnchor A0Z;
    public static final QPTooltipAnchor A0a;
    public static final QPTooltipAnchor A0b;
    public static final QPTooltipAnchor A0c;
    public static final QPTooltipAnchor A0d;
    public static final QPTooltipAnchor A0e;
    public static final QPTooltipAnchor A0f;
    public static final QPTooltipAnchor A0g;
    public static final QPTooltipAnchor A0h;
    public static final QPTooltipAnchor A0i;
    public static final QPTooltipAnchor A0j;
    public static final QPTooltipAnchor A0k;
    public static final QPTooltipAnchor A0l;
    public static final QPTooltipAnchor A0m;
    public static final QPTooltipAnchor A0n;
    public static final QPTooltipAnchor A0o;
    public static final QPTooltipAnchor A0p;
    public static final QPTooltipAnchor A0q;
    public static final QPTooltipAnchor A0r;
    public static final QPTooltipAnchor A0s;
    public static final QPTooltipAnchor A0t;
    public static final QPTooltipAnchor A0u;
    public static final QPTooltipAnchor A0v;
    public static final QPTooltipAnchor A0w;
    public static final QPTooltipAnchor A0x;
    public static final QPTooltipAnchor A0y;
    public static final QPTooltipAnchor A0z;
    public static final QPTooltipAnchor A10;
    public static final QPTooltipAnchor A11;
    public static final QPTooltipAnchor A12;
    public static final QPTooltipAnchor A13;
    public static final QPTooltipAnchor A14;
    public static final QPTooltipAnchor A15;
    public static final QPTooltipAnchor A16;
    public static final QPTooltipAnchor A17;
    public static final QPTooltipAnchor A18;
    public static final QPTooltipAnchor A19;
    public static final QPTooltipAnchor A1A;
    public static final QPTooltipAnchor A1B;
    public static final QPTooltipAnchor A1C;
    public static final QPTooltipAnchor A1D;
    public static final QPTooltipAnchor A1E;
    public static final QPTooltipAnchor A1F;
    public static final QPTooltipAnchor A1G;
    public static final QPTooltipAnchor A1H;
    public static final QPTooltipAnchor A1I;
    public static final QPTooltipAnchor A1J;
    public static final QPTooltipAnchor A1K;
    public static final QPTooltipAnchor A1L;
    public static final QPTooltipAnchor A1M;
    public static final QPTooltipAnchor A1N;
    public static final QPTooltipAnchor A1O;
    public static final QPTooltipAnchor A1P;
    public static final QPTooltipAnchor A1Q;
    public static final QPTooltipAnchor A1R;
    public static final QPTooltipAnchor A1S;
    public static final QPTooltipAnchor A1T;
    public static final QPTooltipAnchor A1U;
    public static final QPTooltipAnchor A1V;
    public static final QPTooltipAnchor A1W;
    public static final QPTooltipAnchor A1X;
    public static final QPTooltipAnchor A1Y;
    public final String A00;

    static {
        QPTooltipAnchor qPTooltipAnchor = new QPTooltipAnchor("DEFAULT_ANCHOR", 0, "default_anchor");
        A0L = qPTooltipAnchor;
        QPTooltipAnchor qPTooltipAnchor2 = new QPTooltipAnchor("ACTIVITY_FEED_FILTER_BUTTON", 1, "activity_feed_filter_button");
        A03 = qPTooltipAnchor2;
        QPTooltipAnchor qPTooltipAnchor3 = new QPTooltipAnchor("ADD_BANNERS_BUTTON", 2, "add_banners_button");
        A04 = qPTooltipAnchor3;
        QPTooltipAnchor qPTooltipAnchor4 = new QPTooltipAnchor("ADVANCED_SETTINGS_ROW", 3, "advanced_settings_row");
        A05 = qPTooltipAnchor4;
        QPTooltipAnchor qPTooltipAnchor5 = new QPTooltipAnchor("ADVANCED_SETTINGS_VIDEO_ROW", 4, "advanced_settings_video_row");
        A06 = qPTooltipAnchor5;
        QPTooltipAnchor qPTooltipAnchor6 = new QPTooltipAnchor("AI_AGENT_CALLING_BUTTON", 5, "ai_agent_calling_button");
        A07 = qPTooltipAnchor6;
        QPTooltipAnchor qPTooltipAnchor7 = new QPTooltipAnchor("AI_AGENT_VIDEO_CALLING_BUTTON", 6, "ai_agent_video_calling_button");
        A08 = qPTooltipAnchor7;
        QPTooltipAnchor qPTooltipAnchor8 = new QPTooltipAnchor("BIO_INTERESTS_FIRST_CELL", 7, "bio_interests_first_cell");
        A09 = qPTooltipAnchor8;
        QPTooltipAnchor qPTooltipAnchor9 = new QPTooltipAnchor("CAPTION_BOX", 8, "caption_box");
        A0B = qPTooltipAnchor9;
        QPTooltipAnchor qPTooltipAnchor10 = new QPTooltipAnchor("CAROUSEL_BUMPING", 9, "carousel_bumping");
        A0C = qPTooltipAnchor10;
        QPTooltipAnchor qPTooltipAnchor11 = new QPTooltipAnchor("CLAIM_LOCATION_PAGE_BUTTON", 10, "claim_location_page_button");
        A0D = qPTooltipAnchor11;
        QPTooltipAnchor qPTooltipAnchor12 = new QPTooltipAnchor("CLIPS_LIKE_BUTTON", 11, "clips_like_button");
        A0F = qPTooltipAnchor12;
        QPTooltipAnchor qPTooltipAnchor13 = new QPTooltipAnchor("CLIPS_TAB_ICON", 12, "reels_tab");
        A0G = qPTooltipAnchor13;
        QPTooltipAnchor qPTooltipAnchor14 = new QPTooltipAnchor("CLIPS_VIEWER_OVERFLOW_ICON_WITH_INSIGHTS", 13, "clips_overflow_with_insights");
        A0H = qPTooltipAnchor14;
        QPTooltipAnchor qPTooltipAnchor15 = new QPTooltipAnchor("CLIPS_CONTENT_APPRECIATION_BUTTON", 14, "clips_send_gift_button");
        A0E = qPTooltipAnchor15;
        QPTooltipAnchor qPTooltipAnchor16 = new QPTooltipAnchor("CONVERT_TO_CREATOR_ACCOUNT_BUTTON", 15, "convert_to_creator_account_button");
        A0J = qPTooltipAnchor16;
        QPTooltipAnchor qPTooltipAnchor17 = new QPTooltipAnchor("CREATE_POST_ICON", 16, "create_post_icon");
        A0K = qPTooltipAnchor17;
        QPTooltipAnchor qPTooltipAnchor18 = new QPTooltipAnchor("DESTINATIONS_SUPPORT_BUTTON", 17, "destinations_support_button");
        A0M = qPTooltipAnchor18;
        QPTooltipAnchor qPTooltipAnchor19 = new QPTooltipAnchor("DIRECT_ICON", 18, "direct_icon");
        A0N = qPTooltipAnchor19;
        QPTooltipAnchor qPTooltipAnchor20 = new QPTooltipAnchor("DIRECT_ICON_TAB_BAR", 19, "direct_icon_tab_bar");
        A0O = qPTooltipAnchor20;
        QPTooltipAnchor qPTooltipAnchor21 = new QPTooltipAnchor("DIRECT_REPLY_TO_AUTHOR_BUTTON", 20, "direct_reply_to_author_button");
        A0P = qPTooltipAnchor21;
        QPTooltipAnchor qPTooltipAnchor22 = new QPTooltipAnchor("EDIT_LOCATION_PAGE_INFO_BUTTON", 21, "edit_location_page_info_button");
        A0Q = qPTooltipAnchor22;
        QPTooltipAnchor qPTooltipAnchor23 = new QPTooltipAnchor("EDIT_PROFILE_BUTTON", 22, "edit_profile_button");
        A0R = qPTooltipAnchor23;
        QPTooltipAnchor qPTooltipAnchor24 = new QPTooltipAnchor("EXPLORE_GRID_1X2", 23, "explore_grid_1x2");
        A0S = qPTooltipAnchor24;
        QPTooltipAnchor qPTooltipAnchor25 = new QPTooltipAnchor("EXPLORE_POPULAR_REELS_PILL", 24, "explore_popular_reels_pill");
        A0T = qPTooltipAnchor25;
        QPTooltipAnchor qPTooltipAnchor26 = new QPTooltipAnchor("EXPLORE_SEARCH_BAR_META_AI_BUTTON", 25, "search_bar_meta_ai_button");
        A0U = qPTooltipAnchor26;
        QPTooltipAnchor qPTooltipAnchor27 = new QPTooltipAnchor("EXPLORE_TAB", 26, "explore_tab");
        A0V = qPTooltipAnchor27;
        QPTooltipAnchor qPTooltipAnchor28 = new QPTooltipAnchor("FUNDRAISER_STICKER", 27, "fundraiser_sticker");
        A0W = qPTooltipAnchor28;
        QPTooltipAnchor qPTooltipAnchor29 = new QPTooltipAnchor("HASHTAG_FOLLOW_BUTTON", 28, "hashtag_follow_button");
        A0X = qPTooltipAnchor29;
        QPTooltipAnchor qPTooltipAnchor30 = new QPTooltipAnchor("IGTV_PIN_PRODUCTS_BUTTON", 29, "igtv_pin_products_button");
        A0b = qPTooltipAnchor30;
        QPTooltipAnchor qPTooltipAnchor31 = new QPTooltipAnchor("INBOX_BOTTOM_TAB", 30, "inbox_bottom_tab");
        A0c = qPTooltipAnchor31;
        QPTooltipAnchor qPTooltipAnchor32 = new QPTooltipAnchor("INBOX_FOLDER_AD_RESPONSES", 31, "inbox_folder_ad_responses");
        A0e = qPTooltipAnchor32;
        QPTooltipAnchor qPTooltipAnchor33 = new QPTooltipAnchor("INBOX_FILTER_ICON", 32, "inbox_filter_icon");
        A0d = qPTooltipAnchor33;
        QPTooltipAnchor qPTooltipAnchor34 = new QPTooltipAnchor("INBOX_VIDEO_CALL_ICON", 33, "inbox_video_call_icon");
        A0l = qPTooltipAnchor34;
        QPTooltipAnchor qPTooltipAnchor35 = new QPTooltipAnchor("INBOX_MESSAGE_ADS_ICON", 34, "inbox_message_ads_icon");
        A0f = qPTooltipAnchor35;
        QPTooltipAnchor qPTooltipAnchor36 = new QPTooltipAnchor("INBOX_OPTIONS_MENU_ICON", 35, "inbox_options_menu_icon");
        A0g = qPTooltipAnchor36;
        QPTooltipAnchor qPTooltipAnchor37 = new QPTooltipAnchor("INBOX_SEARCH_BAR", 36, "inbox_search_bar");
        A0h = qPTooltipAnchor37;
        QPTooltipAnchor qPTooltipAnchor38 = new QPTooltipAnchor("INBOX_THREAD_AUDIO_CALL_ICON", 37, "inbox_thread_audio_call_icon");
        A0i = qPTooltipAnchor38;
        QPTooltipAnchor qPTooltipAnchor39 = new QPTooltipAnchor("INBOX_TRAY_COLLAPSE_BUTTON", 38, "inbox_tray_collapse_button");
        A0j = qPTooltipAnchor39;
        QPTooltipAnchor qPTooltipAnchor40 = new QPTooltipAnchor("INBOX_TRAY_EXPAND_BUTTON", 39, "inbox_tray_expand_button");
        A0k = qPTooltipAnchor40;
        QPTooltipAnchor qPTooltipAnchor41 = new QPTooltipAnchor("KIRBY_THREAD_SETTINGS_BUTTON", 40, "kirby_thread_settings_button");
        A0m = qPTooltipAnchor41;
        QPTooltipAnchor qPTooltipAnchor42 = new QPTooltipAnchor("LIKE_BUTTON", 41, "like_button");
        A0n = qPTooltipAnchor42;
        QPTooltipAnchor qPTooltipAnchor43 = new QPTooltipAnchor("LIVE_CONSUMER_SHOPPING_BUTTON", 42, "live_consumer_shopping_button");
        A0o = qPTooltipAnchor43;
        QPTooltipAnchor qPTooltipAnchor44 = new QPTooltipAnchor("LIVE_CREATE_DETAILS_BUTTON", 43, "live_create_details_button");
        A0p = qPTooltipAnchor44;
        QPTooltipAnchor qPTooltipAnchor45 = new QPTooltipAnchor("LIVE_CREATE_FUNDRAISER_BUTTON", 44, "live_create_fundraiser_button");
        A0q = qPTooltipAnchor45;
        QPTooltipAnchor qPTooltipAnchor46 = new QPTooltipAnchor("LIVE_SCHEDULED_LIVE_CREATION_BUTTON", 45, "live_scheduled_live_creation_button");
        A0u = qPTooltipAnchor46;
        QPTooltipAnchor qPTooltipAnchor47 = new QPTooltipAnchor("LIVE_SCHEDULED_LIVE_MANAGEMENT_BUTTON", 46, "live_scheduled_live_management_button");
        A0v = qPTooltipAnchor47;
        QPTooltipAnchor qPTooltipAnchor48 = new QPTooltipAnchor("LIVE_CREATE_SHOPPING_BUTTON", 47, "live_create_shopping_button");
        A0r = qPTooltipAnchor48;
        QPTooltipAnchor qPTooltipAnchor49 = new QPTooltipAnchor("LIVE_CREATE_TITLE_BUTTON", 48, "live_create_title_button");
        A0s = qPTooltipAnchor49;
        QPTooltipAnchor qPTooltipAnchor50 = new QPTooltipAnchor("LIVE_CREATE_USER_PAY_BUTTON", 49, "live_create_user_pay_button");
        A0t = qPTooltipAnchor50;
        QPTooltipAnchor qPTooltipAnchor51 = new QPTooltipAnchor("LIVE_VIEWER_BADGES_CTA_BUTTON", 50, "live_viewer_badges_cta_button");
        A0x = qPTooltipAnchor51;
        QPTooltipAnchor qPTooltipAnchor52 = new QPTooltipAnchor("LIVE_SUBSCRIBE_BUTTON", 51, "live_subscribe_button");
        A0w = qPTooltipAnchor52;
        QPTooltipAnchor qPTooltipAnchor53 = new QPTooltipAnchor("MENU_ICON", 52, "menu_icon");
        A0z = qPTooltipAnchor53;
        QPTooltipAnchor qPTooltipAnchor54 = new QPTooltipAnchor("NEWS_TAB", 53, "news_tab");
        A10 = qPTooltipAnchor54;
        QPTooltipAnchor qPTooltipAnchor55 = new QPTooltipAnchor("PRIVACY_AND_SECURITY_BUTTON", 54, "privacy_and_security_button");
        A12 = qPTooltipAnchor55;
        QPTooltipAnchor qPTooltipAnchor56 = new QPTooltipAnchor("PROFILE_ACTIONS_ROW", 55, "profile_actions_row");
        A14 = qPTooltipAnchor56;
        QPTooltipAnchor qPTooltipAnchor57 = new QPTooltipAnchor("PROFILE_BANNER", 56, "profile_banner");
        A15 = qPTooltipAnchor57;
        QPTooltipAnchor qPTooltipAnchor58 = new QPTooltipAnchor("PROFILE_MUSIC_BANNER", 57, "profile_music_banner");
        A19 = qPTooltipAnchor58;
        QPTooltipAnchor qPTooltipAnchor59 = new QPTooltipAnchor("PROMOTIONS_CTA", 58, "promotions_cta");
        A1F = qPTooltipAnchor59;
        QPTooltipAnchor qPTooltipAnchor60 = new QPTooltipAnchor("PROFILE_CONTACT_OR_CALL_ICON", 59, "profile_contact_or_call_icon");
        A18 = qPTooltipAnchor60;
        QPTooltipAnchor qPTooltipAnchor61 = new QPTooltipAnchor("PROFILE_VIDEO_TAB", 60, "profile_video_tab");
        A1D = qPTooltipAnchor61;
        QPTooltipAnchor qPTooltipAnchor62 = new QPTooltipAnchor("PROFILE_PICTURE", 61, "profile_picture");
        A1A = qPTooltipAnchor62;
        QPTooltipAnchor qPTooltipAnchor63 = new QPTooltipAnchor("PROFILE_TITLE_BAR", 62, "profile_title_bar");
        A1C = qPTooltipAnchor63;
        QPTooltipAnchor qPTooltipAnchor64 = new QPTooltipAnchor("REEL_ITEM", 63, "reel_item");
        A1J = qPTooltipAnchor64;
        QPTooltipAnchor qPTooltipAnchor65 = new QPTooltipAnchor("REELS_SHARE_SHEET_ADVANCED_SETTINGS_ROW", 64, "reels_share_sheet_advanced_settings_row");
        A1H = qPTooltipAnchor65;
        QPTooltipAnchor qPTooltipAnchor66 = new QPTooltipAnchor("REELS_SHARE_SHEET_RECOMMEND_ON_FACEBOOK_ROW", 65, "reels_share_sheet_recommend_on_facebook_row");
        A1I = qPTooltipAnchor66;
        QPTooltipAnchor qPTooltipAnchor67 = new QPTooltipAnchor("SEARCH_ICON", 66, "search_icon");
        A1O = qPTooltipAnchor67;
        QPTooltipAnchor qPTooltipAnchor68 = new QPTooltipAnchor("HOME_HEADER_ACTIVITY_BUTTON", 67, "home_header_activity_button");
        A0Z = qPTooltipAnchor68;
        QPTooltipAnchor qPTooltipAnchor69 = new QPTooltipAnchor("HOME_HEADER_CREATE_BUTTON", 68, "home_header_create_button");
        A0a = qPTooltipAnchor69;
        QPTooltipAnchor qPTooltipAnchor70 = new QPTooltipAnchor("HOMECOMING_FOLLOWING_TAB", 69, "homecoming_following_tab");
        A0Y = qPTooltipAnchor70;
        QPTooltipAnchor qPTooltipAnchor71 = new QPTooltipAnchor("SAVE_ICON", 70, "save_icon");
        A1L = qPTooltipAnchor71;
        QPTooltipAnchor qPTooltipAnchor72 = new QPTooltipAnchor("SAVED_REPLIES_ITEM", 71, "saved_replies_item");
        A1K = qPTooltipAnchor72;
        QPTooltipAnchor qPTooltipAnchor73 = new QPTooltipAnchor("SCHOOL_DIRECTORY_INVITE_AIRPLANE", 72, "school_directory_invite_airplane");
        A1M = qPTooltipAnchor73;
        QPTooltipAnchor qPTooltipAnchor74 = new QPTooltipAnchor("SCHOOL_PROFILE_BANNER", 73, "school_profile_banner");
        A1N = qPTooltipAnchor74;
        QPTooltipAnchor qPTooltipAnchor75 = new QPTooltipAnchor("SHARE_COLLECTION_BUTTON", 74, "share_collection_button");
        A1P = qPTooltipAnchor75;
        QPTooltipAnchor qPTooltipAnchor76 = new QPTooltipAnchor("SHOP", 75, "Shop");
        A1Q = qPTooltipAnchor76;
        QPTooltipAnchor qPTooltipAnchor77 = new QPTooltipAnchor("SHOPPING_COLLECTION_ICON", 76, "shopping_collection_icon");
        A1R = qPTooltipAnchor77;
        QPTooltipAnchor qPTooltipAnchor78 = new QPTooltipAnchor("SHOPPING_ICON", 77, "shopping_icon");
        A1S = qPTooltipAnchor78;
        QPTooltipAnchor qPTooltipAnchor79 = new QPTooltipAnchor("SHOPPING_SAVE_DIRECTORY_ICON", 78, "shopping_save_directory_icon");
        A1T = qPTooltipAnchor79;
        QPTooltipAnchor qPTooltipAnchor80 = new QPTooltipAnchor("STANDALONE_FUNDRAISER_IN_PROFILE", 79, "standalone_fundraiser_in_profile");
        A1U = qPTooltipAnchor80;
        QPTooltipAnchor qPTooltipAnchor81 = new QPTooltipAnchor("SWITCH_ACCOUNT", 80, "switch_account");
        A1V = qPTooltipAnchor81;
        QPTooltipAnchor qPTooltipAnchor82 = new QPTooltipAnchor("TAG_PRODUCTS_ROW", 81, "tag_products_row");
        A1W = qPTooltipAnchor82;
        QPTooltipAnchor qPTooltipAnchor83 = new QPTooltipAnchor("PROFILE_BOB_LABEL", 82, "profile_bob_label");
        A16 = qPTooltipAnchor83;
        QPTooltipAnchor qPTooltipAnchor84 = new QPTooltipAnchor("PROFILE_TAB", 83, "profile_tab");
        A1B = qPTooltipAnchor84;
        QPTooltipAnchor qPTooltipAnchor85 = new QPTooltipAnchor("MEDIA_OPTIONS_ICON", 84, "media_options");
        A0y = qPTooltipAnchor85;
        QPTooltipAnchor qPTooltipAnchor86 = new QPTooltipAnchor("PROMOTE_CTA", 85, "promote_cta");
        A1E = qPTooltipAnchor86;
        QPTooltipAnchor qPTooltipAnchor87 = new QPTooltipAnchor("PRIVATE_REELS_SHOW_ON_PROFILE_ROW", 86, "private_reels_show_on_profile_row");
        A13 = qPTooltipAnchor87;
        QPTooltipAnchor qPTooltipAnchor88 = new QPTooltipAnchor("PUBLIC_REELS_SHOW_ON_PROFILE_ROW", 87, "public_reels_show_on_profile_row");
        A1G = qPTooltipAnchor88;
        QPTooltipAnchor qPTooltipAnchor89 = new QPTooltipAnchor("VIDEO_CALL_FACE_FILTER", 88, "face_filters_button");
        A1Y = qPTooltipAnchor89;
        QPTooltipAnchor qPTooltipAnchor90 = new QPTooltipAnchor("CONTENT_FUNDING_REELS_ROW", 89, "content_funding_reels_row");
        A0I = qPTooltipAnchor90;
        QPTooltipAnchor qPTooltipAnchor91 = new QPTooltipAnchor("BONUSES_REELS_ROW", 90, "bonuses_reels_row");
        A0A = qPTooltipAnchor91;
        QPTooltipAnchor qPTooltipAnchor92 = new QPTooltipAnchor("PENDING_INBOX_RANKING_DROPDOWN", 91, "pending_inbox_ranking_dropdown");
        A11 = qPTooltipAnchor92;
        QPTooltipAnchor qPTooltipAnchor93 = new QPTooltipAnchor("THREAD_NAME", 92, "thread_name");
        A1X = qPTooltipAnchor93;
        QPTooltipAnchor qPTooltipAnchor94 = new QPTooltipAnchor("PROFILE_CARD_EDIT_BUTTON", 93, "profile_card_edit_button");
        A17 = qPTooltipAnchor94;
        QPTooltipAnchor qPTooltipAnchor95 = new QPTooltipAnchor("PROFILE_HIGHLIGHTS_SUBTAB_BUTTON", 94, "profile_highlights_subtab_button");
        QPTooltipAnchor[] qPTooltipAnchorArr = new QPTooltipAnchor[95];
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor, qPTooltipAnchor2, qPTooltipAnchor3, qPTooltipAnchor4, qPTooltipAnchor5, qPTooltipAnchor6, qPTooltipAnchor7, qPTooltipAnchor8, qPTooltipAnchor9, qPTooltipAnchor10, qPTooltipAnchor11, qPTooltipAnchor12, qPTooltipAnchor13, qPTooltipAnchor14, qPTooltipAnchor15, qPTooltipAnchor16, qPTooltipAnchor17, qPTooltipAnchor18, qPTooltipAnchor19, qPTooltipAnchor20, qPTooltipAnchor21, qPTooltipAnchor22, qPTooltipAnchor23, qPTooltipAnchor24, qPTooltipAnchor25, qPTooltipAnchor26, qPTooltipAnchor27}, 0, qPTooltipAnchorArr, 0, 27);
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor28, qPTooltipAnchor29, qPTooltipAnchor30, qPTooltipAnchor31, qPTooltipAnchor32, qPTooltipAnchor33, qPTooltipAnchor34, qPTooltipAnchor35, qPTooltipAnchor36, qPTooltipAnchor37, qPTooltipAnchor38, qPTooltipAnchor39, qPTooltipAnchor40, qPTooltipAnchor41, qPTooltipAnchor42, qPTooltipAnchor43, qPTooltipAnchor44, qPTooltipAnchor45, qPTooltipAnchor46, qPTooltipAnchor47, qPTooltipAnchor48, qPTooltipAnchor49, qPTooltipAnchor50, qPTooltipAnchor51, qPTooltipAnchor52, qPTooltipAnchor53, qPTooltipAnchor54}, 0, qPTooltipAnchorArr, 27, 27);
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor55, qPTooltipAnchor56, qPTooltipAnchor57, qPTooltipAnchor58, qPTooltipAnchor59, qPTooltipAnchor60, qPTooltipAnchor61, qPTooltipAnchor62, qPTooltipAnchor63, qPTooltipAnchor64, qPTooltipAnchor65, qPTooltipAnchor66, qPTooltipAnchor67, qPTooltipAnchor68, qPTooltipAnchor69, qPTooltipAnchor70, qPTooltipAnchor71, qPTooltipAnchor72, qPTooltipAnchor73, qPTooltipAnchor74, qPTooltipAnchor75, qPTooltipAnchor76, qPTooltipAnchor77, qPTooltipAnchor78, qPTooltipAnchor79, qPTooltipAnchor80, qPTooltipAnchor81}, 0, qPTooltipAnchorArr, 54, 27);
        System.arraycopy(new QPTooltipAnchor[]{qPTooltipAnchor82, qPTooltipAnchor83, qPTooltipAnchor84, qPTooltipAnchor85, qPTooltipAnchor86, qPTooltipAnchor87, qPTooltipAnchor88, qPTooltipAnchor89, qPTooltipAnchor90, qPTooltipAnchor91, qPTooltipAnchor92, qPTooltipAnchor93, qPTooltipAnchor94, qPTooltipAnchor95}, 0, qPTooltipAnchorArr, 81, 14);
        A02 = qPTooltipAnchorArr;
        A01 = C22T.A00(qPTooltipAnchorArr);
    }

    public QPTooltipAnchor(String str, int i, String str2) {
        this.A00 = str2;
    }

    public static QPTooltipAnchor valueOf(String str) {
        return (QPTooltipAnchor) Enum.valueOf(QPTooltipAnchor.class, str);
    }

    public static QPTooltipAnchor[] values() {
        return (QPTooltipAnchor[]) A02.clone();
    }
}
