package com.instagram.quickpromotion.intf;

import kotlin.enums.EnumEntries;
import kotlin.jvm.internal.DefaultConstructorMarker;
import p000X.C15640eG;
import p000X.C22T;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes2.dex */
public final class Trigger {
    public static final /* synthetic */ EnumEntries A02;
    public static final /* synthetic */ Trigger[] A03;
    public static final Trigger A04;
    public static final Trigger A05;
    public static final Trigger A06;
    public static final Trigger A07;
    public static final Trigger A08;
    public static final Trigger A09;
    public static final Trigger A0A;
    public static final Trigger A0B;
    public static final Trigger A0C;
    public static final Trigger A0D;
    public static final Trigger A0E;
    public static final Trigger A0F;
    public static final Trigger A0G;
    public static final Trigger A0H;
    public static final Trigger A0J;
    public static final Trigger A0K;
    public static final Trigger A0L;
    public static final Trigger A0M;
    public static final Trigger A0N;
    public static final Trigger A0O;
    public static final Trigger A0P;
    public static final Trigger A0Q;
    public static final Trigger A0R;
    public static final Trigger A0S;
    public static final Trigger A0T;
    public static final Trigger A0U;
    public static final Trigger A0V;
    public static final Trigger A0W;
    public static final Trigger A0X;
    public static final Trigger A0Y;
    public static final Trigger A0Z;
    public static final Trigger A0a;
    public static final Trigger A0b;
    public static final Trigger A0c;
    public static final Trigger A0d;
    public static final Trigger A0e;
    public static final Trigger A0f;
    public static final Trigger A0g;
    public static final Trigger A0h;
    public static final Trigger A0i;
    public static final Trigger A0j;
    public static final Trigger A0k;
    public static final Trigger A0l;
    public static final Trigger A0m;
    public static final Trigger A0n;
    public static final Trigger A0o;
    public static final Trigger A0p;
    public static final Trigger A0q;
    public static final Trigger A0r;
    public static final Trigger A0s;
    public static final Trigger A0t;
    public static final Trigger A0u;
    public static final Trigger A0v;
    public static final Trigger A0w;
    public static final Trigger A0x;
    public static final Trigger A0y;
    public static final Trigger A0z;
    public static final Trigger A10;
    public static final Trigger A11;
    public static final Trigger A12;
    public static final Trigger A13;
    public static final Trigger A14;
    public static final Trigger A15;
    public static final Trigger A16;
    public static final Trigger A17;
    public static final Trigger A18;
    public static final Trigger A19;
    public static final Trigger A1A;
    public static final Trigger A1B;
    public static final Trigger A1C;
    public static final Trigger A1D;
    public static final Trigger A1E;
    public static final Trigger A1F;
    public static final Trigger A1G;
    public static final Trigger A1H;
    public static final Trigger A1I;
    public static final Trigger A1J;
    public static final Trigger A1K;
    public static final Trigger A1L;
    public static final Trigger A1M;
    public static final Trigger A1N;
    public static final Trigger A1O;
    public static final Trigger A1P;
    public static final Trigger A1Q;
    public static final Trigger A1R;
    public static final Trigger A1S;
    public static final Trigger A1T;
    public static final Trigger A1U;
    public static final Trigger A1V;
    public static final Trigger A1W;
    public static final Trigger A1X;
    public static final Trigger A1Y;
    public static final Trigger A1Z;
    public static final Trigger A1a;
    public static final Trigger A1b;
    public static final Trigger A1c;
    public static final Trigger A1d;
    public static final Trigger A1e;
    public static final Trigger A1f;
    public static final Trigger A1g;
    public static final Trigger A1h;
    public static final Trigger A1i;
    public static final Trigger A1j;
    public static final Trigger A1k;
    public static final Trigger A1l;
    public static final Trigger A1m;
    public static final Trigger A1n;
    public static final Trigger A1o;
    public static final Trigger A1p;
    public static final Trigger A1q;
    public static final Trigger A1r;
    public static final Trigger A1s;
    public static final Trigger A1t;
    public static final Trigger A1u;
    public static final Trigger A1v;
    public static final Trigger A1w;
    public static final Trigger A1x;
    public static final Trigger A1y;
    public static final Trigger A1z;
    public static final Trigger A20;
    public static final Trigger A21;
    public static final Trigger A22;
    public static final Trigger A23;
    public static final Trigger A24;
    public static final Trigger A25;
    public static final Trigger A26;
    public static final Trigger A27;
    public static final Trigger A28;
    public static final Trigger A29;
    public static final Trigger A2A;
    public static final Trigger A2B;
    public static final Trigger A2C;
    public static final Trigger A2D;
    public static final Trigger A2E;
    public static final Trigger A2F;
    public static final Trigger A2G;
    public static final Trigger A2H;
    public static final Trigger A2I;
    public static final Trigger A2J;
    public static final Trigger A2L;
    public static final Trigger A2M;
    public static final Trigger A2N;
    public static final Trigger A2O;
    public static final Trigger A2P;
    public static final Trigger A2Q;
    public static final Trigger A2R;
    public static final Trigger A2S;
    public static final Trigger A2T;
    public static final Trigger A2U;
    public static final Trigger A2V;
    public static final Trigger A2W;
    public static final Trigger A2X;
    public static final Trigger A2Y;
    public static final Trigger A2Z;
    public static final Trigger A2a;
    public static final Trigger A2b;
    public static final Trigger A2c;
    public static final Trigger A2d;
    public static final Trigger A2e;
    public static final Trigger A2f;
    public static final Trigger A2g;
    public static final Trigger A2h;
    public static final Trigger A2i;
    public static final Trigger A2j;
    public static final Trigger A2k;
    public static final Trigger A2l;
    public static final Trigger A2m;
    public static final Trigger A2n;
    public static final Trigger A2o;
    public static final Trigger A2p;
    public static final Trigger A2q;
    public static final Trigger A2r;
    public static final Trigger A2s;
    public static final Trigger A2t;
    public static final Trigger A2u;
    public static final Trigger A2v;
    public static final Trigger A2w;
    public static final Trigger A2y;
    public static final Trigger A2z;
    public static final Trigger A30;
    public static final Trigger A31;
    public static final Trigger A32;
    public C15640eG A00;
    public final String A01;
    public static final Trigger A2x = new Trigger("SURVEY", "instagram_survey", 58);
    public static final Trigger A2K = new Trigger("LOGGED_IN_USER_ID_LOADED", "instagram_other_logged_in_user_id_loaded", 60);
    public static final Trigger A0I = new Trigger("BASEL_PROJECTS_HEADER", "edits_project_tab_view", 184);

    /* JADX WARN: Multi-variable type inference failed */
    static {
        int i = 2;
        DefaultConstructorMarker defaultConstructorMarker = null;
        A2V = new Trigger("PROFILE_HEADER", "instagram_profile_page", defaultConstructorMarker, 0, i, 0 == true ? 1 : 0);
        A2a = new Trigger("PROFILE_PROMPT", "instagram_profile_page_prompt", defaultConstructorMarker, 1, i, 0 == true ? 1 : 0);
        A2b = new Trigger("PROFILE_TOOLTIP", "instagram_self_profile_tooltip", defaultConstructorMarker, i, i, 0 == true ? 1 : 0);
        A2T = new Trigger("PROFILE_FLOATING_BANNER_PROMPT", "instagram_self_profile_floating_banner_prompt", defaultConstructorMarker, 3, i, 0 == true ? 1 : 0);
        A2W = new Trigger("PROFILE_OTHER_CHECKOUT_TOOLTIP", "instagram_other_checkout_profile_tooltip", defaultConstructorMarker, 4, i, 0 == true ? 1 : 0);
        A2X = new Trigger("PROFILE_OTHER_HEADER", "instagram_other_profile_page_header", defaultConstructorMarker, 5, i, 0 == true ? 1 : 0);
        A2Y = new Trigger("PROFILE_OTHER_PROMPT", "instagram_other_profile_page_prompt", defaultConstructorMarker, 6, i, 0 == true ? 1 : 0);
        A2Z = new Trigger("PROFILE_OTHER_TOOLTIP", "instagram_other_profile_tooltip", defaultConstructorMarker, 7, i, 0 == true ? 1 : 0);
        A2R = new Trigger("PROFILE_CLIPS_SUBTAB_TOOLTIP", "instagram_profile_clips_subtab_tooltip", defaultConstructorMarker, 8, i, 0 == true ? 1 : 0);
        A2S = new Trigger("PROFILE_ENTERED_FROM_MUSIC_NOTIF", "instagram_profile_landed_via_music_on_profile_notif", defaultConstructorMarker, 9, i, 0 == true ? 1 : 0);
        A2P = new Trigger("PROFESSIONAL_SETTING_TOOLTIP", "instagram_professional_setting_tooltip", defaultConstructorMarker, 10, i, 0 == true ? 1 : 0);
        A0g = new Trigger("FEED_BANNER", "instagram_feed_banner", defaultConstructorMarker, 11, i, 0 == true ? 1 : 0);
        A0h = new Trigger("FEED_BOTTOMSHEET", "instagram_feed_bottomsheet", defaultConstructorMarker, 12, i, 0 == true ? 1 : 0);
        A0i = new Trigger("FEED_COMMENT_HEADER", "instagram_feed_comment_header", defaultConstructorMarker, 13, i, 0 == true ? 1 : 0);
        A0k = new Trigger("FEED_HEADER", "instagram_feed_header", defaultConstructorMarker, 14, i, 0 == true ? 1 : 0);
        A0m = new Trigger("FEED_PROMPT", "instagram_feed_prompt", defaultConstructorMarker, 15, i, 0 == true ? 1 : 0);
        A0n = new Trigger("FEED_SHARING_HEADER", "instagram_feed_sharing_header", defaultConstructorMarker, 16, i, 0 == true ? 1 : 0);
        A0o = new Trigger("FEED_SHARING_PROMPT", "instagram_feed_sharing_prompt", defaultConstructorMarker, 17, i, 0 == true ? 1 : 0);
        A0p = new Trigger("FEED_TOOLTIP", "instagram_feed_tool_tip", defaultConstructorMarker, 18, i, 0 == true ? 1 : 0);
        A0t = new Trigger("HASHTAG_FEED_TOOLTIP", "instagram_hashtag_feed_tooltip", defaultConstructorMarker, 19, i, 0 == true ? 1 : 0);
        A0y = new Trigger("INBOX_HEADER", "instagram_inbox_header", defaultConstructorMarker, 20, i, 0 == true ? 1 : 0);
        A11 = new Trigger("INBOX_PROMPT", "instagram_inbox_prompt", defaultConstructorMarker, 21, i, 0 == true ? 1 : 0);
        A13 = new Trigger("INBOX_TOOLTIP", "instagram_inbox_tooltip", defaultConstructorMarker, 22, i, 0 == true ? 1 : 0);
        A12 = new Trigger("INBOX_SEARCH_HEADER", "instagram_inbox_search_header", defaultConstructorMarker, 23, i, 0 == true ? 1 : 0);
        A0x = new Trigger("INBOX_FILTER_TOOLTIP", "instagram_inbox_filter_tooltip", defaultConstructorMarker, 24, i, 0 == true ? 1 : 0);
        A0w = new Trigger("INBOX_CLOSE_FRIENDS_FILTER_APPLIED", "instagram_inbox_close_friends_filter_applied", defaultConstructorMarker, 25, i, 0 == true ? 1 : 0);
        A0z = new Trigger("INBOX_HIGH_BOTTOMSHEET", "instagram_aud_inbox_bottom_sheet_high", defaultConstructorMarker, 26, i, 0 == true ? 1 : 0);
        A10 = new Trigger("INBOX_LOW_BOTTOMSHEET", "instagram_aud_inbox_bottom_sheet_low", defaultConstructorMarker, 27, i, 0 == true ? 1 : 0);
        A0v = new Trigger("IGTV_VIEWER_PROMPT", "instagram_tv_viewer_end_of_first_video", defaultConstructorMarker, 28, i, 0 == true ? 1 : 0);
        A0u = new Trigger("IGTV_DISCOVER_HEADER", "instagram_tv_discover_header", defaultConstructorMarker, 29, i, 0 == true ? 1 : 0);
        A2B = new Trigger("LIVE_BADGES_TOOLTIP", "instagram_live_user_pay_tooltip", defaultConstructorMarker, 30, i, 0 == true ? 1 : 0);
        A2C = new Trigger("LIVE_BROADCASTER_SHOPPING_TOOLTIP", "instagram_live_broadcaster_shopping_tooltip", defaultConstructorMarker, 31, i, 0 == true ? 1 : 0);
        A2D = new Trigger("LIVE_COMPOSE", "instagram_live_compose", defaultConstructorMarker, 32, i, 0 == true ? 1 : 0);
        A2t = new Trigger("STORY_CREATION", "instagram_story_creation", defaultConstructorMarker, 33, i, 0 == true ? 1 : 0);
        A2E = new Trigger("LIVE_CREATION_TAB_ENTERED", "instagram_live_creation_tab_entered", defaultConstructorMarker, 34, i, 0 == true ? 1 : 0);
        A2F = new Trigger("LIVE_ROOMS_INTERSTITIAL", "instagram_live_rooms_interstitial", defaultConstructorMarker, 35, i, 0 == true ? 1 : 0);
        A2G = new Trigger("LIVE_ROOMS_TOOLTIP", "instagram_live_rooms_tooltip", defaultConstructorMarker, 36, i, 0 == true ? 1 : 0);
        A2H = new Trigger("LIVE_SHOPPING_TOOLTIP", "instagram_live_shopping_tooltip", defaultConstructorMarker, 37, i, 0 == true ? 1 : 0);
        A2I = new Trigger("LIVE_VIEWER_BADGES_CTA_TOOLTIP", "instagram_live_viewer_badges_tooltip", defaultConstructorMarker, 38, i, 0 == true ? 1 : 0);
        A05 = new Trigger("ACCOUNT_SETTING_TOOLTIP", "instagram_account_setting_tip", defaultConstructorMarker, 39, i, 0 == true ? 1 : 0);
        A07 = new Trigger("ACTIVITY_FEED_HEADER", "instagram_activity_feed_header", defaultConstructorMarker, 40, i, 0 == true ? 1 : 0);
        A08 = new Trigger("ACTIVITY_FEED_PROMPT", "instagram_activity_feed_prompt", defaultConstructorMarker, 41, i, 0 == true ? 1 : 0);
        A09 = new Trigger("ACTIVITY_FEED_TOOLTIP", "instagram_activity_feed_tooltip", defaultConstructorMarker, 42, i, 0 == true ? 1 : 0);
        A0J = new Trigger("BRANDED_CONTENT_AND_SHOPPING_ACTIVITY_FEED_HEADER", "instagram_branded_content_and_shopping_activity_feed", defaultConstructorMarker, 43, i, 0 == true ? 1 : 0);
        A0K = new Trigger("BRANDED_CONTENT_DISCLOSURE_FLOW_LOADED", "instagram_branded_content_disclosure_flow_loaded", defaultConstructorMarker, 44, i, 0 == true ? 1 : 0);
        A0L = new Trigger("BRANDED_CONTENT_SETTINGS_LOADED", "instagram_branded_content_settings_page_header", defaultConstructorMarker, 45, i, 0 == true ? 1 : 0);
        A0M = new Trigger("BRANDED_CONTENT_STORY_SHARED", "instagram_branded_content_story_shared", defaultConstructorMarker, 46, i, 0 == true ? 1 : 0);
        A0d = new Trigger("EXPLORE_HEADER", "instagram_explore_header", defaultConstructorMarker, 47, i, 0 == true ? 1 : 0);
        A0e = new Trigger("EXPLORE_PROMPT", "instagram_explore_prompt", defaultConstructorMarker, 48, i, 0 == true ? 1 : 0);
        A2n = new Trigger("SHOPPING_BUY_ON_INSTAGRAM_HEADER", "instagram_shopping_buy_on_instagram_header", defaultConstructorMarker, 49, i, 0 == true ? 1 : 0);
        A2p = new Trigger("SHOPPING_PDP_HEADER", "instagram_shopping_pdp_header", defaultConstructorMarker, 50, i, 0 == true ? 1 : 0);
        A2q = new Trigger("SHOPPING_SAVE_DIRECTORY_TOOLTIP", "instagram_shopping_save_directory_tooltip", defaultConstructorMarker, 51, i, 0 == true ? 1 : 0);
        A2Q = new Trigger("PROFILE_CARD_LOADED", "instagram_profile_card_loaded", defaultConstructorMarker, 52, i, 0 == true ? 1 : 0);
        A2e = new Trigger("SAVE_HOME_LOADED", "instagram_save_home_loaded", defaultConstructorMarker, 53, i, 0 == true ? 1 : 0);
        A2J = new Trigger("LOCATION_PAGE_INFO_LOADED", "instagram_location_page_info_loaded", defaultConstructorMarker, 54, i, 0 == true ? 1 : 0);
        A2k = new Trigger("SHARE_POST_LOADED", "instagram_share_post_loaded", defaultConstructorMarker, 55, i, 0 == true ? 1 : 0);
        A2m = new Trigger("SHARE_TO_FB_SWITCHED_ON", "instagram_share_to_fb_switched_on", defaultConstructorMarker, 56, i, 0 == true ? 1 : 0);
        A2l = new Trigger("SHARE_TO_FB_SWITCHED_OFF", "instagram_share_to_fb_switched_off", defaultConstructorMarker, 57, i, 0 == true ? 1 : 0);
        A04 = new Trigger("ACCOUNT_INSIGHTS_HEADER", "instagram_account_insights_header", defaultConstructorMarker, 59, i, 0 == true ? 1 : 0);
        A2v = new Trigger("STORY_VIEW_FUNDRAISER_STICKER_TOOLTIP", "instagram_fundraiser_sticker_tooltip", defaultConstructorMarker, 61, i, 0 == true ? 1 : 0);
        A2c = new Trigger("QUICK_PROMOTION_TEST", "instagram_quick_promotion_test", defaultConstructorMarker, 62, i, 0 == true ? 1 : 0);
        A0c = new Trigger("EDIT_PROFILE", "instagram_edit_profile_loaded", defaultConstructorMarker, 63, i, 0 == true ? 1 : 0);
        A1D = new Trigger("INSTAGRAM_EDIT_PROFILE_VISIT", "instagram_edit_profile_visit", defaultConstructorMarker, 64, i, 0 == true ? 1 : 0);
        A0R = new Trigger("CLOSE_FRIENDS_HEADER", "instagram_close_friends_header", defaultConstructorMarker, 65, i, 0 == true ? 1 : 0);
        A0b = new Trigger("DIRECT_THREAD_LOADED", "instagram_thread_loaded", defaultConstructorMarker, 66, i, 0 == true ? 1 : 0);
        A0Y = new Trigger("DIRECT_THREAD_HEADER_LOADED", "instagram_thread_header_loaded", defaultConstructorMarker, 67, i, 0 == true ? 1 : 0);
        A0Z = new Trigger("DIRECT_THREAD_HEADER_UPDATE_AFTER_CALL_ENDED", "instagram_thread_header_update_after_call_ended", defaultConstructorMarker, 68, i, 0 == true ? 1 : 0);
        A0a = new Trigger("DIRECT_THREAD_HEADER_UPDATE_VOICE_MESSAGE_SENT", "instagram_thread_header_update_voice_message_sent", defaultConstructorMarker, 69, i, 0 == true ? 1 : 0);
        A27 = new Trigger("IN_THREAD_MESSAGE_FOOTER", "instagram_message_footer", defaultConstructorMarker, 70, i, 0 == true ? 1 : 0);
        A28 = new Trigger("IN_THREAD_MESSAGE_FOOTER_DOUBLE_TAP_TO_HEART", "instagram_message_footer_double_tap_to_heart", defaultConstructorMarker, 71, i, 0 == true ? 1 : 0);
        A29 = new Trigger("IN_THREAD_MESSAGE_SENT", "instagram_direct_message_sent", defaultConstructorMarker, 72, i, 0 == true ? 1 : 0);
        A2A = new Trigger("IN_THREAD_SAVED_REPLY_MESSAGE_SENT", "instagram_direct_saved_reply_message_sent", defaultConstructorMarker, 73, i, 0 == true ? 1 : 0);
        A2r = new Trigger("SHOPPING_STORY_POSTED", "instagram_shopping_enable_auto_highlight_interstitial", defaultConstructorMarker, 74, i, 0 == true ? 1 : 0);
        A2M = new Trigger("NAVIGATION_TOOLTIP", "instagram_navigation_tooltip", defaultConstructorMarker, 75, i, 0 == true ? 1 : 0);
        A0f = new Trigger("FEATURED_PRODUCT_MEDIA_INTERSTITIAL", "instagram_featured_product_media_interstitial", defaultConstructorMarker, 76, i, 0 == true ? 1 : 0);
        A2u = new Trigger("STORY_VIEWER_PROMOTE_CTA_TOOLTIP", "instagram_story_viewer_promote_cta_tooltip", defaultConstructorMarker, 77, i, 0 == true ? 1 : 0);
        A0l = new Trigger("FEED_PROMOTE_CTA_TOOLTIP", "instagram_feed_promote_cta_tooltip", defaultConstructorMarker, 78, i, 0 == true ? 1 : 0);
        A0N = new Trigger("CLIPS_CREATION_SHARE_SHEET_LOADED", "instagram_clips_creation_share_sheet_loaded", defaultConstructorMarker, 79, i, 0 == true ? 1 : 0);
        A0Q = new Trigger("CLIPS_VIEWER_LOADED", "instagram_clips_viewer_loaded", defaultConstructorMarker, 80, i, 0 == true ? 1 : 0);
        A0P = new Trigger("CLIPS_VIEWER_FRIEND_LANE_LOADED", "instagram_clips_viewer_friend_lane_loaded", defaultConstructorMarker, 81, i, 0 == true ? 1 : 0);
        A0O = new Trigger("CLIPS_VIEWER_FOLLOWING_LANE_LOADED", "instagram_clips_viewer_following_lane_loaded", defaultConstructorMarker, 82, i, 0 == true ? 1 : 0);
        A2f = new Trigger("SELF_CLIPS_VIEWER_LOADED", "instagram_self_clips_viewer_loaded", defaultConstructorMarker, 83, i, 0 == true ? 1 : 0);
        A2z = new Trigger("VIDEO_CALL_LOADED", "instagram_video_call_loaded", defaultConstructorMarker, 84, i, 0 == true ? 1 : 0);
        A0q = new Trigger("FOLLOWING_FEED_LOADED", "instagram_following_feed_loaded", defaultConstructorMarker, 85, i, 0 == true ? 1 : 0);
        A30 = new Trigger("VIDEO_CALL_PEEK_PROMO_PROMPT", "instagram_video_call_peek_promo_prompt", defaultConstructorMarker, 86, i, 0 == true ? 1 : 0);
        A0j = new Trigger("FEED_COMPOSER_PROMPT", "instagram_feed_composer_prompt", defaultConstructorMarker, 87, i, 0 == true ? 1 : 0);
        A0X = new Trigger("DIRECT_STICKER_TRAY_HEADER", "instagram_direct_sticker_tray_header", defaultConstructorMarker, 88, i, 0 == true ? 1 : 0);
        A1U = new Trigger("INSTAGRAM_PENDING_INBOX_HEADER", "instagram_pending_inbox_header", defaultConstructorMarker, 89, i, 0 == true ? 1 : 0);
        A1V = new Trigger("INSTAGRAM_PENDING_INBOX_RANKING_DROPDOWN_TOOLTIP", "instagram_pending_inbox_ranking_dropdown_tooltip", defaultConstructorMarker, 90, i, 0 == true ? 1 : 0);
        A1N = new Trigger("INSTAGRAM_MEDIA_GALLERY", "instagram_media_gallery", defaultConstructorMarker, 91, i, 0 == true ? 1 : 0);
        A2o = new Trigger("SHOPPING_PDP_BANNER_PROMPT", "instagram_shopping_pdp_banner_prompt", defaultConstructorMarker, 92, i, 0 == true ? 1 : 0);
        A1E = new Trigger("INSTAGRAM_EXPLORE_2X2_GRID_LOADED", "instagram_explore_2x2_grid_loaded", defaultConstructorMarker, 93, i, 0 == true ? 1 : 0);
        A1F = new Trigger("INSTAGRAM_EXPLORE_META_AI_BOTTOMSHEET", "instagram_explore_meta_ai_bottomsheet", defaultConstructorMarker, 94, i, 0 == true ? 1 : 0);
        A1G = new Trigger("INSTAGRAM_EXPLORE_TOOLTIP", "instagram_explore_tooltip", defaultConstructorMarker, 95, i, 0 == true ? 1 : 0);
        A1d = new Trigger("INSTAGRAM_PROFILE_SHOW_FB_BANNER_ON_IG_TOOLTIP", "instagram_profile_show_fb_banner_on_ig_tooltip", defaultConstructorMarker, 96, i, 0 == true ? 1 : 0);
        A1v = new Trigger("INSTAGRAM_SHOPPING_PRODUCT_DETAILS_LOADED", "instagram_shopping_product_details_loaded", defaultConstructorMarker, 97, i, 0 == true ? 1 : 0);
        A2d = new Trigger("REEL_CREATED", "instagram_reel_created", defaultConstructorMarker, 98, i, 0 == true ? 1 : 0);
        A2g = new Trigger("SELF_REEL_VIEW", "instagram_self_reel_view", defaultConstructorMarker, 99, i, 0 == true ? 1 : 0);
        A2U = new Trigger("PROFILE_FOLLOW_BUTTON_CLICKED", "instagram_profile_follow_button_clicked", defaultConstructorMarker, 100, i, 0 == true ? 1 : 0);
        A2N = new Trigger("POST_CREATED", "instagram_post_created", defaultConstructorMarker, 101, i, 0 == true ? 1 : 0);
        A2O = new Trigger("POST_LIKE", "instagram_post_like", defaultConstructorMarker, 102, i, 0 == true ? 1 : 0);
        A2s = new Trigger("STORY_CREATED", "instagram_story_created", defaultConstructorMarker, 103, i, 0 == true ? 1 : 0);
        A0S = new Trigger("COMMENT_POSTED", "instagram_comment_posted", defaultConstructorMarker, 104, i, 0 == true ? 1 : 0);
        A0T = new Trigger("COMMENT_SHEET_OPEN", "instagram_comment_sheet_open", defaultConstructorMarker, 105, i, 0 == true ? 1 : 0);
        A2j = new Trigger("SHARE_COLLECTION_BUTTON_LOADED", "instagram_share_collection_button_loaded", defaultConstructorMarker, 106, i, 0 == true ? 1 : 0);
        A2i = new Trigger("SETTINGS_PAGE_PROMPT", "instagram_settings_page_prompt", defaultConstructorMarker, 107, i, 0 == true ? 1 : 0);
        A18 = new Trigger("INSTAGRAM_BOOST_TURNS_OFF_A_PLUS_AUDIENCE", "instagram_boost_turns_off_a_plus_audience", defaultConstructorMarker, 108, i, 0 == true ? 1 : 0);
        A1i = new Trigger("INSTAGRAM_REELS_MIDCARD_LOADED", "instagram_reels_midcard_loaded", defaultConstructorMarker, 109, i, 0 == true ? 1 : 0);
        A2w = new Trigger("SUBSCRIPTION_SETTINGS_LOADED", "instagram_subscriptions_settings_page_header", defaultConstructorMarker, 110, i, 0 == true ? 1 : 0);
        A1l = new Trigger("INSTAGRAM_SEARCH_BAR_META_AI_TOOLTIP", "instagram_search_bar_meta_ai_tooltip", defaultConstructorMarker, 111, i, 0 == true ? 1 : 0);
        A22 = new Trigger("INSTAGRAM_STORY_INSIGHTS_HEADER", "instagram_story_insights_header", defaultConstructorMarker, 112, i, 0 == true ? 1 : 0);
        A0B = new Trigger("AUDIO_PAGE_ENTRY_HEADER", "instagram_audio_page_entry_megaphone", defaultConstructorMarker, 113, i, 0 == true ? 1 : 0);
        A1f = new Trigger("INSTAGRAM_REELS_AUDIO_BROWSER_HEADER", "instagram_reels_audio_browser_header", defaultConstructorMarker, 114, i, 0 == true ? 1 : 0);
        A1e = new Trigger("INSTAGRAM_REELS_AUDIO_BROWSER_FOOTER", "instagram_reels_audio_browser_footer", defaultConstructorMarker, 115, i, 0 == true ? 1 : 0);
        A1w = new Trigger("INSTAGRAM_STORIES_AUDIO_BROWSER_HEADER", "instagram_stories_audio_browser_header", defaultConstructorMarker, 116, i, 0 == true ? 1 : 0);
        A1x = new Trigger("INSTAGRAM_STORIES_POSTCAPTURE_OVERFLOW_TOOLTIP", "instagram_stories_postcapture_overflow_tooltip", defaultConstructorMarker, 117, i, 0 == true ? 1 : 0);
        A1y = new Trigger("INSTAGRAM_STORIES_POSTCAPTURE_VIEW", "instagram_stories_postcapture_view", defaultConstructorMarker, 118, i, 0 == true ? 1 : 0);
        A1O = new Trigger("INSTAGRAM_MERGED_RESTYLE_EFFECTS_VIEW", "instagram_merged_restyle_effects_view", defaultConstructorMarker, 119, i, 0 == true ? 1 : 0);
        A1P = new Trigger("INSTAGRAM_MUSIC_IN_FEED_AUDIO_BROWSER_HEADER", "instagram_music_in_feed_audio_browser_header", defaultConstructorMarker, 120, i, 0 == true ? 1 : 0);
        A1Q = new Trigger("INSTAGRAM_NOTES_AUDIO_BROWSER_HEADER", "instagram_notes_audio_browser_header", defaultConstructorMarker, 121, i, 0 == true ? 1 : 0);
        A20 = new Trigger("INSTAGRAM_STORY_AUDIO_BROWSER_HEADER_DEPRECATED", "instagram_story_audio_browser_header", defaultConstructorMarker, 122, i, 0 == true ? 1 : 0);
        A24 = new Trigger("INSTAGRAM_TABBED_STORY_AUDIO_BROWSER_HEADER", "instagram_tabbed_story_audio_browser_header", defaultConstructorMarker, 123, i, 0 == true ? 1 : 0);
        A23 = new Trigger("INSTAGRAM_TABBED_STORY_AUDIO_BROWSER_FOOTER", "instagram_tabbed_story_audio_browser_footer", defaultConstructorMarker, 124, i, 0 == true ? 1 : 0);
        A1R = new Trigger("INSTAGRAM_NOTES_CREATION_VIEW", "instagram_notes_creation_view", defaultConstructorMarker, 125, i, 0 == true ? 1 : 0);
        A14 = new Trigger("INSTAGRAM_ADD_YOURS_PIVOT_PAGE_CONSUMER_ENTRY_MEGAPHONE", "instagram_add_yours_pivot_page_consumer_entry_megaphone", defaultConstructorMarker, 126, i, 0 == true ? 1 : 0);
        A15 = new Trigger("INSTAGRAM_ADD_YOURS_PIVOT_PAGE_CREATOR_ENTRY_MEGAPHONE", "instagram_add_yours_pivot_page_creator_entry_megaphone", defaultConstructorMarker, 127, i, 0 == true ? 1 : 0);
        A1t = new Trigger("INSTAGRAM_SELF_PROFILE_PAGE_CREATOR_INVITE_MEGAPHONE", "instagram_self_profile_page_creator_invite_megaphone", defaultConstructorMarker, 128, i, 0 == true ? 1 : 0);
        A0A = new Trigger("APP_FOREGROUND", "app_foreground", defaultConstructorMarker, 129, i, 0 == true ? 1 : 0);
        A2h = new Trigger("SESSION_START", "session_start", defaultConstructorMarker, 130, i, 0 == true ? 1 : 0);
        A17 = new Trigger("INSTAGRAM_AUD_STORY_REPLIES_BOTTOMSHEET_LOW", "instagram_aud_story_replies_bottomsheet_low", defaultConstructorMarker, 131, i, 0 == true ? 1 : 0);
        A16 = new Trigger("INSTAGRAM_AUD_SHARING_BOTTOMSHEET_LOW", "instagram_aud_sharing_bottomsheet_low", defaultConstructorMarker, 132, i, 0 == true ? 1 : 0);
        A06 = new Trigger("ACHIEVEMENTS_HUB_ENTERED", "instagram_achievements_hub_entered", defaultConstructorMarker, 133, i, 0 == true ? 1 : 0);
        A0s = new Trigger("FOLLOW_REQUEST_SCREEN_MEGAPHONE", "instagram_follow_requests_screen_megaphone", defaultConstructorMarker, 134, i, 0 == true ? 1 : 0);
        A1m = new Trigger("INSTAGRAM_SELF_FOLLOWERS_LIST_SCREEN_MEGAPHONE", "instagram_self_followers_list_screen_megaphone", defaultConstructorMarker, 135, i, 0 == true ? 1 : 0);
        A1n = new Trigger("INSTAGRAM_SELF_FOLLOWING_LIST_SCREEN_LOAD", "instagram_self_following_list_screen_load", defaultConstructorMarker, 136, i, 0 == true ? 1 : 0);
        A0r = new Trigger("FOLLOW_REQUEST_DENIED", "instagram_follow_request_denied", defaultConstructorMarker, 137, i, 0 == true ? 1 : 0);
        A2L = new Trigger("MESSAGE_REQUEST_ACTION_DIALOG", "instagram_message_request_action_dialog", defaultConstructorMarker, 138, i, 0 == true ? 1 : 0);
        A1c = new Trigger("INSTAGRAM_PROFILE_RESTRICTED", "instagram_profile_restricted", defaultConstructorMarker, 139, i, 0 == true ? 1 : 0);
        A1g = new Trigger("INSTAGRAM_REELS_CREATION_GALLERY_HEADER", "instagram_reels_creation_gallery_header", defaultConstructorMarker, 140, i, 0 == true ? 1 : 0);
        A1j = new Trigger("INSTAGRAM_REPORT_SUBMITTED", "instagram_report_submitted", defaultConstructorMarker, 141, i, 0 == true ? 1 : 0);
        A1u = new Trigger("INSTAGRAM_SELF_PROFILE_PAGE_OPEN_CAROUSEL_MEGAPHONE", "instagram_self_profile_page_open_carousel_megaphone", defaultConstructorMarker, 142, i, 0 == true ? 1 : 0);
        A1o = new Trigger("INSTAGRAM_SELF_MEDIA_OVERFLOW_MENU_TOOLTIP", "instagram_self_media_overflow_menu_tooltip", defaultConstructorMarker, 143, i, 0 == true ? 1 : 0);
        A1z = new Trigger("INSTAGRAM_STORY_ARCHIVE", "instagram_story_archive", defaultConstructorMarker, 144, i, 0 == true ? 1 : 0);
        A21 = new Trigger("INSTAGRAM_STORY_EDIT_HIGHLIGHT", "instagram_story_edit_highlight", defaultConstructorMarker, 145, i, 0 == true ? 1 : 0);
        A1k = new Trigger("INSTAGRAM_SCHOOL_DIRECTORY_INVITE_AIRPLANE_TOOLTIP", "instagram_school_directory_invite_airplane_tooltip", defaultConstructorMarker, 146, i, 0 == true ? 1 : 0);
        A0W = new Trigger("DIRECT_CHAT_META_AI_FIRST_USE", "igd_chat_meta_ai_first_use", defaultConstructorMarker, 147, i, 0 == true ? 1 : 0);
        A25 = new Trigger("INSTAGRAM_VIEW_FOLLOW_REQUESTS", "instagram_view_follow_requests", defaultConstructorMarker, 148, i, 0 == true ? 1 : 0);
        A26 = new Trigger("INSTAGRAM_VIEW_TAGGED_POSTS_GRID", "instagram_view_tagged_posts_grid", defaultConstructorMarker, 149, i, 0 == true ? 1 : 0);
        A0U = new Trigger("CROSSPOST_IG_FEED_TO_FB", "crosspost_ig_feed_to_fb", defaultConstructorMarker, 150, i, 0 == true ? 1 : 0);
        A0V = new Trigger("CROSSPOST_IG_STORY_TO_FB", "crosspost_ig_story_to_fb", defaultConstructorMarker, 151, i, 0 == true ? 1 : 0);
        A2y = new Trigger("TURN_AUTOMATIC_SHARE_TO_FB_SETTING_ON", "turn_automatic_share_to_fb_setting_on", defaultConstructorMarker, 152, i, 0 == true ? 1 : 0);
        A1r = new Trigger("INSTAGRAM_SELF_PROFILE_NEW_FB_ACCOUNT_LINKED_TOOLTIP", "instagram_self_profile_new_fb_account_linked_tooltip", defaultConstructorMarker, 153, i, 0 == true ? 1 : 0);
        A1q = new Trigger("INSTAGRAM_SELF_PROFILE_IG_CROSS_APP_NOTIF_TOOLTIP", "instagram_self_profile_ig_cross_app_notif_tooltip", defaultConstructorMarker, 154, i, 0 == true ? 1 : 0);
        A1s = new Trigger("INSTAGRAM_SELF_PROFILE_NEW_LOGGED_IN_IG_ACCOUNT_TOOLTIP", "instagram_self_profile_new_logged_in_ig_account_tooltip", defaultConstructorMarker, 155, i, 0 == true ? 1 : 0);
        A1C = new Trigger("INSTAGRAM_EDIT_PROFILE_LINKS_LOAD", "instagram_edit_profile_links_load", defaultConstructorMarker, 156, i, 0 == true ? 1 : 0);
        A1h = new Trigger("INSTAGRAM_REELS_CREATION_POST_CAPTURE_ENTERED", "instagram_reels_creation_post_capture_entered", defaultConstructorMarker, 157, i, 0 == true ? 1 : 0);
        A1S = new Trigger("INSTAGRAM_NOTIFICATION_FEED_BANNER", "instagram_notification_feed_banner", defaultConstructorMarker, 158, i, 0 == true ? 1 : 0);
        A1T = new Trigger("INSTAGRAM_NOTIFICATION_SETTINGS_BANNER", "instagram_notification_settings_banner", defaultConstructorMarker, 159, i, 0 == true ? 1 : 0);
        A1B = new Trigger("INSTAGRAM_DIRECT_INBOX_BANNER", "instagram_direct_inbox_banner", defaultConstructorMarker, 160, i, 0 == true ? 1 : 0);
        A1A = new Trigger("INSTAGRAM_CUTOUT_STICKER_CREATION_OPEN", "instagram_cutout_sticker_creation_open", defaultConstructorMarker, 161, i, 0 == true ? 1 : 0);
        A1W = new Trigger("INSTAGRAM_POST_FOLLOW_FROM_FOLLOWING_LIST_BANNER", "instagram_post_follow_from_following_list_banner", defaultConstructorMarker, 162, i, 0 == true ? 1 : 0);
        A1X = new Trigger("INSTAGRAM_POST_FOLLOW_FROM_NOTIF_FEED_BANNER", "instagram_post_follow_from_notif_feed_banner", defaultConstructorMarker, 163, i, 0 == true ? 1 : 0);
        A1Z = new Trigger("INSTAGRAM_PROFILE_HSCROLL_POST_FOLLOW", "instagram_profile_hscroll_post_follow", defaultConstructorMarker, 164, i, 0 == true ? 1 : 0);
        A1a = new Trigger("INSTAGRAM_PROFILE_NON_INTEREST_FOLLOW", "instagram_profile_non_interest_follow", defaultConstructorMarker, 165, i, 0 == true ? 1 : 0);
        A1L = new Trigger("INSTAGRAM_FRIEND_MAP_OPEN", "instagram_friend_map_open", defaultConstructorMarker, 166, i, 0 == true ? 1 : 0);
        A1J = new Trigger("INSTAGRAM_FRIEND_MAP_LOCATION_HUB_OPEN", "instagram_friend_map_location_hub_open", defaultConstructorMarker, 167, i, 0 == true ? 1 : 0);
        A1I = new Trigger("INSTAGRAM_FRIEND_MAP_AUDIENCE_SHEET_OPEN", "instagram_friend_map_audience_sheet_open", defaultConstructorMarker, 168, i, 0 == true ? 1 : 0);
        A1K = new Trigger("INSTAGRAM_FRIEND_MAP_MEDIA_OPEN", "instagram_friend_map_media_open", defaultConstructorMarker, 169, i, 0 == true ? 1 : 0);
        A1b = new Trigger("INSTAGRAM_PROFILE_OUTBOUND_FOLLOW_REQUEST", "instagram_profile_outbound_follow_request", defaultConstructorMarker, 170, i, 0 == true ? 1 : 0);
        A1H = new Trigger("INSTAGRAM_FEED_COMMENT_SORT_SELECTION_CHANGE", "instagram_feed_comment_sort_selection_change", defaultConstructorMarker, 171, i, 0 == true ? 1 : 0);
        A1M = new Trigger("INSTAGRAM_IGD_BIZ_THREAD_BUCKET_ENTERED", "instagram_igd_biz_thread_bucket_entered", defaultConstructorMarker, 172, i, 0 == true ? 1 : 0);
        A19 = new Trigger("INSTAGRAM_COMMENT_COMPOSER_FOCUS", "instagram_comment_composer_focus", defaultConstructorMarker, 173, i, 0 == true ? 1 : 0);
        A0C = new Trigger("BARCELONA_FEED_HEADER", "barcelona_feed_header", defaultConstructorMarker, 174, i, 0 == true ? 1 : 0);
        A0G = new Trigger("BARCELONA_PERMALINK_LOADED", "barcelona_permalink_loaded", defaultConstructorMarker, 175, i, 0 == true ? 1 : 0);
        A0E = new Trigger("BARCELONA_INTERSTITIAL", "barcelona_interstitial", defaultConstructorMarker, 176, i, 0 == true ? 1 : 0);
        A0H = new Trigger("BARCELONA_POST_SHARED", "barcelona_post_shared", defaultConstructorMarker, 177, i, 0 == true ? 1 : 0);
        A0F = new Trigger("BARCELONA_MESSAGE_REPLY", "barcelona_message_reply", defaultConstructorMarker, 178, i, 0 == true ? 1 : 0);
        A0D = new Trigger("BARCELONA_INBOX_OPEN", "barcelona_inbox_open", defaultConstructorMarker, 179, i, 0 == true ? 1 : 0);
        A1Y = new Trigger("INSTAGRAM_PROFILE_HIGHLIGHTS_SUBTAB_TOOLTIP", "instagram_profile_highlights_subtab_tooltip", defaultConstructorMarker, 180, i, 0 == true ? 1 : 0);
        A1p = new Trigger("INSTAGRAM_SELF_PROFILE_HIGHLIGHTS_SUBTAB_TOOLTIP", "instagram_self_profile_highlights_subtab_tooltip", defaultConstructorMarker, 181, i, 0 == true ? 1 : 0);
        A31 = new Trigger("WRITE_COMMUNITY_NOTE", "write_community_note", defaultConstructorMarker, 182, i, 0 == true ? 1 : 0);
        A32 = new Trigger("WRITE_COMMUNITY_NOTE_ONBOARDING_TOOLTIP", "write_community_note_onboarding_tooltip", defaultConstructorMarker, 183, i, 0 == true ? 1 : 0);
        Trigger[] A00 = A00();
        A03 = A00;
        A02 = C22T.A00(A00);
    }

    public Trigger(String str, String str2, int i) {
        this.A01 = str2;
    }

    public static final /* synthetic */ Trigger[] A00() {
        Trigger[] triggerArr = new Trigger[185];
        System.arraycopy(new Trigger[]{A2V, A2a, A2b, A2T, A2W, A2X, A2Y, A2Z, A2R, A2S, A2P, A0g, A0h, A0i, A0k, A0m, A0n, A0o, A0p, A0t, A0y, A11, A13, A12, A0x, A0w, A0z}, 0, triggerArr, 0, 27);
        System.arraycopy(new Trigger[]{A10, A0v, A0u, A2B, A2C, A2D, A2t, A2E, A2F, A2G, A2H, A2I, A05, A07, A08, A09, A0J, A0K, A0L, A0M, A0d, A0e, A2n, A2p, A2q, A2Q, A2e}, 0, triggerArr, 27, 27);
        System.arraycopy(new Trigger[]{A2J, A2k, A2m, A2l, A2x, A04, A2K, A2v, A2c, A0c, A1D, A0R, A0b, A0Y, A0Z, A0a, A27, A28, A29, A2A, A2r, A2M, A0f, A2u, A0l, A0N, A0Q}, 0, triggerArr, 54, 27);
        System.arraycopy(new Trigger[]{A0P, A0O, A2f, A2z, A0q, A30, A0j, A0X, A1U, A1V, A1N, A2o, A1E, A1F, A1G, A1d, A1v, A2d, A2g, A2U, A2N, A2O, A2s, A0S, A0T, A2j, A2i}, 0, triggerArr, 81, 27);
        System.arraycopy(new Trigger[]{A18, A1i, A2w, A1l, A22, A0B, A1f, A1e, A1w, A1x, A1y, A1O, A1P, A1Q, A20, A24, A23, A1R, A14, A15, A1t, A0A, A2h, A17, A16, A06, A0s}, 0, triggerArr, 108, 27);
        System.arraycopy(new Trigger[]{A1m, A1n, A0r, A2L, A1c, A1g, A1j, A1u, A1o, A1z, A21, A1k, A0W, A25, A26, A0U, A0V, A2y, A1r, A1q, A1s, A1C, A1h, A1S, A1T, A1B, A1A}, 0, triggerArr, 135, 27);
        System.arraycopy(new Trigger[]{A1W, A1X, A1Z, A1a, A1L, A1J, A1I, A1K, A1b, A1H, A1M, A19, A0C, A0G, A0E, A0H, A0F, A0D, A1Y, A1p, A31, A32, A0I}, 0, triggerArr, 162, 23);
        return triggerArr;
    }

    public static Trigger valueOf(String str) {
        return (Trigger) Enum.valueOf(Trigger.class, str);
    }

    public static Trigger[] values() {
        return (Trigger[]) A03.clone();
    }

    public /* synthetic */ Trigger(String str, String str2, DefaultConstructorMarker defaultConstructorMarker, int i, int i2, boolean z) {
        this.A01 = str2;
    }
}
