.class public LX/I9L;
.super Ljava/lang/Object;
.source ""


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:I

.field public A06:I

.field public A07:I

.field public A08:I

.field public A09:I

.field public A0A:I

.field public A0B:I

.field public A0C:I

.field public A0D:I

.field public A0E:I

.field public A0F:I

.field public A0G:J

.field public A0H:LX/JDm;

.field public A0I:LX/JDm;

.field public A0J:LX/JDr;

.field public A0K:LX/JEK;

.field public A0L:LX/JDx;

.field public A0M:LX/JDj;

.field public A0N:LX/JDq;

.field public A0O:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0P:LX/JE3;

.field public A0Q:LX/JDn;

.field public A0R:LX/JDh;

.field public A0S:LX/JE6;

.field public A0T:LX/JE6;

.field public A0U:LX/JDl;

.field public A0V:Ljava/lang/String;

.field public A0W:Ljava/util/HashMap;

.field public A0X:Ljava/util/Map;

.field public A0Y:Ljava/util/Set;

.field public A0Z:Ljava/util/Set;

.field public A0a:Ljava/util/Set;

.field public A0b:Ljava/util/Set;

.field public A0c:Ljava/util/Set;

.field public A0d:Ljava/util/Set;

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z

.field public A0m:Z


# direct methods
.method public constructor <init>()V
    .locals 6

    .line 0
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 1
    .line 2
    .line 3
    const/4 v2, 0x0

    .line 4
    sget-object v0, LX/JEM;->A00:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 5
    .line 6
    iput-object v0, p0, LX/I9L;->A0O:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 7
    .line 8
    const/4 v1, 0x1

    .line 9
    iput-boolean v2, p0, LX/I9L;->A0f:Z

    .line 10
    .line 11
    const/4 v0, 0x3

    .line 12
    iput v0, p0, LX/I9L;->A07:I

    .line 13
    .line 14
    const/16 v4, 0x7d0

    .line 15
    .line 16
    const-string v0, "ExoService"

    .line 17
    .line 18
    iput-object v0, p0, LX/I9L;->A0V:Ljava/lang/String;

    .line 19
    .line 20
    iput-boolean v1, p0, LX/I9L;->A0l:Z

    .line 21
    .line 22
    new-instance v0, LX/Hwv;

    .line 23
    .line 24
    invoke-direct {v0}, LX/Hwv;-><init>()V

    .line 25
    .line 26
    .line 27
    iget-boolean v1, v0, LX/Hwv;->A00:Z

    .line 28
    .line 29
    new-instance v0, LX/JDq;

    .line 30
    .line 31
    invoke-direct {v0, v1}, LX/JDq;-><init>(Z)V

    .line 32
    .line 33
    .line 34
    iput-object v0, p0, LX/I9L;->A0N:LX/JDq;

    .line 35
    .line 36
    const/16 v3, 0x3e8

    .line 37
    .line 38
    const/16 v5, 0x1f4

    .line 39
    .line 40
    new-instance v0, LX/JE6;

    .line 41
    .line 42
    invoke-direct {v0, v5, v4}, LX/JE6;-><init>(II)V

    .line 43
    .line 44
    .line 45
    iput-object v0, p0, LX/I9L;->A0S:LX/JE6;

    .line 46
    .line 47
    new-instance v0, LX/JE6;

    .line 48
    .line 49
    invoke-direct {v0, v2, v2}, LX/JE6;-><init>(II)V

    .line 50
    .line 51
    .line 52
    iput-object v0, p0, LX/I9L;->A0T:LX/JE6;

    .line 53
    .line 54
    new-instance v0, LX/JE3;

    .line 55
    .line 56
    invoke-direct {v0}, LX/JE3;-><init>()V

    .line 57
    .line 58
    .line 59
    iput-object v0, p0, LX/I9L;->A0P:LX/JE3;

    .line 60
    .line 61
    new-instance v0, LX/JDx;

    .line 62
    .line 63
    invoke-direct {v0}, LX/JDx;-><init>()V

    .line 64
    .line 65
    .line 66
    iput-object v0, p0, LX/I9L;->A0L:LX/JDx;

    .line 67
    .line 68
    sget-object v0, LX/JEK;->A00:LX/JEK;

    .line 69
    .line 70
    iput-object v0, p0, LX/I9L;->A0K:LX/JEK;

    .line 71
    .line 72
    new-instance v0, LX/JDr;

    .line 73
    .line 74
    invoke-direct {v0}, LX/JDr;-><init>()V

    .line 75
    .line 76
    .line 77
    iput-object v0, p0, LX/I9L;->A0J:LX/JDr;

    .line 78
    .line 79
    new-instance v0, LX/JDj;

    .line 80
    .line 81
    invoke-direct {v0}, LX/JDj;-><init>()V

    .line 82
    .line 83
    .line 84
    iput-object v0, p0, LX/I9L;->A0M:LX/JDj;

    .line 85
    .line 86
    new-instance v0, LX/JDl;

    .line 87
    .line 88
    invoke-direct {v0}, LX/JDl;-><init>()V

    .line 89
    .line 90
    .line 91
    iput-object v0, p0, LX/I9L;->A0U:LX/JDl;

    .line 92
    .line 93
    new-instance v0, LX/JDh;

    .line 94
    .line 95
    invoke-direct {v0}, LX/JDh;-><init>()V

    .line 96
    .line 97
    .line 98
    iput-object v0, p0, LX/I9L;->A0R:LX/JDh;

    .line 99
    .line 100
    new-instance v1, LX/I5B;

    .line 101
    .line 102
    invoke-direct {v1}, Ljava/lang/Object;-><init>()V

    .line 103
    .line 104
    .line 105
    const v0, 0x186a0

    .line 106
    .line 107
    .line 108
    iput v0, v1, LX/I5B;->A00:I

    .line 109
    .line 110
    iput v3, v1, LX/I5B;->A03:I

    .line 111
    .line 112
    iput v5, v1, LX/I5B;->A02:I

    .line 113
    .line 114
    const/16 v0, 0xfa

    .line 115
    .line 116
    iput v0, v1, LX/I5B;->A01:I

    .line 117
    .line 118
    new-instance v0, LX/JDm;

    .line 119
    .line 120
    invoke-direct {v0, v1}, LX/JDm;-><init>(LX/I5B;)V

    .line 121
    .line 122
    .line 123
    iput-object v0, p0, LX/I9L;->A0H:LX/JDm;

    .line 124
    .line 125
    new-instance v1, LX/I5B;

    .line 126
    .line 127
    invoke-direct {v1}, Ljava/lang/Object;-><init>()V

    .line 128
    .line 129
    .line 130
    iput v4, v1, LX/I5B;->A00:I

    .line 131
    .line 132
    const v0, 0x249f0

    .line 133
    .line 134
    .line 135
    iput v0, v1, LX/I5B;->A03:I

    .line 136
    .line 137
    const v0, 0x86470

    .line 138
    .line 139
    .line 140
    iput v0, v1, LX/I5B;->A02:I

    .line 141
    .line 142
    const v0, 0x1e8480

    .line 143
    .line 144
    .line 145
    iput v0, v1, LX/I5B;->A01:I

    .line 146
    .line 147
    new-instance v0, LX/JDm;

    .line 148
    .line 149
    invoke-direct {v0, v1}, LX/JDm;-><init>(LX/I5B;)V

    .line 150
    .line 151
    .line 152
    iput-object v0, p0, LX/I9L;->A0I:LX/JDm;

    .line 153
    .line 154
    iput-boolean v2, p0, LX/I9L;->A0g:Z

    .line 155
    .line 156
    iput-boolean v2, p0, LX/I9L;->A0i:Z

    .line 157
    .line 158
    const/16 v4, 0xfa0

    .line 159
    .line 160
    invoke-static {}, LX/1aa;->A1A()Ljava/util/HashMap;

    .line 161
    .line 162
    .line 163
    move-result-object v0

    .line 164
    iput-object v0, p0, LX/I9L;->A0W:Ljava/util/HashMap;

    .line 165
    .line 166
    const-wide/16 v0, 0x0

    .line 167
    .line 168
    iput-wide v0, p0, LX/I9L;->A0G:J

    .line 169
    .line 170
    invoke-static {}, LX/1aa;->A1A()Ljava/util/HashMap;

    .line 171
    .line 172
    .line 173
    move-result-object v0

    .line 174
    iput-object v0, p0, LX/I9L;->A0X:Ljava/util/Map;

    .line 175
    .line 176
    const/16 v0, 0x7530

    .line 177
    .line 178
    iput v0, p0, LX/I9L;->A04:I

    .line 179
    .line 180
    const/4 v1, -0x1

    .line 181
    iput v1, p0, LX/I9L;->A0D:I

    .line 182
    .line 183
    iput v4, p0, LX/I9L;->A03:I

    .line 184
    .line 185
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 186
    .line 187
    .line 188
    move-result-object v0

    .line 189
    iput-object v0, p0, LX/I9L;->A0b:Ljava/util/Set;

    .line 190
    .line 191
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 192
    .line 193
    .line 194
    move-result-object v0

    .line 195
    iput-object v0, p0, LX/I9L;->A0a:Ljava/util/Set;

    .line 196
    .line 197
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 198
    .line 199
    .line 200
    move-result-object v0

    .line 201
    iput-object v0, p0, LX/I9L;->A0c:Ljava/util/Set;

    .line 202
    .line 203
    new-instance v0, LX/JDn;

    .line 204
    .line 205
    invoke-direct {v0}, LX/JDn;-><init>()V

    .line 206
    .line 207
    .line 208
    iput-object v0, p0, LX/I9L;->A0Q:LX/JDn;

    .line 209
    .line 210
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 211
    .line 212
    .line 213
    move-result-object v0

    .line 214
    iput-object v0, p0, LX/I9L;->A0Z:Ljava/util/Set;

    .line 215
    .line 216
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 217
    .line 218
    .line 219
    move-result-object v0

    .line 220
    iput-object v0, p0, LX/I9L;->A0Y:Ljava/util/Set;

    .line 221
    .line 222
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 223
    .line 224
    .line 225
    move-result-object v0

    .line 226
    iput-object v0, p0, LX/I9L;->A0d:Ljava/util/Set;

    .line 227
    .line 228
    const/16 v0, 0x28

    .line 229
    .line 230
    iput v0, p0, LX/I9L;->A0C:I

    .line 231
    .line 232
    iput v0, p0, LX/I9L;->A0B:I

    .line 233
    .line 234
    iput v2, p0, LX/I9L;->A08:I

    .line 235
    .line 236
    iput v1, p0, LX/I9L;->A09:I

    .line 237
    .line 238
    iput v1, p0, LX/I9L;->A0E:I

    .line 239
    .line 240
    iput v3, p0, LX/I9L;->A06:I

    .line 241
    .line 242
    const/16 v0, 0x7d0

    .line 243
    .line 244
    iput v0, p0, LX/I9L;->A05:I

    .line 245
    .line 246
    iput v3, p0, LX/I9L;->A00:I

    .line 247
    .line 248
    iput v3, p0, LX/I9L;->A02:I

    .line 249
    .line 250
    const v0, 0x8000

    .line 251
    .line 252
    .line 253
    iput v0, p0, LX/I9L;->A01:I

    .line 254
    .line 255
    iput-boolean v2, p0, LX/I9L;->A0h:Z

    .line 256
    .line 257
    iput-boolean v2, p0, LX/I9L;->A0e:Z

    .line 258
    .line 259
    const/16 v0, 0x18

    .line 260
    .line 261
    iput v0, p0, LX/I9L;->A0A:I

    .line 262
    .line 263
    iput-boolean v2, p0, LX/I9L;->A0m:Z

    .line 264
    .line 265
    iput v1, p0, LX/I9L;->A0F:I

    .line 266
    .line 267
    return-void
.end method
