.class public final LX/IRM;
.super Ljava/lang/Object;
.source ""


# static fields
.field public static final A0m:Ljava/util/HashSet;


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:J

.field public A06:LX/JDo;

.field public A07:LX/JDo;

.field public A08:LX/H2U;

.field public A09:LX/JDu;

.field public A0A:LX/JDg;

.field public A0B:LX/JEF;

.field public A0C:LX/JDw;

.field public A0D:LX/JDi;

.field public A0E:LX/JE5;

.field public A0F:LX/JDv;

.field public A0G:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0H:LX/JDy;

.field public A0I:LX/JE4;

.field public A0J:LX/JDs;

.field public A0K:LX/JE7;

.field public A0L:LX/JE7;

.field public A0M:LX/JDk;

.field public A0N:Ljava/lang/String;

.field public A0O:Ljava/util/HashSet;

.field public A0P:Ljava/util/Map;

.field public A0Q:Ljava/util/Set;

.field public A0R:Ljava/util/Set;

.field public A0S:Ljava/util/Set;

.field public A0T:Ljava/util/Set;

.field public A0U:Ljava/util/Set;

.field public A0V:Ljava/util/Set;

.field public A0W:Ljava/util/Set;

.field public A0X:Ljava/util/Set;

.field public A0Y:Z

.field public A0Z:Z

.field public A0a:Z

.field public A0b:Z

.field public A0c:Z

.field public A0d:Z

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z


# direct methods
.method public static constructor <clinit>()V
    .locals 3

    .line 0
    const/4 v0, 0x7

    .line 1
    new-array v2, v0, [Ljava/lang/String;

    .line 2
    .line 3
    const/4 v1, 0x0

    .line 4
    const-string v0, "omx.sprd.av1.decoder"

    .line 5
    .line 6
    aput-object v0, v2, v1

    .line 7
    .line 8
    const/4 v1, 0x1

    .line 9
    const-string v0, "c2.qti.av1.decoder"

    .line 10
    .line 11
    aput-object v0, v2, v1

    .line 12
    .line 13
    const/4 v1, 0x2

    .line 14
    const-string v0, "c2.qti.av1.decoder.low_latency"

    .line 15
    .line 16
    aput-object v0, v2, v1

    .line 17
    .line 18
    const/4 v1, 0x3

    .line 19
    const-string v0, "c2.exynos.av1.decoder"

    .line 20
    .line 21
    aput-object v0, v2, v1

    .line 22
    .line 23
    const/4 v1, 0x4

    .line 24
    const-string v0, "c2.mtk.av1.decoder"

    .line 25
    .line 26
    aput-object v0, v2, v1

    .line 27
    .line 28
    const/4 v1, 0x5

    .line 29
    const-string v0, "omx.mtk.video.decoder.av1"

    .line 30
    .line 31
    aput-object v0, v2, v1

    .line 32
    .line 33
    const/4 v1, 0x6

    .line 34
    const-string v0, "c2.unisoc.av1.decoder"

    .line 35
    .line 36
    aput-object v0, v2, v1

    .line 37
    .line 38
    invoke-static {v2}, LX/Abt;->A15([Ljava/lang/Object;)Ljava/util/HashSet;

    .line 39
    .line 40
    .line 41
    move-result-object v0

    .line 42
    sput-object v0, LX/IRM;->A0m:Ljava/util/HashSet;

    .line 43
    .line 44
    return-void
.end method

.method public constructor <init>()V
    .locals 8

    .line 0
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 1
    .line 2
    .line 3
    const/4 v1, 0x0

    .line 4
    const/4 v2, 0x1

    .line 5
    const/4 v5, -0x1

    .line 6
    new-instance v0, LX/JDv;

    .line 7
    .line 8
    invoke-direct {v0}, LX/JDv;-><init>()V

    .line 9
    .line 10
    .line 11
    iput-object v0, p0, LX/IRM;->A0F:LX/JDv;

    .line 12
    .line 13
    sget-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 14
    .line 15
    iput-object v0, p0, LX/IRM;->A0G:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 16
    .line 17
    iput-boolean v1, p0, LX/IRM;->A0Z:Z

    .line 18
    .line 19
    const/4 v0, 0x3

    .line 20
    iput v0, p0, LX/IRM;->A02:I

    .line 21
    .line 22
    const/16 v3, 0x7d0

    .line 23
    .line 24
    const-string v0, "ExoService"

    .line 25
    .line 26
    iput-object v0, p0, LX/IRM;->A0N:Ljava/lang/String;

    .line 27
    .line 28
    iput-boolean v2, p0, LX/IRM;->A0k:Z

    .line 29
    .line 30
    new-instance v0, LX/HwJ;

    .line 31
    .line 32
    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    .line 33
    .line 34
    .line 35
    iget-boolean v2, v0, LX/HwJ;->A00:Z

    .line 36
    .line 37
    new-instance v0, LX/JE5;

    .line 38
    .line 39
    invoke-direct {v0, v2}, LX/JE5;-><init>(Z)V

    .line 40
    .line 41
    .line 42
    iput-object v0, p0, LX/IRM;->A0E:LX/JE5;

    .line 43
    .line 44
    const/16 v6, 0x1f4

    .line 45
    .line 46
    new-instance v0, LX/JE7;

    .line 47
    .line 48
    invoke-direct {v0, v6, v3}, LX/JE7;-><init>(II)V

    .line 49
    .line 50
    .line 51
    iput-object v0, p0, LX/IRM;->A0K:LX/JE7;

    .line 52
    .line 53
    new-instance v0, LX/JE7;

    .line 54
    .line 55
    invoke-direct {v0, v1, v1}, LX/JE7;-><init>(II)V

    .line 56
    .line 57
    .line 58
    iput-object v0, p0, LX/IRM;->A0L:LX/JE7;

    .line 59
    .line 60
    const/16 v4, 0xfa0

    .line 61
    .line 62
    new-instance v0, LX/JE4;

    .line 63
    .line 64
    invoke-direct {v0}, LX/JE4;-><init>()V

    .line 65
    .line 66
    .line 67
    iput-object v0, p0, LX/IRM;->A0I:LX/JE4;

    .line 68
    .line 69
    new-instance v0, LX/JDw;

    .line 70
    .line 71
    invoke-direct {v0}, LX/JDw;-><init>()V

    .line 72
    .line 73
    .line 74
    iput-object v0, p0, LX/IRM;->A0C:LX/JDw;

    .line 75
    .line 76
    sget-object v0, LX/JEF;->A00:LX/JEF;

    .line 77
    .line 78
    iput-object v0, p0, LX/IRM;->A0B:LX/JEF;

    .line 79
    .line 80
    new-instance v0, LX/JDg;

    .line 81
    .line 82
    invoke-direct {v0}, LX/JDg;-><init>()V

    .line 83
    .line 84
    .line 85
    iput-object v0, p0, LX/IRM;->A0A:LX/JDg;

    .line 86
    .line 87
    new-instance v2, LX/Hw5;

    .line 88
    .line 89
    invoke-direct {v2}, LX/Hw5;-><init>()V

    .line 90
    .line 91
    .line 92
    new-instance v0, LX/JDu;

    .line 93
    .line 94
    invoke-direct {v0, v2}, LX/JDu;-><init>(LX/Hw5;)V

    .line 95
    .line 96
    .line 97
    iput-object v0, p0, LX/IRM;->A09:LX/JDu;

    .line 98
    .line 99
    new-instance v0, LX/JDi;

    .line 100
    .line 101
    invoke-direct {v0}, LX/JDi;-><init>()V

    .line 102
    .line 103
    .line 104
    iput-object v0, p0, LX/IRM;->A0D:LX/JDi;

    .line 105
    .line 106
    new-instance v0, LX/JDk;

    .line 107
    .line 108
    invoke-direct {v0}, LX/JDk;-><init>()V

    .line 109
    .line 110
    .line 111
    iput-object v0, p0, LX/IRM;->A0M:LX/JDk;

    .line 112
    .line 113
    new-instance v2, LX/I4s;

    .line 114
    .line 115
    invoke-direct {v2}, Ljava/lang/Object;-><init>()V

    .line 116
    .line 117
    .line 118
    const v0, 0x186a0

    .line 119
    .line 120
    .line 121
    iput v0, v2, LX/I4s;->A00:I

    .line 122
    .line 123
    const/16 v0, 0x3e8

    .line 124
    .line 125
    iput v0, v2, LX/I4s;->A03:I

    .line 126
    .line 127
    iput v6, v2, LX/I4s;->A02:I

    .line 128
    .line 129
    const/16 v0, 0xfa

    .line 130
    .line 131
    iput v0, v2, LX/I4s;->A01:I

    .line 132
    .line 133
    new-instance v0, LX/JDo;

    .line 134
    .line 135
    invoke-direct {v0, v2}, LX/JDo;-><init>(LX/I4s;)V

    .line 136
    .line 137
    .line 138
    iput-object v0, p0, LX/IRM;->A06:LX/JDo;

    .line 139
    .line 140
    new-instance v2, LX/I4s;

    .line 141
    .line 142
    invoke-direct {v2}, Ljava/lang/Object;-><init>()V

    .line 143
    .line 144
    .line 145
    iput v3, v2, LX/I4s;->A00:I

    .line 146
    .line 147
    const v0, 0x249f0

    .line 148
    .line 149
    .line 150
    iput v0, v2, LX/I4s;->A03:I

    .line 151
    .line 152
    const v0, 0x86470

    .line 153
    .line 154
    .line 155
    iput v0, v2, LX/I4s;->A02:I

    .line 156
    .line 157
    const v0, 0x1e8480

    .line 158
    .line 159
    .line 160
    iput v0, v2, LX/I4s;->A01:I

    .line 161
    .line 162
    new-instance v0, LX/JDo;

    .line 163
    .line 164
    invoke-direct {v0, v2}, LX/JDo;-><init>(LX/I4s;)V

    .line 165
    .line 166
    .line 167
    iput-object v0, p0, LX/IRM;->A07:LX/JDo;

    .line 168
    .line 169
    iput-boolean v1, p0, LX/IRM;->A0d:Z

    .line 170
    .line 171
    iput-boolean v1, p0, LX/IRM;->A0h:Z

    .line 172
    .line 173
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 174
    .line 175
    .line 176
    move-result-object v0

    .line 177
    iput-object v0, p0, LX/IRM;->A0O:Ljava/util/HashSet;

    .line 178
    .line 179
    const-wide/16 v2, 0x0

    .line 180
    .line 181
    iput-wide v2, p0, LX/IRM;->A05:J

    .line 182
    .line 183
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 184
    .line 185
    .line 186
    move-result-object v0

    .line 187
    iput-object v0, p0, LX/IRM;->A0Q:Ljava/util/Set;

    .line 188
    .line 189
    invoke-static {}, LX/1aa;->A1A()Ljava/util/HashMap;

    .line 190
    .line 191
    .line 192
    move-result-object v0

    .line 193
    iput-object v0, p0, LX/IRM;->A0P:Ljava/util/Map;

    .line 194
    .line 195
    iput-boolean v1, p0, LX/IRM;->A0e:Z

    .line 196
    .line 197
    const/16 v0, 0x7530

    .line 198
    .line 199
    iput v0, p0, LX/IRM;->A01:I

    .line 200
    .line 201
    iput v5, p0, LX/IRM;->A04:I

    .line 202
    .line 203
    iput v4, p0, LX/IRM;->A00:I

    .line 204
    .line 205
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 206
    .line 207
    .line 208
    move-result-object v0

    .line 209
    iput-object v0, p0, LX/IRM;->A0V:Ljava/util/Set;

    .line 210
    .line 211
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 212
    .line 213
    .line 214
    move-result-object v0

    .line 215
    iput-object v0, p0, LX/IRM;->A0U:Ljava/util/Set;

    .line 216
    .line 217
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 218
    .line 219
    .line 220
    move-result-object v0

    .line 221
    iput-object v0, p0, LX/IRM;->A0W:Ljava/util/Set;

    .line 222
    .line 223
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 224
    .line 225
    .line 226
    move-result-object v0

    .line 227
    iput-object v0, p0, LX/IRM;->A0R:Ljava/util/Set;

    .line 228
    .line 229
    new-instance v0, LX/JDs;

    .line 230
    .line 231
    invoke-direct {v0}, LX/JDs;-><init>()V

    .line 232
    .line 233
    .line 234
    iput-object v0, p0, LX/IRM;->A0J:LX/JDs;

    .line 235
    .line 236
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 237
    .line 238
    .line 239
    move-result-object v0

    .line 240
    iput-object v0, p0, LX/IRM;->A0T:Ljava/util/Set;

    .line 241
    .line 242
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 243
    .line 244
    .line 245
    move-result-object v0

    .line 246
    iput-object v0, p0, LX/IRM;->A0S:Ljava/util/Set;

    .line 247
    .line 248
    invoke-static {}, LX/1aa;->A1B()Ljava/util/HashSet;

    .line 249
    .line 250
    .line 251
    move-result-object v0

    .line 252
    iput-object v0, p0, LX/IRM;->A0X:Ljava/util/Set;

    .line 253
    .line 254
    const/4 v0, 0x0

    .line 255
    iput-object v0, p0, LX/IRM;->A0H:LX/JDy;

    .line 256
    .line 257
    iput-boolean v1, p0, LX/IRM;->A0g:Z

    .line 258
    .line 259
    iput-boolean v1, p0, LX/IRM;->A0c:Z

    .line 260
    .line 261
    iput-boolean v1, p0, LX/IRM;->A0b:Z

    .line 262
    .line 263
    iput-boolean v1, p0, LX/IRM;->A0a:Z

    .line 264
    .line 265
    const/16 v3, 0x3e8

    .line 266
    .line 267
    const/16 v4, 0x7d0

    .line 268
    .line 269
    const v7, 0x8000

    .line 270
    .line 271
    .line 272
    new-instance v2, LX/H2U;

    .line 273
    .line 274
    move v6, v3

    .line 275
    move v5, v3

    .line 276
    invoke-direct/range {v2 .. v7}, LX/H2U;-><init>(IIIII)V

    .line 277
    .line 278
    .line 279
    iput-object v2, p0, LX/IRM;->A08:LX/H2U;

    .line 280
    .line 281
    const/16 v0, 0x1a

    .line 282
    .line 283
    iput v0, p0, LX/IRM;->A03:I

    .line 284
    .line 285
    iput-boolean v1, p0, LX/IRM;->A0l:Z

    .line 286
    .line 287
    iput-boolean v1, p0, LX/IRM;->A0Y:Z

    .line 288
    .line 289
    iput-boolean v1, p0, LX/IRM;->A0j:Z

    .line 290
    .line 291
    iput-boolean v1, p0, LX/IRM;->A0f:Z

    .line 292
    .line 293
    return-void
    .line 294
    .line 295
    .line 296
    .line 297
    .line 298
    .line 299
    .line 300
    .line 301
    .line 302
    .line 303
.end method
