package com.facebook.video.heroplayer.setting;

import java.io.Serializable;
import p000X.XN8;

/* loaded from: classes.dex */
public class FbAutogeneratedSettings implements Serializable {
    public static final long serialVersionUID = 968006291006349357L;
    public final int autoAddIntParams;
    public final boolean enableSloHttpHeaderLogging;
    public final String grootPrefetchSuboriginBlocklist;
    public final int maxAllowed503RetryCount;

    public FbAutogeneratedSettings() {
        this.autoAddIntParams = 101;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = false;
        this.grootPrefetchSuboriginBlocklist = "";
    }

    public FbAutogeneratedSettings(XN8 xn8) {
        this.autoAddIntParams = 101;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = false;
        this.grootPrefetchSuboriginBlocklist = "";
    }
}
