package com.facebook.wa.video.heroplayer.setting;

import java.io.Serializable;
import p000X.C39557Hlj;

/* loaded from: classes8.dex */
public class FbAutogeneratedSettings implements Serializable {
    public static final long serialVersionUID = 968006291006349357L;
    public final int autoAddIntParams;
    public final boolean enableSloHttpHeaderLogging;
    public final String grootPrefetchSuboriginBlocklist;
    public final int maxAllowed503RetryCount;

    public FbAutogeneratedSettings(C39557Hlj c39557Hlj) {
        this.autoAddIntParams = 101;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = false;
        this.grootPrefetchSuboriginBlocklist = "";
    }
}
