package p000X;

/* renamed from: X.2tC, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes2.dex */
public abstract class AbstractC75862tC {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 0:
                return "autoplay_disabled";
            case 1:
                return "context_sheet";
            case 2:
                return C11M.A00(314);
            case 3:
                return "bottom_sheet";
            case 4:
                return "paused_for_pinch_to_zoom";
            case 5:
                return "debug_pause";
            case 6:
                return "error";
            case 7:
                return "clips_pause_reason_instream_ads_switching";
            case 8:
                return "instream_ads_swipe_to_dismiss";
            case 9:
                return "scroll";
            case 10:
                return "bloks";
            case 11:
                return "opening_learn_more";
            case 12:
                return "launching_music_pick_template";
            case 13:
                return "zero_cmon_interstitial_shown";
            case 14:
                return "media_level_survey_shown";
            case 15:
                return "seek";
            case 16:
                return "seek_force_pause";
            case 17:
                return "start_playing_different_clips_media";
            case 18:
                return "message_unsent";
            case 19:
                return "peek_browser_dragging";
            case 20:
                return "peek_browser_dragging_full_screen";
            case 21:
                return "peek_browser_dragging_full_sheet";
            case 22:
                return "peek_browser_dragging_anchor";
            case 23:
                return "paused_for_replay";
            case 24:
                return "paused_for_story_draw";
            case 25:
                return "paused_for_music_audio_off";
            case 26:
                return "user_played_carousel_with_music";
            case 27:
                return C11M.A00(374);
            case 28:
                return AnonymousClass049.A00(217);
            case 29:
                return "fragment_stopped";
            case 30:
                return "preview_end";
            case 31:
            case 40:
            case 41:
            case 42:
            case 48:
            case 53:
            case 56:
            case 58:
            case 60:
            default:
                return "super_like_animation";
            case 32:
                return "tapped";
            case 33:
                return "long_pressed";
            case 34:
                return "long_pressed_persistent_pause";
            case 35:
                return "context_switch";
            case 36:
                return "media_mismatch";
            case 37:
                return "peek";
            case 38:
                return "end_peek";
            case 39:
                return "hide";
            case 43:
                return "pip_audio_focus_loss";
            case 44:
                return "pip_stashed";
            case 45:
                return "pip_unstashed";
            case 46:
                return "pip_audio_focus_gain";
            case 47:
                return "finished";
            case 49:
                return "cobroadcast_start";
            case 50:
                return "dialog";
            case 51:
                return "rage_shake_dialog";
            case 52:
                return "polaroid_shake_to_reveal";
            case 54:
                return "horizontal_scroll";
            case 55:
                return "birthday_unit_overlay_shown";
            case 57:
                return "out_of_playback_range";
            case 59:
                return "stop_reason_sticker_tap";
            case 61:
                return "thread_deleted";
            case 62:
                return "left_thread";
            case 63:
                return "unknown";
            case 64:
                return "concurrent_video_played";
            case 65:
                return "comment";
            case 66:
                return "share";
            case 67:
                return "animation";
            case 68:
                return "end_scene";
            case 69:
                return "caption_and_browse";
            case 70:
                return "attempt_to_launch_ig_boost";
            case 71:
                return "end_scene_truncated_long_video";
            case 72:
                return "quick_promotion_tooltip_shown";
            case 73:
                return "deletion_nux";
            case 74:
                return "effect_applied";
            case 75:
                return "high_intent_discovery_entrypoint_tapped";
            case 76:
                return "user_paused_video";
            case 77:
                return "single_tap_paused";
            case 78:
                return "server_paused_video";
            case 79:
                return "insights_bottom_sheet_shown";
            case 80:
                return "launching_stories_template";
            case 81:
                return "bottom_sheet_height_threshold_reached";
            case 82:
                return "send";
            case 83:
                return "navigate_deeper";
            case 84:
                return "report_flow_shown";
            case 85:
                return "content_lane_switch";
            case 86:
                return "audio_focus_loss";
            case 87:
                return AnonymousClass218.A00(374);
        }
    }
}
