package p000X;

/* renamed from: X.6jD, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes2.dex */
public abstract class AbstractC171596jD {
    public static final int A00(EnumC220558fz enumC220558fz) {
        AbstractC171606jE abstractC171606jE = AbstractC171606jE.$redex_init_class;
        switch (enumC220558fz.ordinal()) {
            case 2:
                return 0;
            case 3:
                return 10;
            case 4:
            case 6:
            case 7:
            case 8:
            case 16:
            case 17:
            case 23:
            case 24:
            case 40:
            case 63:
            case 77:
            case 79:
            case 88:
            case 90:
            case 99:
            case 104:
            case 105:
            case 106:
            case 111:
            case 112:
            case 114:
            default:
                return 1;
            case 5:
                return 3;
            case 9:
            case 10:
                return 20;
            case 11:
            case 43:
                return 55;
            case 12:
            case 89:
                return 69;
            case 13:
                return 59;
            case 14:
                return 2;
            case 15:
                return 5;
            case 18:
            case 19:
            case 20:
            case 21:
                return 68;
            case 22:
                return 61;
            case 25:
            case 26:
            case 27:
            case 28:
            case 33:
            case 34:
            case 35:
            case 36:
            case 37:
            case 38:
            case 39:
            case 41:
            case 42:
            case 50:
            case 51:
            case 53:
            case 54:
            case 55:
            case 61:
            case 64:
            case 65:
            case 66:
            case 67:
            case 68:
            case 69:
            case 70:
            case 71:
            case 84:
            case 92:
            case 93:
            case 94:
            case 95:
            case 100:
            case 103:
            case 113:
                return 13;
            case 29:
            case 30:
                return 71;
            case 31:
            case 32:
                return 42;
            case 44:
            case 45:
                return 70;
            case 46:
            case 98:
                return 4;
            case 47:
            case 48:
                return 22;
            case 49:
            case 52:
            case 56:
                return 76;
            case 57:
                return 30;
            case 58:
            case 60:
            case 62:
            case 91:
            case 96:
            case 97:
            case 102:
            case 107:
                return 62;
            case 59:
                return 8;
            case 72:
                return 63;
            case 73:
                return 17;
            case 74:
            case 80:
            case 81:
                return 31;
            case 75:
                return 28;
            case 76:
            case 110:
                return 82;
            case 78:
                return 77;
            case 82:
                return 46;
            case 83:
                return 65;
            case 85:
                return 66;
            case 86:
                return 45;
            case 87:
                return 49;
            case 101:
                return 85;
            case 108:
                return 72;
            case 109:
                return 83;
            case 115:
                return 74;
            case 116:
                return 78;
        }
    }

    public static final boolean A01(EnumC220558fz enumC220558fz) {
        AbstractC171606jE abstractC171606jE = AbstractC171606jE.$redex_init_class;
        switch (enumC220558fz.ordinal()) {
            case 10:
            case 21:
            case 24:
            case 26:
            case 28:
            case 29:
            case 34:
            case 37:
            case 39:
            case 42:
            case 45:
            case 51:
            case 52:
            case 53:
            case 54:
            case 57:
            case 58:
            case 60:
            case 61:
            case 62:
            case 64:
            case 65:
            case 66:
            case 68:
            case 69:
            case 70:
            case 71:
            case 72:
            case 73:
            case 75:
            case 77:
            case 78:
            case 82:
            case 83:
            case 84:
            case 85:
            case 86:
            case 87:
            case 89:
            case 90:
            case 91:
            case 92:
            case 93:
            case 94:
            case 95:
            case 96:
            case 98:
            case 100:
            case 104:
            case 105:
            case 107:
            case 116:
            case 117:
            case 118:
                return true;
            case 11:
            case 12:
            case 13:
            case 14:
            case 15:
            case 16:
            case 17:
            case 18:
            case 19:
            case 20:
            case 22:
            case 23:
            case 25:
            case 27:
            case 30:
            case 31:
            case 32:
            case 33:
            case 35:
            case 36:
            case 38:
            case 40:
            case 41:
            case 43:
            case 44:
            case 46:
            case 47:
            case 48:
            case 49:
            case 50:
            case 55:
            case 56:
            case 59:
            case 63:
            case 67:
            case 74:
            case 76:
            case 79:
            case 80:
            case 81:
            case 88:
            case 97:
            case 99:
            case 101:
            case 102:
            case 103:
            case 106:
            case 108:
            case 109:
            case 110:
            case 111:
            case 112:
            case 113:
            case 114:
            case 115:
            default:
                return false;
        }
    }
}
