package p000X;

/* renamed from: X.N6j, reason: case insensitive filesystem */
/* loaded from: classes11.dex */
public abstract class AbstractC59103N6j {
    public static final long A00;
    public static final long A01;
    public static final long A02;
    public static final long A03;
    public static final long A04;
    public static final long A05;
    public static final long A06;
    public static final long A07;
    public static final long A08;
    public static final long A09;
    public static final long A0A;
    public static final long A0B;
    public static final long A0C;
    public static final long A0D;
    public static final long A0E;
    public static final long A0F;
    public static final long A0G;
    public static final long A0H;
    public static final long A0I;
    public static final long A0J;
    public static final long A0K;
    public static final long A0L;
    public static final long A0M;
    public static final long A0N;
    public static final long A0O;
    public static final long A0P;
    public static final long A0Q;
    public static final long A0R;
    public static final long A0S;
    public static final long A0T;
    public static final long A0U;
    public static final long A0V;
    public static final long A0W;
    public static final long A0X;
    public static final long A0Y;

    static {
        long j = C6SJ.A0G;
        A0P = j;
        long j2 = C6SJ.A0L;
        long j3 = C6SJ.A0O;
        A0Q = j3;
        A0U = j2;
        A0V = j3;
        long j4 = C6SJ.A0Q;
        long j5 = C6SJ.A00;
        A0K = j5;
        A0L = C6SJ.A0j;
        A0O = j5;
        A0R = C6SJ.A0R;
        long j6 = C6SJ.A0P;
        A0S = j6;
        long j7 = C6SJ.A0T;
        A0F = j7;
        long j8 = C6SJ.A1m;
        long j9 = C6SJ.A0S;
        A0I = j;
        A0J = j4;
        A0W = j7;
        A0T = j6;
        A0X = C6SJ.A1o;
        long j10 = C6SJ.A1w;
        A00 = j10;
        A0H = j8;
        A0M = C6SJ.A1n;
        A02 = j5;
        A03 = j9;
        A04 = C6SJ.A1l;
        A05 = C6SJ.A0H;
        A01 = C6SJ.A1f;
        long j11 = C6SJ.A0a;
        A0N = j11;
        long j12 = C6SJ.A0z;
        A06 = j12;
        long j13 = C6SJ.A1W;
        A0Y = C6SJ.A03;
        A0C = j13;
        A09 = j12;
        A0B = C6SJ.A1L;
        A0D = C6SJ.A1g;
        A0A = C6SJ.A1A;
        A0E = j10;
        A08 = j11;
        A07 = C6SJ.A0A;
        A0G = C6SJ.A0F;
    }
}
