package p000X;

import java.util.HashMap;

/* renamed from: X.NeS, reason: case insensitive filesystem */
/* loaded from: classes10.dex */
public abstract class AbstractC60150NeS {
    public static final HashMap A00 = AbstractC50871tz.A04(A00("ProfileAppSwitcher", "Instagram Profile App Switcher", "self_profile_switcher", "IG%26utm_medium%3DProfileAppSwitcher%26utm_campaign%3DInstagram%2520Profile%2520App%2520Switcher"), A00("ProfileBadge", "Instagram Profile Badge", "self_profile_badge", "IG%26utm_medium%3DProfileBadge%26utm_campaign%3DInstagram%2520Profile%2520Badge"), A00("ProfileBadge", "Instagram Profile Badge", "other_profile_badge", "IG%26utm_medium%3DProfileBadge%26utm_campaign%3DInstagram%2520Profile%2520Badge"), A00("ActivityFeedNotif", "Instagram Activity feed notifications", "activity_feed_notification", "IG%26utm_medium%3DActivityFeedNotif%26utm_campaign%3DInstagram%2520Activity%2520feed%2520notifications"), A00("PushNotif", "Instagram Push notifications", "push_notification", "IG%26utm_medium%3DPushNotif%26utm_campaign%3DInstagram%2520Push%2520notifications"), A00("FeedMegaphoneQP", "Instagram Feed Megaphone QP", "feed_qp", "IG%26utm_medium%3DFeedMegaphoneQP%26utm_campaign%3DInstagram%2520Feed%2520Megaphone%2520QP"), A00("GoldenTicket", "Instagram Golden tickets", "golden_ticket", "IG%26utm_medium%3DGoldenTicket%26utm_campaign%3DInstagram%2520Golden%2520tickets"), A00("Tifu", "Instagram TIFU", "tifu", "IG%26utm_medium%3DTifu%26utm_campaign%3DInstagram%2520TIFU"), A00("Tifu", "Instagram TIFU", "tifu_header", "IG%26utm_medium%3DTifu%26utm_campaign%3DInstagram%2520TIFU"), A00("DmNux", "Direct message nux", "direct_message_nux", "IG%26utm_medium%3DDmNux%26utm_campaign%3DDirect%2520message%2520nux"), A00("Tiru", "Instagram Tiru", "tiru", "IG%26utm_medium%3DTiru%26utm_campaign%3DInstagram%2BTiru"), A00("Tisu", "Instagram Tisu", "tisu", "IG%26utm_medium%3DTisu%26utm_campaign%3DInstagram%2BTisu"), A00("Tischu", "Instagram Tischu", "tischu", "IG%26utm_medium%3DTischu%26utm_campaign%3DInstagram%2BTischu"), A00("Tischu", "Instagram Tischu", "tischu_header", "IG%26utm_medium%3DTischu%26utm_campaign%3DInstagram%2BTischu"), A00("Settings", "Instagram Settings", "settings", "IG%26utm_medium%3DSettings%26utm_campaign%3DInstagram%2BSettings"), A00("IgFoaOnboarding", "Instagram FOA Onboarding", "foa_onboarding", "IG%26utm_medium%3DIgFoaOnboarding%26utm_campaign%3DInstagram%2BFOA%2BOnboarding"), A00("SUSuggestion", "Instagram SU Suggestion", "profile_follow_suggestions_cta_acquisition", "IG%26utm_medium%3DSUSuggestion%26utm_campaign%3DInstagram%2BSUSuggestion"), A00("SUSuggestion", "Instagram SU Suggestion", "profile_follow_suggestions_cta_retention", "IG%26utm_medium%3DSUSuggestion%26utm_campaign%3DInstagram%2BSUSuggestion"));

    public static C50641tc A00(String str, String str2, String str3, String str4) {
        return new C50641tc(str3, new DFE(str, str2, str3, str4));
    }
}
