package p000X;

/* renamed from: X.Gp2, reason: case insensitive filesystem */
/* loaded from: classes6.dex */
public abstract class AbstractC42990Gp2 {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 1:
                return "CallEngineDispatch";
            case 2:
                return "CallEngineState";
            case 3:
                return "CallState";
            case 4:
                return "DEPRECATED_CheckStateEnableStella";
            case 5:
                return "ConnectedUserActive";
            case 6:
                return "ContactChangeEvent";
            case 7:
                return "DeclineCall";
            case 8:
                return "DeviceConnectionState";
            case 9:
                return "EndCall";
            case 10:
                return "FetchContacts";
            case 11:
                return "FetchGroupThreads";
            case 12:
                return "FetchLogs";
            case 13:
                return "FetchMessageAudio";
            case 14:
                return "FetchMessageImage";
            case 15:
                return "FetchPaymentCapabilities";
            case 16:
                return "FetchPendingMedia";
            case 17:
                return "FetchProviderLinkingStatus";
            case 18:
                return "FetchShareLocationStatus";
            case 19:
                return "CheckLocationPermission";
            case 20:
                return "FetchUnreadMessage";
            case 21:
                return "GetCallHistory";
            case 22:
                return "GetCallState";
            case 23:
                return "GetEncryptedCacheKey";
            case 24:
                return "GetNotificationSubscribeStatus";
            case 25:
                return "GetRequestToken";
            case 26:
                return "GroupThreadsChangeEvent";
            case 27:
                return "IgdMessageSent";
            case 28:
                return "ImportMediaItem";
            case 29:
                return "Inbox";
            case 30:
                return "InboxSnapshot";
            case 31:
                return "InboxThread";
            case 32:
                return "IncomingCall";
            case 33:
                return "IncomingMessage";
            case 34:
                return "IncomingMessageReaction";
            case 35:
                return "IncomingSubscriptionNotification";
            case 36:
                return "LoadMessages";
            case 37:
                return "LoadThreads";
            case 38:
                return "LogCallEventData";
            case 39:
                return "MarkPlayed";
            case 40:
                return "MarkRead";
            case 41:
                return "MediaItemImportStatus";
            case 42:
                return "MessageReceivedByServer";
            case 43:
                return "MissedCall";
            case 44:
                return "MuteUnmuteMic";
            case 45:
                return "OptInOut";
            case 46:
                return "OptOut";
            case 47:
                return "PendingImports";
            case 48:
                return "PlayVoiceMessage";
            case 49:
                return "MailboxPSISearchQuery";
            case 50:
                return "PSIMessageSearchConsent";
            case 51:
                return "PSIMessageSearchConsentStatus";
            case 52:
                return "PSIMessageSearchStatus";
            case 53:
                return "RevokeMessage";
            case 54:
                return "SendMessage";
            case 55:
                return "SendPayment";
            case 56:
                return "SendVoiceMessage";
            case 57:
                return "ShareMedia";
            case 58:
                return "ShareMediaStory";
            case 59:
                return "StartCall";
            case 60:
                return "StartSharingLocation";
            case 61:
                return "StartUpiLiteOnboarding";
            case 62:
                return "StopSharingLocation";
            case 63:
                return "StopVoiceMessage";
            case 64:
                return "SubscribeToNotifications";
            case 65:
                return "SyncDevices";
            case 66:
                return "ToggleCallBluetoothAudio";
            case 67:
                return "ToggleCallVideo";
            case 68:
                return "UpdateLiveLocation";
            case 69:
                return "UnlinkDevice";
            case 70:
                return "Unknown";
            default:
                return "AnswerCall";
        }
    }
}
