package p000X;

import com.facebook.ultralight.AutoGeneratedSwitchAppModuleSubClass;
import com.facebook.ultralight.AutoGeneratedSwitchSubClassMasterMethod;
import dalvik.annotation.optimization.NeverInline;

@AutoGeneratedSwitchAppModuleSubClass(1)
/* renamed from: X.R2z, reason: case insensitive filesystem */
/* loaded from: classes12.dex */
public abstract class AbstractC69185R2z {
    @NeverInline
    @AutoGeneratedSwitchSubClassMasterMethod
    public static Object A00(int i, InterfaceC98588org interfaceC98588org, Object obj) {
        if (((i >> 7) & 15) == 0) {
            return A01(i, interfaceC98588org, obj);
        }
        throw AnonymousClass031.A0R("Invalid Static DI binding id");
    }

    public static Object A01(int i, InterfaceC98588org interfaceC98588org, Object obj) {
        switch ((i >> 0) & 127) {
            case 0:
            case 14:
                return qjO.A00();
            case 1:
            case 15:
                return qjS.A01();
            case 2:
            case 16:
                return qjQ.A00();
            case 3:
            case 17:
                return qjR.A00();
            case 4:
            case 18:
                return qjN.A00();
            case 5:
                return qjS.A00(obj);
            case 6:
                return qjU.A00();
            case 7:
                return qjU.A02();
            case 8:
                return qjU.A01();
            case 9:
                return qjT.A00();
            case 10:
                return qjT.A01();
            case 11:
            case 12:
            default:
                throw AnonymousClass031.A0R("Invalid Static DI binding id");
            case 13:
                return qjP.A00();
        }
    }
}
