package p000X;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes5.dex */
public final class BCK implements InterfaceC26580vu {
    public static final /* synthetic */ BCK[] A01;
    public static final BCK A02;
    public static final BCK A03;
    public static final BCK A04;
    public static final BCK A05;
    public static final BCK A06;
    public static final BCK A07;
    public static final BCK A08;
    public static final BCK A09;
    public static final BCK A0A;
    public static final BCK A0B;
    public static final BCK A0C;
    public static final BCK A0D;
    public static final BCK A0E;
    public static final BCK A0F;
    public static final BCK A0G;
    public static final BCK A0H;
    public static final BCK A0I;
    public static final BCK A0J;
    public static final BCK A0K;
    public static final BCK A0L;
    public static final BCK A0M;
    public static final BCK A0N;
    public static final BCK A0O;
    public static final BCK A0P;
    public static final BCK A0Q;
    public static final BCK A0R;
    public static final BCK A0S;
    public static final BCK A0T;
    public static final BCK A0U;
    public static final BCK A0V;
    public static final BCK A0W;
    public static final BCK A0X;
    public static final BCK A0Y;
    public static final BCK A0Z;
    public static final BCK A0a;
    public static final BCK A0b;
    public static final BCK A0c;
    public static final BCK A0d;
    public static final BCK A0e;
    public static final BCK A0f;
    public static final BCK A0g;
    public static final BCK A0h;
    public static final BCK A0i;
    public static final BCK A0j;
    public static final BCK A0k;
    public static final BCK A0l;
    public static final BCK A0m;
    public static final BCK A0n;
    public static final BCK A0o;
    public static final BCK A0p;
    public static final BCK A0q;
    public static final BCK A0r;
    public static final BCK A0s;
    public static final BCK A0t;
    public static final BCK A0u;
    public static final BCK A0v;
    public static final BCK A0w;
    public static final BCK A0x;
    public static final BCK A0y;
    public static final BCK A0z;
    public static final BCK A10;
    public final String A00;

    static {
        BCK[] bckArr = new BCK[128];
        BCK bck = new BCK("IPC_SERVICE_START", 0, "ipc_service_start");
        A0a = bck;
        BCK bck2 = new BCK("IPC_XPOST_FAIL", 1, "ipc_xpost_fail");
        A0c = bck2;
        BCK bck3 = new BCK("IPC_XPOST_START", 2, "ipc_xpost_start");
        A0d = bck3;
        BCK bck4 = new BCK("IPC_XPOST_SUCCESS", 3, "ipc_xpost_success");
        A0e = bck4;
        BCK bck5 = new BCK("IPC_GET_WA_PROFILE_FAIL", 4, "ipc_get_wa_profile_fail");
        A0W = bck5;
        BCK bck6 = new BCK("IPC_GET_WA_PROFILE_SUCCESS", 5, "ipc_get_wa_profile_success");
        A0Y = bck6;
        BCK bck7 = new BCK("IPC_GET_WA_PROFILE_START", 6, "ipc_get_wa_profile_start");
        A0X = bck7;
        BCK bck8 = new BCK("IPC_SERVICE_SUCCESS", 7, "ipc_service_success");
        A0b = bck8;
        BCK bck9 = new BCK("IPC_SERVICE_FAIL", 8, "ipc_service_fail");
        A0Z = bck9;
        BCK bck10 = new BCK("LINKING_ENTRY_SHOWN", 9, "linking_entry_shown");
        A0g = bck10;
        BCK bck11 = new BCK("LINKING_ENTRY_CLICKED", 10, "linking_entry_clicked");
        A0f = bck11;
        BCK bck12 = new BCK("AC_HOME_TOGGLE_WA_CROSSPOSTING_SETTING", 11, "ac_home_toggle_wa_crossposting_setting");
        BCK bck13 = new BCK("ALWAYS_SHARE_STORIES", 12, "always_share_stories");
        A06 = bck13;
        BCK bck14 = new BCK("ALWAYS_SHARE_STORIES_OFF_FAILURE", 13, "always_share_stories_off_failure");
        A07 = bck14;
        BCK bck15 = new BCK("ALWAYS_SHARE_STORIES_OFF_SUCCESS", 14, "always_share_stories_off_success");
        A08 = bck15;
        BCK bck16 = new BCK("ALWAYS_SHARE_STORIES_ON_FAILURE", 15, "always_share_stories_on_failure");
        A09 = bck16;
        BCK bck17 = new BCK("ALWAYS_SHARE_STORIES_ON_SUCCESS", 16, "always_share_stories_on_success");
        A0A = bck17;
        BCK bck18 = new BCK("AUTOMATICALLY_SHARE_IG", 17, "automatically_share_ig");
        BCK bck19 = new BCK("AUTOMATICALLY_SHARE_IG_OFF_SUCCESS", 18, "automatically_share_ig_off_success");
        BCK bck20 = new BCK("AUTOMATICALLY_SHARE_IG_ON_SUCCESS", 19, "automatically_share_ig_on_success");
        BCK bck21 = new BCK("AUTOMATICALLY_SHARE_IG_ON_FAILURE", 20, "automatically_share_ig_on_failure");
        BCK bck22 = new BCK("AUTOMATICALLY_SHARE_IG_OFF_FAILURE", 21, "automatically_share_ig_off_failure");
        BCK bck23 = new BCK("BOTTOM_SHEET_SHOW", 22, "bottom_sheet_show");
        BCK bck24 = new BCK("CLIENT_SETTING_CROSSPOSTING_TOGGLE_CLICKED", 23, "client_setting_crossposting_toggle_clicked");
        BCK bck25 = new BCK("CONFIRM", 24, "confirm");
        A0C = bck25;
        BCK bck26 = new BCK("CANCEL", 25, "cancel");
        A0B = bck26;
        System.arraycopy(new BCK[]{bck, bck2, bck3, bck4, bck5, bck6, bck7, bck8, bck9, bck10, bck11, bck12, bck13, bck14, bck15, bck16, bck17, bck18, bck19, bck20, bck21, bck22, bck23, bck24, bck25, bck26, new BCK("CROSSPOST_STOP_SHARING_DIALOG_DISMISSED", 26, "crosspost_stop_sharing_dialog_dismissed")}, 0, bckArr, 0, 27);
        BCK bck27 = new BCK("CROSSPOSTING_BOTTOM_SHEET_DISMISSED", 27, "crossposting_bottom_sheet_dismissed");
        BCK bck28 = new BCK("CROSSPOSTING_START_SHARING_DIALOG_DISMISSED", 28, "crossposting_start_sharing_dialog_dismissed");
        A0D = bck28;
        BCK bck29 = new BCK("CROSSPOSTING_TOGGLE_BOTTOM_SHEET_DISMISSED", 29, "crossposting_toggle_bottom_sheet_dismissed");
        BCK bck30 = new BCK("CROSSPOSTING_TOGGLE_CLICKED", 30, "crossposting_toggle_clicked");
        BCK bck31 = new BCK("CROSSPOSTING_TOGGLE_DISMISSED", 31, "crossposting_toggle_dismissed");
        A0E = bck31;
        BCK bck32 = new BCK("CROSSPOSTING_TOGGLE_FB", 32, "crossposting_toggle_fb");
        A0F = bck32;
        BCK bck33 = new BCK("CROSSPOSTING_TOGGLE_FB_OFF_SUCCESS", 33, "crossposting_toggle_fb_off_success");
        A0G = bck33;
        BCK bck34 = new BCK("CROSSPOSTING_TOGGLE_FB_ON_SUCCESS", 34, "crossposting_toggle_fb_on_success");
        A0H = bck34;
        BCK bck35 = new BCK("CROSSPOSTING_TOGGLE_FB_ON_FAILURE", 35, "crossposting_toggle_fb_on_failure");
        BCK bck36 = new BCK("CROSSPOSTING_TOGGLE_FB_OFF_FAILURE", 36, "crossposting_toggle_fb_off_failure");
        BCK bck37 = new BCK("CROSSPOSTING_TOGGLE_WA", 37, "crossposting_toggle_wa");
        A0I = bck37;
        BCK bck38 = new BCK("CROSSPOSTING_TOGGLE_WA_OFF_SUCCESS", 38, "crossposting_toggle_wa_off_success");
        A0K = bck38;
        BCK bck39 = new BCK("CROSSPOSTING_TOGGLE_WA_ON_SUCCESS", 39, "crossposting_toggle_wa_on_success");
        A0M = bck39;
        BCK bck40 = new BCK("CROSSPOSTING_TOGGLE_WA_OFF_FAILURE", 40, "crossposting_toggle_wa_off_failure");
        A0J = bck40;
        BCK bck41 = new BCK("CROSSPOSTING_TOGGLE_WA_ON_FAILURE", 41, "crossposting_toggle_wa_on_failure");
        A0L = bck41;
        BCK bck42 = new BCK("LOAD_PAGE", 42, "load_page");
        A0h = bck42;
        BCK bck43 = new BCK("SECURITY_DIALOG_CANCEL_CLICKED", 43, "security_dialog_cancel_clicked");
        BCK bck44 = new BCK("SECURITY_DIALOG_CONFIRM_CLICKED", 44, "security_dialog_confirm_clicked");
        BCK bck45 = new BCK("SECURITY_DIALOG_DISMISSED", 45, "security_dialog_dismissed");
        BCK bck46 = new BCK("SHARE_THIS_STORY", 46, "share_this_story");
        A0k = bck46;
        BCK bck47 = new BCK("SHARE_TO_FB", 47, "share_to_fb");
        A0l = bck47;
        BCK bck48 = new BCK("SHARE_TO_WA", 48, "share_to_wa");
        A0m = bck48;
        BCK bck49 = new BCK("SHARING_OPTIONS", 49, "sharing_options");
        A0n = bck49;
        BCK bck50 = new BCK("SHOW_CROSSPOSTING_START_SHARING_DIALOG", 50, "show_crossposting_start_sharing_dialog");
        A0o = bck50;
        BCK bck51 = new BCK("SHOW_CROSSPOSTING_STOP_SHARING_DIALOG", 51, "show_crossposting_stop_sharing_dialog");
        BCK bck52 = new BCK("SHOW_CROSSPOSTING_TOAST_WA", 52, "show_crossposting_toast_wa");
        BCK bck53 = new BCK("SHOW_SECURITY_DIALOG", 53, "show_security_dialog");
        System.arraycopy(new BCK[]{bck27, bck28, bck29, bck30, bck31, bck32, bck33, bck34, bck35, bck36, bck37, bck38, bck39, bck40, bck41, bck42, bck43, bck44, bck45, bck46, bck47, bck48, bck49, bck50, bck51, bck52, bck53}, 0, bckArr, 27, 27);
        A0p = bck53;
        BCK bck54 = new BCK("SHOW_WA_ALREADY_CROSSPOSTED_TOAST_SELF_VIEW", 54, "show_wa_already_crossposted_toast_self_view");
        BCK bck55 = new BCK("SHOW_WA_CROSSPOST_TOAST_SELF_VIEW", 55, "show_wa_crosspost_toast_self_view");
        BCK bck56 = new BCK("STOP_SHARING_ALL_STORIES", 56, "stop_sharing_all_stories");
        A0q = bck56;
        BCK bck57 = new BCK("DONT_SHARE_THIS_STORY", 57, "dont_share_this_story");
        BCK bck58 = new BCK("TOGGLE_WHATSAPP_CROSSPOSTING_STORY_SETTING", 58, "toggle_whatsapp_crossposting_story_setting");
        A0s = bck58;
        BCK bck59 = new BCK("WA_CROSSPOST_SELF_VIEW_CLICK", 59, "wa_crosspost_self_view_click");
        BCK bck60 = new BCK("WA_CROSSPOST_SELF_VIEW_START_CROSSPOST_DIALOG_SHOW", 60, "wa_crosspost_self_view_start_crosspost_dialog_show");
        BCK bck61 = new BCK("WA_STATUS_TOGGLE_CLICK", 61, "wa_status_toggle_click");
        A10 = bck61;
        BCK bck62 = new BCK("GENERIC_ERROR_TOAST", 62, "generic_error_toast");
        A0Q = bck62;
        BCK bck63 = new BCK("INACTIVE_STATE_DIALOG", 63, "inactive_state_dialog");
        BCK bck64 = new BCK("INACTIVE_STATE_DIALOG_DISMISSED", 64, "inactive_state_dialog_dismissed");
        A0V = bck64;
        BCK bck65 = new BCK("CROSSPOSTING_STORY_VIEWER_CLOSED_BEFORE_LOADING_STATE_DISMISSED", 65, "crossposting_story_viewer_closed_before_loading_state_dismissed");
        BCK bck66 = new BCK("TAP_SHARE_BUTTON", 66, "tap_share_button");
        A0r = bck66;
        BCK bck67 = new BCK("LOAD_PAGE_SHARE_TRAY", 67, "load_page_share_tray");
        A0i = bck67;
        BCK bck68 = new BCK("CROSSPOSTING_CACHE_CLEAN_UP_STARTED", 68, "crossposting_cache_clean_up_started");
        BCK bck69 = new BCK("CROSSPOSTING_CACHE_CLEAN_UP_SUCCESS", 69, "crossposting_cache_clean_up_success");
        BCK bck70 = new BCK("CROSSPOSTING_CACHE_CLEAN_UP_FAILURE", 70, "crossposting_cache_clean_up_failure");
        BCK bck71 = new BCK("ELIGIBILITY_PREFETCH_START", 71, "eligibility_prefetch_start");
        A0N = bck71;
        BCK bck72 = new BCK("ELIGIBILITY_PREFETCH_SUCCESS", 72, "eligibility_prefetch_success");
        A0O = bck72;
        BCK bck73 = new BCK("ELIGIBLITY_PREFETCH_FAIL", 73, "eligibility_prefetch_fail");
        A0P = bck73;
        BCK bck74 = new BCK("DATA_BUNDLE_FETCH_START", 74, "data_bundle_fetch_start");
        BCK bck75 = new BCK("DATA_BUNDLE_FETCH_SUCCESS", 75, "data_bundle_fetch_success");
        BCK bck76 = new BCK("DATA_BUNDLE_FETCH_FAIL", 76, "data_bundle_fetch_fail");
        BCK bck77 = new BCK("ACCOUNT_LINKING_START", 77, "account_linking_start");
        A04 = bck77;
        BCK bck78 = new BCK("ACCOUNT_LINKING_SUCCESS", 78, "account_linking_success");
        A05 = bck78;
        BCK bck79 = new BCK("ACCOUNT_LINKING_FAIL", 79, "account_linking_fail");
        A03 = bck79;
        System.arraycopy(new BCK[]{bck54, bck55, bck56, bck57, bck58, bck59, bck60, bck61, bck62, bck63, bck64, bck65, bck66, bck67, bck68, bck69, bck70, bck71, bck72, bck73, bck74, bck75, bck76, bck77, bck78, bck79, new BCK("WA_ACCOUNT_FETCHED", 80, "wa_account_fetched")}, 0, bckArr, 54, 27);
        BCK bck80 = new BCK("OTHER_XAPP_ACCOUNTS_PRIORITIZED_FOR_NTA", 81, "other_xapp_accounts_prioritized_for_nta");
        BCK bck81 = new BCK("AYMH_ACCOUNTS_PRIORITIZED_FOR_NTA", 82, "aymh_accounts_prioritized_for_nta");
        BCK bck82 = new BCK("USER_IN_NTA_BOUNDARY_TEST", 83, "user_in_nta_boundary_test");
        BCK bck83 = new BCK("ELIGIBLE_TO_SEE_WA_AS_SOURCE", 84, "eligible_to_see_wa_as_source");
        BCK bck84 = new BCK("NTA_ELIGIBLE_ACCOUNTS_LIST", 85, "nta_eligible_accounts_list");
        BCK bck85 = new BCK("WA_AS_SOURCE_ELIGIBLE_FOR_NTA", 86, "wa_as_source_eligible_for_nta");
        BCK bck86 = new BCK("WA_AS_SOURCE_IN_ELIGIBLE_FOR_NTA_LIST", 87, "wa_as_source_in_eligible_for_nta_list");
        BCK bck87 = new BCK("WA_AS_SOURCE_NOT_ELIGIBLE_FOR_NTA", 88, "wa_as_source_not_eligible_for_nta");
        BCK bck88 = new BCK("WA_AS_SOURCE_NOT_ELIGIBLE_FOR_NTA_REASON", 89, "wa_as_source_not_eligible_for_nta_reason");
        BCK bck89 = new BCK("WA_DATA_BUNDLE_NULL_DURING_CREATION", 90, "wa_data_bundle_null_during_creation");
        BCK bck90 = new BCK("WA_PHONE_NUMBER_FAILS_PARSER_VALIDATION", 91, "wa_phone_number_fails_parser_validation");
        BCK bck91 = new BCK("WA_AUTHPROOF_NULL_DURING_CREATION", 92, "wa_authtoken_null_during_creation");
        BCK bck92 = new BCK("WA_AUTHPROOF_ADDED_DURING_CREATION", 93, "wa_authtoken_added_during_creation");
        BCK bck93 = new BCK("WA_AUTHPROOF_RPC_SUCCESS", 94, "wa_authtoken_rpc_success");
        BCK bck94 = new BCK("WA_AUTHPROOF_AVAILABLE_NO_RPC", 95, "wa_authtoken_available_no_rpc");
        BCK bck95 = new BCK("WA_AUTHPROOF_RPC_FAIL", 96, "wa_authtoken_rpc_fail");
        BCK bck96 = new BCK("WA_AUTHPRROF_RPC_TRIGGERED", 97, "wa_authtoken_rpc_triggered");
        BCK bck97 = new BCK("EXCEPTION_DURING_TOKEN_VALIDATION", 98, "exception_during_token_validation");
        BCK bck98 = new BCK("EXCEPTION_DURING_ACCOUNT_CREATION_AND_LINKING", 99, "exception_during_account_creation_and_linking");
        BCK bck99 = new BCK("LINKING_VALIDATOR_RESULT_DURING_OPAQUE_ACCOUNT_GENERATION", 100, "linking_validator_result_during_opaque_account_generation");
        BCK bck100 = new BCK("ACCOUNT_CREATION_STARTED", 101, "account_creation_started");
        A02 = bck100;
        System.arraycopy(new BCK[]{bck80, bck81, bck82, bck83, bck84, bck85, bck86, bck87, bck88, bck89, bck90, bck91, bck92, bck93, bck94, bck95, bck96, bck97, bck98, bck99, bck100, new BCK("ACCOUNT_CREATION_SUCCESS", 102, "account_creation_success"), new BCK("WA_AS_TARGET_VALIDATOR_RESULT", 103, "wa_as_target_validator_result"), new BCK("WA_AS_TARGET_VALIDATOR_EXCEPTION", 104, "wa_as_target_validator_exception"), new BCK("WA_AS_TARGET_DURING_AUTH_VALIDATOR_RESULT", 105, "wa_as_target_during_auth_validator_result"), new BCK("WA_AS_TARGET_DURING_AUTH_VALIDATOR_EXCEPTION", 106, "wa_as_target_during_auth_validator_exception"), new BCK("WA_PRE_AUTH_NTA_VALIDATOR_RESULT", 107, "wa_pre_auth_nta_validator_result")}, 0, bckArr, 81, 27);
        BCK bck101 = new BCK("WA_PRE_AUTH_NTA_VALIDATOR_EXCEPTION", 108, "wa_pre_auth_nta_validator_exception");
        BCK bck102 = new BCK("WA_LANDING_PAGE_RENDERED", 109, "wa_landing_page_rendered");
        BCK bck103 = new BCK("LINKING_FLOW_INITIATED", 110, "linking_flow_initiated");
        BCK bck104 = new BCK("LINK_ACCOUNT_SUCCESS", 111, "link_account_success");
        BCK bck105 = new BCK("LINK_ACCOUNT_FAIL", 112, "link_account_fail");
        BCK bck106 = new BCK("IMPORT_FROM_WA_PROFILE_PICTURE_URL_FETCH_SUCCESS", 113, "import_from_wa_profile_picture_url_fetch_success");
        A0U = bck106;
        BCK bck107 = new BCK("IMPORT_FROM_WA_PROFILE_PICTURE_URL_FETCH_FAILURE", 114, "import_from_wa_profile_picture_url_fetch_failure");
        A0T = bck107;
        BCK bck108 = new BCK("IMPORT_FROM_WA_PROFILE_PICTURE_SUCCESS", 115, "import_from_wa_profile_picture_success");
        A0S = bck108;
        BCK bck109 = new BCK("IMPORT_FROM_WA_PROFILE_PICTURE_FAILURE", 116, "import_from_wa_profile_picture_failure");
        A0R = bck109;
        BCK bck110 = new BCK("UPSELLS_TARGETING_ELIGIBLE", 117, "upsells_targeting_eligible");
        BCK bck111 = new BCK("UPSELLS_TARGETING_NOT_ELIGIBLE", 118, "upsells_targeting_not_eligible");
        BCK bck112 = new BCK("UPSELL_ELIGIBILITY_CHECK_STARTED", 119, "upsell_eligibility_check_started");
        A0w = bck112;
        BCK bck113 = new BCK("UPSELL_ELIGIBILITY_CHECK_SUCCESS", 120, "upsell_eligibility_check_success");
        A0x = bck113;
        BCK bck114 = new BCK("UPSELL_ELIGIBILITY_CHECK_FAILED", 121, "upsell_eligibility_check_failed");
        A0v = bck114;
        BCK bck115 = new BCK("UPSELL_ELIGIBILITY_CACHE_UPDATED", 122, "upsell_eligibility_cache_updated");
        A0u = bck115;
        BCK bck116 = new BCK("QUERY_UPSELL_ELIGIBILITY_CACHE", 123, "query_upsell_eligibility_cache");
        A0j = bck116;
        BCK bck117 = new BCK("UPSELL_ELIGIBILITY_CACHE_EVICTED", 124, "upsell_eligibility_cache_evicted");
        A0t = bck117;
        BCK bck118 = new BCK("UPSELL_LAUNCH_STARTED", 125, "upsell_launch_started");
        BCK bck119 = new BCK("UPSELL_LAUNCH_SUCCESS", 126, "upsell_launch_success");
        A0z = bck119;
        BCK bck120 = new BCK("UPSELL_LAUNCH_FAILED", 127, "upsell_launch_failed");
        System.arraycopy(new BCK[]{bck101, bck102, bck103, bck104, bck105, bck106, bck107, bck108, bck109, bck110, bck111, bck112, bck113, bck114, bck115, bck116, bck117, bck118, bck119, bck120}, 0, bckArr, 108, 20);
        A0y = bck120;
        A01 = bckArr;
    }

    public BCK(String str, int i, String str2) {
        this.A00 = str2;
    }

    public static BCK valueOf(String str) {
        return (BCK) Enum.valueOf(BCK.class, str);
    }

    public static BCK[] values() {
        return (BCK[]) A01.clone();
    }

    @Override // p000X.InterfaceC26580vu
    public final /* bridge */ /* synthetic */ Object getValue() {
        return this.A00;
    }
}
