package p000X;

import com.instagram.fx.igxfb.IgxfbNetEgoCTABannerParams;
import com.instagram.profile.intf.AutoLaunchReelParams;
import com.instagram.profile.intf.UserDetailEntryInfo;
import com.instagram.profile.intf.UserDetailLaunchConfig;
import com.instagram.sponsored.analytics.SourceModelInfoParams;
import redex.C$StoreFenceHelper;

/* loaded from: classes6.dex */
public final class BWP {
    public IgxfbNetEgoCTABannerParams A00;
    public AutoLaunchReelParams A01;
    public UserDetailEntryInfo A02;
    public SourceModelInfoParams A03;
    public Long A04;
    public Long A05;
    public String A06;
    public String A07;
    public String A09;
    public String A0A;
    public String A0B;
    public String A0C;
    public String A0D;
    public String A0E;
    public String A0F;
    public String A0G;
    public String A0H;
    public String A0I;
    public String A0J;
    public String A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public boolean A0S;
    public boolean A0T;
    public boolean A0U;
    public boolean A0W;
    public boolean A0X;
    public boolean A0Y;
    public boolean A0Z;
    public boolean A0a;
    public boolean A0b;
    public boolean A0c;
    public boolean A0d;
    public boolean A0e;
    public boolean A0f;
    public boolean A0g;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0m;
    public boolean A0n;
    public boolean A0o;
    public boolean A0p;
    public final String A0q;
    public final String A0r;
    public boolean A0V = true;
    public String A08 = "";

    public BWP(String str, String str2, String str3) {
        this.A0r = str;
        this.A0A = str2;
        this.A0q = str3;
    }

    public final UserDetailLaunchConfig A00() {
        String str = this.A0r;
        String str2 = this.A0A;
        String str3 = this.A0q;
        String str4 = this.A0R;
        String str5 = this.A0Q;
        AutoLaunchReelParams autoLaunchReelParams = this.A01;
        String str6 = this.A0F;
        String str7 = this.A0J;
        String str8 = this.A0E;
        SourceModelInfoParams sourceModelInfoParams = this.A03;
        boolean z = this.A0W;
        boolean z2 = this.A0a;
        UserDetailEntryInfo userDetailEntryInfo = this.A02;
        boolean z3 = this.A0U;
        String str9 = this.A0M;
        boolean z4 = this.A0e;
        boolean z5 = this.A0b;
        boolean z6 = this.A0f;
        String str10 = this.A06;
        String str11 = this.A0L;
        String str12 = this.A07;
        boolean z7 = this.A0h;
        String str13 = this.A0H;
        String str14 = this.A0I;
        boolean z8 = this.A0V;
        boolean z9 = this.A0n;
        String str15 = this.A0O;
        String str16 = this.A0P;
        Long l = this.A05;
        Long l2 = this.A04;
        boolean z10 = this.A0S;
        boolean z11 = this.A0j;
        boolean z12 = this.A0Y;
        boolean z13 = this.A0X;
        boolean z14 = this.A0o;
        String str17 = this.A0B;
        boolean z15 = this.A0g;
        String str18 = this.A08;
        String str19 = this.A0K;
        boolean z16 = this.A0m;
        boolean z17 = this.A0l;
        boolean z18 = this.A0i;
        String str20 = this.A0C;
        boolean z19 = this.A0p;
        String str21 = this.A0G;
        boolean z20 = this.A0T;
        IgxfbNetEgoCTABannerParams igxfbNetEgoCTABannerParams = this.A00;
        boolean z21 = this.A0Z;
        String str22 = this.A0D;
        String str23 = this.A0N;
        boolean z22 = this.A0c;
        String str24 = this.A09;
        boolean z23 = this.A0d;
        boolean z24 = this.A0k;
        UserDetailLaunchConfig userDetailLaunchConfig = new UserDetailLaunchConfig();
        userDetailLaunchConfig.A0W = str;
        userDetailLaunchConfig.A0B = str2;
        userDetailLaunchConfig.A0D = str3;
        userDetailLaunchConfig.A0V = str4;
        userDetailLaunchConfig.A0U = str5;
        userDetailLaunchConfig.A02 = autoLaunchReelParams;
        userDetailLaunchConfig.A0J = str6;
        userDetailLaunchConfig.A0E = null;
        userDetailLaunchConfig.A0F = null;
        userDetailLaunchConfig.A0N = str7;
        userDetailLaunchConfig.A0I = str8;
        userDetailLaunchConfig.A0X = null;
        userDetailLaunchConfig.A00 = null;
        userDetailLaunchConfig.A04 = sourceModelInfoParams;
        userDetailLaunchConfig.A0c = z;
        userDetailLaunchConfig.A0g = z2;
        userDetailLaunchConfig.A03 = userDetailEntryInfo;
        userDetailLaunchConfig.A0a = z3;
        userDetailLaunchConfig.A0Q = str9;
        userDetailLaunchConfig.A0l = z4;
        userDetailLaunchConfig.A0i = z5;
        userDetailLaunchConfig.A0h = z6;
        userDetailLaunchConfig.A07 = str10;
        userDetailLaunchConfig.A0P = str11;
        userDetailLaunchConfig.A08 = str12;
        userDetailLaunchConfig.A0n = z7;
        userDetailLaunchConfig.A0L = str13;
        userDetailLaunchConfig.A0M = str14;
        userDetailLaunchConfig.A0b = z8;
        userDetailLaunchConfig.A0t = z9;
        userDetailLaunchConfig.A0S = str15;
        userDetailLaunchConfig.A0T = str16;
        userDetailLaunchConfig.A06 = l;
        userDetailLaunchConfig.A05 = l2;
        userDetailLaunchConfig.A0Y = z10;
        userDetailLaunchConfig.A0p = z11;
        userDetailLaunchConfig.A0e = z12;
        userDetailLaunchConfig.A0d = z13;
        userDetailLaunchConfig.A0u = z14;
        userDetailLaunchConfig.A0C = str17;
        userDetailLaunchConfig.A0m = z15;
        userDetailLaunchConfig.A09 = str18;
        userDetailLaunchConfig.A0O = str19;
        userDetailLaunchConfig.A0s = z16;
        userDetailLaunchConfig.A0r = z17;
        userDetailLaunchConfig.A0o = z18;
        userDetailLaunchConfig.A0G = str20;
        userDetailLaunchConfig.A0v = z19;
        userDetailLaunchConfig.A0K = str21;
        userDetailLaunchConfig.A0Z = z20;
        userDetailLaunchConfig.A01 = igxfbNetEgoCTABannerParams;
        userDetailLaunchConfig.A0f = z21;
        userDetailLaunchConfig.A0H = str22;
        userDetailLaunchConfig.A0R = str23;
        userDetailLaunchConfig.A0j = z22;
        userDetailLaunchConfig.A0A = str24;
        userDetailLaunchConfig.A0k = z23;
        userDetailLaunchConfig.A0q = z24;
        C$StoreFenceHelper.DUMMY_VOLATILE = 0;
        return userDetailLaunchConfig;
    }
}
