package p000X;

import com.facebook.video.heroplayer.setting.FbAutogeneratedSettings;
import com.facebook.video.heroplayer.setting.HeroPlayerSetting;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/* renamed from: X.6kq, reason: invalid class name and case insensitive filesystem */
/* loaded from: classes.dex */
public final class C172606kq {
    public int A02;
    public int A0Y;
    public int A0c;
    public long A0g;
    public C173766mi A0h;
    public C173766mi A0i;
    public C173766mi A0j;
    public C173766mi A0l;
    public C173766mi A0m;
    public C173766mi A0n;
    public C173766mi A0p;
    public C192427bi A12;
    public boolean A1l;
    public boolean A1v;
    public boolean A1w;
    public boolean A1x;
    public boolean A24;
    public boolean A27;
    public boolean A2F;
    public boolean A2G;
    public boolean A2I;
    public boolean A2O;
    public boolean A2P;
    public boolean A2b;
    public boolean A2h;
    public boolean A2l;
    public boolean A2p;
    public boolean A2w;
    public boolean A32;
    public boolean A34;
    public boolean A36;
    public boolean A39;
    public boolean A3B;
    public boolean A3H;
    public boolean A3L;
    public boolean A3Q;
    public boolean A3X;
    public C172656kv A0x = new C172656kv(0, 100, -1, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false);
    public FbAutogeneratedSettings A0y = HeroPlayerSetting.A3b;
    public boolean A2k = false;
    public boolean A1m = false;
    public boolean A2S = true;
    public boolean A1f = false;
    public int A0W = 3;
    public String A18 = "ExoService";
    public boolean A3O = true;
    public boolean A2K = true;
    public boolean A3U = false;
    public C173106le A0w = new C173106le(null, null, 0.3d, 0.1d, 104857600, 1048576, 0, 0, -1, -1, 10, 1, 0, 60000, 3600000, 0, 0, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false);
    public boolean A2M = false;
    public C173126lg A13 = new C173126lg(500, 2000);
    public C173126lg A14 = new C173126lg(0, 0);
    public boolean A1U = false;
    public C173146li A10 = new C173146li(0.0f, 0.0f, 0, 0, 0, 0, 0, 0);
    public boolean A33 = false;
    public boolean A37 = false;
    public C173196ln A0u = new C173196ln();
    public C173206lo A0t = C173206lo.A00;
    public C173256lt A0s = new C173256lt();
    public C173426mA A0r = new C173426mA(new C173276lv());
    public boolean A2u = false;
    public boolean A1c = false;
    public C173696mb A0v = new C173696mb();
    public boolean A29 = false;
    public C173726me A15 = new C173726me();
    public int A07 = 12323;
    public int A06 = 14151;
    public boolean A26 = false;
    public boolean A2v = false;
    public boolean A2d = false;
    public boolean A38 = false;
    public boolean A1O = false;
    public boolean A1r = false;
    public int A05 = 0;
    public int A0I = 3;
    public boolean A1p = false;
    public C173766mi A0k = new C173766mi(100000, 250, 500, 1000);
    public C173766mi A0o = new C173766mi(2000, 2000000, 550000, 150000);
    public boolean A1z = false;
    public boolean A3a = false;
    public boolean A3N = false;
    public boolean A2a = false;
    public int A0X = 0;
    public boolean A1N = false;
    public boolean A3G = false;
    public boolean A1W = false;
    public String A17 = "";
    public boolean A1n = false;
    public boolean A1y = false;
    public boolean A3A = false;
    public boolean A2r = false;
    public boolean A1K = false;
    public boolean A3Y = true;
    public boolean A2E = false;
    public boolean A2D = false;
    public int A0L = 2;
    public boolean A2m = false;
    public boolean A2n = false;
    public boolean A3T = false;
    public boolean A2f = false;
    public boolean A2e = false;
    public boolean A2t = false;
    public boolean A3c = false;
    public boolean A3b = false;
    public boolean A2x = false;
    public boolean A3E = false;
    public boolean A2Y = false;
    public boolean A3Z = false;
    public boolean A3S = false;
    public int A0F = 4000;
    public boolean A3K = false;
    public boolean A3J = false;
    public boolean A2o = false;
    public int A0a = 1;
    public boolean A3W = false;
    public boolean A3V = false;
    public boolean A1X = false;
    public boolean A2s = false;
    public boolean A2H = false;
    public boolean A3P = false;
    public int A0R = 0;
    public int A0S = 4000;
    public boolean A2y = true;
    public boolean A1o = false;
    public String A16 = "";
    public int A0K = 131072;
    public int A0J = 65536;
    public int A0H = 33000;
    public int A0G = 45000;
    public boolean A2c = true;
    public boolean A1R = false;
    public boolean A2A = false;
    public boolean A1j = false;
    public boolean A35 = false;
    public boolean A2R = false;
    public boolean A1b = false;
    public int A0T = 0;
    public int A0U = 0;
    public int A0V = 0;
    public int A04 = 0;
    public boolean A30 = false;
    public boolean A31 = false;
    public HashSet A19 = new HashSet();
    public boolean A1L = false;
    public int A0B = 1;
    public int A09 = 1;
    public int A0A = 100;
    public boolean A1P = false;
    public long A0e = 0;
    public boolean A1M = false;
    public int A0Q = 0;
    public int A0N = -1;
    public int A0Z = 8500;
    public boolean A1i = false;
    public boolean A1h = false;
    public boolean A3D = false;
    public double A00 = 1.0d;
    public boolean A3M = false;
    public boolean A2V = false;
    public boolean A2U = false;
    public boolean A2T = false;
    public int A0M = 0;
    public Set A1B = new HashSet();
    public Map A1A = new HashMap();
    public boolean A2C = false;
    public boolean A2J = false;
    public int A0D = 1;
    public boolean A2i = false;
    public int A0P = 0;
    public boolean A1s = false;
    public boolean A2Q = false;
    public boolean A1S = false;
    public int A0d = 64;
    public boolean A2B = false;
    public boolean A3F = false;
    public boolean A3C = false;
    public int A0E = 30000;
    public int A0b = -1;
    public int A0C = 4000;
    public int A01 = 4000;
    public Set A1G = new HashSet();
    public Set A1F = new HashSet();
    public Set A1H = new HashSet();
    public boolean A2q = false;
    public Set A1C = new HashSet();
    public boolean A1J = false;
    public boolean A3I = false;
    public boolean A1T = false;
    public boolean A2j = false;
    public boolean A1q = false;
    public boolean A23 = false;
    public boolean A25 = false;
    public boolean A1e = false;
    public boolean A2z = false;
    public boolean A2g = false;
    public C173806mm A11 = new C173806mm();
    public boolean A1Y = false;
    public boolean A3R = false;
    public Set A1E = new HashSet();
    public Set A1D = new HashSet();
    public Set A1I = new HashSet();
    public boolean A2Z = false;
    public int A0O = 1000;
    public boolean A2N = true;
    public boolean A1u = false;
    public boolean A20 = false;
    public boolean A21 = false;
    public long A0f = 0;
    public boolean A1t = false;
    public int A08 = 0;
    public int A03 = 0;
    public boolean A1a = false;
    public boolean A1V = false;
    public boolean A1g = false;
    public boolean A28 = false;
    public boolean A1d = false;
    public boolean A2X = false;
    public boolean A1k = false;
    public boolean A1Z = false;
    public boolean A22 = false;
    public boolean A2W = false;
    public boolean A1Q = false;
    public boolean A2L = false;
    public C173876mt A0z = null;
    public C173836mp A0q = new C173836mp(null, 0, 0, 0, 0, 0, 31);

    public final void A01() {
        this.A1f = true;
    }

    public final void A02() {
        this.A1M = true;
    }

    public final void A03() {
        this.A1N = true;
    }

    public final void A04() {
        this.A1O = true;
    }

    public final void A05() {
        this.A03 = 1;
    }

    public final void A06() {
        this.A1S = true;
    }

    public final void A07() {
        this.A1U = true;
    }

    public final void A0B() {
        this.A1X = true;
    }

    public final void A0C() {
        this.A1Y = true;
    }

    public final void A0D() {
        this.A1Z = true;
    }

    public final void A0E() {
        this.A1b = true;
    }

    public final void A0F() {
        this.A1c = true;
    }

    public final void A0G() {
        this.A1g = true;
    }

    public final void A0H() {
        this.A1J = true;
    }

    public final void A0I() {
        this.A1l = true;
    }

    public final void A0J() {
        this.A1m = true;
    }

    public final void A0K() {
        this.A1n = true;
    }

    public final void A0L() {
        this.A1q = true;
    }

    public final void A0M() {
        this.A1s = true;
    }

    public final void A0N() {
        this.A1u = true;
    }

    public final void A0O() {
        this.A23 = true;
    }

    public final void A0P() {
        this.A24 = true;
    }

    public final void A0Q() {
        this.A25 = true;
    }

    public final void A0R() {
        this.A26 = true;
    }

    public final void A0S() {
        this.A27 = true;
    }

    public final void A0T() {
        this.A28 = true;
    }

    public final void A0U() {
        this.A29 = true;
    }

    public final void A0V() {
        this.A2C = true;
    }

    public final void A0W() {
        this.A2I = true;
    }

    public final void A0X() {
        this.A2M = true;
    }

    public final void A0Y() {
        this.A2O = true;
    }

    public final void A0Z() {
        this.A2P = true;
    }

    public final void A0a() {
        this.A2R = true;
    }

    public final void A0b() {
        this.A2S = false;
    }

    public final void A0c() {
        this.A2c = false;
    }

    public final void A0d() {
        this.A2X = true;
    }

    public final void A0e() {
        this.A2a = true;
    }

    public final void A0f() {
        this.A2b = true;
    }

    public final void A0g() {
        this.A2d = true;
    }

    public final void A0h() {
        this.A2o = true;
    }

    public final void A0i() {
        this.A2p = true;
    }

    public final void A0j() {
        this.A2g = true;
    }

    public final void A0k() {
        this.A2h = true;
    }

    public final void A0l() {
        this.A2j = true;
    }

    public final void A0n() {
        this.A2k = true;
    }

    public final void A0o() {
        this.A2m = true;
    }

    public final void A0p() {
        this.A2q = true;
    }

    public final void A0q() {
        this.A2r = true;
    }

    public final void A0u() {
        this.A0I = 5;
    }

    public final void A0x() {
        this.A0M = 2;
    }

    public final void A0z() {
        this.A0Q = 1;
    }

    public final void A10() {
        this.A2u = true;
    }

    public final void A11() {
        this.A0T = 1;
    }

    public final void A12() {
        this.A0U = 1;
    }

    public final void A13() {
        this.A2w = true;
    }

    public final void A14() {
        this.A0X = 1;
    }

    public final void A17() {
        this.A2y = false;
    }

    public final void A18() {
        this.A2z = true;
    }

    public final void A19() {
        this.A34 = true;
    }

    public final void A1A() {
        this.A35 = true;
    }

    public final void A1B() {
        this.A36 = true;
    }

    public final void A1C() {
        this.A39 = false;
    }

    public final void A1D() {
        this.A3J = true;
    }

    public final void A1E() {
        this.A3K = true;
    }

    public final void A1F() {
        this.A3L = true;
    }

    public final void A1G() {
        this.A3M = true;
    }

    public final void A1H() {
        this.A3R = true;
    }

    public final void A1I() {
        this.A3T = true;
    }

    public final void A1J() {
        this.A3U = true;
    }

    public final void A1K() {
        this.A3V = true;
    }

    public final void A1L() {
        this.A3Y = false;
    }

    public final void A1M() {
        this.A3c = true;
    }

    public final HeroPlayerSetting A00() {
        return new HeroPlayerSetting(this);
    }

    public final void A08() {
        this.A06 = 12000;
    }

    public final void A09() {
        this.A07 = 6000;
    }

    public final void A0A() {
        this.A08 = 10;
    }

    public final void A0r() {
        this.A0F = 3500;
    }

    public final void A0v() {
        this.A0J = 1048576;
    }

    public final void A0w() {
        this.A0K = 1048576;
    }

    public final void A0y() {
        this.A0N = 1000;
    }

    public final void A15() {
        this.A0Y = 8000;
    }

    public final void A16() {
        this.A0Z = 15500;
    }

    public final void A1N() {
        this.A0d = 56;
    }

    public final void A1O(double d) {
        this.A00 = d;
    }

    public final void A1P(int i) {
        this.A01 = i;
    }

    public final void A1Q(int i) {
        this.A02 = i;
    }

    public final void A1R(int i) {
        this.A04 = i;
    }

    public final void A1S(int i) {
        this.A05 = i;
    }

    public final void A1T(int i) {
        this.A09 = i;
    }

    public final void A1U(int i) {
        this.A0A = i;
    }

    public final void A1V(int i) {
        this.A0B = i;
    }

    public final void A1W(int i) {
        this.A0C = i;
    }

    public final void A1X(int i) {
        this.A0D = i;
    }

    public final void A1Y(int i) {
        this.A0E = i;
    }

    public final void A1Z(int i) {
        this.A0L = i;
    }

    public final void A1a(int i) {
        this.A0O = i;
    }

    public final void A1b(int i) {
        this.A0P = i;
    }

    public final void A1c(int i) {
        this.A0R = i;
    }

    public final void A1d(int i) {
        this.A0S = i;
    }

    public final void A1e(int i) {
        this.A0V = i;
    }

    public final void A1f(int i) {
        this.A0W = i;
    }

    public final void A1g(int i) {
        this.A0a = i;
    }

    public final void A1h(int i) {
        this.A0b = i;
    }

    public final void A1i(int i) {
        this.A0c = i;
    }

    public final void A1j(long j) {
        this.A0f = j;
    }

    public final void A1k(long j) {
        this.A0g = j;
    }

    public final void A1l(C173766mi c173766mi) {
        this.A0h = c173766mi;
    }

    public final void A1m(C173766mi c173766mi) {
        this.A0i = c173766mi;
    }

    public final void A1n(C173766mi c173766mi) {
        this.A0j = c173766mi;
    }

    public final void A1o(C173766mi c173766mi) {
        this.A0l = c173766mi;
    }

    public final void A1p(C173766mi c173766mi) {
        this.A0m = c173766mi;
    }

    public final void A1q(C173766mi c173766mi) {
        this.A0n = c173766mi;
    }

    public final void A1r(C173766mi c173766mi) {
        this.A0o = c173766mi;
    }

    public final void A1s(C173766mi c173766mi) {
        this.A0p = c173766mi;
    }

    public final void A1t(C173426mA c173426mA) {
        this.A0r = c173426mA;
    }

    public final void A1u(C173206lo c173206lo) {
        this.A0t = c173206lo;
    }

    public final void A1v(C173196ln c173196ln) {
        this.A0u = c173196ln;
    }

    public final void A1w(C173696mb c173696mb) {
        this.A0v = c173696mb;
    }

    public final void A1x(C173106le c173106le) {
        this.A0w = c173106le;
    }

    public final void A1y(C172656kv c172656kv) {
        this.A0x = c172656kv;
    }

    public final void A1z(C173876mt c173876mt) {
        this.A0z = c173876mt;
    }

    public final void A20(C173146li c173146li) {
        this.A10 = c173146li;
    }

    public final void A21(C173806mm c173806mm) {
        this.A11 = c173806mm;
    }

    public final void A22(C192427bi c192427bi) {
        this.A12 = c192427bi;
    }

    public final void A23(String str) {
        this.A16 = str;
    }

    public final void A24(String str) {
        if (str == null || str.isEmpty()) {
            this.A19 = new HashSet();
        }
        HashSet hashSet = new HashSet();
        try {
            JSONArray jSONArray = (JSONArray) new JSONObject(str).get("blocklist");
            for (int i = 0; i < jSONArray.length(); i++) {
                try {
                    hashSet.add(jSONArray.getJSONObject(i).getString("decoderName").toLowerCase(Locale.ROOT));
                } catch (ExceptionInInitializerError | RuntimeException | JSONException unused) {
                }
            }
        } catch (ExceptionInInitializerError | RuntimeException | JSONException unused2) {
        }
        this.A19 = hashSet;
    }

    public final void A25(String str) {
        this.A17 = str;
    }

    public final void A26(Set set) {
        this.A1B = set;
    }

    public final void A27(Set set) {
        this.A1I = set;
    }

    public final void A28(boolean z) {
        this.A1K = z;
    }

    public final void A29(boolean z) {
        this.A1L = z;
    }

    public final void A2A(boolean z) {
        this.A1P = z;
    }

    public final void A2B(boolean z) {
        this.A1Q = z;
    }

    public final void A2C(boolean z) {
        this.A1R = z;
    }

    public final void A2D(boolean z) {
        this.A1T = z;
    }

    public final void A2E(boolean z) {
        this.A1V = z;
    }

    public final void A2F(boolean z) {
        this.A1W = z;
    }

    public final void A2G(boolean z) {
        this.A1a = z;
    }

    public final void A2H(boolean z) {
        this.A1e = z;
    }

    public final void A2I(boolean z) {
        this.A1h = z;
    }

    public final void A2J(boolean z) {
        this.A1i = z;
    }

    public final void A2K(boolean z) {
        this.A1j = z;
    }

    public final void A2L(boolean z) {
        this.A1k = z;
    }

    public final void A2M(boolean z) {
        this.A1o = z;
    }

    public final void A2N(boolean z) {
        this.A1p = z;
    }

    public final void A2O(boolean z) {
        this.A1r = z;
    }

    public final void A2P(boolean z) {
        this.A1t = z;
    }

    public final void A2Q(boolean z) {
        this.A1v = z;
    }

    public final void A2R(boolean z) {
        this.A1w = z;
    }

    public final void A2S(boolean z) {
        this.A1x = z;
    }

    public final void A2T(boolean z) {
        this.A1y = z;
    }

    public final void A2U(boolean z) {
        this.A1z = z;
    }

    public final void A2V(boolean z) {
        this.A20 = z;
    }

    public final void A2W(boolean z) {
        this.A21 = z;
    }

    public final void A2X(boolean z) {
        this.A22 = z;
    }

    public final void A2Y(boolean z) {
        this.A2A = z;
    }

    public final void A2Z(boolean z) {
        this.A2B = z;
    }

    public final void A2a(boolean z) {
        this.A2D = z;
    }

    public final void A2b(boolean z) {
        this.A2E = z;
    }

    public final void A2c(boolean z) {
        this.A2F = z;
    }

    public final void A2d(boolean z) {
        this.A2G = z;
    }

    public final void A2e(boolean z) {
        this.A2H = z;
    }

    public final void A2f(boolean z) {
        this.A2J = z;
    }

    public final void A2g(boolean z) {
        this.A2K = z;
    }

    public final void A2h(boolean z) {
        this.A2L = z;
    }

    public final void A2i(boolean z) {
        this.A2N = z;
    }

    public final void A2j(boolean z) {
        this.A2Q = z;
    }

    public final void A2k(boolean z) {
        this.A2T = z;
    }

    public final void A2l(boolean z) {
        this.A2U = z;
    }

    public final void A2m(boolean z) {
        this.A2V = z;
    }

    public final void A2n(boolean z) {
        this.A2W = z;
    }

    public final void A2o(boolean z) {
        this.A2Y = z;
    }

    public final void A2p(boolean z) {
        this.A2Z = z;
    }

    public final void A2q(boolean z) {
        this.A2e = z;
    }

    public final void A2r(boolean z) {
        this.A2f = z;
    }

    public final void A2s(boolean z) {
        this.A2i = z;
    }

    public final void A2t(boolean z) {
        this.A2l = z;
    }

    public final void A2u(boolean z) {
        this.A2n = z;
    }

    public final void A2v(boolean z) {
        this.A2s = z;
    }

    public final void A2w(boolean z) {
        this.A2t = z;
    }

    public final void A2x(boolean z) {
        this.A2v = z;
    }

    public final void A2y(boolean z) {
        this.A2x = z;
    }

    public final void A2z(boolean z) {
        this.A30 = z;
    }

    public final void A30(boolean z) {
        this.A31 = z;
    }

    public final void A31(boolean z) {
        this.A32 = z;
    }

    public final void A32(boolean z) {
        this.A33 = z;
    }

    public final void A33(boolean z) {
        this.A37 = z;
    }

    public final void A34(boolean z) {
        this.A38 = z;
    }

    public final void A35(boolean z) {
        this.A3A = z;
    }

    public final void A36(boolean z) {
        this.A3B = z;
    }

    public final void A37(boolean z) {
        this.A3C = z;
    }

    public final void A38(boolean z) {
        this.A3D = z;
    }

    public final void A39(boolean z) {
        this.A3E = z;
    }

    public final void A3A(boolean z) {
        this.A3F = z;
    }

    public final void A3B(boolean z) {
        this.A3G = z;
    }

    public final void A3C(boolean z) {
        this.A3H = z;
    }

    public final void A3D(boolean z) {
        this.A3I = z;
    }

    public final void A3E(boolean z) {
        this.A3N = z;
    }

    public final void A3F(boolean z) {
        this.A3O = z;
    }

    public final void A3G(boolean z) {
        this.A3P = z;
    }

    public final void A3H(boolean z) {
        this.A3Q = z;
    }

    public final void A3I(boolean z) {
        this.A3W = z;
    }

    public final void A3J(boolean z) {
        this.A3X = z;
    }

    public final void A3K(boolean z) {
        this.A3a = z;
    }

    public final void A3L(boolean z) {
        this.A3b = z;
    }

    public final void A3M(boolean z) {
        this.A3S = z;
    }

    public final void A3N(boolean z) {
        this.A3Z = z;
    }

    public final void A0m() {
        this.A0e = 40000L;
    }

    public final void A0s() {
        this.A0G = 45000;
    }

    public final void A0t() {
        this.A0H = 33000;
    }
}
