package p000X;

import com.instagram.api.schemas.AggregatedRatingDict;
import com.instagram.api.schemas.CommerceReviewStatisticsDictIntf;
import com.instagram.api.schemas.ImageQualityMetadataDictIntf;
import com.instagram.api.schemas.LoyaltyToplineInfoDict;
import com.instagram.api.schemas.ProductAffiliateInformationDict;
import com.instagram.api.schemas.ProductArtsLabelsDictIntf;
import com.instagram.api.schemas.ProductDiscountsDict;
import com.instagram.api.schemas.SellerBadgeDictIntf;
import com.instagram.api.schemas.UntaggableReasonIntf;
import com.instagram.model.shopping.productcheckoutproperties.ProductCheckoutPropertiesIntf;
import com.instagram.model.shopping.productimagecontainer.ProductImageContainer;
import com.instagram.user.model.ProductDetailsProductItemDict;
import com.instagram.user.model.ProductDetailsProductItemDictIntf;
import java.util.List;

/* renamed from: X.Gb3, reason: case insensitive filesystem */
/* loaded from: classes4.dex */
public class C42123Gb3 {
    public AggregatedRatingDict A00;
    public C4FZ A01;
    public CommerceReviewStatisticsDictIntf A02;
    public ImageQualityMetadataDictIntf A03;
    public LoyaltyToplineInfoDict A04;
    public ProductAffiliateInformationDict A05;
    public ProductArtsLabelsDictIntf A06;
    public ProductDiscountsDict A07;
    public C4FN A08;
    public C4FN A09;
    public SellerBadgeDictIntf A0A;
    public UntaggableReasonIntf A0B;
    public EnumC47305Ich A0C;
    public ProductCheckoutPropertiesIntf A0D;
    public ProductCheckoutPropertiesIntf A0E;
    public ProductImageContainer A0F;
    public ProductImageContainer A0G;
    public C64012a5 A0H;
    public Boolean A0I;
    public Boolean A0J;
    public Boolean A0K;
    public Boolean A0L;
    public Boolean A0M;
    public Boolean A0N;
    public Boolean A0O;
    public Boolean A0P;
    public Boolean A0Q;
    public Boolean A0R;
    public Boolean A0S;
    public Integer A0T;
    public Long A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public String A0Z;
    public String A0a;
    public String A0b;
    public String A0c;
    public String A0d;
    public String A0e;
    public String A0f;
    public String A0g;
    public String A0h;
    public String A0i;
    public String A0j;
    public String A0k;
    public String A0l;
    public String A0m;
    public String A0n;
    public String A0o;
    public List A0p;
    public List A0q;
    public List A0r;
    public final ProductDetailsProductItemDictIntf A0s;

    public C42123Gb3(ProductDetailsProductItemDictIntf productDetailsProductItemDictIntf) {
        this.A0s = productDetailsProductItemDictIntf;
        this.A05 = productDetailsProductItemDictIntf.B0c();
        this.A00 = productDetailsProductItemDictIntf.B0j();
        this.A06 = productDetailsProductItemDictIntf.B42();
        this.A0V = productDetailsProductItemDictIntf.B6u();
        this.A0I = productDetailsProductItemDictIntf.BEe();
        this.A0J = productDetailsProductItemDictIntf.BF8();
        this.A0K = productDetailsProductItemDictIntf.BF9();
        this.A0D = productDetailsProductItemDictIntf.BHZ();
        this.A0E = productDetailsProductItemDictIntf.BHa();
        this.A01 = productDetailsProductItemDictIntf.BHd();
        this.A02 = productDetailsProductItemDictIntf.BKy();
        this.A0W = productDetailsProductItemDictIntf.BLU();
        this.A0X = productDetailsProductItemDictIntf.BRc();
        this.A0Y = productDetailsProductItemDictIntf.BRd();
        this.A0Z = productDetailsProductItemDictIntf.BRe();
        this.A0a = productDetailsProductItemDictIntf.BTM();
        this.A0b = productDetailsProductItemDictIntf.BUe();
        this.A07 = productDetailsProductItemDictIntf.BWR();
        this.A0c = productDetailsProductItemDictIntf.Bdf();
        this.A0d = productDetailsProductItemDictIntf.Bkb();
        this.A0e = productDetailsProductItemDictIntf.Bkc();
        this.A0f = productDetailsProductItemDictIntf.Bkd();
        this.A0L = productDetailsProductItemDictIntf.BpX();
        this.A0M = productDetailsProductItemDictIntf.Bpd();
        this.A0N = productDetailsProductItemDictIntf.Btf();
        this.A03 = productDetailsProductItemDictIntf.Buw();
        this.A0g = productDetailsProductItemDictIntf.BxL();
        this.A0U = productDetailsProductItemDictIntf.BxO();
        this.A0O = productDetailsProductItemDictIntf.DXD();
        this.A0P = productDetailsProductItemDictIntf.DXL();
        this.A0Q = productDetailsProductItemDictIntf.Dae();
        this.A0R = productDetailsProductItemDictIntf.DcZ();
        this.A0S = productDetailsProductItemDictIntf.DlH();
        this.A04 = productDetailsProductItemDictIntf.C5C();
        this.A0F = productDetailsProductItemDictIntf.C5Q();
        this.A0h = productDetailsProductItemDictIntf.C5R();
        this.A0H = productDetailsProductItemDictIntf.C9N();
        this.A0i = productDetailsProductItemDictIntf.getName();
        this.A0j = productDetailsProductItemDictIntf.CM8();
        this.A0k = productDetailsProductItemDictIntf.CQy();
        this.A08 = productDetailsProductItemDictIntf.CRz();
        this.A0l = productDetailsProductItemDictIntf.CSH();
        this.A0p = productDetailsProductItemDictIntf.CSN();
        this.A0m = productDetailsProductItemDictIntf.CXQ();
        this.A0n = productDetailsProductItemDictIntf.Cbp();
        this.A09 = productDetailsProductItemDictIntf.Cc8();
        this.A0q = productDetailsProductItemDictIntf.CcH();
        this.A0A = productDetailsProductItemDictIntf.ChC();
        this.A0C = productDetailsProductItemDictIntf.CnF();
        this.A0T = productDetailsProductItemDictIntf.CnG();
        this.A0G = productDetailsProductItemDictIntf.D0R();
        this.A0o = productDetailsProductItemDictIntf.D60();
        this.A0B = productDetailsProductItemDictIntf.D79();
        this.A0r = productDetailsProductItemDictIntf.D9X();
    }

    public final ProductDetailsProductItemDict A00() {
        ProductAffiliateInformationDict productAffiliateInformationDict = this.A05;
        AggregatedRatingDict aggregatedRatingDict = this.A00;
        ProductArtsLabelsDictIntf productArtsLabelsDictIntf = this.A06;
        String str = this.A0V;
        Boolean bool = this.A0I;
        Boolean bool2 = this.A0J;
        Boolean bool3 = this.A0K;
        ProductCheckoutPropertiesIntf productCheckoutPropertiesIntf = this.A0D;
        ProductCheckoutPropertiesIntf productCheckoutPropertiesIntf2 = this.A0E;
        C4FZ c4fz = this.A01;
        CommerceReviewStatisticsDictIntf commerceReviewStatisticsDictIntf = this.A02;
        String str2 = this.A0W;
        String str3 = this.A0X;
        String str4 = this.A0Y;
        String str5 = this.A0Z;
        String str6 = this.A0a;
        String str7 = this.A0b;
        ProductDiscountsDict productDiscountsDict = this.A07;
        String str8 = this.A0c;
        String str9 = this.A0d;
        String str10 = this.A0e;
        String str11 = this.A0f;
        Boolean bool4 = this.A0L;
        Boolean bool5 = this.A0M;
        Boolean bool6 = this.A0N;
        ImageQualityMetadataDictIntf imageQualityMetadataDictIntf = this.A03;
        String str12 = this.A0g;
        Long l = this.A0U;
        Boolean bool7 = this.A0O;
        Boolean bool8 = this.A0P;
        Boolean bool9 = this.A0Q;
        Boolean bool10 = this.A0R;
        Boolean bool11 = this.A0S;
        LoyaltyToplineInfoDict loyaltyToplineInfoDict = this.A04;
        ProductImageContainer productImageContainer = this.A0F;
        String str13 = this.A0h;
        C64012a5 c64012a5 = this.A0H;
        String str14 = this.A0i;
        String str15 = this.A0j;
        String str16 = this.A0k;
        C4FN c4fn = this.A08;
        String str17 = this.A0l;
        List list = this.A0p;
        String str18 = this.A0m;
        String str19 = this.A0n;
        C4FN c4fn2 = this.A09;
        List list2 = this.A0q;
        SellerBadgeDictIntf sellerBadgeDictIntf = this.A0A;
        EnumC47305Ich enumC47305Ich = this.A0C;
        Integer num = this.A0T;
        return new ProductDetailsProductItemDict(aggregatedRatingDict, c4fz, commerceReviewStatisticsDictIntf, imageQualityMetadataDictIntf, loyaltyToplineInfoDict, productAffiliateInformationDict, productArtsLabelsDictIntf, productDiscountsDict, c4fn, c4fn2, sellerBadgeDictIntf, this.A0B, enumC47305Ich, productCheckoutPropertiesIntf, productCheckoutPropertiesIntf2, productImageContainer, this.A0G, c64012a5, bool, bool2, bool3, bool4, bool5, bool6, bool7, bool8, bool9, bool10, bool11, num, l, str, str2, str3, str4, str5, str6, str7, str8, str9, str10, str11, str12, str13, str14, str15, str16, str17, str18, str19, this.A0o, list, list2, this.A0r);
    }
}
