package p000X;

/* renamed from: X.4E5, reason: invalid class name */
/* loaded from: classes7.dex */
public enum C4E5 implements InterfaceC26580vu {
    ACR_BROWSER_ENTRY_POINT_GALLERY("ACR_BROWSER_ENTRY_POINT_GALLERY"),
    ACR_BROWSER_ENTRY_POINT_DESTINATION_PICKER("ACR_BROWSER_ENTRY_POINT_DESTINATION_PICKER"),
    ACR_BROWSER_ENTRY_POINT_MIDCARD("ACR_BROWSER_ENTRY_POINT_MIDCARD"),
    ACR_BROWSER_ENTRY_POINT_NOTIFICATION("ACR_BROWSER_ENTRY_POINT_NOTIFICATION"),
    ACR_BROWSER_ENTRY_POINT_REELS_VIEWER("ACR_BROWSER_ENTRY_POINT_REELS_VIEWER"),
    ACR_BROWSER_ENTRY_POINT_PROFILE_CREATION_MENU("ACR_BROWSER_ENTRY_POINT_PROFILE_CREATION_MENU"),
    ACR_BROWSER_ENTRY_POINT_AUDIO_PAGE("ACR_BROWSER_ENTRY_POINT_AUDIO_PAGE"),
    ACR_BROWSER_ENTRY_POINT_CAMERA_ROLL_MIDCARD("ACR_BROWSER_ENTRY_POINT_CAMERA_ROLL_MIDCARD"),
    ACR_BROWSER_ENTRY_UNTRACKED("ACR_BROWSER_ENTRY_UNTRACKED");

    public final String A00;

    C4E5(String str) {
        this.A00 = str;
    }

    @Override // p000X.InterfaceC26580vu
    public final /* bridge */ /* synthetic */ Object getValue() {
        return this.A00;
    }
}
