package p000X;

/* renamed from: X.8Y7, reason: invalid class name */
/* loaded from: classes6.dex */
public abstract class C8Y7 {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 0:
                return "first_system_dispatch_mutation_start";
            case 1:
                return "first_system_dispatch_mutation_end";
            case 2:
                return "cancel_send_mutations";
            case 3:
                return "dispatch_mutation_start";
            case 4:
                return "dispatch_mutation_end";
            case 5:
                return "send_mutation_start";
            case 6:
                return "send_mutation_end";
            case 7:
                return "send_mutation";
            case 8:
                return "schedule_mutations";
            case 9:
                return "execute_mutation_start";
            case 10:
                return "execute_mutation_end";
            case 11:
                return "create_armadillo_express_protobuf_payload_start";
            case 12:
                return "create_armadillo_express_protobuf_payload_end";
            case 13:
                return "send_text_message_mutation_start";
            case 14:
                return "send_text_message_mutation_end";
            case 15:
                return "send_armadillo_express_payload_start";
            case 16:
                return "send_armadillo_express_payload_end";
            case 17:
                return "armadillo_express_event_listener_send_success_start";
            case 18:
                return "armadillo_express_event_listener_send_success_end";
            case 19:
                return "handle_outgoing_payload_start";
            case 20:
                return "handle_outgoing_payload_end";
            case 21:
                return "bump_thread_start";
            case 22:
                return "bump_thread_end";
            case 23:
                return "remove_message_context_start";
            case 24:
                return "remove_message_context_end";
            case 25:
                return "process_dm_message_start";
            case 26:
                return "process_dm_message_end";
            case 27:
                return "message_sync_start";
            case 28:
                return "message_sync_end";
            case 29:
                return "flow_connect_id";
            case 30:
                return "armadillo_tlc_control_open_thread";
            case 31:
                return "send_server_authoritative";
            case 32:
                return "mqtt_publish";
            case 33:
                return "mqtt_ack";
            case 34:
                return "mqtt_failure";
            case 35:
            default:
                return "skip_schedule_send_mutations_on_dispatch";
            case 36:
                return "http_publish";
            case 37:
                return "http_response";
            case 38:
                return "http_failure";
            case 39:
                return "direct_mutation_execute";
            case 40:
                return "direct_mutation_success";
            case 41:
                return "direct_mutation_confirm";
            case 42:
                return "direct_mutation_dispatch";
            case 43:
                return AnonymousClass019.A00(1229);
            case 44:
                return "direct_mutation_cancel";
            case 45:
                return "direct_mutation_retry";
            case 46:
                return "direct_mutation_drop";
            case 47:
                return "media_scrutiny_success";
            case 48:
                return "media_scrutiny_failed";
            case 49:
                return "render_video_success";
            case 50:
                return "render_video_failed";
            case 51:
                return "pii_removal_start";
            case 52:
                return "pii_removal_success";
            case 53:
                return "pii_removal_failed";
            case 54:
                return "msys_api_main_context_invoked";
            case 55:
                return "mcc_error_domain";
            case 56:
                return "mcc_error_event";
            case 57:
                return "mcc_error_sub_event";
            case 58:
                return "mcc_error_code";
            case 59:
                return "lss_end_flow_succeed";
            case 60:
                return "start_flow_from_dispatch";
        }
    }
}
