package p000X;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* renamed from: X.NVp, reason: case insensitive filesystem */
/* loaded from: classes12.dex */
public final class EnumC59759NVp implements InterfaceC26580vu {
    public static final /* synthetic */ EnumC59759NVp[] A01;
    public static final EnumC59759NVp A02;
    public final String A00;

    static {
        EnumC59759NVp[] enumC59759NVpArr = new EnumC59759NVp[173];
        EnumC59759NVp A00 = A00("IG_ORDERS_LIST", "ig_orders_list", 0);
        EnumC59759NVp A002 = A00("GAME_BALANCE", "game_balance", 1);
        EnumC59759NVp A003 = A00("STAR_BALANCE", "star_balance", 2);
        A02 = A003;
        System.arraycopy(new EnumC59759NVp[]{A00, A002, A003, A00("SECURITY_SETTINGS", "security_settings", 3), A00("CONFIRMATION_TOAST", "confirmation_toast", 4), A00("LITE_CHECKOUT", "lite_checkout", 5), A00("SHOPS_LITE_DISCLAIMER", "shops_lite_disclaimer", 6), new EnumC59759NVp("SHOW_MERCHANT_BRANDING", 7, "SHOW_MERCHANT_BRANDING"), new EnumC59759NVp("HIDE_MERCHANT_BRANDING", 8, "HIDE_MERCHANT_BRANDING"), A00("APM_BUTTON", "apm_button", 9), A00("CHECKOUT", "checkout", 10), A00("CHECKOUT_ADD_COUPON_CODE", "checkout_add_coupon_code", 11), A00("CHECKOUT_ADDRESS_CITY", "checkout_address_city", 12), A00("CHECKOUT_ADDRESS_LINE_ONE", "checkout_address_line_one", 13), A00("CHECKOUT_ADDRESS_LINE_TWO", "checkout_address_line_two", 14), A00("CHECKOUT_ADDRESS_POSTAL_CODE", "checkout_address_postal_code", 15), A00("CHECKOUT_ADDRESS_STATE", "checkout_address_state", 16), A00("CHECKOUT_ADDRESS_TYPEAHEAD", "checkout_address_typeahead", 17), A00("CHECKOUT_ASYNC_LOAD_NUX", "checkout_async_load_nux", 18), A00("CHECKOUT_ASYNC_LOAD_PUX", "checkout_async_load_pux", 19), A00("CHECKOUT_AUTOFILL_CITY_STATE", "checkout_autofill_city_state", 20), A00("CHECKOUT_BANNER", "checkout_banner", 21), A00("CHECKOUT_BILLING_ADDRESS_CONFIRMATION_INTERSITIAL", "checkout_billing_address_confirmation_intersitial", 22), A00("CHECKOUT_CARD_CSC", "checkout_card_csc", 23), A00("CHECKOUT_CARD_EXPIRATION", "checkout_card_expiration", 24), A00("CHECKOUT_CARD_NUMBER", "checkout_card_number", 25), A00("CHECKOUT_CARDINAL", "checkout_cardinal", 26)}, 0, enumC59759NVpArr, 0, 27);
        System.arraycopy(new EnumC59759NVp[]{A00("CHECKOUT_CONTACT_INFO_SECTION", "checkout_contact_info_section", 27), A00("CHECKOUT_CREDENTIAL_LINK", "checkout_credential_link", 28), A00("CHECKOUT_CREDENTIAL_REAUTH", "checkout_credential_reauth", 29), A00("CHECKOUT_CREDENTIALAUTOCONNECT_BANNER", "checkout_credentialautoconnect_banner", 30), A00("CHECKOUT_DELIVERY_SECTION", "checkout_delivery_section", 31), A00("CHECKOUT_DROPS_CHECKING_AVAILABILITY", "checkout_drops_checking_availability", 32), A00("CHECKOUT_EMAIL", "checkout_email", 33), A00("CHECKOUT_EMAIL_PREFILLED", "checkout_email_prefilled", 34), A00("CHECKOUT_ERROR_DIALOG", "checkout_error_dialog", 35), A00("CHECKOUT_ERROR_MISSING_INFO_DIALOG", "checkout_error_missing_info_dialog", 36), A00("CHECKOUT_ERROR_VIEW", "checkout_error_view", 37), A00("CHECKOUT_EXPIRED_CARD_CSC", "checkout_expired_card_csc", 38), A00("CHECKOUT_EXPIRED_CARD_EXPIRATION_DATE", "checkout_expired_card_expiration_date", 39), A00("CHECKOUT_EXPIRED_CREDIT_CARD", "checkout_expired_credit_card", 40), A00("CHECKOUT_EXPRESS_CHECKOUT_CONSENT", "checkout_express_checkout_consent", 41), A00("CHECKOUT_EXPRESS_CHECKOUT_ACCOUNT_CENTER", "checkout_express_checkout_account_center", 42), A00("CHECKOUT_FAUCET", "checkout_faucet", 43), A00("CHECKOUT_FBCONNECT_BANNER", "checkout_fbconnect_banner", 44), A00("CHECKOUT_FBCONNECT_PAYMENT_BANNER", "checkout_fbconnect_payment_banner", 45), A00("CHECKOUT_FETCH", "checkout_fetch", 46), A00("CHECKOUT_FORM", "checkout_form", 47), A00("CHECKOUT_FORM_VALIDATION_ERROR", "checkout_form_validation_error", 48), A00("CHECKOUT_GIFT_TOGGLE", "checkout_gift_toggle", 49), A00("CHECKOUT_NAME", "checkout_name", 50), A00("CHECKOUT_FULL_NAME", "checkout_full_name", 51), A00("CHECKOUT_FIRST_NAME", "checkout_first_name", 52), A00("CHECKOUT_LAST_NAME", "checkout_last_name", 53)}, 0, enumC59759NVpArr, 27, 27);
        System.arraycopy(new EnumC59759NVp[]{A00("CHECKOUT_MODULE_ENTRYPOINT", "checkout_module_entrypoint", 54), A00("CHECKOUT_NAVBAR", "checkout_navbar", 55), A00("CHECKOUT_NUX_CONTACT_AND_SHIPPING_FORM_VALIDATION", "checkout_nux_contact_and_shipping_form_validation", 56), A00("CHECKOUT_NUX_PAYMENT_FORM_VALIDATION", "checkout_nux_payment_form_validation", 57), A00("CHECKOUT_NUX_EXIT_DIALOG", "checkout_nux_exit_dialog", 58), A00("CHECKOUT_NUX_FORM_VALIDATION", "checkout_nux_form_validation", 59), A00("CHECKOUT_NUX_LABEL", "checkout_nux_label", 60), A00("CHECKOUT_NUX_LABEL_FB_FUNDED_FREE_SHIPPING", "checkout_nux_label_fb_funded_free_shipping", 61), A00("CHECKOUT_OPEN_SHOP_PAY_CONNECT_FLOW_ASYNC", "open_shop_pay_connect_flow_async", 62), A00("CHECKOUT_OPP", "checkout_opp", 63), A00("CHECKOUT_OPP_FORM_VALIDATION", "checkout_opp_form_validation", 64), A00("CHECKOUT_ORDER_CANCELLATION", "checkout_order_cancellation", 65), A00("CHECKOUT_ORDER_CONFIRMATION", "checkout_order_confirmation", 66), A00("CHECKOUT_ORDER_CONFIRMATION_GIFT_BANNER", "checkout_order_confirmation_gift_banner", 67), A00("CHECKOUT_PHONE_NUMBER", "checkout_phone_number", 68), A00("CHECKOUT_QUEUE_LOADING", "checkout_queue_loading", 69), A00("CHECKOUT_SOLD_OUT", "checkout_sold_out", 70), A00("CHECKOUT_ORDER_CONFIRMATION_RECOMMENDATION", "checkout_order_confirmation_recommendation", 71), A00("CHECKOUT_ORDER_CONFIRMATION_RECOMMENDATION_PRODUCT_TILE", "checkout_order_confirmation_recommendation_product_tile", 72), A00("CHECKOUT_ORDER_DEDUPLICATION_INTERSITIAL", "checkout_order_deduplication_intersitial", 73), A00("CHECKOUT_ORDER_DETAILS_SECTION", "checkout_order_details_section", 74), A00("CHECKOUT_ORDER_PROCESSING", "checkout_order_processing", 75), A00("CHECKOUT_OFFER_LIST", "checkout_offer_list", 76), A00("CHECKOUT_PAYMENT_METHOD_LOCK", "checkout_payment_method_lock", 77), A00("CHECKOUT_PAYMENT_METHOD", "checkout_payment_method", 78), A00("CHECKOUT_PAYMENT_METHOD_SECTION", "checkout_payment_method_section", 79), A00("CHECKOUT_PAYMENT_STATUS", "checkout_payment_status", 80)}, 0, enumC59759NVpArr, 54, 27);
        System.arraycopy(new EnumC59759NVp[]{A00("CHECKOUT_PAYPAL_BA_CONVERSION_CONSENT_CONFIRM", "checkout_paypal_ba_conversion_consent_confirm", 81), A00("CHECKOUT_PAYPAL_EC_BUTTON", "checkout_paypal_ec_button", 82), A00("CHECKOUT_PAYPAL_BA_EC_BUTTON", "checkout_paypal_ba_ec_button", 83), A00("CHECKOUT_PAYPAL_OTC_EC_BUTTON", "checkout_paypal_otc_ec_button", 84), A00("CHECKOUT_PAYPAL_EC_SIDE_BY_SIDE_BUTTON", "checkout_paypal_ec_side_by_side_button", 85), A00("CHECKOUT_PAY_WITH_SECTION", "checkout_pay_with_section", 86), A00("CHECKOUT_PRICE_MISMATCH_TOGGLE", "checkout_price_mismatch_toggle", 87), A00("CHECKOUT_PRICE_TABLE_URGENCY_MESSAGE", "checkout_price_table_urgency_message", 88), A00("CHECKOUT_PICKUP_LOCATIONS", "checkout_pickup_locations", 89), A00("CHECKOUT_PRODUCT_VARIANT_BOTTOMSHEET", "checkout_product_variant_bottomsheet", 90), A00("CHECKOUT_PROMOCODE", "checkout_promocode", 91), A00("CHECKOUT_REFETCH", "checkout_refetch", 92), A00("CHECKOUT_REVIEW_ORDER", "checkout_review_order", 93), A00("CHECKOUT_REVIEW_ORDER_EXIT_DIALOG", "checkout_review_order_exit_dialog", 94), A00("CHECKOUT_REVIEW_ORDER_UPDATE_CARD", "checkout_review_order_update_card", 95), A00("CHECKOUT_REWARD_OFFERS_SECTION", "checkout_reward_offers_section", 96), A00("CHECKOUT_SAVE_USER_DATA_TOGGLE", "checkout_save_user_data_toggle", 97), A00("CHECKOUT_SHIP_TO_SECTION", "checkout_ship_to_section", 98), A00("CHECKOUT_SHIPPING_ADDRESS", "checkout_shipping_address", 99), A00("CHECKOUT_SHIPPING_SPEED", "checkout_shipping_speed", 100), A00("CHECKOUT_SHOP_PAY_EC_BUTTON", "checkout_shop_pay_ec_button", 101), A00("CHECKOUT_SHOP_PAY_EC_SIDE_BY_SIDE_BUTTON", "checkout_shop_pay_ec_side_by_side_button", 102), A00("CHECKOUT_SHOP_PAY_INTERSTITIAL", "checkout_shop_pay_interstitial", 103), A00("CHECKOUT_SHOP_PAY_INTERSTITIAL_NOT_NOW", "checkout_shop_pay_interstitial_not_now", 104), A00("CHECKOUT_SPINNER_OVERLAY", "checkout_spinner_overlay", 105), A00("CHECKOUT_STRIPE_3DS_REDIRECT", "checkout_stripe_3ds_redirect", 106), A00("CHECKOUT_TTRC_COMPLETED", "checkout_ttrc_completed", 107)}, 0, enumC59759NVpArr, 81, 27);
        System.arraycopy(new EnumC59759NVp[]{A00("CHECKOUT_UPDATE_CARD_CSC", "checkout_update_card_csc", 108), A00("CHECKOUT_UPDATE_CARD_EXPIRATION_DATE", "checkout_update_card_expiration_date", 109), A00("CHECKOUT_UPDATE_CHECKOUT", "checkout_update_checkout", 110), A00("CHECKOUT_UPDATE_CREDIT_CARD", "checkout_update_credit_card", 111), A00("CHECKOUT_ZIPCODE_AUTOFILL_CITY", "checkout_zipcode_autofill_city", 112), A00("CHECKOUT_ZIPCODE_AUTOFILL_STATE", "checkout_zipcode_autofill_state", 113), A00("CHECKOUT_UPSELL_DISCOUNT", "checkout_upsell_discount", 114), A00("CHECKOUT_PIVOTS_ITEM_DETAILS", "checkout_pivots_item_details", 115), A00("FIELD_AUTOFOCUS", "field_autofocus", 116), A00("NUX_CHECKOUT", "nux_checkout", 117), A00("PUX_CHECKOUT", "pux_checkout", 118), A00("SELECTED_CREDENTIAL", "selected_credential", 119), A00("ADD_EMAIL", "add_email", 120), A00("ADD_EMAIL_NUX", "add_email_nux", 121), A00("EDIT_EMAIL", "edit_email", 122), A00("EDIT_EMAIL_NUX", "edit_email_nux", 123), A00("REMOVE_EMAIL", "remove_email", 124), A00("ADD_PHONE_NUMBER", "add_phone_number", 125), A00("ADD_PHONE_NUMBER_NUX", "add_phone_number_nux", 126), A00("EDIT_PHONE_NUMBER", "edit_phone_number", 127), A00("EDIT_PHONE_NUMBER_NUX", "edit_phone_number_nux", 128), A00("REMOVE_PHONE_NUMBER", "remove_phone_number", 129), A00("ADD_SHIPPING_ADDRESS", "add_shipping_address", 130), A00("ADD_SHIPPING_ADDRESS_NUX", "add_shipping_address_nux", 131), A00("EDIT_SHIPPING_ADDRESS", "edit_shipping_address", 132), A00("EDIT_SHIPPING_ADDRESS_NUX", "edit_shipping_address_nux", 133), A00("REMOVE_SHIPPING_ADDRESS", "remove_shipping_address", 134)}, 0, enumC59759NVpArr, 108, 27);
        System.arraycopy(new EnumC59759NVp[]{A00("ADD_CARD", "add_card", 135), A00("ADD_CARD_NUX", "add_card_nux", 136), A00("ADD_PAYPAL_BA", "add_paypal_ba", 137), A00("ADD_PAYPAL_BA_NUX", "add_paypal_ba_nux", 138), A00("EDIT_CARD", "edit_card", 139), A00("EDIT_CARD_NUX", "edit_card_nux", 140), A00("REMOVE_CARD", "remove_card", 141), A00("REMOVE_PAYPAL", "remove_paypal", 142), A00("LPM_NEXT_ACTION", "lpm_next_action", 143), new EnumC59759NVp("PREFETCH", 144, "PREFETCH"), A00("BUSINESS_DETAILS", "business_details", 145), A00("BUSINESS_REQUIRED", "business_required", 146), A00("ONBOARDING_STATUS", "onboarding_status", 147), A00("OWNER_DETAILS", "owner_details", 148), A00("PAYOUT_INFO", "payout_info", 149), A00("SELECT_EXISTING_FE", "select_existing_fe", 150), A00("SELECT_EXISTING_PAYOUT_CREDENTIAL", "select_existing_payout_credential", 151), A00("TAX_VERIFICATION_INTRO", "tax_verification_intro", 152), A00("TAX_VERIFICATION_UPLOAD_FORM", "tax_verification_upload_form", 153), A00("USE_EXISTING_FE", "use_existing_fe", 154), A00("USE_EXISTING_FE_BUSINESSES", "use_existing_fe_businesses", 155), A00("TASKLESS_TAX_NOTIFICATION", "taskless_tax_notification", 156), A00("CART_LINK_SHOP_PAY", "cart_link_shop_pay", 157), A00("CART_LINK_PAYPAL", "cart_link_paypal", 158), A00("CHALLENGE_DISPLAY", "challenge_display", 159), A00("COMPLETE_3DS", "complete_3ds", 160), A00("COMPLETE_REDIRECT_3DS", "complete_redirect_3ds", 161)}, 0, enumC59759NVpArr, 135, 27);
        System.arraycopy(new EnumC59759NVp[]{A00("CHALLENGE_FAIL", "challenge_fail", 162), A00("CHALLENGE_SUCCESS", "challenge_success", 163), A00("CHALLENGE_COMPLETE", "challenge_complete", 164), A00("DEVICE_DATA_COLLECTION", "device_data_collection", 165), A00("FETCH_STEP_UP_URL_STATUS", "fetch_step_up_auth_url", 166), A00("THREEDS_CARDINAL_INIT_XCONTROLLER", "3ds_cardinal_init_xcontroller", 167), A00("THREEDS_CARDINAL_INIT_COMPONENT", "3ds_cardinal_init_component", 168), A00("LOAD_3DS_INIT_URL", "load_3ds_init_url", 169), A00("THREEDS_ELIGIBILITY", "3ds_eligibility", 170), A00("THREEDS_INIT_COMPONENT", "3ds_init_component", 171), A00("THREEDS_INIT_XCONTROLLER", "3ds_init_xcontroller", 172)}, 0, enumC59759NVpArr, 162, 11);
        A01 = enumC59759NVpArr;
    }

    public EnumC59759NVp(String str, int i, String str2) {
        this.A00 = str2;
    }

    public static EnumC59759NVp A00(String str, String str2, int i) {
        return new EnumC59759NVp(str, i, str2);
    }

    public static EnumC59759NVp valueOf(String str) {
        return (EnumC59759NVp) Enum.valueOf(EnumC59759NVp.class, str);
    }

    public static EnumC59759NVp[] values() {
        return (EnumC59759NVp[]) A01.clone();
    }

    @Override // p000X.InterfaceC26580vu
    public final /* bridge */ /* synthetic */ Object getValue() {
        return this.A00;
    }
}
