package p000X;

/* renamed from: X.Ekr, reason: case insensitive filesystem */
/* loaded from: classes5.dex */
public enum EnumC37637Ekr implements InterfaceC26580vu {
    PRE_CAPTURE("PRE_CAPTURE"),
    TIMELINE_AUDIO_GHOST_TRACK("TIMELINE_AUDIO_GHOST_TRACK"),
    TIMELINE_AUDIO_REPLACE("TIMELINE_AUDIO_REPLACE"),
    POST_CAPTURE_AUDIO_BUTTON("POST_CAPTURE_AUDIO_BUTTON"),
    POST_CAPTURE_AUDIO_PILL("POST_CAPTURE_AUDIO_PILL"),
    POST_CAPTURE_AUDIO_BROWSE("POST_CAPTURE_AUDIO_BROWSE"),
    AUDIO_EDITOR_TRACK_DETAILS("AUDIO_EDITOR_TRACK_DETAILS"),
    GALLERY_DESTINATION_BAR("GALLERY_DESTINATION_BAR"),
    TIMELINE_TOOLBAR_AUDIO_OPTION("TIMELINE_TOOLBAR_AUDIO_OPTION"),
    CHOOSE_MUSIC_ON_PROFILE("CHOOSE_MUSIC_ON_PROFILE"),
    FEED_DIALOG_REPLACE_AUDIO("FEED_DIALOG_REPLACE_AUDIO"),
    SHARE_SHEET("SHARE_SHEET"),
    CHOOSE_MUSIC_ON_NOTES("CHOOSE_MUSIC_ON_NOTES"),
    MUSIC_NOTE_SONG_ATTRIBUTION("MUSIC_NOTE_SONG_ATTRIBUTION"),
    NO_MUSIC_BROWSER("NO_MUSIC_BROWSER"),
    ADD_AUDIO("ADD_AUDIO"),
    /* JADX INFO: Fake field, exist only in values array */
    SELF_PROFILE_MUSIC_SWAP_AWARENESS_CAMPAIGN("SELF_PROFILE_MUSIC_SWAP_AWARENESS_CAMPAIGN"),
    AUDIO_EDITOR_CHANGE_AUDIO("AUDIO_EDITOR_CHANGE_AUDIO"),
    STORY_MUSIC_STICKER("STORY_MUSIC_STICKER"),
    STORY_ADD_YOURS_MUSIC_STICKER("STORY_ADD_YOURS_MUSIC_STICKER"),
    /* JADX INFO: Fake field, exist only in values array */
    ADD_SOUND_EFFECTS("ADD_SOUND_EFFECTS"),
    /* JADX INFO: Fake field, exist only in values array */
    REPLACE_SOUND_EFFECTS("REPLACE_SOUND_EFFECTS"),
    /* JADX INFO: Fake field, exist only in values array */
    EDIT_FEED_POST_ADD_AUDIO("EDIT_FEED_POST_ADD_AUDIO"),
    AI_CHARACTERS_CONTENT("AI_CHARACTERS_CONTENT"),
    /* JADX INFO: Fake field, exist only in values array */
    BASEL_AUDIO_UNAVAILABLE_DIALOG_REPLACE_AUDIO("BASEL_AUDIO_UNAVAILABLE_DIALOG_REPLACE_AUDIO");

    public final String A00;

    EnumC37637Ekr(String str) {
        this.A00 = str;
    }

    @Override // p000X.InterfaceC26580vu
    public final /* bridge */ /* synthetic */ Object getValue() {
        return this.A00;
    }
}
