package p000X;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes10.dex */
public final class JOH implements InterfaceC26580vu {
    public static final /* synthetic */ JOH[] A01;
    public static final JOH A02;
    public static final JOH A03;
    public static final JOH A04;
    public static final JOH A05;
    public final String A00;

    static {
        JOH[] johArr = new JOH[250];
        System.arraycopy(new JOH[]{A00("CLICK", "click", 0), A00("MOUNT", "mount", 1), A00("CLOSE", "close", 2), A00("TOGGLE_ON", "toggle_on", 3), A00("TOGGLE_OFF", "toggle_off", 4), A00("VIEW", "view", 5), A00("TOOLTIP_OPENED", "tooltip_opened", 6), A00("TOOLTIP_CLOSED", "tooltip_closed", 7), A00("COMPOSER_GENERATE_ENT_SHARE", "composer_generate_ent_share", 8), A00("COMPOSER_GENERATE_ENT_SHARE_BEGIN", "composer_generate_ent_share_begin", 9), A00("COMPOSER_GENERATE_ENT_SHARE_SUCCESS", "composer_generate_ent_share_success", 10), A00("CALL_EXTENSION_RENDER", "call_extension_render", 11), A00("CALL_EXTENSION_VIEW_CALL_CLICKED", "call_extension_view_call_clicked", 12), A00("CALL_EXTENSION_IOS_WAB_HIDE_ADDON", "call_extension_ios_wab_hide_addon", 13), A00("CALL_EXTENSION_IOS_WAB_UNHIDE_ADDON", "call_extension_ios_wab_unhide_addon", 14), A00("CALL_EXTENSION_FAIL_GET_POST_ID_FOR_CALL_EXTENSION_AD", "call_extension_fail_get_post_id_for_call_extension_ad", 15), A00("CALL_EXTENSION_PHONE_DATA_NOT_SET_ON_POST_FOR_IMAGE_AD", "call_extension_phone_data_not_set_on_post_for_image_ad", 16), A00("CALL_EXTENSION_PHONE_DATA_NOT_SET_ON_POST_FOR_VIDEO_AD", "call_extension_phone_data_not_set_on_post_for_video_ad", 17), A00("CALL_EXTENSION_GET_DEFAULTING_PREFERENCES_START", "call_extension_get_defaulting_preferences_start", 18), A00("CALL_EXTENSION_GET_DEFAULTING_PREFERENCES_SUCCESS", "call_extension_get_defaulting_preferences_success", 19), A00("CALL_EXTENSION_GET_DEFAULTING_PREFERENCES_FAIL", "call_extension_get_defaulting_preferences_fail", 20), A00("CALL_EXTENSION_APPLY_DEFAULTING_START", "call_extension_apply_defaulting_start", 21), A00("CALL_EXTENSION_APPLY_DEFAULTING_SUCCESS", "call_extension_apply_defaulting_success", 22), A00("CALL_EXTENSION_APPLY_DEFAULTING_FAIL", "call_extension_apply_defaulting_fail", 23), A00("CALL_EXTENSION_DUPLICATION_CONFIRM_CLICK", "call_extension_duplication_confirm_click", 24), A00("CALL_EXTENSION_CALL_BUTTON_HIDDEN", "call_extension_call_button_hidden", 25), A00("CALL_EXTENSION_DELIVERY_OPTIMIZATION_CALL_BUTTON_HIDDEN", "call_extension_delivery_optimization_call_button_hidden", 26)}, 0, johArr, 0, 27);
        System.arraycopy(new JOH[]{A00("CALL_EXTENSION_DELIVERY_OPTIMIZATION_CALL_BUTTON_SHOWN", "call_extension_delivery_optimization_call_button_shown", 27), A00("CALL_EXTENSION_UNABLE_TO_READ_PHONE_NUMBER_FROM_CALL_ADS_CONFIGURATION", "call_extension_unable_to_read_phone_number_from_call_ads_configuration", 28), A00("CALL_EXTENSION_READ_PHONE_NUMBER_FROM_CALL_ADS_CONFIGURATION_SUCCESS", "call_extension_read_phone_number_from_call_ads_configuration_success", 29), A00("CALL_EXTENSION_READ_PHONE_NUMBER_FROM_PHONE_DATA", "call_extension_read_phone_number_from_phone_data", 30), A00("CALL_EXTENSION_READ_PAGE_ID_FROM_PHONE_DATA_ID", "call_extension_read_page_id_from_phone_data_id", 31), A00("CLICK_TO_CALL_INFO_GENERATE_EXCEPTION", "click_to_call_info_generate_exception", 32), A00("CLICK_TO_CALL_INFO_MISSING_FIELD_EXCEPTION", "click_to_call_info_missing_field_exception", 33), A00("CLICK_TO_CALL_INFO_PHONE_NUMBER_INVALID", "click_to_call_info_phone_number_invalid_exception", 34), A00("CALL_EXTENSION_IMAGE_INVALID_PHONE_DATA_ID", "call_extension_image_invalid_phone_data_id", 35), A00("CALL_EXTENSION_VIDEO_INVALID_PHONE_DATA_ID", "call_extension_video_invalid_phone_data_id", 36), A00("CALL_EXTENSION_UNABLE_PARSE_PHONE_NUMBER", "call_extension_unable_parse_phone_number", 37), A00("CALL_EXTENSION_USER_COUNTRY_INTERNATIONAL_SAMPLED_TEN_THOUSAND", "call_extension_user_country_international_sampled_ten_thousand", 38), A00("CTC_AM_UPSELL_IN_LASER", "ctc_am_upsell_in_laser", 39), A00("CTC_AM_UPSELL_NOT_ELIGIBLE", "ctc_am_upsell_not_eligible", 40), A00("CTC_AM_UPSELL_VALIDATE_CONDITION", "ctc_am_upsell_validate_condition", 41), A00("GENERATE_PHONE_NUMBER_FROM_PREVIOUS_CALL_ADS", "generate_phone_number_from_previous_call_ads", 42), A00("GET_CTA_FROM_BOOSTED_POST", "get_cta_from_boosted_post", 43), A00("LWI_PHONE_NUMBER_PREFILLED", "lwi_phone_number_prefilled", 44), A00("LWI_PHONE_NUMBER_NOT_PREFILLED", "lwi_phone_number_not_prefilled", 45), A00("CALLBACK_RENDER_CALL_CONFIRMATION_DIALOG", "callback_render_call_confirmation_dialog", 46), A00("NATIVE_CALLBACK_RENDER_CALL_ALTER_DIALOG", "native_callback_render_call_alter_dialog", 47), A00("NATIVE_CALLBACK_CLICK_REQUEST_CALLBACK_ON_DIALOG", "native_callback_click_request_callback_on_dialog", 48), A00("NATIVE_CALLBACK_CLICK_CANCEL_ON_DIALOG", "native_callback_click_cancel_on_dialog", 49), A00("NATIVE_OUTBOUND_CALL_ENDED_WITH_SUB_REASON", "native_outbound_call_ended_with_sub_reason", 50), A00("NATIVE_CALLBACK_PRE_CALL_LOBBY_CTA_CLICKED", "native_callback_pre_call_lobby_cta_clicked", 51), A00("CALLBACK_MSG_CLICK_REQUEST_CALL_ON_DIALOG", "callback_msg_click_request_call_on_dialog", 52), A00("CALLBACK_MSG_CLICK_CALL_ON_DIALOG", "callback_msg_click_call_on_dialog", 53)}, 0, johArr, 27, 27);
        System.arraycopy(new JOH[]{A00("CALLBACK_MSG_CLICK_CANCEL_ON_DIALOG", "callback_msg_click_cancel_on_dialog", 54), A00("CALLBACK_MSG_CLICK_BACKGROUND_OF_DIALOG", "callback_msg_click_background_of_dialog", 55), A00("CALLBACK_MSG_RENDER_BOTTOM_SHEET", "callback_msg_render_bottom_sheet", 56), A00("CALLBACK_MSG_CHANGE_INPUT", "callback_msg_change_input", 57), A00("CALLBACK_MSG_CLICK_CTA", "callback_msg_click_cta", 58), A00("CALLBACK_MSG_CLICK_BUSINESS_PAGE_LINK_ON_BOTTOM_SHEET", "callback_msg_click_business_page_link_on_bottom_sheet", 59), A00("CALLBACK_MSG_SEND_SUCCESS", "callback_msg_send_success", 60), A00("CALLBACK_MSG_SEND_FAIL", "callback_msg_send_fail", 61), A00("CALLBACK_MSG_SEND_FAIL_SERVER", "callback_msg_send_fail_server", 62), A00("CALLBACK_MSG_PASS_ELIGIBILITY_CHECK_ON_SERVER_SIDE", "callback_msg_pass_eligibility_check_on_server_side", 63), A00("CALLBACK_MSG_RENDER_INSTANT_FEEDBACK", "callback_msg_render_instant_feedback", 64), A00("CALLBACK_MSG_CLICK_VIEW_ON_INSTANT_FEEDBACK", "callback_msg_click_view_on_instant_feedback", 65), A00("CALLBACK_MSG_LOGGING_EXCEPTION", "callback_msg_logging_exception", 66), A00("CALLBACK_MSG_ADVERTISER_DEFAULTING", "callback_msg_advertiser_defaulting", 67), A00("CALLBACK_MSG_ADVERTISER_TOGGLE", "callback_msg_advertiser_toggle", 68), A00("CALLBACK_FORM_CLICK_REQUEST_CALL_ON_DIALOG", "callback_form_click_request_call_on_dialog", 69), A00("CALLBACK_FORM_NOT_COMPLETED_OPENED", "callback_form_not_completed_opened", 70), A00("CALLBACK_FORM_COMPLETED_OPENED", "callback_form_completed_opened", 71), A00("CALLBACK_FORM_START_CALL_DURING_FORM", "callback_form_start_call_during_form", 72), A00("CALLBACK_FORM_SUBMIT", "callback_form_submit", 73), A00("CALLBACK_FORM_SUBMIT_FAIL", "callback_form_submit_fail", 74), A00("CALLBACK_FORM_SUBMIT_SUCCESS", "callback_form_submit_success", 75), A00("CALLBACK_FORM_RENDER_CLIENT_SUCCESS", "callback_form_render_client_success", 76), A00("CALLBACK_FORM_SUBMITTED_INTERSTITIAL_RENDER_CLIENT_SUCCESS", "callback_form_submitted_interstitial_render_client_success", 77), A00("CALLBACK_FORM_RENDER_SERVER_FAIL", "callback_form_render_server_fail", 78), A00("CALLBACK_FORM_DATE_TIME_PICKER_CLICKED", "callback_form_date_time_picker_clicked", 79), A00("CALLBACK_FORM_BLOKS_DATE_TIME_PICKER_UNSUPPORTED", "callback_form_bloks_date_time_picker_unsupported", 80)}, 0, johArr, 54, 27);
        System.arraycopy(new JOH[]{A00("CALLBACK_FORM_SUBMIT_CTA_CLICKED", "callback_form_submit_cta_clicked", 81), A00("CALLBACK_FORM_INPUT_FOCUS", "callback_form_input_focus", 82), A00("CALLBACK_FORM_INPUT_VALIDATION_ERROR", "callback_form_input_validation_error", 83), A00("CALLBACK_FORM_DATE_TIME_PICKER_DATE_TIME_PICKED", "callback_form_date_time_picker_date_time_picked", 84), A00("CALLBACK_FORM_META_PRIVACY_POLICY_CLICK", "callback_form_meta_privacy_policy_click", 85), A00("CALLBACK_FORM_ADVERTISER_PRIVACY_POLICY_CLICK", "callback_form_advertiser_privacy_policy_click", 86), A00("CALLBACK_MULTIPLE_CALLBACK_FORMS", "callback_multiple_callback_forms", 87), A00("CALLBACK_FORM_SET_PRIVACY_POLICY", "callback_form_set_privacy_policy", 88), A00("CALLBACK_FORM_UNSET_PRIVACY_POLICY", "callback_form_unset_privacy_policy", 89), A00("CALLBACK_FORM_RENDER_WITH_SUBMITTED_LEAD_ALREADY", "callback_form_render_with_submitted_lead_already", 90), A00("CALLBACK_FORM_MISSING_FORM_ID", "callback_form_missing_form_id", 91), A00("CLICK_TO_CALL_CALLBACK_REQUEST_SUBMITTED", "click_to_call_callback_request_submitted", 92), A00("MULTIPHOTO_POST_CALL_RENDER", "multiphoto_post_call_render", 93), A00("MULTIPHOTO_POST_INVALID_FIELD_EXCEPTION", "multiphoto_post_invalid_field_exception", 94), A00("MULTIPHOTO_STORY_VIEW_CALL_CLICKED", "multiphoto_story_view_call_clicked", 95), A00("MULTIPHOTO_STORY_VIEW_LEARN_MORE_CLICKED", "multiphoto_story_view_learn_more_clicked", 96), A00("MULTIPHOTO_OVERLAYER_VIEW_CALL_CLICKED", "multiphoto_overlayer_view_call_clicked", 97), A00("CALL_FEED_UNIT_CLICKED", "call_feed_unit_clicked", 98), A00("CALL_CONFIRMATION_DIALOG_RENDER", "call_confirmation_dialog_render", 99), A00("CALL_CONFIRMATION_DIALOG_CLICKED", "call_confirmation_dialog_clicked", 100), A00("CALL_CONFIRMATION_DIALOG_DISMISSED", "call_confirmation_dialog_dismissed", 101), A00("CALL_PRIVACY_BOTTOM_SHEET_SHOWN", "call_privacy_bottom_sheet_shown", 102), A00("CALL_FULL_SCREEN_CALL_RENDER", "call_full_screen_call_render", 103), A00("CALL_HANG_UP_BUTTON_CLICKED", "call_hang_up_button_clicked", 104), A00("CALL_ACTIONBAR_BACK_BUTTON_CLICKED", "call_back_button_clicked", 105), A00("CALL_HANG_UP_WITHOUT_ALERT", "call_hang_up_without_alert", 106), A00("CALL_HANG_UP_WITH_ALERT", "call_hang_up_with_alert", 107)}, 0, johArr, 81, 27);
        System.arraycopy(new JOH[]{A00("CALL_HANG_UP_CANCEL_WITH_ALERT", "call_hang_up_cancel_with_alert", 108), A00("CALL_HANG_UP_EXIT_OUT_BUTTON_CLICKED", "call_hang_up_exit_out_button_clicked", 109), A00("CALL_MUTED", "call_muted", 110), A00("CALL_UNMUTED", "call_unmuted", 111), A00("CALL_SPEAKER_ON", "call_speaker_on", 112), A00("CALL_SPEAKER_OFF", "call_speaker_off", 113), A00("CALL_BOOTSTRAP_DATA_MISSING_FIELDS", "call_bootstrap_data_missing_fields", 114), A00("CALL_COULDNT_START", "call_couldnt_start", 115), A00("CALL_RENDER_INVALID_POST", "call_render_invalid_post", 116), A00("CALL_RENDER_INVALID_PAGE", "call_render_invalid_page", 117), A00("CALL_OPEN_DIALPAD", "call_open_dialpad", 118), A00("CALL_CLOSE_DIALPAD", "call_close_dialpad", 119), A00("CALL_SEND_DTMF_DIGIT", "call_send_dtmf_digit", 120), A00("CALL_STAR_RATING_RENDER", "call_star_rating_render", 121), A00("CALL_STAR_RATING_SUBMIT", "call_star_rating_submit", 122), A00("CALL_STAR_RATING_SKIP", "call_star_rating_skip", 123), A00("CALL_DIALER_FALLBACK_ON_CLICK", "call_dialer_fallback_on_click", 124), A00("CALL_DIALER_FALLBACK_POST_DENY", "call_dialer_fallback_post_deny", 125), A00("CALL_CTC_URL_INVALID", "call_ctc_url_invalid", 126), A00("CALL_DISPLAY_PHONE_NUMBER_MISSING", "call_display_phone_number_missing", 127), A00("CALL_BLOKS_START_CALL_SIGNATURE_UNSUPPORTED", "call_bloks_start_call_signature_unsupported", 128), A00("CALL_CLIENT_EXCEPTION", "call_client_exception", 129), A00("NATIVE_CALL_FAIL_TO_GENERATE_PHONE_NUMBER_IN_SIP_USER", "native_call_fail_to_generate_phone_number_in_sip_user", 130), A00("NATIVE_CALL_FAIL_TO_GET_DIALOUT_NUMBER_IN_DOOR", "native_call_fail_to_get_dialout_number_in_door", 131), A00("ACTION_LINK_FAIL_PARSE_PHONE_NUMBER", "action_link_fail_parse_phone_number", 132), A00("ACTION_LINK_FAIL_GET_USER_COUNTRY", "action_link_fail_get_user_country", 133), A00("CALL_FROM_CALL_LOG", "call_from_call_log", 134)}, 0, johArr, 108, 27);
        System.arraycopy(new JOH[]{A00("NATIVE_CALL_WITH_CAPTION_STARTED", "native_call_with_caption_started", 135), A00("NATIVE_CALL_WITHOUT_CAPTION_STARTED", "native_call_without_caption_started", 136), A00("CALL_MICROPHONE_PERMISSIONS_PRESENT", "call_microphone_permissions_allowed", 137), A00("CALL_MICROPHONE_PERMISSIONS_NEEDED", "call_microphone_permissions_needed", 138), A00("CALL_MICROPHONE_REQUEST_GRANTED", "call_microphone_request_granted", 139), A00("CALL_MICROPHONE_REQUEST_DENIED", "call_microphone_request_denied", 140), A00("PIP_START", "start_pip", 141), A00("PIP_END_BY_CLICK", "pip_end_by_click", 142), A00("PIP_END_BY_CALL_END", "pip_end_by_call_end", 143), A00("DETAIL_BOTTOM_SHEET_RENDER", "detail_bottom_sheet_render", 144), A00("CALL_SETTING_BOTTOM_SHEET_RENDER", "call_setting_bottom_sheet_render", 145), A00("OUTPUT_DEVICE_CHANGED", "changed_output_device", 146), A00("CALL_HANG_UP_WITH_DETAIL_BOTTOM_SHEET", "call_hang_up_with_detail_bottom_sheet", 147), A00("ANDROID_ACTIVITY_ON_CREATE", "android_activity_on_create", 148), A00("ANDROID_ACTIVITY_ON_START", "android_activity_on_start", 149), A00("ANDROID_ACTIVITY_ON_RESUME", "android_activity_on_resume", 150), A00("ANDROID_ACTIVITY_ON_PAUSE", "android_activity_on_pause", 151), A00("ANDROID_ACTIVITY_ON_STOP", "android_activity_on_stop", 152), A00("ANDROID_ACTIVITY_ON_DESTROY", "android_activity_on_destroy", 153), A00("ANDROID_ACTIVITY_ON_BACK_PRESS", "android_activity_on_back_press", 154), A00("HOLISTIC_EXPERIENCE_LOBBY_BOTTOM_SHEET_RENDER", "holistic_experience_lobby_bottom_sheet_render", 155), A00("HOLISTIC_EXPERIENCE_LOBBY_BOTTOM_SHEET_CLICK_CALL_NOW", "holistic_experience_lobby_bottom_sheet_click_call_now", 156), A00("HOLISTIC_EXPERIENCE_LOBBY_BOTTOM_SHEET_CLICK_LEARN_MORE", "holistic_experience_lobby_bottom_sheet_click_learn_more", 157), A00("HOLISTIC_EXPERIENCE_PRIVACY_BOTTOM_SHEET_CLICK_CALL_NOW", "holistic_experience_privacy_bottom_sheet_click_call_now", 158), A00("HOLISTIC_EXPERIENCE_PRIVACY_BOTTOM_SHEET_CLICK_BACK_BUTTON", "holistic_experience_privacy_bottom_sheet_click_back_button", 159), A00("HOLISTIC_EXPERIENCE_PRIVACY_LOBBY_CLICK_CALL_NOW", "holistic_experience_privacy_lobby_click_call_now", 160), A00("HOLISTIC_EXPERIENCE_PAGE_PROFILE_CLICK", "holistic_experience_page_profile_click", 161)}, 0, johArr, 135, 27);
        System.arraycopy(new JOH[]{A00("TRUST_SIGNAL_LIKES_INTEREST_CLICK", "trust_signal_likes_interest_click", 162), A00("TRUST_SIGNAL_REVIEWS_INTEREST_CLICK", "trust_signal_reviews_interest_click", 163), A00("TRUST_SIGNAL_ADDRESS_INTEREST_CLICK", "trust_signal_address_interest_click", 164), A00("TRUST_SIGNAL_OPEN_HOURS_INTEREST_CLICK", "trust_signal_open_hours_interest_click", 165), A00("TRUST_SIGNAL_FOLLOWS_INTEREST_CLICK", "trust_signal_follows_interest_click", 166), A00("TRUST_SIGNAL_WEBSITE_LINK_INTEREST_CLICK", "trust_signal_website_link_interest_click", 167), A00("TRUST_SIGNAL_LIKES_FACEPILE_INTEREST_CLICK", "trust_signal_likes_facepile_interest_click", 168), A00("TRUST_SIGNAL_PAGE_CATEGORY_INTEREST_CLICK", "trust_signal_page_category_interest_click", 169), A00("TRUST_SIGNAL_PRICE_RANGE_INTEREST_CLICK", "trust_signal_price_range_interest_click", 170), A00("TRUST_SIGNAL_LIKES_RENDER", "trust_signal_likes_render", 171), A00("TRUST_SIGNAL_REVIEWS_RENDER", "trust_signal_reviews_render", 172), A00("TRUST_SIGNAL_ADDRESS_RENDER", "trust_signal_address_render", 173), A00("TRUST_SIGNAL_OPEN_HOURS_RENDER", "trust_signal_open_hours_render", 174), A00("TRUST_SIGNAL_FOLLOWS_RENDER", "trust_signal_follows_render", 175), A00("TRUST_SIGNAL_WEBSITE_LINK_RENDER", "trust_signal_website_link_render", 176), A00("TRUST_SIGNAL_LIKES_FACEPILE_RENDER", "trust_signal_likes_facepile_render", 177), A00("TRUST_SIGNAL_PAGE_CATEGORY_RENDER", "trust_signal_page_category_render", 178), A00("TRUST_SIGNAL_PRICE_RANGE_RENDER", "trust_signal_price_range_render", 179), A00("MBS_BOOSTED_CALL_NOW_PRODUCT_SHOWN", "mbs_boosted_call_now_product_shown", 180), A00("MBS_BOOSTED_CALL_NOW_PRODUCT_RECOMMENDED", "mbs_boosted_call_now_product_recommended", 181), A00("PHONE_NUMBER_PREFILLED", "phone_number_prefilled", 182), A00("PHONE_NUMBER_NOT_PREFILLED", "phone_number_not_prefilled", 183), A00("FLOATING_CTA_RENDER", "floating_cta_render", 184), A00("FLOATING_CTA_CTA_CLICKED", "floating_cta_cta_clicked", 185), A00("FLOATING_CTA_FOOTER_CLICKED", "floating_cta_footer_clicked", 186), A00("CAWC_RENDER", "cawc_render", 187), A00("CAWC_CTA_CLICKED", "cawc_cta_clicked", 188)}, 0, johArr, 162, 27);
        System.arraycopy(new JOH[]{A00("CAWC_APP_SWITCH_INITIATED", "cawc_app_switch_initiated", 189), A00("CAWC_FALLBACK_TO_PSTN_INVALID_DEEPLINK", "cawc_fallback_to_pstn_invalid_deeplink", 190), A00("CAWC_FALLBACK_TO_PSTN_WHATSAPP_NOT_INSTALLED", "cawc_fallback_to_pstn_whatsapp_not_installed", 191), A00("CALL_CTA_UPGRADE_GET_PHONE_NUMBER", "call_cta_upgrade_get_phone_number", 192), A00("CALL_CTA_UPGRADE_GRAPHQL_RESULT", "call_cta_upgrade_graphql_result", 193), A00("FC_MIGRATION_SHOW_GUIDANCE_CARD", "fc_migration_show_guidance_card", 194), A00("FC_APPLY_MIGRATION_TO_DRAFT_ADSET", "fc_apply_migration_to_draft_adset", 195), A00("FC_APPLY_MIGRATION_TO_PUBLISHED_ADSET", "fc_apply_migration_to_published_adset", 196), A00("WEBSITE_AND_CALL_NO_CALL_EXTENSION_CREATIVE", "website_and_call_no_call_extension_creative", 197), A00("PRODUCT_SET_AND_WEBSITE_AND_CALL_NO_CALL_EXTENSION_CREATIVE", "product_set_and_website_and_call_no_call_extension_creative", 198), A00("CALL_FROM_AD_CONTENT_CLICK", "call_from_ad_content_click", 199), A00("CALL_CAPTION_RECEIVED", "call_caption_received", 200), A00("CALL_NOW_BOOSTED_TOGGLE_HAS_RECENT_CALL_ADS", "call_now_boosted_toggle_has_recent_call_ads", 201), A00("LWI_DAYPARTING_BACK_TO_BACK_INTERVALS", "lwi_dayparting_back_to_back_intervals", 202), A00("LWI_DAYPARTING_PAGE_HOURS_OVER_2_INTERVALS", "lwi_dayparting_page_hours_over_2_intervals", 203), A00("LWI_DAYPARTING_INTERVAL_LESS_THAN_180_MINUTES", "lwi_dayparting_interval_less_than_180_minutes", 204), A00("LWI_DAYPARTING_USING_PAGE_HOURS", "lwi_dayparting_using_page_hours", 205), A00("LWI_DAYPARTING_USING_STANDARD_HOURS", "lwi_dayparting_using_standard_hours", 206), A00("LWI_DAYPARTING_EXTENDING_SHORT_START_WINDOW", "lwi_dayparting_extending_short_start_window", 207), A00("LWI_DAYPARTING_EXTENDING_SHORT_END_WINDOW", "lwi_dayparting_extending_short_end_window", 208), A00("LWI_DAYPARTING_CONVERSION_ILLEGAL", "lwi_dayparting_conversion_illegal", 209), A00("LWI_DAYPARTING_CONVERSION_LEGAL", "lwi_dayparting_conversion_legal", 210), A00("LWI_DAYPARTING_GRAPHQL_PAGE_HOURS_FAILED", "lwi_dayparting_graphql_page_hours_failed", 211), A00("LWI_DAYPARTING_NEEDED_TO_UPDATE_PAGE_HOURS", "lwi_dayparting_needed_to_update_page_hours", 212), A00("LWI_DAYPARTING_FETCH_ORIGINAL_AD_CREATION_SOURCE_APP_ID", "lwi_dayparting_fetch_original_ad_creation_source_app_id", 213), A00("LWI_DAYPARTING_DAYPARTS_PUBLISH_SUCCESS", "lwi_dayparting_dayparts_publish_success", 214), A00("LWI_DAYPARTING_LOG_DENY_SCHEDULE_TOO_SHORT_RULE", "lwi_dayparting_log_deny_schedule_too_short_rule", 215)}, 0, johArr, 189, 27);
        JOH A00 = A00("LWI_DAYPARTING_DAILY_BUDGET_DAYPARTING_DEBUG_LOG", "lwi_dayparting_daily_budget_dayparting_debug_log", 216);
        JOH A002 = A00("LWI_DAYPARTING_DAILY_BUDGET_DAYPARTING_APP_ID_DEBUG_LOG", "lwi_dayparting_daily_budget_dayparting_app_id_debug_log", 217);
        JOH A003 = A00("CALL_FORWARDING_REQUEST_PROXY_NUMBER", "call_forwarding_request_proxy_number", 218);
        A05 = A003;
        JOH A004 = A00("CALL_FORWARDING_RECEIVE_PROXY_NUMBER", "call_forwarding_receive_proxy_number", 219);
        A04 = A004;
        JOH A005 = A00("CALL_FORWARDING_INITIATE_CALL", "call_forwarding_initiate_call", 220);
        A03 = A005;
        JOH A006 = A00("CALL_FORWARDING_CALL_PLACED", "call_forwarding_call_placed", 221);
        A02 = A006;
        System.arraycopy(new JOH[]{A00, A002, A003, A004, A005, A006, A00("AM_CONVERSION_LOCATION_ML_DEFAULTING", "am_conversion_location_ml_defaulting", 222), A00("AM_CONVERSION_LOCATION_ML_DEFAULTING_RESULTS", "am_conversion_location_ml_defaulting_results", 223), A00("CALL_CENTER_PAGE_IMPRESSION_START", "call_center_page_impression_start", 224), A00("CALL_CENTER_PAGE_IMPRESSION_END", "call_center_page_impression_end", 225), A00("CALL_CENTER_FILTER_CREATION_MENU_OPENED", "call_center_filter_creation_menu_opened", 226), A00("CALL_CENTER_FILTER_CREATION_MENU_CLOSED", "call_center_filter_creation_menu_closed", 227), A00("CALL_CENTER_FILTER_TYPE_SELECTED", "call_center_filter_type_selected", 228), A00("CALL_CENTER_FILTER_CONDITION_ADDED", "call_center_filter_condition_added", 229), A00("CALL_CENTER_FILTER_CONDITION_REMOVED", "call_center_filter_condition_removed", 230), A00("CALL_CENTER_FILTER_SUBMITTED", "call_center_filter_submitted", 231), A00("CALL_CENTER_FILTER_VALIDATION_ERROR", "call_center_filter_validation_error", 232), A00("CALL_CENTER_FILTERS_CLEARED", "call_center_filters_cleared", 233), A00("CALL_CENTER_FILTER_TOKEN_CLICKED", "call_center_filter_token_clicked", 234), A00("CALL_CENTER_FILTER_TOKEN_REMOVED", "call_center_filter_token_removed", 235), A00("CALL_CENTER_QUALITY_CALL_DROPDOWN_OPENED", "call_center_quality_call_dropdown_opened", 236), A00("CALL_CENTER_QUALITY_CALL_DROPDOWN_CLOSED", "call_center_quality_call_dropdown_closed", 237), A00("CALL_CENTER_QUALITY_CALL_APPLIED", "call_center_quality_call_applied", 238), A00("CALL_CENTER_QUERY_SUCCESS", "call_center_query_success", 239), A00("CALL_CENTER_QUERY_ERROR", "call_center_query_error", 240), A00("CALL_CENTER_TABLE_LOAD_MORE", "call_center_table_load_more", 241), A00("CALL_CENTER_TABLE_LOAD_MORE_SUCCESS", "call_center_table_load_more_success", 242)}, 0, johArr, 216, 27);
        System.arraycopy(new JOH[]{A00("CALL_CENTER_COLUMN_SELECTOR_OPENED", "call_center_column_selector_opened", 243), A00("CALL_CENTER_COLUMN_VISIBILITY_CHANGED", "call_center_column_visibility_changed", 244), A00("CALL_CENTER_TABLE_SORT_CLICKED", "call_center_table_sort_clicked", 245), A00("CALL_CENTER_TABLE_SORT_SUCCESS", "call_center_table_sort_success", 246), A00("CALL_CENTER_DATE_PICKER_OPENED", "call_center_date_picker_opened", 247), A00("CALL_CENTER_DATE_PICKER_CLOSED", "call_center_date_picker_closed", 248), A00("CALL_CENTER_DATE_RANGE_UPDATED", "call_center_date_range_updated", 249)}, 0, johArr, 243, 7);
        A01 = johArr;
    }

    public JOH(String str, int i, String str2) {
        this.A00 = str2;
    }

    public static JOH A00(String str, String str2, int i) {
        return new JOH(str, i, str2);
    }

    public static JOH valueOf(String str) {
        return (JOH) Enum.valueOf(JOH.class, str);
    }

    public static JOH[] values() {
        return (JOH[]) A01.clone();
    }

    @Override // p000X.InterfaceC26580vu
    public final /* bridge */ /* synthetic */ Object getValue() {
        return this.A00;
    }
}
