package p000X;

/* loaded from: classes9.dex */
public abstract class LLD {
    public static final Integer A00(Integer num) {
        switch (num.intValue()) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 6:
            case 8:
            case 9:
            case 10:
            case 11:
            case 12:
            case 27:
            case 36:
            case 41:
            case 45:
                return C00A.A0C;
            case 5:
            case 13:
            case 14:
            case 15:
            case 16:
            case 17:
            case 18:
            case 19:
            case 21:
            case 22:
            case 24:
            case 28:
            case 29:
            case 30:
            case 31:
            case 35:
            case 37:
            case 38:
            case 43:
            case 44:
            case 47:
            case 48:
            case 49:
            case 50:
            case 51:
            case 55:
            case 56:
            case 57:
            case 58:
            case 59:
            case 63:
            case 64:
            case 66:
            case 67:
            case 70:
            case 71:
            case 72:
                return C00A.A00;
            case 7:
            case 20:
            case 23:
            case 25:
            case 26:
            case 32:
            case 33:
            case 34:
            case 39:
            case 40:
            case 42:
            case 46:
            case 52:
            case 53:
            case 54:
            case 60:
            case 61:
            case 62:
            case 65:
            case 68:
                return C00A.A01;
            case 69:
            case 73:
                return C00A.A0N;
            default:
                throw AnonymousClass021.A10();
        }
    }

    public static String A01(Integer num) {
        switch (num.intValue()) {
            case 1:
                return "clientLowBweBps";
            case 2:
                return "clientMidBweBps";
            case 3:
                return "clientHighBweBps";
            case 4:
                return "clientConnectionClass";
            case 5:
                return "clientStallDuration";
            case 6:
                return "clientRTTPrediction";
            case 7:
                return "clientStallWatchTime";
            case 8:
                return "clientMemoryState";
            case 9:
                return "clientThermalState";
            case 10:
                return "clientDarkMode";
            case 11:
                return "clientScreenBrightness";
            case 12:
                return "tasosBweBps";
            case 13:
                return "videoPause";
            case 14:
                return "videoCompleted";
            case 15:
                return "videoCanceled";
            case 16:
                return "videoPlaying";
            case 17:
                return "videoAutoplayed";
            case 18:
                return "videoStartedBuffering";
            case 19:
                return "videoFinishedBuffering";
            case 20:
                return "videoWatchTime";
            case 21:
                return "videoUnmute";
            case 22:
                return "videoMute";
            case 23:
                return "videoAudioOnWatchTime";
            case 24:
                return "videoFullscreen";
            case 25:
                return "videoFullscreenWatchTime";
            case 26:
                return "videoFullscreenDuration";
            case 27:
                return "videoUpoadAudioMOS";
            case 28:
                return "reelsCommentSurfaceClick";
            case 29:
                return "reelsReaction";
            case 30:
                return "reelsShare";
            case 31:
                return "reelsVideoId";
            case 32:
                return "activeFeedItem";
            case 33:
                return "recentFeedItem";
            case 34:
                return "reelsEngagements";
            case 35:
                return "currentActivePost";
            case 36:
                return "appSessionForegroundTimeMarkMs";
            case 37:
                return "scrollSpeed";
            case 38:
                return AnonymousClass010.A00(335);
            case 39:
                return "scrollSpeedState";
            case 40:
                return "scrollStopPostId";
            case 41:
                return "currentActivePostPosition";
            case 42:
                return "crossSurfaceSignal";
            case 43:
                return "navigationSurface";
            case 44:
                return "navigationHop";
            case 45:
                return "firstQueryId";
            case 46:
                return "scrollSpeedAvg";
            case 47:
                return "vpvQid";
            case 48:
                return "vpvZoomIn";
            case 49:
                return "vpvEnded";
            case 50:
                return "vpvTopLevelPostId";
            case 51:
                return "vpvViewMoreRepliesClick";
            case 52:
                return "vpvViewMoreRepliesClickCount";
            case 53:
                return "adsInlineCommentDwellTime";
            case 54:
                return "adsCommentsClick";
            case 55:
                return "vpvPostId";
            case 56:
                return "vpvPosition";
            case 57:
                return "vpvMaxSeenPosition";
            case 58:
                return "videoChannelDepth";
            case 59:
                return "videoChannelParentVideoId";
            case 60:
                return "channelSecondVideoId";
            case 61:
                return "channelSecondVideoWatchTime";
            case 62:
                return "videoDidFullscreen";
            case 63:
                return "appOpenUrl";
            case 64:
                return "appOpenNotification";
            case 65:
                return "appEntryPoint";
            case 66:
                return "surfaceSessionId";
            case 67:
                return "refreshType";
            case 68:
                return "last5vpvs";
            case 69:
                return "navigationSnapshot";
            case 70:
                return "feedImpression";
            case 71:
                return "reelsImpression";
            case 72:
                return "storiesImpression";
            case 73:
                return "spfGraphQlPayload";
            default:
                return "UNKNOWN";
        }
    }
}
