package p000X;

/* loaded from: classes10.dex */
public abstract class LUC {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 0:
                return "bc_ineligible_screen_impression";
            case 1:
                return "bc_ineligible_launch_unified_monetization_screen";
            case 2:
                return "bc_partnerships_creator_entrypoint_impression";
            case 3:
                return "bc_partnerships_brand_entrypoint_impression";
            case 4:
                return "branded_content_creator_contact_about_partnership_tap";
            case 5:
                return "settings_screen_impression";
            case 6:
                return "approve_creators_screen_impression";
            case 7:
                return "approve_creators_screen_button_action";
            case 8:
                return "approve_creators_screen_request_impression";
            case 9:
                return "request_brand_approval_screen_impression";
            case 10:
                return "approve_media_request_screen_impression";
            case 11:
                return "approve_media_request_screen_button_action";
            case 12:
                return "ig_branded_content_allowlisted_accounts_entry";
            case 13:
                return "branded_content_creator_contact_drawer_shown";
            case 14:
                return "brand_onboarding_bc_settings_impression";
            case 15:
                return "brand_onboarding_bc_settings_click";
            case 16:
                return "app_campaign_cta_click";
            case 17:
                return "desktop_tool_bc_settings_impression";
            case 18:
                return "desktop_tool_bc_settings_click";
            case 19:
            case 45:
            default:
                return "paid_partnership_label_impression";
            case 20:
                return "add_brand_partners_brand_action";
            case 21:
                return "add_brand_partners_next_button_tapped";
            case 22:
                return "disclosure_entrypoint_rendered";
            case 23:
                return "disclosure_suggestions_rendered";
            case 24:
                return "disclosure_entrypoint_tapped";
            case 25:
                return "disclosure_suggestion_tapped";
            case 26:
                return "disclosure_menu_rendered";
            case 27:
                return "disclosure_menu_select_project_click";
            case 28:
                return "disclosure_menu_add_brands_manually_click";
            case 29:
                return "disclosure_menu_back_click";
            case 30:
                return "disclosure_menu_project_deselected";
            case 31:
                return "disclosure_menu_audience_restrictions_click";
            case 32:
                return "disclosure_menu_brand_deselected";
            case 33:
                return "disclosure_menu_ads_permission_toggled";
            case 34:
                return "disclosure_review_done_button_tapped";
            case 35:
                return "disclosure_review_brand_partners_tapped";
            case 36:
                return "disclosure_review_brand_removed";
            case 37:
                return "disclosure_review_add_audience_restrictions_tapped";
            case 38:
                return "request_approval_dialog_action";
            case 39:
                return "project_selection_project_selected";
            case 40:
                return "project_selection_done_click";
            case 41:
                return "project_selection_back_click";
            case 42:
                return "error_loading_user";
            case 43:
                return "error_get_list_of_projects_api";
            case 44:
                return "error_get_list_of_projects_missing_fields";
            case 46:
                return "error_get_list_of_campaign_api";
            case 47:
                return "error_get_list_of_campaign_missing_fields";
            case 48:
                return "suspected_bc_alert_impression";
            case 49:
                return "suspected_bc_share_anyway_tapped";
            case 50:
                return "suspected_bc_add_tags_tapped";
            case 51:
                return "suspected_bc_creator_review_impression";
            case 52:
                return "suspected_bc_creator_add_ppl_tapped";
            case 53:
                return "suspected_bc_creator_not_bc_tapped";
            case 54:
                return "suspected_bc_creator_review_confirmation_impression";
        }
    }
}
