package p000X;

/* loaded from: classes11.dex */
public abstract class N6G {
    public static final long A00;
    public static final long A01;
    public static final long A02;
    public static final long A03;
    public static final long A04;
    public static final long A05;
    public static final long A06;
    public static final long A07;
    public static final long A08;
    public static final long A09;
    public static final long A0A;
    public static final long A0B;
    public static final long A0C;
    public static final long A0D;
    public static final long A0E;
    public static final long A0F;
    public static final long A0G;
    public static final long A0H;
    public static final long A0I;
    public static final long A0J;
    public static final long A0K;
    public static final long A0L;
    public static final long A0M;
    public static final long A0N;
    public static final long A0O;
    public static final long A0P;
    public static final long A0Q;
    public static final long A0R;
    public static final long A0S;
    public static final long A0T;
    public static final long A0U;
    public static final long A0V;
    public static final long A0W;
    public static final long A0X;
    public static final long A0Y;

    static {
        long j = C6SJ.A00;
        A0P = j;
        long j2 = C6SJ.A0L;
        A0Q = j2;
        A0U = C6SJ.A0N;
        A0V = j2;
        long j3 = C6SJ.A0K;
        A0K = C6SJ.A0G;
        A0L = C6SJ.A0p;
        long j4 = C6SJ.A1l;
        A0O = j4;
        long j5 = C6SJ.A0I;
        A0R = j5;
        long j6 = C6SJ.A0J;
        A0S = j6;
        A0F = j4;
        long j7 = C6SJ.A0H;
        A0I = C6SJ.A0T;
        A0J = j3;
        A0W = j5;
        A0T = j6;
        A0X = C6SJ.A04;
        long j8 = C6SJ.A1w;
        A00 = j8;
        A0H = C6SJ.A01;
        A0M = C6SJ.A02;
        A02 = j;
        A03 = C6SJ.A0S;
        A04 = j4;
        A05 = j7;
        A01 = C6SJ.A1h;
        A0N = C6SJ.A0c;
        long j9 = C6SJ.A0z;
        A06 = j9;
        long j10 = C6SJ.A1W;
        A0Y = C6SJ.A03;
        A0C = j10;
        A09 = j9;
        A0B = C6SJ.A1L;
        A0D = C6SJ.A1g;
        A0A = C6SJ.A1A;
        A0E = j8;
        A08 = C6SJ.A0a;
        A07 = C6SJ.A0A;
        A0G = C6SJ.A0F;
    }
}
