package p000X;

/* loaded from: classes12.dex */
public abstract class PUE {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 1:
                return "ACCOUNT_SETTINGS_DEEP_LINK";
            case 2:
                return "ACCOUNT_SETTINGS";
            case 3:
                return "ACTIVE_SESSION_LIST";
            case 4:
                return "PHONE_CHANGE_SETTINGS";
            case 5:
                return "MESSAGE";
            case 6:
                return "SHARE_MESSAGE";
            case 7:
                return "MESSENGER_IAB_TRANSPARENCY_SCREEN";
            case 8:
                return "MESSENGER_ADS";
            case 9:
                return "MESSENGER_THREAD_DISCOVERABLE_PUBLIC_CHAT";
            case 10:
                return "MESSENGER_THREAD";
            case 11:
                return "MESSENGER_THREAD_THIRD_PARTY";
            case 12:
                return "MESSENGER_E2EE_THREAD";
            case 13:
                return "MESSENGER_MR_CALL";
            case 14:
                return "INBOX_ADS_REPORT";
            case 15:
                return "INBOX_ADS_RATING_TOOL";
            case 16:
                return "INBOX_ADS_HIDE";
            case 17:
                return "INBOX_ADS_WHY";
            case 18:
                return "INBOX_ADS_HELP";
            case 19:
                return "MESSENGER_STORY_ADS";
            case 20:
                return "MESSENGER_STORY_ADS_REPORT";
            case 21:
                return "MESSENGER_STORY_AI_READY_MADE_LEARN_MORE";
            case 22:
                return "MESSENGER_STORIES_VIEWER";
            case 23:
                return "MESSENGER_BUSINESS_CONTEXT_PROFILE";
            case 24:
                return "SPONSORED_MESSAGES_ADS";
            case 25:
                return "MARKETPLACE_BANNER";
            case 26:
                return "MARKETPLACE_REPORT";
            case 27:
                return "MARKETPLACE_MEETING_LOCATION";
            case 28:
                return "MARKETPLACE_RATINGS";
            case 29:
                return "MARKETPLACE_RESERVE_CHECKOUT";
            case 30:
                return "PAGE_MESSAGES";
            case 31:
                return "CHECKPOINT";
            case 32:
                return "HIGH_SCHOOL_NETWORK";
            case 33:
                return "FORM_PROGRESS_XMA";
            case 34:
                return "ANIMATED_THREAD_ACTIVITY_BANNER";
            case 35:
                return "ROOMS2LIVE_OPT_IN_LEARN_MORE";
            case 36:
                return "ROOMS2LIVE_BROADCAST_LEARN_MORE";
            case 37:
                return "ROOMS2LIVE_COMMUNITY_STANDARDS";
            case 38:
                return "ROOMS2LIVE_DATA_POLICY";
            case 39:
                return "ROOMS2LIVE_REPORT_OR_GIVE_FEEDBACK";
            case 40:
                return "ROOMS2LIVE_FACEBOOK_LIVE_POLICIES";
            case 41:
                return "FX_CAL";
            case 42:
                return "MESSAGING_ADS";
            case 43:
                return "CONSENT_FLOW_AI_STICKERS";
            case 44:
                return "CONSENT_FLOW_AI_THEMES";
            case 45:
                return "CONSENT_FLOW_WRITE_WITH_AI";
            case 46:
                return AnonymousClass497.A00(56);
            case 47:
                return "SMART_GLASSES_VIDEO_CALL_LEARN_MORE";
            case 48:
                return "CSAM";
            case 49:
                return "CM_GEN_AI_SUGGESTED_CHATS_LEARN_MORE";
            case 50:
                return "PRO_MODE_BUSINESS_TOOLS_LEARN_MORE_E2EE";
            case 51:
                return "COMMUNITY_MESSAGING_HIGHLIGHTS";
            case 52:
                return "IN_APP_BROWSER_DEEPLINK";
            case 53:
                return "PUBLIC_CHANNELS_INCREMENTALITY_BUTTON";
            case 54:
                return "MESSAGE_TRANSLATION_NUX_LEARN_MORE_E2EE";
            case 55:
                return "VOICE_TRANSCRIPTION_UNSUPPORTED_LANGUAGE_LEARN_MORE";
            case 56:
                return "MEMU_ONBOARDING";
            case 57:
                return "THIRD_PARTY_APPS_SETTINGS";
            case 58:
                return "HIGHLIGHTS_TAB";
            case 59:
                return "MEMORIES_TEMPLATES_MESSAGES_NUX";
            case 60:
                return "MEMORIES_SETTINGS";
            case 61:
                return "MALWARE_INTERVENTION_LEARN_MORE";
            case 62:
                return "DECRYPTION_FAILURE_LEARN_MORE";
            case 63:
                return "MESSENGER_META_AI_VOICE";
            case 64:
                return "MESSENGER_META_AI_IMAGINE";
            case 65:
                return "MESSENGER_META_AI_RESPONSE";
            case 66:
                return "MESSENGER_META_AI_INLINE_ENTITY";
            case 67:
                return "MESSENGER_META_AI_FEEDBACK";
            case 68:
                return "MESSENGER_META_AI_NUX";
            case 69:
                return "MESSENGER_META_AI_PLANNER";
            case 70:
                return "MESSENGER_SAFETY_INTERVENTION_PLATFORM";
            case 71:
                return "MESSENGER_SEARCH_LEARN_MORE";
            case 72:
                return "MESSENGER_SEARCH_REEL";
            case 73:
                return "MEMORY_LEARN_MORE";
            case 74:
                return "VOICE_PERSONALIZATION_LEARN_MORE";
            case 75:
                return "AI_COMMENTING_LEARN_MORE";
            case 76:
                return "MESSENGER_USERNAMES_UPSELL_LEARN_MORE";
            case 77:
                return "EDIT_USERNAME_LEARN_MORE";
            case 78:
                return "AI_STUDIO_REVIEW_BANNER_POLICY";
            case 79:
                return "META_AI_CHAT_MESSAGES_LEARN_MORE";
            case 80:
                return "META_AI_LOOKUP_LEARN_MORE";
            case 81:
                return "FB_BUTTON_IN_CHATS_NAV_BAR";
            case 82:
                return "MESSENGER_MEDIA_ATTRIBUTION";
            case 83:
                return "MESSENGER_WEARABLE_ATTRIBUTION";
            case 84:
                return "META_AI_APP_THREAD_SETTING";
            case 85:
                return "META_AI_APP_THREAD_HEADER_SUBTITLE";
            case 86:
                return "META_AI_APP_THREAD_DETAILS_SUBTITLE";
            case 87:
                return "META_AI_APP_THREAD_INFO";
            case 88:
                return "MSGR_CONTEXTUAL_IMAGINE_MUSTACHE_UPSELL";
            case 89:
                return "PHONE_CONNECTION_LEARN_MORE";
            case 90:
                return "FX_3P_LINKING_WEB_AUTH";
            case 91:
                return "MESSENGER_CALLING_RESTRICTIONS_LEARN_MORE";
            case 92:
                return "MESSENGER_META_AI_BIZ_AGENT";
            case 93:
                return "MESSENGER_QUICKSNAP_INSTRUCTIONS_COMMUNITY_STANDARDS";
            case 94:
                return "MESSENGER_REELS_RECAP_POG";
            case 95:
                return "MESSENGER_OMNIPICKER_PUBLIC_GROUP_CHAT_CREATION_LEARN_MORE";
            case 96:
                return "AI_PARENTAL_CONTROLS_LEARN_MORE";
            case 97:
                return "SPECTRA_EB_NOTICE_HELP";
            case 98:
                return "UNKNOWN";
            default:
                return "CONSENT_FLOW_DEEP_LINK";
        }
    }
}
