package p000X;

import com.facebook.ultralight.AutoGeneratedSwitchAppModuleSubClass;
import com.facebook.ultralight.AutoGeneratedSwitchSubClassMasterMethod;
import dalvik.annotation.optimization.NeverInline;

@AutoGeneratedSwitchAppModuleSubClass(2)
/* loaded from: classes12.dex */
public abstract class R3A {
    @NeverInline
    @AutoGeneratedSwitchSubClassMasterMethod
    public static Object A00(int i, InterfaceC98588org interfaceC98588org, Object obj) {
        if (((i >> 7) & 15) == 0) {
            return A01(i, interfaceC98588org, obj);
        }
        throw AnonymousClass031.A0R("Invalid Static DI binding id");
    }

    public static Object A01(int i, InterfaceC98588org interfaceC98588org, Object obj) {
        if (((i >> 0) & 127) != 0) {
            throw AnonymousClass031.A0R("Invalid Static DI binding id");
        }
        return qqC.A00();
    }
}
