package com.facebook.wa.exoplayer.datasource;

import android.net.Uri;
import com.facebook.wa.video.heroplayer.setting.FbAutogeneratedSettings;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import p000X.AbstractC127845ir;
import p000X.AbstractC23467Abq;
import p000X.AbstractC34821ac;
import p000X.AbstractC34831ad;
import p000X.AbstractC34841ae;
import p000X.AbstractC34861ag;
import p000X.AbstractC37199Ghy;
import p000X.AbstractC37202Gi1;
import p000X.AbstractC40853IKx;
import p000X.AbstractC41228Ibh;
import p000X.AnonymousClass000;
import p000X.C0DV;
import p000X.C41170IaJ;
import p000X.C41182IaW;
import p000X.C41287Id1;
import p000X.C87Y;
import p000X.EnumC38895HZs;
import p000X.HXT;
import p000X.HaS;
import p000X.I0R;
import p000X.IO7;
import p000X.IOd;
import p000X.ITT;
import p000X.IYI;
import p000X.IZ3;
import p000X.InterfaceC44003Jtg;
import p000X.InterfaceC44283JzA;
import p000X.InterfaceC44284JzB;
import p000X.InterfaceC44285JzC;
import p000X.J30;
import p000X.JEM;

/* loaded from: classes8.dex */
public class FbHttpProxyDataSource implements InterfaceC44284JzB, InterfaceC44283JzA {
    public InterfaceC44284JzB A00;
    public InterfaceC44285JzC A01;
    public int A02;
    public long A03 = 0;
    public boolean A04;
    public final C41182IaW A05;
    public final JEM A06;
    public final I0R A07;
    public final HaS A08;

    public static void A00(FbHttpProxyDataSource fbHttpProxyDataSource, String str, Map map) {
        List list = (List) map.get(str);
        if (list != null) {
            fbHttpProxyDataSource.A01.Bl8(str, list.get(0));
        }
    }

    @Override // p000X.InterfaceC44284JzB, p000X.InterfaceC44090JvP
    public synchronized void close() {
        this.A00.close();
    }

    @Override // p000X.InterfaceC44284JzB, p000X.InterfaceC44090JvP
    public synchronized int read(byte[] bArr, int i, int i2) {
        long j = this.A03;
        if (j == 0) {
            return -1;
        }
        if (j != -1) {
            i2 = (int) Math.min(i2, j);
        }
        int read = this.A00.read(bArr, i, i2);
        if (read != -1) {
            this.A03 -= read;
        }
        return read;
    }

    @Override // p000X.InterfaceC44284JzB
    public Map AnI() {
        return this.A00.AnI();
    }

    @Override // p000X.InterfaceC44090JvP
    public Uri AuF() {
        return this.A00.AuF();
    }

    /* JADX WARN: Code restructure failed: missing block: B:16:0x0045, code lost:
    
        if (r64.A03 <= 50000) goto L17;
     */
    @Override // p000X.InterfaceC44284JzB, p000X.InterfaceC44090JvP
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public synchronized long Bnl(C41287Id1 c41287Id1) {
        JEM jem;
        long A0I;
        boolean A1X;
        HXT hxt;
        Uri uri = c41287Id1.A04;
        ITT itt = c41287Id1.A05;
        IZ3 iz3 = itt.A0F;
        boolean z = iz3.A02;
        String str = iz3.A00;
        String str2 = iz3.A01;
        String str3 = this.A05.A07;
        IZ3 iz32 = new IZ3(str, str2, z);
        C41170IaJ c41170IaJ = itt.A0E;
        if (c41170IaJ == null) {
            c41170IaJ = HXT.A00.mHttpPriority;
        }
        if (z) {
            jem = this.A06;
            if (jem.enableHttpPriorityForPrefetch) {
                c41170IaJ = new C41170IaJ(c41170IaJ.A00, AbstractC34841ae.A1J(jem.useHttpPriorityIncrementalForPrefetch ? 1 : 0));
            }
            boolean z2 = jem.useLowerHttpPriorityForUnimportantPrefetch;
            if (jem.useLowerHttpPriorityForAllPrefetch) {
                if (z2) {
                    hxt = jem.useHttpPriorityIncrementalForPrefetch ? HXT.A09 : HXT.A08;
                    c41170IaJ = hxt.mHttpPriority;
                }
            } else if (z2) {
            }
            hxt = jem.useHttpPriorityIncrementalForPrefetch ? HXT.A07 : HXT.A06;
            c41170IaJ = hxt.mHttpPriority;
        } else {
            jem = this.A06;
            if (jem.enableHttpPriorityForStreaming) {
                c41170IaJ = (jem.useHttpPriorityIncrementalForStreaming ? HXT.A05 : HXT.A04).mHttpPriority;
                int i = jem.bufferedDurationBasedHttpPriorityUpperBoundMs;
                if (i > 0 && itt.A00 > i) {
                    boolean z3 = jem.useHttpPriorityWarmupForLongBufferedStreaming;
                    boolean z4 = jem.useHttpPriorityIncrementalForLongBufferedStreaming;
                    c41170IaJ = (z3 ? z4 ? HXT.A0B : HXT.A0A : z4 ? HXT.A03 : HXT.A02).mHttpPriority;
                }
            }
        }
        byte[] bArr = c41287Id1.A08;
        long j = c41287Id1.A01;
        long j2 = c41287Id1.A03;
        long j3 = c41287Id1.A02;
        String str4 = c41287Id1.A06;
        int i2 = c41287Id1.A00;
        int i3 = this.A02;
        String str5 = itt.A0J;
        long j4 = itt.A09;
        boolean z5 = itt.A0P;
        int i4 = itt.A07;
        int i5 = itt.A06;
        int i6 = itt.A00;
        int i7 = itt.A08;
        boolean z6 = itt.A0R;
        boolean z7 = itt.A0O;
        long j5 = itt.A0B;
        long j6 = itt.A0D;
        boolean z8 = itt.A0Q;
        int i8 = itt.A05;
        int i9 = itt.A02;
        long j7 = itt.A0C;
        long j8 = itt.A0A;
        int i10 = itt.A01;
        Map map = itt.A0N;
        C41287Id1 c41287Id12 = new C41287Id1(uri, new ITT(c41170IaJ, iz32, str5, itt.A0H, itt.A0G, null, itt.A0I, itt.A0M, itt.A0K, map, i4, i5, i6, i7, i3, i8, i9, i10, itt.A03, j4, j5, j6, j7, j8, z5, z6, z7, z8), str4, bArr, i2, j, j2, j3);
        if (jem.enableVideoPlayerServerSideBweAnnotations) {
            HaS haS = this.A08;
            if (haS != HaS.A04) {
                if (haS != HaS.A08) {
                    if (haS == HaS.A07) {
                    }
                }
            }
            c41287Id12.A05.A0N.put("x-fb-ssbwe-annotation-request-type", 1 - (z ? IO7.A01 : IO7.A0C).intValue() != 0 ? "android-playing-video" : "android-prefetch-video");
        }
        FbAutogeneratedSettings fbAutogeneratedSettings = jem.autogenSettings;
        if (fbAutogeneratedSettings != null && fbAutogeneratedSettings.enableSloHttpHeaderLogging) {
            if (str3 != null) {
                IOd iOd = IOd.A01;
                synchronized (iOd) {
                    try {
                        A1X = AbstractC34841ae.A1X(iOd.A00.get(str3));
                    } catch (Throwable th) {
                        throw th;
                    }
                }
                if (A1X) {
                }
            }
            if (!map.containsKey("x-fb-qpl-ec")) {
                StringBuilder A04 = AnonymousClass000.A04();
                A04.append("video_uid=");
                String A1G = AbstractC34821ac.A1G(C0DV.A00(), A04);
                if (A1G != null) {
                    map.put("x-fb-qpl-ec", A1G);
                }
            }
            String A1E = AbstractC127845ir.A1E("x-fb-qpl-ec", map);
            if (A1E != null) {
                Map map2 = c41287Id12.A05.A0N;
                map2.clear();
                Iterator A15 = AbstractC34831ad.A15(map);
                while (A15.hasNext()) {
                    C87Y.A1Q(AbstractC34861ag.A18(A15), map2);
                }
                IOd iOd2 = IOd.A01;
                synchronized (iOd2) {
                    try {
                        iOd2.A00.put(str3, A1E);
                    } catch (Throwable th2) {
                        throw th2;
                    }
                }
            }
        }
        try {
            InterfaceC44285JzC interfaceC44285JzC = this.A01;
            if (interfaceC44285JzC != null) {
                interfaceC44285JzC.BlB(c41287Id12, EnumC38895HZs.A03);
            }
            InterfaceC44284JzB interfaceC44284JzB = this.A00;
            long Bnl = interfaceC44284JzB.Bnl(c41287Id12);
            boolean A1J = AbstractC34841ae.A1J(jem.enableCaseInsensitiveHttpResponseHeaderKey ? 1 : 0);
            Map AnI = interfaceC44284JzB.AnI();
            if (AnI != null && this.A01 != null) {
                List A01 = AbstractC40853IKx.A01("X-FB-Connection-Quality", AnI, A1J);
                if (A01 != null) {
                    this.A01.Bl8("X-FB-Connection-Quality", AbstractC34861ag.A12(A01, 0));
                }
                List A16 = AbstractC23467Abq.A16("x-fb-cec-video-limit", AnI);
                if (A16 != null) {
                    this.A01.Bl8("x-fb-cec-video-limit", AbstractC34861ag.A12(A16, 0));
                }
                A00(this, "up-ttfb", AnI);
                A00(this, "x-fb-log-session-id", AnI);
                A00(this, "x-fb-log-transaction-id", AnI);
                A00(this, "x-fb-session-id", AnI);
                A00(this, "x-fb-response-time-ms", AnI);
                A00(this, "x-bwe-mean", AnI);
                A00(this, "x-bwe-std-dev", AnI);
                A00(this, "x-fb-dynamic-predictive-response-chunk-size", AnI);
                Iterator A152 = AbstractC34831ad.A15(AnI);
                while (A152.hasNext()) {
                    Map.Entry A18 = AbstractC34861ag.A18(A152);
                    if (A18.getKey() != null && A18.getValue() != null && !((List) A18.getValue()).isEmpty() && AbstractC34861ag.A13(A18).startsWith("x-fb-ull-")) {
                        this.A01.Bl8(AbstractC34861ag.A13(A18), ((List) A18.getValue()).get(0));
                    }
                }
            }
            long A00 = AbstractC40853IKx.A00(AnI, A1J);
            long j9 = c41287Id12.A03;
            A0I = AbstractC37202Gi1.A0I(A00 - j9);
            if (Bnl == -1 || Bnl > A0I) {
                this.A03 = A0I;
            } else {
                this.A03 = Bnl;
            }
            Object[] A1Z = AbstractC37199Ghy.A1Z();
            AbstractC127845ir.A1P(A1Z, 0, j9);
            long j10 = c41287Id12.A02;
            AbstractC127845ir.A1P(A1Z, 1, j10);
            AbstractC37202Gi1.A1P(A1Z, A0I);
            A1Z[3] = str3;
            A1Z[4] = c41287Id12.A06;
            IYI.A01("com.facebook.wa.exoplayer.datasource.FbHttpProxyDataSource", "Opening data spec Offset: %d, Length %d Open Length %d Videoid %s Key %s", A1Z);
            if (j10 != -1) {
                A0I = Math.min(Bnl, A0I);
            }
        } catch (IOException e) {
            throw e;
        }
        return A0I;
    }

    @Override // p000X.InterfaceC44090JvP
    public void cancel() {
        if (this.A04) {
            this.A00.cancel();
        }
    }

    public FbHttpProxyDataSource(InterfaceC44284JzB interfaceC44284JzB, InterfaceC44285JzC interfaceC44285JzC, I0R i0r, C41182IaW c41182IaW, JEM jem, int i, int i2, boolean z) {
        HaS haS;
        this.A05 = c41182IaW;
        this.A00 = interfaceC44284JzB;
        this.A02 = i;
        this.A01 = interfaceC44285JzC;
        HaS[] values = HaS.values();
        int length = values.length;
        int i3 = 0;
        while (true) {
            if (i3 >= length) {
                haS = HaS.A09;
                break;
            }
            haS = values[i3];
            if (haS.value == i2) {
                break;
            } else {
                i3++;
            }
        }
        this.A08 = haS;
        this.A04 = z;
        this.A06 = jem;
        this.A07 = i0r;
    }

    @Override // p000X.InterfaceC44090JvP
    public void A8h(InterfaceC44003Jtg interfaceC44003Jtg) {
        AbstractC41228Ibh.A01(interfaceC44003Jtg);
        if (interfaceC44003Jtg instanceof InterfaceC44285JzC) {
            this.A01 = (InterfaceC44285JzC) interfaceC44003Jtg;
        } else {
            this.A01 = new J30(interfaceC44003Jtg);
        }
    }
}
