.class public abstract LX/R2z;
.super Ljava/lang/Object;
.source ""


# annotations
.annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchAppModuleSubClass;
    value = 0x1
.end annotation


# direct methods
.method public static A00(ILX/org;Ljava/lang/Object;)Ljava/lang/Object;
    .locals 1
    .annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchSubClassMasterMethod;
    .end annotation

    .annotation build Ldalvik/annotation/optimization/NeverInline;
    .end annotation

    shr-int/lit8 v0, p0, 0x7

    and-int/lit8 v0, v0, 0xf

    if-nez v0, :cond_0

    invoke-static {p0, p1, p2}, LX/R2z;->A01(ILX/org;Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0

    return-object v0

    :cond_0
    const-string v0, "Invalid Static DI binding id"

    invoke-static {v0}, LX/031;->A0R(Ljava/lang/String;)Ljava/lang/IllegalArgumentException;

    move-result-object v0

    throw v0
.end method

.method public static A01(ILX/org;Ljava/lang/Object;)Ljava/lang/Object;
    .locals 0

    shr-int/lit8 p0, p0, 0x0

    and-int/lit8 p0, p0, 0x7f

    packed-switch p0, :pswitch_data_0

    :pswitch_0
    const-string p0, "Invalid Static DI binding id"

    invoke-static {p0}, LX/031;->A0R(Ljava/lang/String;)Ljava/lang/IllegalArgumentException;

    move-result-object p0

    throw p0

    :pswitch_1
    invoke-static {p2}, LX/qjS;->A00(Ljava/lang/Object;)LX/qjd;

    move-result-object p0

    return-object p0

    :pswitch_2
    invoke-static {}, LX/qjU;->A00()LX/qkb;

    move-result-object p0

    return-object p0

    :pswitch_3
    invoke-static {}, LX/qjU;->A02()LX/qkE;

    move-result-object p0

    return-object p0

    :pswitch_4
    invoke-static {}, LX/qjU;->A01()LX/qkD;

    move-result-object p0

    return-object p0

    :pswitch_5
    invoke-static {}, LX/qjT;->A00()LX/qkk;

    move-result-object p0

    return-object p0

    :pswitch_6
    invoke-static {}, LX/qjT;->A01()LX/qkF;

    move-result-object p0

    return-object p0

    :pswitch_7
    invoke-static {}, LX/qjP;->A00()LX/qkB;

    move-result-object p0

    return-object p0

    :pswitch_8
    invoke-static {}, LX/qjO;->A00()LX/qkA;

    move-result-object p0

    return-object p0

    :pswitch_9
    invoke-static {}, LX/qjS;->A01()LX/qkC;

    move-result-object p0

    return-object p0

    :pswitch_a
    invoke-static {}, LX/qjQ;->A00()LX/qlu;

    move-result-object p0

    return-object p0

    :pswitch_b
    invoke-static {}, LX/qjR;->A00()LX/qkL;

    move-result-object p0

    return-object p0

    :pswitch_c
    invoke-static {}, LX/qjN;->A00()LX/qk9;

    move-result-object p0

    return-object p0

    :pswitch_data_0
    .packed-switch 0x0
        :pswitch_8
        :pswitch_9
        :pswitch_a
        :pswitch_b
        :pswitch_c
        :pswitch_1
        :pswitch_2
        :pswitch_3
        :pswitch_4
        :pswitch_5
        :pswitch_6
        :pswitch_0
        :pswitch_0
        :pswitch_7
        :pswitch_8
        :pswitch_9
        :pswitch_a
        :pswitch_b
        :pswitch_c
    .end packed-switch
.end method
