.class public abstract LX/R3A;
.super Ljava/lang/Object;
.source ""


# annotations
.annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchAppModuleSubClass;
    value = 0x2
.end annotation


# direct methods
.method public static A00(ILX/org;Ljava/lang/Object;)Ljava/lang/Object;
    .locals 1
    .annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchSubClassMasterMethod;
    .end annotation

    .annotation build Ldalvik/annotation/optimization/NeverInline;
    .end annotation

    shr-int/lit8 v0, p0, 0x7

    and-int/lit8 v0, v0, 0xf

    if-nez v0, :cond_0

    invoke-static {p0, p1, p2}, LX/R3A;->A01(ILX/org;Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0

    return-object v0

    :cond_0
    const-string v0, "Invalid Static DI binding id"

    invoke-static {v0}, LX/031;->A0R(Ljava/lang/String;)Ljava/lang/IllegalArgumentException;

    move-result-object v0

    throw v0
.end method

.method public static A01(ILX/org;Ljava/lang/Object;)Ljava/lang/Object;
    .locals 0

    shr-int/lit8 p0, p0, 0x0

    and-int/lit8 p0, p0, 0x7f

    if-eqz p0, :cond_0

    const-string p0, "Invalid Static DI binding id"

    invoke-static {p0}, LX/031;->A0R(Ljava/lang/String;)Ljava/lang/IllegalArgumentException;

    move-result-object p0

    throw p0

    :cond_0
    invoke-static {}, LX/qqC;->A00()LX/qqD;

    move-result-object p0

    return-object p0
.end method
