package p000X;

import java.util.Collections;

/* renamed from: X.IMi, reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public abstract class AbstractC40887IMi {
    public static final AnonymousClass013 A00;

    static {
        AnonymousClass013 anonymousClass013 = new AnonymousClass013(59);
        A00 = anonymousClass013;
        String[] strArr = new String[2];
        strArr[0] = "ZA";
        anonymousClass013.put("af", AbstractC37200Ghz.A0t("NA", strArr, 1));
        String[] strArr2 = new String[4];
        strArr2[0] = "EG";
        strArr2[1] = "SA";
        strArr2[2] = "SY";
        anonymousClass013.put("ar", AbstractC37200Ghz.A0t("IQ", strArr2, 3));
        String[] strArr3 = new String[5];
        strArr3[0] = "AL";
        strArr3[1] = "XK";
        strArr3[2] = "GR";
        strArr3[3] = "MK";
        anonymousClass013.put("sq", AbstractC37200Ghz.A0t("IT", strArr3, 4));
        anonymousClass013.put("az", Collections.singletonList("AZ"));
        String[] strArr4 = new String[2];
        strArr4[0] = "IN";
        anonymousClass013.put("bn", AbstractC37200Ghz.A0t("BD", strArr4, 1));
        anonymousClass013.put("bg", Collections.singletonList("BG"));
        String[] strArr5 = new String[2];
        strArr5[0] = "ES";
        anonymousClass013.put("ca", AbstractC37200Ghz.A0t("AD", strArr5, 1));
        String[] strArr6 = new String[4];
        strArr6[0] = "MY";
        strArr6[1] = "SG";
        strArr6[2] = "CN";
        anonymousClass013.put("zh-Hans", AbstractC37200Ghz.A0t("HK", strArr6, 3));
        String[] strArr7 = new String[4];
        strArr7[0] = "HK";
        strArr7[1] = "TW";
        strArr7[2] = "MY";
        anonymousClass013.put("zh-Hant", AbstractC37200Ghz.A0t("MO", strArr7, 3));
        String[] strArr8 = new String[2];
        strArr8[0] = "HR";
        anonymousClass013.put("hr", AbstractC37200Ghz.A0t("BA", strArr8, 1));
        anonymousClass013.put("cs", Collections.singletonList("CZ"));
        anonymousClass013.put("da", Collections.singletonList("DK"));
        String[] strArr9 = new String[3];
        strArr9[0] = "NL";
        strArr9[1] = "BE";
        anonymousClass013.put("nl", AbstractC37200Ghz.A0t("SR", strArr9, 2));
        String[] strArr10 = new String[5];
        strArr10[0] = "IN";
        strArr10[1] = "PK";
        strArr10[2] = "ZA";
        strArr10[3] = "GB";
        anonymousClass013.put("en", AbstractC37200Ghz.A0t("US", strArr10, 4));
        anonymousClass013.put("et", Collections.singletonList("EE"));
        anonymousClass013.put("fil", Collections.singletonList("PH"));
        anonymousClass013.put("fi", Collections.singletonList("FI"));
        anonymousClass013.put("fr", Collections.singletonList("FR"));
        String[] strArr11 = new String[3];
        strArr11[0] = "DE";
        strArr11[1] = "AT";
        anonymousClass013.put("de", AbstractC37200Ghz.A0t("CH", strArr11, 2));
        String[] strArr12 = new String[2];
        strArr12[0] = "GR";
        anonymousClass013.put("el", AbstractC37200Ghz.A0t("CY", strArr12, 1));
        A00(anonymousClass013, "IN", "gu");
        anonymousClass013.put("he", Collections.singletonList("IL"));
        A00(anonymousClass013, "IN", "hi");
        String[] strArr13 = new String[2];
        strArr13[0] = "HU";
        anonymousClass013.put("hu", AbstractC37200Ghz.A0t("RO", strArr13, 1));
        anonymousClass013.put("id", Collections.singletonList("ID"));
        String[] strArr14 = new String[2];
        strArr14[0] = "IE";
        anonymousClass013.put("ga", AbstractC37200Ghz.A0t("GB", strArr14, 1));
        String[] strArr15 = new String[2];
        strArr15[0] = "IT";
        anonymousClass013.put("it", AbstractC37200Ghz.A0t("CH", strArr15, 1));
        anonymousClass013.put("ja", Collections.singletonList("JP"));
        A00(anonymousClass013, "IN", "kn");
        String[] strArr16 = new String[3];
        strArr16[0] = "KZ";
        strArr16[1] = "UZ";
        anonymousClass013.put("kk", AbstractC37200Ghz.A0t("MN", strArr16, 2));
        anonymousClass013.put("ko", Collections.singletonList("KR"));
        anonymousClass013.put("lo", Collections.singletonList("LA"));
        anonymousClass013.put("lv", Collections.singletonList("LV"));
        anonymousClass013.put("lt", Collections.singletonList("LT"));
        A00(anonymousClass013, "MK", "mk");
        A00(anonymousClass013, "MY", "ms");
        A00(anonymousClass013, "IN", "ml");
        A00(anonymousClass013, "IN", "mr");
        anonymousClass013.put("nb", Collections.singletonList("NO"));
        String[] strArr17 = new String[2];
        strArr17[0] = "IR";
        anonymousClass013.put("fa", AbstractC37200Ghz.A0t("AF", strArr17, 1));
        anonymousClass013.put("pl", Collections.singletonList("PL"));
        anonymousClass013.put("pt-BR", Collections.singletonList("BR"));
        String[] strArr18 = new String[4];
        strArr18[0] = "PT";
        strArr18[1] = "AO";
        strArr18[2] = "BR";
        anonymousClass013.put("pt-PT", AbstractC37200Ghz.A0t("MZ", strArr18, 3));
        A00(anonymousClass013, "IN", "pa");
        String[] strArr19 = new String[2];
        strArr19[0] = "RO";
        anonymousClass013.put("ro", AbstractC37200Ghz.A0t("MD", strArr19, 1));
        String[] strArr20 = new String[4];
        strArr20[0] = "RU";
        strArr20[1] = "KZ";
        strArr20[2] = "KG";
        anonymousClass013.put("ru", AbstractC37200Ghz.A0t("UA", strArr20, 3));
        String[] strArr21 = new String[3];
        strArr21[0] = "RS";
        strArr21[1] = "BA";
        anonymousClass013.put("sr", AbstractC37200Ghz.A0t("ME", strArr21, 2));
        anonymousClass013.put("sk", Collections.singletonList("SK"));
        anonymousClass013.put("sl", Collections.singletonList("SI"));
        String[] strArr22 = new String[6];
        strArr22[0] = "MX";
        strArr22[1] = "AR";
        strArr22[2] = "CL";
        strArr22[3] = "CO";
        strArr22[4] = "ES";
        anonymousClass013.put("es", AbstractC37200Ghz.A0t("PE", strArr22, 5));
        String[] strArr23 = new String[4];
        strArr23[0] = "TZ";
        strArr23[1] = "KE";
        strArr23[2] = "RW";
        anonymousClass013.put("sw", AbstractC37200Ghz.A0t("BI", strArr23, 3));
        String[] strArr24 = new String[2];
        strArr24[0] = "SE";
        anonymousClass013.put("sv", AbstractC37200Ghz.A0t("FI", strArr24, 1));
        String[] strArr25 = new String[4];
        strArr25[0] = "IN";
        strArr25[1] = "LK";
        strArr25[2] = "MY";
        anonymousClass013.put("ta", AbstractC37200Ghz.A0t("SG", strArr25, 3));
        A00(anonymousClass013, "IN", "te");
        String[] strArr26 = new String[2];
        strArr26[0] = "TH";
        anonymousClass013.put("th", AbstractC37200Ghz.A0t("LA", strArr26, 1));
        anonymousClass013.put("tr", Collections.singletonList("TR"));
        anonymousClass013.put("uk", Collections.singletonList("UA"));
        String[] strArr27 = new String[2];
        strArr27[0] = "PK";
        anonymousClass013.put("ur", AbstractC37200Ghz.A0t("IN", strArr27, 1));
        String[] A1b = C87U.A1b("UZ", "RU", 4, 1);
        A1b[2] = "KZ";
        anonymousClass013.put("uz", AbstractC37200Ghz.A0t("KG", A1b, 3));
        anonymousClass013.put("vi", Collections.singletonList("VN"));
    }

    public static void A00(AnonymousClass012 anonymousClass012, Object obj, Object obj2) {
        anonymousClass012.put(obj2, Collections.singletonList(obj));
    }
}
