package p000X;

/* renamed from: X.H4s, reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public class C38198H4s extends JED {
    public static final long serialVersionUID = 1014987236950835638L;
    public final String appNetSessionId;
    public final long avgBitrate;
    public final int bufferedDurationMs;
    public final int bufferedDurationMsAtDataSpecCreation;
    public final EnumC38897HZu cacheType;
    public final long cdnResponseTime;
    public final Long clientWallClockOffsetMs;
    public final String codec;
    public final long confidenceBasedBitrateEstimate;
    public final int confidencePctForBitrateEstimate;
    public final String connectionQuality;
    public final Long contentLength;
    public final String contentType;
    public final String dataSourceFactory;
    public final long dataSpecCreationTimeMs;
    public final String edgeHit;
    public final String exceptionMessage;
    public final int expectedPredictedNumber;
    public final int firstChunkSize;
    public final boolean inRewoundState;
    public final boolean isChunkedTransfer;
    public final boolean isFBMS;
    public final boolean isFbPredictiveDASH;
    public final boolean isFirstTimePlay;
    public final boolean isInWarmup;
    public final boolean isLowestBitrate;
    public final boolean isManifestDynamic;
    public final boolean isPredictedURL;
    public final boolean isPrefetch;
    public final boolean isSkipAheadChunk;
    public final boolean isSpherical;
    public final boolean isSponsored;
    public final boolean isTemplatedManifest;
    public final int latestSegmentId;
    public final long manifestFirstSegmentStartTs;
    public final long manifestLastSegmentEndTs;
    public final long manifestNumSegments;
    public final int minimumLoadPositionMs;
    public final int networkPriority;
    public final long numSegmentsToEndOfManifest;
    public final String oneObserved;
    public final String oneReqWave;
    public final String oneResWave;
    public final String oneVariant;
    public final String originHit;
    public final String playOrigin;
    public final String playSubOrigin;
    public final long playerId;
    public final String playerType;
    public final int positionInUnit;
    public final int predictedNumberMapping;
    public final String prefetchSource;
    public final String qualityLabel;
    public final long requestQueueDurationMs;
    public final long requestedLength;
    public final int segmentDurationMs;
    public final long segmentStartMs;
    public final long startVideoBandwidth;
    public final long startVideoTTFB;
    public final long startingByteOffset;
    public final int streamType;
    public final String tigonSessionId;
    public final String tigonTransactionId;
    public final long timeMs;
    public final int transferSeqNum;
    public final long transferStartDurationMs;
    public final long upstreamTTFB;
    public final String url;
    public final String videoBandwidthEstimateStr;
    public final String videoId;
    public final String vpSessionId;

    public String toString() {
        StringBuilder A04 = AnonymousClass000.A04();
        StringBuilder A042 = AnonymousClass000.A04();
        A042.append("timeMs=");
        StringBuilder A0w = AbstractC37204Gi3.A0w(A042, A04, this.timeMs);
        A0w.append(", videoId=");
        StringBuilder A0u = AbstractC37204Gi3.A0u(this.videoId, A0w, A04);
        A0u.append(", playerId=");
        StringBuilder A0w2 = AbstractC37204Gi3.A0w(A0u, A04, this.playerId);
        A0w2.append(", url=");
        StringBuilder A0u2 = AbstractC37204Gi3.A0u(this.url, A0w2, A04);
        A0u2.append(", exception=");
        StringBuilder A0u3 = AbstractC37204Gi3.A0u(this.exceptionMessage, A0u2, A04);
        A0u3.append(", isPrefetch=");
        StringBuilder A0x = AbstractC37204Gi3.A0x(A0u3, A04, this.isPrefetch);
        A0x.append(", prefetchSource=");
        StringBuilder A0u4 = AbstractC37204Gi3.A0u(this.prefetchSource, A0x, A04);
        A0u4.append(", queueDuration=");
        StringBuilder A0w3 = AbstractC37204Gi3.A0w(A0u4, A04, this.requestQueueDurationMs);
        A0w3.append(", startDuration=");
        StringBuilder A0w4 = AbstractC37204Gi3.A0w(A0w3, A04, this.transferStartDurationMs);
        A0w4.append(", seqNum=");
        StringBuilder A0v = AbstractC37204Gi3.A0v(A0w4, A04, this.transferSeqNum);
        A0v.append(", cacheType=");
        StringBuilder A0u5 = AbstractC37204Gi3.A0u(this.cacheType.mName, A0v, A04);
        A0u5.append(", isFirstPlay=");
        StringBuilder A0x2 = AbstractC37204Gi3.A0x(A0u5, A04, this.isFirstTimePlay);
        A0x2.append(", playOrigin=");
        StringBuilder A0u6 = AbstractC37204Gi3.A0u(this.playOrigin, A0x2, A04);
        A0u6.append(", startingByteOffset=");
        StringBuilder A0w5 = AbstractC37204Gi3.A0w(A0u6, A04, this.startingByteOffset);
        A0w5.append(", requestedLength=");
        StringBuilder A0w6 = AbstractC37204Gi3.A0w(A0w5, A04, this.requestedLength);
        A0w6.append(", streamType=");
        StringBuilder A0v2 = AbstractC37204Gi3.A0v(A0w6, A04, this.streamType);
        A0v2.append(", segmentStart=");
        StringBuilder A0w7 = AbstractC37204Gi3.A0w(A0v2, A04, this.segmentStartMs);
        A0w7.append(", segmentDuration=");
        StringBuilder A0v3 = AbstractC37204Gi3.A0v(A0w7, A04, this.segmentDurationMs);
        A0v3.append(", dataSourceFactory=");
        StringBuilder A0u7 = AbstractC37204Gi3.A0u(this.dataSourceFactory, A0v3, A04);
        A0u7.append(", qualityLabel=");
        StringBuilder A0u8 = AbstractC37204Gi3.A0u(this.qualityLabel, A0u7, A04);
        A0u8.append(", connQual=");
        StringBuilder A0u9 = AbstractC37204Gi3.A0u(this.connectionQuality, A0u8, A04);
        A0u9.append(", networkPriority=");
        StringBuilder A0v4 = AbstractC37204Gi3.A0v(A0u9, A04, this.networkPriority);
        A0v4.append(", bufferedDurationMs=");
        StringBuilder A0v5 = AbstractC37204Gi3.A0v(A0v4, A04, this.bufferedDurationMs);
        A0v5.append(", startVideoBandwidth=");
        StringBuilder A0w8 = AbstractC37204Gi3.A0w(A0v5, A04, this.startVideoBandwidth);
        A0w8.append(", startVideoTTFB=");
        StringBuilder A0w9 = AbstractC37204Gi3.A0w(A0w8, A04, this.startVideoTTFB);
        A0w9.append(", videoBandwidthEstimateStr=");
        StringBuilder A0u10 = AbstractC37204Gi3.A0u(this.videoBandwidthEstimateStr, A0w9, A04);
        A0u10.append(", upstreamTTFB=");
        StringBuilder A0w10 = AbstractC37204Gi3.A0w(A0u10, A04, this.upstreamTTFB);
        A0w10.append(", tigonSessionId=");
        StringBuilder A0u11 = AbstractC37204Gi3.A0u(this.tigonSessionId, A0w10, A04);
        A0u11.append(", tigonTransactionId=");
        StringBuilder A0u12 = AbstractC37204Gi3.A0u(this.tigonTransactionId, A0u11, A04);
        A0u12.append(", appNetSesssionId=");
        StringBuilder A0u13 = AbstractC37204Gi3.A0u(this.appNetSessionId, A0u12, A04);
        A0u13.append(", manifestFirstSegmentStartTs=");
        StringBuilder A0w11 = AbstractC37204Gi3.A0w(A0u13, A04, this.manifestFirstSegmentStartTs);
        A0w11.append(", manifestLastSegmentEndTs=");
        StringBuilder A0w12 = AbstractC37204Gi3.A0w(A0w11, A04, this.manifestLastSegmentEndTs);
        A0w12.append(", manifestNumSegments=");
        StringBuilder A0w13 = AbstractC37204Gi3.A0w(A0w12, A04, this.manifestNumSegments);
        A0w13.append(", bufferedDurationMsAtDataSpecCreation=");
        StringBuilder A0v6 = AbstractC37204Gi3.A0v(A0w13, A04, this.bufferedDurationMsAtDataSpecCreation);
        A0v6.append(", dataSpecCreationTimeMs=");
        StringBuilder A0w14 = AbstractC37204Gi3.A0w(A0v6, A04, this.dataSpecCreationTimeMs);
        A0w14.append(", playSubOrigin=");
        StringBuilder A0u14 = AbstractC37204Gi3.A0u(this.playSubOrigin, A0w14, A04);
        A0u14.append(", isFBMS=");
        StringBuilder A0x3 = AbstractC37204Gi3.A0x(A0u14, A04, this.isFBMS);
        A0x3.append(", isFbPredictiveDASH=");
        StringBuilder A0x4 = AbstractC37204Gi3.A0x(A0x3, A04, this.isFbPredictiveDASH);
        A0x4.append(", isSkipAheadChunk=");
        StringBuilder A0x5 = AbstractC37204Gi3.A0x(A0x4, A04, this.isSkipAheadChunk);
        A0x5.append(", inRewoundState=");
        StringBuilder A0x6 = AbstractC37204Gi3.A0x(A0x5, A04, this.inRewoundState);
        A0x6.append(", isManifestDynamic=");
        StringBuilder A0x7 = AbstractC37204Gi3.A0x(A0x6, A04, this.isManifestDynamic);
        A0x7.append(", isChunkedTransfer=");
        StringBuilder A0x8 = AbstractC37204Gi3.A0x(A0x7, A04, this.isChunkedTransfer);
        A0x8.append(", isPredictedURL=");
        StringBuilder A0x9 = AbstractC37204Gi3.A0x(A0x8, A04, this.isPredictedURL);
        A0x9.append(", expectedPredictedNumber=");
        StringBuilder A0v7 = AbstractC37204Gi3.A0v(A0x9, A04, this.expectedPredictedNumber);
        A0v7.append(", predictedNumberMapping=");
        StringBuilder A0v8 = AbstractC37204Gi3.A0v(A0v7, A04, this.predictedNumberMapping);
        A0v8.append(", numSegmentsToEndOfManifest= ");
        StringBuilder A0w15 = AbstractC37204Gi3.A0w(A0v8, A04, this.numSegmentsToEndOfManifest);
        A0w15.append(", edgeHit= ");
        StringBuilder A0u15 = AbstractC37204Gi3.A0u(this.edgeHit, A0w15, A04);
        A0u15.append(", originHit= ");
        StringBuilder A0u16 = AbstractC37204Gi3.A0u(this.originHit, A0u15, A04);
        A0u16.append(", codec= ");
        StringBuilder A0u17 = AbstractC37204Gi3.A0u(this.codec, A0u16, A04);
        A0u17.append(", cdnResponseTime= ");
        StringBuilder A0w16 = AbstractC37204Gi3.A0w(A0u17, A04, this.cdnResponseTime);
        A0w16.append(", contentType= ");
        StringBuilder A0u18 = AbstractC37204Gi3.A0u(this.contentType, A0w16, A04);
        A0u18.append(", latestSegmentId= ");
        StringBuilder A0v9 = AbstractC37204Gi3.A0v(A0u18, A04, this.latestSegmentId);
        A0v9.append(", confidenceBasedBitrateEstimate=");
        StringBuilder A0w17 = AbstractC37204Gi3.A0w(A0v9, A04, this.confidenceBasedBitrateEstimate);
        A0w17.append(", confidencePctForBitrateEstimate=");
        StringBuilder A0v10 = AbstractC37204Gi3.A0v(A0w17, A04, this.confidencePctForBitrateEstimate);
        A0v10.append(", minimumLoadPositionMs=");
        StringBuilder A0v11 = AbstractC37204Gi3.A0v(A0v10, A04, this.minimumLoadPositionMs);
        A0v11.append(", oneReqWave=");
        StringBuilder A0u19 = AbstractC37204Gi3.A0u(this.oneReqWave, A0v11, A04);
        A0u19.append(", oneResWave=");
        StringBuilder A0u20 = AbstractC37204Gi3.A0u(this.oneResWave, A0u19, A04);
        A0u20.append(", oneObserved=");
        StringBuilder A0u21 = AbstractC37204Gi3.A0u(this.oneObserved, A0u20, A04);
        A0u21.append(", oneVariant=");
        StringBuilder A0u22 = AbstractC37204Gi3.A0u(this.oneVariant, A0u21, A04);
        A0u22.append(", playerType=");
        StringBuilder A0u23 = AbstractC37204Gi3.A0u(this.playerType, A0u22, A04);
        A0u23.append(", positionInUnit=");
        StringBuilder A0v12 = AbstractC37204Gi3.A0v(A0u23, A04, this.positionInUnit);
        A0v12.append(", vpSessionId=");
        StringBuilder A0u24 = AbstractC37204Gi3.A0u(this.vpSessionId, A0v12, A04);
        A0u24.append(", firstChunkSize=");
        StringBuilder A0v13 = AbstractC37204Gi3.A0v(A0u24, A04, this.firstChunkSize);
        A0v13.append(", clientWallClockOffsetMs=");
        A0v13.append(this.clientWallClockOffsetMs);
        C3WE.A1P(A0v13, A04);
        StringBuilder A043 = AnonymousClass000.A04();
        A043.append(", contentLength=");
        A043.append(this.contentLength);
        C3WE.A1P(A043, A04);
        return A04.toString();
    }

    public C38198H4s(EnumC38897HZu enumC38897HZu, Long l, Long l2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8) {
        super(EnumC38909HaM.A0H);
        this.timeMs = j;
        this.videoId = str;
        this.playerId = j2;
        this.url = str2;
        this.exceptionMessage = str3;
        this.isPrefetch = z;
        this.prefetchSource = "";
        this.requestQueueDurationMs = j3;
        this.transferStartDurationMs = j4;
        this.transferSeqNum = i;
        this.cacheType = enumC38897HZu;
        this.isFirstTimePlay = z2;
        this.isInWarmup = z3;
        this.playOrigin = "WA_Player_Origin";
        this.playSubOrigin = "WA_Player_SubOrigin";
        this.startingByteOffset = j5;
        this.requestedLength = j6;
        this.streamType = i2;
        this.segmentStartMs = j7;
        this.segmentDurationMs = i3;
        this.dataSourceFactory = "Apache";
        this.qualityLabel = str4;
        this.connectionQuality = str5;
        this.networkPriority = i4;
        this.avgBitrate = j8;
        this.isLowestBitrate = z4;
        this.bufferedDurationMs = i5;
        this.startVideoBandwidth = j9;
        this.startVideoTTFB = j10;
        this.isSpherical = false;
        this.isSponsored = false;
        this.isTemplatedManifest = false;
        this.videoBandwidthEstimateStr = str6;
        this.upstreamTTFB = j11;
        this.tigonSessionId = null;
        this.tigonTransactionId = null;
        this.appNetSessionId = str7;
        this.manifestFirstSegmentStartTs = -1L;
        this.manifestLastSegmentEndTs = -1L;
        this.manifestNumSegments = -1L;
        this.bufferedDurationMsAtDataSpecCreation = i6;
        this.dataSpecCreationTimeMs = j12;
        this.isFBMS = false;
        this.isFbPredictiveDASH = false;
        this.isSkipAheadChunk = z5;
        this.inRewoundState = z6;
        this.isManifestDynamic = false;
        this.isChunkedTransfer = z7;
        this.isPredictedURL = z8;
        this.expectedPredictedNumber = i8;
        this.predictedNumberMapping = i7;
        this.numSegmentsToEndOfManifest = j13;
        this.edgeHit = str8;
        this.originHit = str9;
        this.codec = null;
        this.cdnResponseTime = j14;
        this.contentType = str10;
        this.latestSegmentId = i9;
        this.confidenceBasedBitrateEstimate = j15;
        this.confidencePctForBitrateEstimate = i10;
        this.minimumLoadPositionMs = i11;
        this.oneReqWave = str11;
        this.oneResWave = str12;
        this.oneObserved = str13;
        this.oneVariant = str14;
        this.playerType = str15;
        this.positionInUnit = -1;
        this.vpSessionId = str16;
        this.firstChunkSize = i12;
        this.clientWallClockOffsetMs = l;
        this.contentLength = l2;
    }
}
