package p000X;

import android.net.Uri;
import android.util.LruCache;
import com.facebook.video.heroplayer.setting.FbAutogeneratedSettings;
import com.facebook.video.heroplayer.setting.HeroPlayerSetting;
import java.io.IOException;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;

/* renamed from: X.Iwq, reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public final class C42231Iwq implements InterfaceC44262Jyl {
    public static final String A09;
    public long A00;
    public InterfaceC44264Jyn A01;
    public final InterfaceC44262Jyl A02;
    public final C40746IFh A03;
    public final HeroPlayerSetting A04;
    public final C40161Hvz A05;
    public final EnumC38901HZy A06;
    public final AtomicBoolean A07;
    public final AtomicBoolean A08;

    @Override // p000X.InterfaceC44257Jyg
    public void A8g(InterfaceC44029JuF interfaceC44029JuF) {
        C00C.A0A(interfaceC44029JuF, 0);
        if (interfaceC44029JuF instanceof InterfaceC44264Jyn) {
            this.A01 = (InterfaceC44264Jyn) interfaceC44029JuF;
        } else {
            this.A01 = new C42239Iwz(interfaceC44029JuF);
        }
    }

    @Override // p000X.InterfaceC44257Jyg
    public synchronized void close() {
        this.A02.close();
    }

    @Override // p000X.InterfaceC43738JoS
    public synchronized int read(byte[] bArr, int i, int i2) {
        C00C.A0A(bArr, 0);
        long j = this.A00;
        if (j == 0) {
            return -1;
        }
        if (j != -1) {
            i2 = (int) Math.min(i2, j);
        }
        int read = this.A02.read(bArr, i, i2);
        if (read != -1) {
            this.A00 -= read;
        }
        return read;
    }

    static {
        String name = C42231Iwq.class.getName();
        C00C.A06(name);
        A09 = name;
    }

    @Override // p000X.InterfaceC44257Jyg
    public Map AnI() {
        return this.A02.AnI();
    }

    @Override // p000X.InterfaceC44257Jyg
    public Uri AuF() {
        return this.A02.AuF();
    }

    /* JADX WARN: Code restructure failed: missing block: B:47:0x006b, code lost:
    
        if (r3.startsWith("fb-") == false) goto L32;
     */
    /* JADX WARN: Code restructure failed: missing block: B:9:0x002d, code lost:
    
        if ("https".equalsIgnoreCase(r0.getScheme()) == false) goto L32;
     */
    /* JADX WARN: Removed duplicated region for block: B:17:0x008a  */
    /* JADX WARN: Removed duplicated region for block: B:31:0x0077 A[Catch: all -> 0x0440, TryCatch #1 {, blocks: (B:4:0x0003, B:6:0x0017, B:8:0x0023, B:10:0x008b, B:12:0x0095, B:15:0x0080, B:21:0x0436, B:22:0x043f, B:24:0x00a1, B:26:0x00a7, B:29:0x006d, B:31:0x0077, B:32:0x002f, B:34:0x0035, B:36:0x003d, B:38:0x0045, B:40:0x004d, B:42:0x0055, B:44:0x005d, B:46:0x0065, B:48:0x00b9, B:50:0x00c1, B:51:0x00c3, B:53:0x00cc, B:54:0x00ce, B:56:0x00d6, B:57:0x00d8, B:59:0x00e0, B:60:0x00e2, B:62:0x00f3, B:65:0x0116, B:67:0x011c, B:69:0x0126, B:71:0x012a, B:72:0x0164, B:75:0x0181, B:78:0x0215, B:80:0x022c, B:82:0x0232, B:84:0x0236, B:87:0x023c, B:88:0x0241, B:91:0x024e, B:93:0x0256, B:95:0x023f, B:96:0x025f, B:98:0x0263, B:100:0x0267, B:101:0x026c, B:106:0x027d, B:108:0x0280, B:110:0x0286, B:112:0x0291, B:114:0x0295, B:116:0x02a7, B:117:0x02b0, B:121:0x02bb, B:132:0x02c2, B:128:0x02b2, B:134:0x02c3, B:136:0x02c7, B:137:0x02cc, B:138:0x02d2, B:140:0x02da, B:142:0x02e2, B:144:0x02ea, B:145:0x02ed, B:149:0x02fe, B:150:0x0302, B:152:0x0306, B:154:0x0309, B:156:0x0315, B:160:0x031e, B:161:0x0322, B:163:0x0325, B:165:0x0331, B:169:0x033a, B:170:0x033e, B:172:0x0341, B:174:0x034d, B:178:0x0356, B:179:0x035a, B:181:0x035d, B:183:0x0369, B:187:0x0372, B:188:0x0376, B:190:0x0379, B:192:0x0385, B:196:0x038e, B:197:0x0392, B:199:0x0395, B:201:0x03a1, B:204:0x03a7, B:205:0x03ab, B:206:0x03ae, B:207:0x03b2, B:209:0x03b8, B:214:0x03ca, B:217:0x03d0, B:220:0x03d9, B:223:0x03dd, B:232:0x03e5, B:237:0x0404, B:239:0x042b, B:246:0x0132, B:248:0x0136, B:250:0x013f, B:251:0x0141, B:252:0x0147, B:253:0x014a, B:255:0x014e, B:257:0x0156, B:259:0x0160, B:260:0x00f7, B:261:0x00ff, B:263:0x0105), top: B:3:0x0003 }] */
    @Override // p000X.InterfaceC44257Jyg
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public synchronized long Bnk(C41158Ia6 c41158Ia6) {
        boolean z;
        C41171IaK c41171IaK;
        long max;
        InterfaceC44264Jyn interfaceC44264Jyn;
        InterfaceC44264Jyn interfaceC44264Jyn2;
        InterfaceC44264Jyn interfaceC44264Jyn3;
        InterfaceC44264Jyn interfaceC44264Jyn4;
        InterfaceC44264Jyn interfaceC44264Jyn5;
        InterfaceC44264Jyn interfaceC44264Jyn6;
        InterfaceC44264Jyn interfaceC44264Jyn7;
        LruCache lruCache;
        boolean A1X;
        EnumC38901HZy enumC38901HZy;
        String queryParameter;
        long parseLong;
        String host;
        C00C.A0A(c41158Ia6, 0);
        Uri uri = c41158Ia6.A05;
        C00C.A05(uri);
        HeroPlayerSetting heroPlayerSetting = this.A04;
        if (heroPlayerSetting.enableCdnUrlExpiryCheck) {
            if (!"http".equalsIgnoreCase(uri.getScheme())) {
            }
            String host2 = uri.getHost();
            if (host2 != null) {
                if (!host2.endsWith(".fbcdn.net")) {
                    if (!host2.endsWith(".cdninstagram.com")) {
                        if (host2.endsWith(".akamaihd.net")) {
                            if (!host2.startsWith("fbcdn-")) {
                                if (!host2.startsWith("fbstatic-")) {
                                    if (!host2.startsWith("fbexternal-")) {
                                    }
                                }
                            }
                        }
                    }
                }
                queryParameter = uri.getQueryParameter("oe");
                if (queryParameter != null) {
                    parseLong = Long.parseLong(queryParameter, 16) * 1000;
                    long currentTimeMillis = System.currentTimeMillis();
                    if (parseLong != -1 && parseLong < currentTimeMillis) {
                        throw new C37720GsV(c41158Ia6, EnumC38917HaW.A0K.value, 1);
                    }
                }
                parseLong = -1;
                long currentTimeMillis2 = System.currentTimeMillis();
                if (parseLong != -1) {
                    throw new C37720GsV(c41158Ia6, EnumC38917HaW.A0K.value, 1);
                }
            }
            if (("http".equalsIgnoreCase(uri.getScheme()) || "https".equalsIgnoreCase(uri.getScheme())) && (host = uri.getHost()) != null && C3WF.A1a(host, AbstractC207139Eo.A01)) {
                queryParameter = uri.getQueryParameter("oe");
                if (queryParameter != null) {
                }
            }
            parseLong = -1;
            long currentTimeMillis22 = System.currentTimeMillis();
            if (parseLong != -1) {
            }
        }
        IQD iqd = C41164IaD.A00(c41158Ia6).A0H;
        boolean z2 = iqd != null ? iqd.A02 : false;
        IQD iqd2 = C41164IaD.A00(c41158Ia6).A0H;
        String str = iqd2 != null ? iqd2.A00 : "";
        IQD iqd3 = C41164IaD.A00(c41158Ia6).A0H;
        String str2 = iqd3 != null ? iqd3.A01 : "";
        IQD iqd4 = C41164IaD.A00(c41158Ia6).A0H;
        if (iqd4 != null) {
            z = iqd4.A03;
        } else {
            AtomicBoolean atomicBoolean = this.A03.A03;
            z = atomicBoolean != null ? atomicBoolean.get() : false;
        }
        String str3 = this.A03.A02;
        IQD iqd5 = new IQD(str, str2, z2, z);
        C41164IaD A00 = C41164IaD.A00(c41158Ia6);
        if (A00 == null || (c41171IaK = A00.A0G) == null) {
            c41171IaK = HXS.A00.mHttpPriority;
            C00C.A06(c41171IaK);
        }
        if (z2) {
            if (!heroPlayerSetting.gen.enable_http_priority_for_prefetch_fix || c41171IaK.equals(HXS.A01.mHttpPriority)) {
                c41171IaK = ((!heroPlayerSetting.useLowerHttpPriorityForUnimportantPrefetch || c41158Ia6.A03 <= 50000) ? HXS.A03 : HXS.A04).mHttpPriority;
                C00C.A09(c41171IaK);
            } else if (heroPlayerSetting.enableHttpPriorityForPrefetch) {
                c41171IaK = new C41171IaK(c41171IaK.A00, false);
            }
        } else if (heroPlayerSetting.enableHttpPriorityForStreaming) {
            c41171IaK = HXS.A02.mHttpPriority;
            if (heroPlayerSetting.bufferedDurationBasedHttpPriorityUpperBoundMs > 0 && C41164IaD.A00(c41158Ia6).A00 > heroPlayerSetting.bufferedDurationBasedHttpPriorityUpperBoundMs) {
                c41171IaK = HXS.A05.mHttpPriority;
            }
        }
        Map emptyMap = Collections.emptyMap();
        byte[] bArr = c41158Ia6.A09;
        long j = c41158Ia6.A01;
        long j2 = c41158Ia6.A03;
        long j3 = j - j2;
        long j4 = c41158Ia6.A02;
        if (j4 <= 0) {
            j4 = -1;
        }
        int i = c41158Ia6.A00;
        C41164IaD A002 = C41164IaD.A00(c41158Ia6);
        C41171IaK c41171IaK2 = c41171IaK;
        C41164IaD c41164IaD = new C41164IaD(c41171IaK2, iqd5, A002.A0K, A002.A0I, null, A002.A0J, A002.A0N, A002.A0L, A002.A0O, A002.A07, A002.A06, A002.A00, A002.A08, 0, A002.A05, A002.A01, A002.A03, -1, A002.A09, A002.A0B, A002.A0C, A002.A0E, A002.A0A, -1L, -1L, A002.A0S, A002.A0U, A002.A0Q, A002.A0T, false, A002.A0R);
        String str4 = c41158Ia6.A07;
        C41158Ia6 c41158Ia62 = new C41158Ia6(uri, c41164IaD, str4 != null ? str4 : null, emptyMap, bArr, i, j3, j2, j4);
        if (heroPlayerSetting.enableVideoPlayerServerSideBweAnnotations && ((enumC38901HZy = this.A06) == EnumC38901HZy.A04 || enumC38901HZy == EnumC38901HZy.A09 || enumC38901HZy == EnumC38901HZy.A08)) {
            String str5 = 1 - (z2 ? IO7.A01 : IO7.A0C).intValue() != 0 ? "android-playing-video" : "android-prefetch-video";
            C41158Ia6 c41158Ia63 = IM1.A00;
            if (c41158Ia62.A06 instanceof C41164IaD) {
                C41164IaD.A00(c41158Ia62).A0O.put("x-fb-ssbwe-annotation-request-type", str5);
            }
        }
        FbAutogeneratedSettings fbAutogeneratedSettings = heroPlayerSetting.autogenSettings;
        if (fbAutogeneratedSettings != null && fbAutogeneratedSettings.enableSloHttpHeaderLogging) {
            C00C.A06(str3);
            C40922IOa c40922IOa = C40922IOa.A01;
            synchronized (c40922IOa) {
                try {
                    lruCache = c40922IOa.A00;
                    A1X = AbstractC34841ae.A1X(lruCache.get(str3));
                } catch (Throwable th) {
                    throw th;
                }
            }
            if (!A1X) {
                C41164IaD A003 = C41164IaD.A00(c41158Ia6);
                if (A003 == null || !A003.A0O.containsKey("x-fb-qpl-ec")) {
                    IXF.A02(c41158Ia6);
                }
                if (c41158Ia6.A06 != null) {
                    C41164IaD.A00(c41158Ia6);
                    String A1E = AbstractC127845ir.A1E("x-fb-qpl-ec", C41164IaD.A00(c41158Ia6).A0O);
                    if (A1E != null) {
                        IM1.A00(c41158Ia62, C41164IaD.A00(c41158Ia6).A0O);
                        synchronized (c40922IOa) {
                            try {
                                lruCache.put(str3, A1E);
                            } finally {
                            }
                        }
                    }
                }
            }
        }
        try {
            InterfaceC44264Jyn interfaceC44264Jyn8 = this.A01;
            if (interfaceC44264Jyn8 != null) {
                interfaceC44264Jyn8.BlA(c41158Ia62, EnumC38897HZu.A04);
            }
            InterfaceC44262Jyl interfaceC44262Jyl = this.A02;
            long Bnk = interfaceC44262Jyl.Bnk(c41158Ia62);
            Map AnI = interfaceC44262Jyl.AnI();
            if (this.A01 != null) {
                List A01 = IXF.A01("X-FB-Connection-Quality", AnI, true);
                if (A01 != null) {
                    String A12 = AbstractC34861ag.A12(A01, 0);
                    InterfaceC44264Jyn interfaceC44264Jyn9 = this.A01;
                    if (interfaceC44264Jyn9 != null) {
                        interfaceC44264Jyn9.Bl8("X-FB-Connection-Quality", A12);
                    }
                }
                Object obj = AnI.get("x-fb-cec-video-limit");
                List list = (List) obj;
                if (obj != null) {
                    String A122 = list != null ? AbstractC34861ag.A12(list, 0) : null;
                    InterfaceC44264Jyn interfaceC44264Jyn10 = this.A01;
                    if (interfaceC44264Jyn10 != null) {
                        interfaceC44264Jyn10.Bl8("x-fb-cec-video-limit", A122);
                    }
                }
                Object obj2 = AnI.get("up-ttfb");
                List list2 = (List) obj2;
                if (obj2 != null && (interfaceC44264Jyn7 = this.A01) != null) {
                    interfaceC44264Jyn7.Bl8("up-ttfb", list2 != null ? AbstractC34861ag.A12(list2, 0) : null);
                }
                Object obj3 = AnI.get("x-fb-session-id");
                List list3 = (List) obj3;
                if (obj3 != null && (interfaceC44264Jyn6 = this.A01) != null) {
                    interfaceC44264Jyn6.Bl8("x-fb-session-id", list3 != null ? AbstractC34861ag.A12(list3, 0) : null);
                }
                Object obj4 = AnI.get("x-fb-response-time-ms");
                List list4 = (List) obj4;
                if (obj4 != null && (interfaceC44264Jyn5 = this.A01) != null) {
                    interfaceC44264Jyn5.Bl8("x-fb-response-time-ms", list4 != null ? AbstractC34861ag.A12(list4, 0) : null);
                }
                Object obj5 = AnI.get("x-bwe-mean");
                List list5 = (List) obj5;
                if (obj5 != null && (interfaceC44264Jyn4 = this.A01) != null) {
                    interfaceC44264Jyn4.Bl8("x-bwe-mean", list5 != null ? AbstractC34861ag.A12(list5, 0) : null);
                }
                Object obj6 = AnI.get("x-bwe-std-dev");
                List list6 = (List) obj6;
                if (obj6 != null && (interfaceC44264Jyn3 = this.A01) != null) {
                    interfaceC44264Jyn3.Bl8("x-bwe-std-dev", list6 != null ? AbstractC34861ag.A12(list6, 0) : null);
                }
                Object obj7 = AnI.get("x-fb-dynamic-predictive-response-chunk-size");
                List list7 = (List) obj7;
                if (obj7 != null && (interfaceC44264Jyn2 = this.A01) != null) {
                    interfaceC44264Jyn2.Bl8("x-fb-dynamic-predictive-response-chunk-size", list7 != null ? AbstractC34861ag.A12(list7, 0) : null);
                }
                Iterator A15 = AbstractC34831ad.A15(AnI);
                while (A15.hasNext()) {
                    Map.Entry A18 = AbstractC34861ag.A18(A15);
                    String A13 = AbstractC34861ag.A13(A18);
                    List list8 = (List) A18.getValue();
                    if (A13 != null && list8 != null && !list8.isEmpty() && C3WE.A1b("x-fb-ull-", 1, A13) && (interfaceC44264Jyn = this.A01) != null) {
                        interfaceC44264Jyn.Bl8(A13, list8.get(0));
                    }
                }
            }
            C00C.A0C(AnI, "null cannot be cast to non-null type kotlin.collections.Map<kotlin.String?, kotlin.collections.List<kotlin.String>?>");
            long A004 = IXF.A00(AnI, true);
            long j5 = c41158Ia62.A03;
            max = (long) Math.max(0.0d, A004 - j5);
            this.A00 = (Bnk == -1 || Bnk > max) ? max : Bnk;
            String str6 = A09;
            Object[] A1Z = AbstractC37199Ghy.A1Z();
            AbstractC127845ir.A1P(A1Z, 0, j5);
            long j6 = c41158Ia62.A02;
            AbstractC127845ir.A1P(A1Z, 1, j6);
            AbstractC127855is.A1T(Long.valueOf(max), str3, A1Z);
            A1Z[4] = c41158Ia62.A07;
            INB.A01(str6, "Opening data spec Offset: %d, Length %d Open Length %d Videoid %s Key %s", A1Z);
            if (j6 != -1) {
                max = (long) Math.min(Bnk, max);
            }
        } catch (IOException e) {
            throw e;
        }
        return max;
    }

    public C42231Iwq(InterfaceC44262Jyl interfaceC44262Jyl, InterfaceC44264Jyn interfaceC44264Jyn, C40161Hvz c40161Hvz, C40746IFh c40746IFh, HeroPlayerSetting heroPlayerSetting, AtomicBoolean atomicBoolean, AtomicBoolean atomicBoolean2, int i) {
        EnumC38901HZy enumC38901HZy;
        this.A03 = c40746IFh;
        this.A02 = interfaceC44262Jyl;
        this.A01 = interfaceC44264Jyn;
        this.A07 = atomicBoolean;
        this.A08 = atomicBoolean2;
        this.A04 = heroPlayerSetting;
        this.A05 = c40161Hvz;
        EnumC38901HZy[] values = EnumC38901HZy.values();
        int length = values.length;
        int i2 = 0;
        while (true) {
            if (i2 >= length) {
                enumC38901HZy = EnumC38901HZy.A0A;
                break;
            }
            enumC38901HZy = values[i2];
            if (enumC38901HZy.value == i) {
                break;
            } else {
                i2++;
            }
        }
        this.A06 = enumC38901HZy;
    }
}
