package p000X;

/* loaded from: classes6.dex */
public final class C80 {
    public final int A00;
    public final String A01;
    public final String A02;
    public final int A03;

    public boolean equals(Object obj) {
        if (this != obj) {
            if (obj == null || !AbstractC34911al.A1Y(this, obj)) {
                return false;
            }
            C80 c80 = (C80) obj;
            if (this.A00 != c80.A00 || !C00C.areEqual(this.A02, c80.A02) || !C00C.areEqual(this.A01, c80.A01)) {
                return false;
            }
        }
        return true;
    }

    public C80(int i, String str, String str2) {
        this.A00 = i;
        this.A02 = str;
        this.A01 = str2;
        this.A03 = (AbstractC34861ag.A02(str) * 31) + ((str2 != null ? str2.hashCode() : 0) * 31) + i;
    }

    public int hashCode() {
        return this.A03;
    }

    public String toString() {
        String str;
        StringBuilder A04 = AnonymousClass000.A04();
        A04.append("TransitionId{");
        A04.append("\"");
        A04.append(this.A02);
        A04.append("\", ");
        int i = this.A00;
        if (i == 1) {
            str = "GLOBAL";
        } else if (i != 2) {
            str = "AUTOGENERATED";
        } else {
            A04.append("SCOPED(");
            A04.append(this.A01);
            str = ")";
        }
        A04.append(str);
        String A03 = AnonymousClass000.A03("}", A04);
        C00C.A06(A03);
        return A03;
    }
}
