package p000X;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/* loaded from: classes7.dex */
public final class EJT extends C0DA {
    public Boolean A00;
    public Boolean A01;
    public Boolean A02;
    public Boolean A03;
    public Boolean A04;
    public Boolean A05;
    public Boolean A06;
    public Boolean A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Boolean A0H;
    public Boolean A0I;
    public Boolean A0J;
    public Boolean A0K;
    public Integer A0L;
    public Integer A0M;
    public Integer A0N;
    public Integer A0O;
    public Integer A0P;
    public Long A0Q;
    public Long A0R;
    public Long A0S;
    public Long A0T;
    public Long A0U;
    public Long A0V;
    public Long A0W;
    public Long A0X;
    public Long A0Y;
    public Long A0Z;
    public Long A0a;
    public Long A0b;
    public Long A0c;
    public Long A0d;
    public Long A0e;
    public Long A0f;
    public Long A0g;
    public Long A0h;
    public Long A0i;
    public Long A0j;
    public Long A0k;
    public Long A0l;
    public Long A0m;
    public Long A0n;
    public Long A0o;
    public Long A0p;
    public Long A0q;
    public Long A0r;
    public Long A0s;
    public Long A0t;
    public Long A0u;
    public Long A0v;
    public Long A0w;
    public Long A0x;
    public Long A0y;
    public Long A0z;
    public Long A10;
    public Long A11;
    public Long A12;
    public Long A13;
    public Long A14;
    public Long A15;
    public Long A16;
    public Long A17;
    public Long A18;
    public Long A19;
    public Long A1A;
    public Long A1B;
    public Long A1C;
    public Long A1D;
    public Long A1E;
    public Long A1F;
    public Long A1G;
    public Long A1H;
    public Long A1I;
    public Long A1J;
    public Long A1K;
    public Long A1L;
    public Long A1M;
    public Long A1N;
    public Long A1O;
    public Long A1P;
    public Long A1Q;
    public Long A1R;
    public Long A1S;
    public Long A1T;
    public Long A1U;
    public Long A1V;
    public Long A1W;
    public Long A1X;
    public Long A1Y;
    public Long A1Z;
    public Long A1a;
    public Long A1b;
    public Long A1c;
    public Long A1d;
    public Long A1e;
    public Long A1f;
    public Long A1g;
    public Long A1h;
    public Long A1i;
    public Long A1j;
    public Long A1k;
    public Long A1l;
    public Long A1m;
    public Long A1n;
    public Long A1o;
    public Long A1p;
    public String A1q;
    public String A1r;
    public String A1s;
    public String A1t;

    public EJT() {
        super(6466, AbstractC34801aa.A0t(1), 0, -1);
    }

    @Override // p000X.C0DA
    public String getEventNameForFalco() {
        return "wam_thread_interaction_data_core_consumer";
    }

    @Override // p000X.C0DA
    public Map getFieldsMapForLogging() {
        return null;
    }

    @Override // p000X.C0DA
    public List validate() {
        ArrayList A13 = this.A1r == null ? AbstractC34831ad.A13(C67762vc.A00("thread_ds", "thread_interaction_data_core_consumer", C025601d.A00)) : null;
        if (this.A1s == null) {
            C67762vc A00 = C67762vc.A00("thread_id", "thread_interaction_data_core_consumer", C025601d.A00);
            if (A13 != null) {
                A13.add(A00);
                return A13;
            }
            A13 = AbstractC34831ad.A13(A00);
        }
        if (A13 == null) {
            return C025601d.A00;
        }
        return A13;
    }

    @Override // p000X.C0DA
    public Map getFieldsMap() {
        LinkedHashMap A1C = AbstractC34801aa.A1C();
        A1C.put(AbstractC34891aj.A0d(AbstractC34891aj.A0c(AbstractC34891aj.A0b(AbstractC34841ae.A18(AbstractC34841ae.A17(AbstractC34841ae.A16(AbstractC34841ae.A15(AbstractC34841ae.A14(AbstractC34841ae.A12(AbstractC34841ae.A11(AbstractC34891aj.A0Y(AbstractC34821ac.A0t(), this.A0Q, A1C), this.A0R, A1C), this.A0S, A1C), this.A0T, A1C), this.A0U, A1C), this.A0L, A1C), this.A0V, A1C), this.A0M, A1C), this.A0W, A1C), this.A0X, A1C), this.A0Y, A1C), this.A0Z);
        A1C.put(AbstractC127885iv.A0o(AbstractC127885iv.A0n(AbstractC127885iv.A0m(DYZ.A0f(AbstractC127885iv.A0l(AbstractC127885iv.A0k(AbstractC127885iv.A0j(AbstractC127885iv.A0i(AbstractC127885iv.A0h(AbstractC127885iv.A0g(AbstractC127885iv.A0f(AbstractC127885iv.A0d(AbstractC127885iv.A0c(AbstractC34891aj.A0e(110, this.A0a, A1C), this.A0b, A1C), this.A0c, A1C), this.A0d, A1C), this.A0e, A1C), this.A0f, A1C), this.A0g, A1C), this.A0h, A1C), this.A0i, A1C), this.A0j, A1C), this.A0k, A1C), this.A0l, A1C), this.A0m, A1C), this.A0n, A1C), this.A0o);
        A1C.put(AbstractC127885iv.A0p(AbstractC127855is.A18(), this.A0p, A1C), this.A0q);
        A1C.put(34, this.A0r);
        A1C.put(35, this.A0s);
        A1C.put(AbstractC127885iv.A0r(AbstractC127855is.A19(), this.A0t, A1C), this.A0u);
        A1C.put(38, this.A0v);
        A1C.put(39, this.A0w);
        A1C.put(40, this.A0x);
        A1C.put(AbstractC127895iw.A0n(AbstractC127855is.A1A(), this.A0y, A1C), this.A0z);
        A1C.put(43, this.A0N);
        A1C.put(44, this.A10);
        A1C.put(45, this.A11);
        A1C.put(AbstractC127895iw.A0o(47, this.A12, A1C), this.A13);
        A1C.put(49, this.A14);
        A1C.put(113, this.A15);
        A1C.put(114, this.A16);
        A1C.put(115, this.A17);
        A1C.put(116, this.A18);
        A1C.put(117, this.A19);
        A1C.put(118, this.A1A);
        A1C.put(119, this.A1B);
        A1C.put(120, this.A1C);
        A1C.put(50, this.A00);
        A1C.put(51, this.A01);
        A1C.put(52, this.A02);
        A1C.put(53, this.A03);
        A1C.put(54, this.A04);
        A1C.put(55, this.A05);
        A1C.put(57, this.A06);
        A1C.put(112, this.A07);
        A1C.put(58, this.A08);
        A1C.put(121, this.A09);
        A1C.put(59, this.A0A);
        A1C.put(122, this.A0B);
        A1C.put(60, this.A0C);
        A1C.put(61, this.A0D);
        A1C.put(123, this.A0E);
        A1C.put(124, this.A0F);
        A1C.put(62, this.A1D);
        A1C.put(63, this.A1E);
        A1C.put(64, this.A1F);
        A1C.put(65, this.A1G);
        A1C.put(66, this.A1H);
        A1C.put(68, this.A1I);
        A1C.put(125, this.A0G);
        A1C.put(69, this.A0O);
        A1C.put(70, this.A1J);
        A1C.put(71, this.A1K);
        A1C.put(72, this.A1L);
        A1C.put(73, this.A1M);
        A1C.put(74, this.A1N);
        A1C.put(75, this.A1O);
        A1C.put(76, this.A1P);
        A1C.put(77, this.A1Q);
        A1C.put(78, this.A1R);
        A1C.put(79, this.A1S);
        A1C.put(80, this.A1T);
        A1C.put(81, this.A1U);
        A1C.put(82, this.A1V);
        A1C.put(83, this.A1W);
        A1C.put(85, this.A1X);
        A1C.put(86, this.A0H);
        A1C.put(87, this.A0I);
        A1C.put(89, this.A0J);
        A1C.put(107, this.A0K);
        A1C.put(90, this.A1Y);
        A1C.put(126, this.A1Z);
        A1C.put(91, this.A1a);
        A1C.put(127, this.A1b);
        A1C.put(92, this.A1c);
        A1C.put(93, this.A1d);
        A1C.put(94, this.A1e);
        A1C.put(95, this.A1f);
        A1C.put(96, this.A1g);
        A1C.put(111, this.A1q);
        A1C.put(97, this.A1r);
        A1C.put(98, this.A1s);
        A1C.put(109, this.A1t);
        A1C.put(128, this.A1h);
        A1C.put(129, this.A1i);
        A1C.put(108, this.A0P);
        A1C.put(99, this.A1j);
        A1C.put(100, this.A1k);
        A1C.put(102, this.A1l);
        A1C.put(103, this.A1m);
        A1C.put(104, this.A1n);
        A1C.put(105, this.A1o);
        A1C.put(106, this.A1p);
        return A1C;
    }

    @Override // p000X.C0DA
    public Map getFieldsMapForFalco() {
        LinkedHashMap A1C = AbstractC34801aa.A1C();
        A1C.put("audio_messages_received", this.A0Q);
        A1C.put("audio_messages_sent", this.A0R);
        A1C.put("broadcast_msgs_received", this.A0S);
        A1C.put("broadcast_msgs_sent", this.A0T);
        A1C.put("chat_ephemerality_duration", this.A0U);
        A1C.put("chat_muted", AbstractC34901ak.A0m(this.A0L));
        A1C.put("chat_overflow_clicks", this.A0V);
        A1C.put("chat_type_ind", AbstractC34901ak.A0m(this.A0M));
        A1C.put("comments_received", this.A0W);
        A1C.put("document_messages_received", this.A0X);
        A1C.put("document_messages_sent", this.A0Y);
        A1C.put("edited_msgs_sent", this.A0Z);
        A1C.put("ephemeral_messages_expired", this.A0a);
        A1C.put("ephemeral_messages_received", this.A0b);
        A1C.put("ephemeral_messages_sent", this.A0c);
        A1C.put("ephemeral_messages_unread_expired", this.A0d);
        A1C.put("event_creation_messages_received", this.A0e);
        A1C.put("event_creation_messages_sent", this.A0f);
        A1C.put("event_response_messages_received", this.A0g);
        A1C.put("event_response_messages_sent", this.A0h);
        A1C.put("forward_audio_messages_received", this.A0i);
        A1C.put("forward_audio_messages_sent", this.A0j);
        A1C.put("forward_document_messages_received", this.A0k);
        A1C.put("forward_document_messages_sent", this.A0l);
        A1C.put("forward_gif_messages_received", this.A0m);
        A1C.put("forward_gif_messages_sent", this.A0n);
        A1C.put("forward_messages_received", this.A0o);
        A1C.put("forward_messages_sent", this.A0p);
        A1C.put("forward_photo_messages_received", this.A0q);
        A1C.put("forward_photo_messages_sent", this.A0r);
        A1C.put("forward_sticker_messages_received", this.A0s);
        A1C.put("forward_sticker_messages_sent", this.A0t);
        A1C.put("forward_text_messages_received", this.A0u);
        A1C.put("forward_text_messages_sent", this.A0v);
        A1C.put("forward_url_messages_received", this.A0w);
        A1C.put("forward_url_messages_sent", this.A0x);
        A1C.put("forward_video_messages_received", this.A0y);
        A1C.put("forward_video_messages_sent", this.A0z);
        A1C.put("ga_status", AbstractC34901ak.A0m(this.A0N));
        A1C.put("gif_messages_received", this.A10);
        A1C.put("gif_messages_sent", this.A11);
        A1C.put("group_membership_replies", this.A12);
        A1C.put("group_private_replies", this.A13);
        A1C.put("group_size", this.A14);
        A1C.put("group_status_likes_others_to_others", this.A15);
        A1C.put("group_status_likes_others_to_own", this.A16);
        A1C.put("group_status_likes_own_to_others", this.A17);
        A1C.put("group_status_likes_own_to_own", this.A18);
        A1C.put("group_status_replies_others_to_others", this.A19);
        A1C.put("group_status_replies_others_to_own", this.A1A);
        A1C.put("group_status_replies_own_to_others", this.A1B);
        A1C.put("group_status_replies_own_to_own", this.A1C);
        A1C.put("has_username", this.A00);
        A1C.put("has_username_pin", this.A01);
        A1C.put("is_a_contact", this.A02);
        A1C.put("is_a_contact_at_thread_creation", this.A03);
        A1C.put("is_a_group", this.A04);
        A1C.put("is_archived", this.A05);
        A1C.put("is_deleted", this.A06);
        A1C.put("is_guest_thread", this.A07);
        A1C.put("is_invite_created_thread", this.A08);
        A1C.put("is_managed_account", this.A09);
        A1C.put("is_meta_ai_assistant", this.A0A);
        A1C.put("is_new_managed_account_em_ignored", this.A0B);
        A1C.put("is_pinned", this.A0C);
        A1C.put("is_pnh_enabled_chat", this.A0D);
        A1C.put("is_username_thread", this.A0E);
        A1C.put("limit_sharing_option", this.A0F);
        A1C.put("marked_read_cnt", this.A1D);
        A1C.put("marked_read_message_cnt", this.A1E);
        A1C.put("messages_read", this.A1F);
        A1C.put("messages_received", this.A1G);
        A1C.put("messages_sent", this.A1H);
        A1C.put("messages_unread", this.A1I);
        A1C.put("opposite_party_limit_sharing_option", this.A0G);
        A1C.put("opposite_visible_identification", AbstractC34901ak.A0m(this.A0O));
        A1C.put("photo_messages_received", this.A1J);
        A1C.put("photo_messages_sent", this.A1K);
        A1C.put("poll_creation_messages_received", this.A1L);
        A1C.put("poll_creation_messages_sent", this.A1M);
        A1C.put("poll_update_messages_received", this.A1N);
        A1C.put("poll_update_messages_sent", this.A1O);
        A1C.put("profile_replies", this.A1P);
        A1C.put("profile_views", this.A1Q);
        A1C.put("ptt_messages_received", this.A1R);
        A1C.put("ptt_messages_sent", this.A1S);
        A1C.put("ptv_messages_received", this.A1T);
        A1C.put("ptv_messages_sent", this.A1U);
        A1C.put("reactions_received", this.A1V);
        A1C.put("reactions_sent", this.A1W);
        A1C.put("replies_sent", this.A1X);
        A1C.put("requested_phone_number", this.A0H);
        A1C.put("seen_masked_phone_number", this.A0I);
        A1C.put("shared_phone_number", this.A0J);
        A1C.put("shares_common_group", this.A0K);
        A1C.put("status_reactions_received", this.A1Y);
        A1C.put("status_reactions_sent", this.A1Z);
        A1C.put("status_replies", this.A1a);
        A1C.put("status_reply_messages_received", this.A1b);
        A1C.put("status_views", this.A1c);
        A1C.put("sticker_messages_received", this.A1d);
        A1C.put("sticker_messages_sent", this.A1e);
        A1C.put("text_messages_received", this.A1f);
        A1C.put("text_messages_sent", this.A1g);
        A1C.put("thread_creation_date", this.A1q);
        A1C.put("thread_ds", this.A1r);
        A1C.put("thread_id", this.A1s);
        A1C.put("thread_id_by_lid", this.A1t);
        A1C.put("tombstone_ephemeral_messages_received", this.A1h);
        A1C.put("tombstone_view_once_messages_received", this.A1i);
        A1C.put("type_of_group", AbstractC34901ak.A0m(this.A0P));
        A1C.put("url_messages_received", this.A1j);
        A1C.put("url_messages_sent", this.A1k);
        A1C.put("video_messages_received", this.A1l);
        A1C.put("video_messages_sent", this.A1m);
        A1C.put("view_once_messages_opened", this.A1n);
        A1C.put("view_once_messages_received", this.A1o);
        A1C.put("view_once_messages_sent", this.A1p);
        return A1C;
    }

    @Override // p000X.C0DA
    public void serialize(InterfaceC77443Sm interfaceC77443Sm) {
        throw AbstractC34871ah.A0h();
    }

    public String toString() {
        StringBuilder A04 = AnonymousClass000.A04();
        A04.append("WamThreadInteractionDataCoreConsumer {");
        C0DC.A00(this.A0Q, "audioMessagesReceived", A04);
        C0DC.A00(this.A0R, "audioMessagesSent", A04);
        C0DC.A00(this.A0S, "broadcastMsgsReceived", A04);
        C0DC.A00(this.A0T, "broadcastMsgsSent", A04);
        C0DC.A00(this.A0U, "chatEphemeralityDuration", A04);
        C0DC.A00(AbstractC34901ak.A0m(this.A0L), "chatMuted", A04);
        C0DC.A00(this.A0V, "chatOverflowClicks", A04);
        C0DC.A00(AbstractC34901ak.A0m(this.A0M), "chatTypeInd", A04);
        C0DC.A00(this.A0W, "commentsReceived", A04);
        C0DC.A00(this.A0X, "documentMessagesReceived", A04);
        C0DC.A00(this.A0Y, "documentMessagesSent", A04);
        C0DC.A00(this.A0Z, "editedMsgsSent", A04);
        C0DC.A00(this.A0a, "ephemeralMessagesExpired", A04);
        C0DC.A00(this.A0b, "ephemeralMessagesReceived", A04);
        C0DC.A00(this.A0c, "ephemeralMessagesSent", A04);
        C0DC.A00(this.A0d, "ephemeralMessagesUnreadExpired", A04);
        C0DC.A00(this.A0e, "eventCreationMessagesReceived", A04);
        C0DC.A00(this.A0f, "eventCreationMessagesSent", A04);
        C0DC.A00(this.A0g, "eventResponseMessagesReceived", A04);
        C0DC.A00(this.A0h, "eventResponseMessagesSent", A04);
        C0DC.A00(this.A0i, "forwardAudioMessagesReceived", A04);
        C0DC.A00(this.A0j, "forwardAudioMessagesSent", A04);
        C0DC.A00(this.A0k, "forwardDocumentMessagesReceived", A04);
        C0DC.A00(this.A0l, "forwardDocumentMessagesSent", A04);
        C0DC.A00(this.A0m, "forwardGifMessagesReceived", A04);
        C0DC.A00(this.A0n, "forwardGifMessagesSent", A04);
        C0DC.A00(this.A0o, "forwardMessagesReceived", A04);
        C0DC.A00(this.A0p, "forwardMessagesSent", A04);
        C0DC.A00(this.A0q, "forwardPhotoMessagesReceived", A04);
        C0DC.A00(this.A0r, "forwardPhotoMessagesSent", A04);
        C0DC.A00(this.A0s, "forwardStickerMessagesReceived", A04);
        C0DC.A00(this.A0t, "forwardStickerMessagesSent", A04);
        C0DC.A00(this.A0u, "forwardTextMessagesReceived", A04);
        C0DC.A00(this.A0v, "forwardTextMessagesSent", A04);
        C0DC.A00(this.A0w, "forwardUrlMessagesReceived", A04);
        C0DC.A00(this.A0x, "forwardUrlMessagesSent", A04);
        C0DC.A00(this.A0y, "forwardVideoMessagesReceived", A04);
        C0DC.A00(this.A0z, "forwardVideoMessagesSent", A04);
        C0DC.A00(AbstractC34901ak.A0m(this.A0N), "gaStatus", A04);
        C0DC.A00(this.A10, "gifMessagesReceived", A04);
        C0DC.A00(this.A11, "gifMessagesSent", A04);
        C0DC.A00(this.A12, "groupMembershipReplies", A04);
        C0DC.A00(this.A13, "groupPrivateReplies", A04);
        C0DC.A00(this.A14, "groupSize", A04);
        C0DC.A00(this.A15, "groupStatusLikesOthersToOthers", A04);
        C0DC.A00(this.A16, "groupStatusLikesOthersToOwn", A04);
        C0DC.A00(this.A17, "groupStatusLikesOwnToOthers", A04);
        C0DC.A00(this.A18, "groupStatusLikesOwnToOwn", A04);
        C0DC.A00(this.A19, "groupStatusRepliesOthersToOthers", A04);
        C0DC.A00(this.A1A, "groupStatusRepliesOthersToOwn", A04);
        C0DC.A00(this.A1B, "groupStatusRepliesOwnToOthers", A04);
        C0DC.A00(this.A1C, "groupStatusRepliesOwnToOwn", A04);
        C0DC.A00(this.A00, "hasUsername", A04);
        C0DC.A00(this.A01, "hasUsernamePin", A04);
        C0DC.A00(this.A02, "isAContact", A04);
        C0DC.A00(this.A03, "isAContactAtThreadCreation", A04);
        C0DC.A00(this.A04, "isAGroup", A04);
        C0DC.A00(this.A05, "isArchived", A04);
        C0DC.A00(this.A06, "isDeleted", A04);
        C0DC.A00(this.A07, "isGuestThread", A04);
        C0DC.A00(this.A08, "isInviteCreatedThread", A04);
        C0DC.A00(this.A09, "isManagedAccount", A04);
        C0DC.A00(this.A0A, "isMetaAiAssistant", A04);
        C0DC.A00(this.A0B, "isNewManagedAccountEmIgnored", A04);
        C0DC.A00(this.A0C, "isPinned", A04);
        C0DC.A00(this.A0D, "isPnhEnabledChat", A04);
        C0DC.A00(this.A0E, "isUsernameThread", A04);
        C0DC.A00(this.A0F, "limitSharingOption", A04);
        C0DC.A00(this.A1D, "markedReadCnt", A04);
        C0DC.A00(this.A1E, "markedReadMessageCnt", A04);
        C0DC.A00(this.A1F, "messagesRead", A04);
        C0DC.A00(this.A1G, "messagesReceived", A04);
        C0DC.A00(this.A1H, "messagesSent", A04);
        C0DC.A00(this.A1I, "messagesUnread", A04);
        C0DC.A00(this.A0G, "oppositePartyLimitSharingOption", A04);
        C0DC.A00(AbstractC34901ak.A0m(this.A0O), "oppositeVisibleIdentification", A04);
        C0DC.A00(this.A1J, "photoMessagesReceived", A04);
        C0DC.A00(this.A1K, "photoMessagesSent", A04);
        C0DC.A00(this.A1L, "pollCreationMessagesReceived", A04);
        C0DC.A00(this.A1M, "pollCreationMessagesSent", A04);
        C0DC.A00(this.A1N, "pollUpdateMessagesReceived", A04);
        C0DC.A00(this.A1O, "pollUpdateMessagesSent", A04);
        C0DC.A00(this.A1P, "profileReplies", A04);
        C0DC.A00(this.A1Q, "profileViews", A04);
        C0DC.A00(this.A1R, "pttMessagesReceived", A04);
        C0DC.A00(this.A1S, "pttMessagesSent", A04);
        C0DC.A00(this.A1T, "ptvMessagesReceived", A04);
        C0DC.A00(this.A1U, "ptvMessagesSent", A04);
        C0DC.A00(this.A1V, "reactionsReceived", A04);
        C0DC.A00(this.A1W, "reactionsSent", A04);
        C0DC.A00(this.A1X, "repliesSent", A04);
        C0DC.A00(this.A0H, "requestedPhoneNumber", A04);
        C0DC.A00(this.A0I, "seenMaskedPhoneNumber", A04);
        C0DC.A00(this.A0J, "sharedPhoneNumber", A04);
        C0DC.A00(this.A0K, "sharesCommonGroup", A04);
        C0DC.A00(this.A1Y, "statusReactionsReceived", A04);
        C0DC.A00(this.A1Z, "statusReactionsSent", A04);
        C0DC.A00(this.A1a, "statusReplies", A04);
        C0DC.A00(this.A1b, "statusReplyMessagesReceived", A04);
        C0DC.A00(this.A1c, "statusViews", A04);
        C0DC.A00(this.A1d, "stickerMessagesReceived", A04);
        C0DC.A00(this.A1e, "stickerMessagesSent", A04);
        C0DC.A00(this.A1f, "textMessagesReceived", A04);
        C0DC.A00(this.A1g, "textMessagesSent", A04);
        C0DC.A00(this.A1q, "threadCreationDate", A04);
        C0DC.A00(this.A1r, "threadDs", A04);
        C0DC.A00(this.A1s, "threadId", A04);
        C0DC.A00(this.A1t, "threadIdByLid", A04);
        C0DC.A00(this.A1h, "tombstoneEphemeralMessagesReceived", A04);
        C0DC.A00(this.A1i, "tombstoneViewOnceMessagesReceived", A04);
        C0DC.A00(AbstractC34901ak.A0m(this.A0P), "typeOfGroup", A04);
        C0DC.A00(this.A1j, "urlMessagesReceived", A04);
        C0DC.A00(this.A1k, "urlMessagesSent", A04);
        C0DC.A00(this.A1l, "videoMessagesReceived", A04);
        C0DC.A00(this.A1m, "videoMessagesSent", A04);
        C0DC.A00(this.A1n, "viewOnceMessagesOpened", A04);
        C0DC.A00(this.A1o, "viewOnceMessagesReceived", A04);
        return AbstractC34921am.A0T(this.A1p, "viewOnceMessagesSent", A04);
    }
}
