package p000X;

/* loaded from: classes7.dex */
public final class G68 implements C0LD {
    @Override // p000X.C0LD
    public /* bridge */ /* synthetic */ void ANj(C0L7 c0l7, C0LA c0la) {
        C00C.A0A(c0la, 0);
        c0la.Bsk("status", "status_uuid_user_index", "\n        CREATE UNIQUE INDEX IF NOT EXISTS status_uuid_user_index\n        ON status (uuid, sender_user_jid)\n      ");
        c0la.Bsk("status", "status_state_index", "\n        CREATE INDEX IF NOT EXISTS status_state_index\n        ON status (state)\n      ");
        c0la.Bsk("status", "status_info_sort_id_index", "\n        CREATE UNIQUE INDEX IF NOT EXISTS status_info_sort_id_index\n        ON status (status_info_row_id, sort_id)\n      ");
        c0la.Bsk("status", "status_type_index", "CREATE INDEX IF NOT EXISTS status_type_index ON status (type)");
        c0la.Bsk("status", "status_is_archived_index", "CREATE INDEX IF NOT EXISTS status_is_archived_index ON status (is_archived)");
    }

    @Override // p000X.C0LD
    public /* bridge */ /* synthetic */ void ANn(C0L9 c0l9) {
        C0LF A0V = DYY.A0V(c0l9);
        C0LG[] c0lgArr = new C0LG[19];
        C0LH A0c = DYX.A0c(A0V);
        AbstractC30167DYa.A1E(A0V, A0c, c0lgArr);
        A0V.A02 = "sort_id";
        boolean A1Y = AbstractC30167DYa.A1Y(A0V, A0c, c0lgArr);
        A0V.A02 = "uuid";
        C0LH c0lh = C0LH.A0B;
        AbstractC30167DYa.A1G(A0V, c0lh, c0lgArr, A1Y);
        AbstractC30168DYb.A17(A0V, c0lh, "sender_user_jid", c0lgArr, A1Y);
        AbstractC30168DYb.A18(A0V, A0c, "status_info_row_id", c0lgArr, A1Y);
        AbstractC30168DYb.A19(A0V, A0c, "type", c0lgArr, A1Y);
        c0lgArr[6] = AbstractC30167DYa.A0Q(A0V, A0c, "timestamp", A1Y);
        AbstractC30167DYa.A14(A0V, A0c, "server_receipt_timestamp", c0lgArr);
        AbstractC30167DYa.A15(A0V, c0lh, "text_data", c0lgArr);
        c0lgArr[9] = AbstractC30167DYa.A0Q(A0V, A0c, "state", A1Y);
        A0V.A02 = "secret";
        C0LH c0lh2 = C0LH.A02;
        A0V.A00 = c0lh2;
        c0lgArr[10] = A0V.A00();
        AbstractC30167DYa.A18(A0V, c0lh2, "content_proto", c0lgArr);
        AbstractC30167DYa.A19(A0V, c0lh2, "fp_proto", c0lgArr);
        c0lgArr[13] = AbstractC30167DYa.A0Q(A0V, A0c, "origin", A1Y);
        c0lgArr[14] = AbstractC30167DYa.A0Q(A0V, A0c, "flags", A1Y);
        c0lgArr[15] = AbstractC30167DYa.A0P(A0V, A0c, "audience_type", 0, A1Y);
        c0lgArr[16] = AbstractC30167DYa.A0Q(A0V, A0c, "is_archived", A1Y);
        c0lgArr[17] = DYZ.A0M(A0V, c0lh2, "stanza_xml");
        c0lgArr[18] = DYZ.A0M(A0V, A0c, "received_timestamp");
        c0l9.Bsv("status", c0lgArr);
    }

    @Override // p000X.C0LD
    public /* bridge */ /* synthetic */ void ANp(C0LB c0lb) {
        C00C.A0A(c0lb, 0);
        c0lb.Bsx("status", C0LL.A00("status_info", "status", "status_info_row_id = old.row_id"));
        c0lb.Bsy("status", "status_ai_revoke_for_status_info_total_count_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ai_revoke_for_status_info_total_count_trigger\n          AFTER INSERT ON status\n        BEGIN\n        UPDATE status_info\n        SET total_count = total_count + 1\n          WHERE row_id = new.status_info_row_id\n            AND new.type = 8;\n        END;\n      ");
        c0lb.Bsy("status", "status_au_for_status_info_total_count_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_au_for_status_info_total_count_trigger\n          AFTER UPDATE OF state ON status\n        BEGIN\n        UPDATE status_info\n        SET total_count = total_count - 1\n          WHERE row_id = new.status_info_row_id\n          AND new.type = 8\n          AND old.state <> 3\n          AND new.state = 3\n          AND total_count > 0;\n        END;\n      ");
        c0lb.Bsy("status", "status_info_decrement_total_count_unsent_revoke_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_info_decrement_total_count_unsent_revoke_trigger\n          AFTER DELETE ON status\n        WHEN\n          old.type = 8\n          And old.state <> 3\n        BEGIN\n        UPDATE status_info\n        SET total_count = total_count - 1\n          WHERE row_id = old.status_info_row_id\n          AND total_count > 0;\n        END;\n      ");
        c0lb.Bsy("status", "status_ai_for_status_info_total_count_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ai_for_status_info_total_count_trigger\n          AFTER INSERT ON status\n        WHEN\n          new.type <> 8\n          AND new.type <> 2\n          AND new.is_archived = 0\n        BEGIN\n        UPDATE status_info\n        SET total_count = total_count + 1\n          WHERE row_id = new.status_info_row_id;\n        END;\n      ");
        c0lb.Bsy("status", "status_ad_for_status_info_total_count_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ad_for_status_info_total_count_trigger\n          AFTER DELETE ON status\n        WHEN\n          old.type <> 8\n          And old.type <> 2\n          AND old.is_archived = 0\n        BEGIN\n        UPDATE status_info\n        SET total_count = total_count - 1\n          WHERE row_id = old.status_info_row_id\n\n          AND total_count > 0;\n        END;\n      ");
        c0lb.Bsy("status", "status_archived_update_status_info_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_archived_update_status_info_trigger\n          AFTER UPDATE OF is_archived on status\n        BEGIN\n        UPDATE status_info\n        SET total_count = CASE\n              WHEN total_count > 0 THEN total_count - 1\n              ELSE total_count\n            END,\n            unread_count = CASE\n              WHEN old.state <= 4 AND unread_count > 0 THEN unread_count - 1\n              ELSE unread_count\n            END,\n            unread_count_close_friends = CASE\n              WHEN old.state <= 4 AND old.audience_type = 1 AND unread_count_close_friends > 0 THEN unread_count_close_friends - 1\n              ELSE unread_count_close_friends\n            END,\n            last_status_sort_id =\n                (\n                  SELECT MAX(sort_id)\n                  FROM status\n                  WHERE status_info_row_id = old.status_info_row_id\n                  AND type <> 8\n                  AND type <> 2\n                  AND is_archived = 0\n                ),\n             last_status_timestamp =\n                (\n                  SELECT \n                  CASE\n                    WHEN COALESCE(server_receipt_timestamp, 0) > 0 THEN server_receipt_timestamp\n                    ELSE timestamp\n                  END\n                  FROM status\n                  WHERE status_info_row_id = old.status_info_row_id\n                  AND type <> 8\n                  AND type <> 2\n                  AND is_archived = 0\n                  ORDER BY sort_id DESC\n                  LIMIT 1\n                ),\n            first_unread_sort_id =\n                (\n                  SELECT MIN(sort_id)\n                  FROM status\n                  WHERE status_info_row_id = old.status_info_row_id\n                  AND type <> 8\n                  AND type <> 2\n                  AND is_archived = 0\n                  AND state = 4\n                )\n\n        WHERE\n          row_id = new.status_info_row_id\n          AND old.is_archived = 0 AND new.is_archived = 1;\n        END;\n      ");
        c0lb.Bsy("status", "status_ai_for_status_info_last_status_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ai_for_status_info_last_status_trigger\n          AFTER INSERT ON status\n        WHEN\n          new.type <> 8\n          AND new.type <> 2\n          AND new.is_archived = 0\n        BEGIN\n        UPDATE status_info\n        SET last_status_sort_id = new.sort_id,\n            last_status_timestamp = new.timestamp\n          WHERE row_id = new.status_info_row_id\n          AND (last_status_sort_id IS NULL OR last_status_sort_id < new.sort_id);\n        END;\n    ");
        c0lb.Bsy("status", "status_ad_for_status_info_last_status_sort_id_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ad_for_status_info_last_status_sort_id_trigger\n          AFTER DELETE ON status\n        BEGIN\n        UPDATE status_info\n        SET\n        last_status_sort_id = (SELECT MAX(sort_id)\n          FROM status\n          WHERE status_info_row_id = old.status_info_row_id\n          AND type <> 8\n          AND type <> 2\n          AND is_archived = 0)\n        WHERE row_id = old.status_info_row_id AND last_status_sort_id = old.sort_id;\n        END;\n    ");
        c0lb.Bsy("status", "status_ad_for_status_info_last_status_timestamp_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ad_for_status_info_last_status_timestamp_trigger\n          AFTER DELETE ON status\n        BEGIN\n        UPDATE status_info\n        SET\n        last_status_timestamp = (\n        SELECT\n          CASE\n            WHEN COALESCE(server_receipt_timestamp, 0) > 0 THEN server_receipt_timestamp\n            ELSE timestamp\n          END\n          FROM status\n          WHERE status_info_row_id = old.status_info_row_id\n          AND type <> 8\n          AND type <> 2\n          AND is_archived = 0\n          ORDER BY sort_id DESC\n          LIMIT 1)\n        WHERE row_id = old.status_info_row_id AND last_status_sort_id = old.sort_id;\n        END;\n    ");
        c0lb.Bsy("status", "status_server_receipt_ts_for_status_info_last_status_timestamp_trigger", "\n          CREATE TRIGGER IF NOT EXISTS status_server_receipt_ts_for_status_info_last_status_timestamp_trigger\n            AFTER UPDATE OF server_receipt_timestamp ON status\n          BEGIN\n          UPDATE status_info\n          SET last_status_timestamp = new.server_receipt_timestamp\n          WHERE\n            row_id = new.status_info_row_id\n            AND last_status_sort_id = new.sort_id\n            AND new.server_receipt_timestamp > 0;\n          END;\n          ");
        c0lb.Bsy("status", "status_ai_for_status_info_unread_count_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ai_for_status_info_unread_count_trigger\n          AFTER INSERT ON status\n        WHEN\n          new.type <> 8\n          AND new.type <> 2\n          AND new.is_archived = 0\n          AND new.state <= 4\n        BEGIN\n        UPDATE status_info\n        SET unread_count = unread_count + 1,\n        unread_count_close_friends = CASE\n          WHEN new.audience_type = 1 THEN unread_count_close_friends + 1\n          ELSE unread_count_close_friends\n        END\n          WHERE row_id = new.status_info_row_id;\n        END;\n    ");
        c0lb.Bsy("status", "status_ad_for_status_info_unread_count_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ad_for_status_info_unread_count_trigger\n          AFTER DELETE ON status\n        WHEN\n          old.type <> 8\n          AND old.type <> 2\n          AND old.is_archived = 0\n          AND old.state <= 4\n        BEGIN\n        UPDATE status_info\n        SET unread_count = unread_count - 1,\n        unread_count_close_friends = CASE\n          WHEN old.audience_type = 1 AND unread_count_close_friends > 0 THEN\n            unread_count_close_friends - 1\n          ELSE unread_count_close_friends\n        END\n          WHERE row_id = old.status_info_row_id\n          AND unread_count > 0;\n        END;\n    ");
        c0lb.Bsy("status", "status_au_for_status_info_unread_count_state_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_au_for_status_info_unread_count_state_trigger\n          AFTER UPDATE OF state ON status\n        BEGIN\n        UPDATE status_info\n        SET unread_count = unread_count - 1,\n        unread_count_close_friends = CASE\n          WHEN old.audience_type = 1 AND unread_count_close_friends > 0 THEN\n            unread_count_close_friends - 1\n          ELSE unread_count_close_friends\n        END\n          WHERE row_id = new.status_info_row_id\n          AND (\n              new.state = 5\n              OR new.state = 6\n          )\n          AND (old.state = 4 or old.state = 3)\n          AND old.type <> 8\n          AND old.type <> 2\n          AND old.is_archived = 0\n          AND unread_count > 0;\n        END;\n    ");
        c0lb.Bsy("status", "status_ai_for_status_info_first_unread_sort_id_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ai_for_status_info_first_unread_sort_id_trigger\n          AFTER INSERT ON status\n          WHEN\n            new.type <> 8\n            AND new.type <> 2\n            AND new.is_archived = 0\n            AND (new.state <> 5 AND new.state <> 6)\n        BEGIN\n        UPDATE status_info\n        SET first_unread_sort_id = new.sort_id\n          WHERE row_id = new.status_info_row_id\n          AND (\n               first_unread_sort_id IS NULL\n               OR first_unread_sort_id <= 0\n               OR new.sort_id < first_unread_sort_id\n              );\n        END;\n    ");
        c0lb.Bsy("status", "status_ad_for_status_info_first_unread_sort_id_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_ad_for_status_info_first_unread_sort_id_trigger\n          AFTER DELETE ON status\n        BEGIN\n        UPDATE status_info\n        SET first_unread_sort_id =\n        (\n          SELECT MIN(sort_id)\n            FROM status\n            WHERE status_info_row_id = old.status_info_row_id\n            AND type <> 8\n            AND type <> 2\n            AND is_archived = 0\n            AND (\n              state <> 5\n              AND state <> 6\n            )\n          )\n          WHERE row_id = old.status_info_row_id AND first_unread_sort_id = old.sort_id;\n        END;\n    ");
        c0lb.Bsy("status", "status_au_for_status_info_first_unread_sort_id_trigger", "\n        CREATE TRIGGER IF NOT EXISTS status_au_for_status_info_first_unread_sort_id_trigger\n          AFTER UPDATE OF state ON status\n        BEGIN\n        UPDATE status_info\n        SET first_unread_sort_id =\n          (\n          SELECT MIN(sort_id)\n            FROM status\n            WHERE status_info_row_id = new.status_info_row_id\n            AND type <> 8\n            AND type <> 2\n            AND is_archived = 0\n            AND (\n              state <> 5\n              AND state <> 6\n            )\n          )\n            WHERE row_id = new.status_info_row_id\n            AND (\n              new.state = 5\n              OR new.state = 6\n            )\n            AND (\n              old.state = 4\n              OR old.state = 3\n            );\n        END;\n    ");
    }
}
