package p000X;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes8.dex */
public final class HZD {
    public static final /* synthetic */ HZD[] A00;
    public static final HZD A01;
    public final int mCppValue;

    static {
        HZD[] hzdArr = new HZD[172];
        HZD hzd = new HZD("Dummy", 0, 0);
        hzdArr[0] = hzd;
        A01 = hzd;
        A00("AREngine_ForceNoMSAA", hzdArr, 1);
        A00("BackgroundProcessor_UseCaptureTime", hzdArr, 2);
        A00("Network_Logging", hzdArr, 3);
        A00("AREngine_ForcePhase4Audio", hzdArr, 4);
        A00("AsyncLoading_UseAsyncAssetLoaderForDynamicExternalAssets", hzdArr, 5);
        A00("FaceTracker_UseNonStaticReferenceFaceShapeLoader", hzdArr, 6);
        A00("WorldTracker_EnableUXR", hzdArr, 7);
        A00("Segmentation_Android_Caffe2_Thread_Enabled", hzdArr, 8);
        A00("Platform_Person_Segmentation_Enabled", hzdArr, 9);
        A00("WorldTracker_UseWolfSlamForWarfSlam", hzdArr, 10);
        A00("WorldTracker_UseWorldTrackerV2", hzdArr, 11);
        A00("WorldTracker_EnableTrackingDataInVideoData", hzdArr, 12);
        A00("WorldTracker_PlatformSLAMSupported", hzdArr, 13);
        A00("WorldTracker_EnableHitTestWithDepth", hzdArr, 14);
        A00("FaceTracker_UseAsyncModelLoad", hzdArr, 15);
        A00("ExpressionFitting_UseEFDataProvider", hzdArr, 16);
        A00("ExpressionFitting_UseTimestampSync", hzdArr, 17);
        A00("WOLFService_ClearAlgorithmsOnServiceReset", hzdArr, 18);
        A00("Segmentation_UseAsyncModelLoad", hzdArr, 19);
        A00("AREngine_AsyncDestructionEnabled", hzdArr, 20);
        A00("AREngine_CosmoRuntimeEnabled", hzdArr, 21);
        A00("AREngine_JSI_ForceEagerCompilation", hzdArr, 22);
        A00("AREngine_JSI_UseEmbeddedBytecode", hzdArr, 23);
        A00("AREngine_JSI_UseHermesHardenedRuntime", hzdArr, 24);
        A00("AREngine_JSI_registerHermesForProfiling", hzdArr, 25);
        A00("AREngine_AssetEncoding", hzdArr, 26);
        A00("AREngine_PrefabStorageCache_PreloadRenderData", hzdArr, 27);
        A00("AREngine_TextureStorageCache_EnablePreload", hzdArr, 28);
        A00("AREngine_ShaderCodeStorageCache_UseUnifex", hzdArr, 29);
        A00("AREngine_UseCountedRenderPipelineStatePool", hzdArr, 30);
        A00("AREngine_ScriptIsolationEnabled", hzdArr, 31);
        A00("AREngine_UseCaptureBusForInputCapture", hzdArr, 32);
        A00("AREngine_AutoStartBlocksPreload", hzdArr, 33);
        A00("AREngine_Stability_Push_UnprovenPath", hzdArr, 34);
        A00("AREngine_Stability_Lion_Path", hzdArr, 35);
        A00("AREngine_Stability_Leopard_Path", hzdArr, 36);
        A00("AREngine_Stability_Rhino_Path", hzdArr, 37);
        A00("AREngine_Stability_Elephant_Path", hzdArr, 38);
        A00("AREngine_XOR_EnableXorRendering", hzdArr, 39);
        A00("AREngine_XOR_EnableXorRendering_ProductionRollout", hzdArr, 40);
        A00("AREngine_XOR_EnableXorMesh", hzdArr, 41);
        A00("AREngine_XOR_EnableXorPhase2Mesh", hzdArr, 42);
        A00("AREngine_XOR_EnableEngineUniformBlock", hzdArr, 43);
        A00("AREngine_XOR_EnableSceneTreeToEntity", hzdArr, 44);
        A00("AREngine_XOR_EnableSceneTreeToEntity_ProductionRollout", hzdArr, 45);
        A00("AREngine_XOR_EnableSceneTreeToEntity_ProductionRollout_BatchB", hzdArr, 46);
        A00("AREngine_XOR_EnableAudioXorContextProxy", hzdArr, 47);
        A00("AREngine_ReactiveGraph_ScopedToRootBlocks", hzdArr, 48);
        A00("AREngine_SkipSimulationByBlockId", hzdArr, 49);
        A00("AREngine_BVH_PerTriangle_HitTesting", hzdArr, 50);
        A00("AREngine_BVH_PerTriangle_HitTesting_Skinned_Meshes", hzdArr, 51);
        A00("AREngine_Use_SandboxedHermesVM", hzdArr, 52);
        A00("AREngine_Disable_Legacy_Audio_Thread", hzdArr, 53);
        A00("AREngine_ShaderCompression", hzdArr, 54);
        A00("AREngine_RemoveTrimAnimatorFromPlaneSynchronizer", hzdArr, 55);
        A00("AREngine_Sandboxed_Process_FoA", hzdArr, 56);
        A00("AREngine_UseGltfEcosDataModel", hzdArr, 57);
        A00("AREngine_UseStyle2AvatarShaders", hzdArr, 58);
        A00("AREngine_MergeTextExtrusionShapes", hzdArr, 59);
        A00("AREngine_SoftErrorOnExceptions", hzdArr, 60);
        A00("FBA_Expose_At_Creation", hzdArr, 61);
        A00("FBA_Expose_At_Audio_Input_Start", hzdArr, 62);
        A00("FBA_Expose_At_Platform_Output_Start", hzdArr, 63);
        A00("FBA_Buffer_Optimization", hzdArr, 64);
        A00("FBA_State_Machine", hzdArr, 65);
        A00("FBA_Async_Media_Codec", hzdArr, 66);
        A00("FBA_Allow_Ar_Audio_Post_Capture", hzdArr, 67);
        A00("FBA_XplatControlsStartInput", hzdArr, 68);
        A00("FBA_Audio_Reactive_Effect", hzdArr, 69);
        A00("FBA_Use48kHz_Sample_Rate", hzdArr, 70);
        A00("FBA_FBA_Is_Processing_Graph", hzdArr, 71);
        A00("FBA_PCMFloat", hzdArr, 72);
        A00("FBA_Stereo", hzdArr, 73);
        A00("OpenGLES30", hzdArr, 74);
        A00("AnomalyDetector", hzdArr, 75);
        A00("AspectRatioFix", hzdArr, 76);
        A00("TrivialOutputFixForAspectRatioFix", hzdArr, 77);
        A00("MatchCameraSdkPreviewScalingMode", hzdArr, 78);
        A00("SyncOnlyCopyToOutput", hzdArr, 79);
        A00("ConfigureBFrames", hzdArr, 80);
        A00("ExplicitlySetBaseline", hzdArr, 81);
        A00("GpuTimer", hzdArr, 82);
        A00("FrameBuffering", hzdArr, 83);
        A00("AllowMultipleOutputTypesRendering", hzdArr, 84);
        A00("PreviewFrameController", hzdArr, 85);
        A00("AsyncMediaCodec", hzdArr, 86);
        A00("SyncCpuFrames", hzdArr, 87);
        A00("CrashFromGlThread", hzdArr, 88);
        A00("UnifiedStackCamera2", hzdArr, 89);
        A00("CpuFramesSyncForCamera2", hzdArr, 90);
        A00("UseThreadPriorityForCamera2", hzdArr, 91);
        A00("OffScreenOutput", hzdArr, 92);
        A00("CloseCameraOnSwitch", hzdArr, 93);
        A00("UseOptic2", hzdArr, 94);
        A00("UseOptic2Priority", hzdArr, 95);
        A00("UseOptimalRecordSize", hzdArr, 96);
        A00("MultiWindowSupport", hzdArr, 97);
        A00("WarmUpRenderManager", hzdArr, 98);
        A00("MediaPipeline_RenderMonitor", hzdArr, 99);
        A00("MediaPipeline_UseSharedCopyRenderer", hzdArr, 100);
        A00("MediaPipeline_UseRendererProvider", hzdArr, 101);
        A00("MediaPipeline_UseSurfaceHolder", hzdArr, 102);
        A00("MediaPipeline_UseSingleInputLayout", hzdArr, 103);
        A00("MediaPipeline_OverrideYuv2RgbCopyShader", hzdArr, 104);
        A00("VideoCaptureBitrate_Enabled", hzdArr, 105);
        A00("SaveCameraSensorRotationToEffectServiceHost", hzdArr, 106);
        A00("ReducedVideoResolution_Exclude_Unreleased_High_End_Device", hzdArr, 107);
        A00("VideoRecording_Stage1MuxerStop", hzdArr, 108);
        A00("VideoRecording_ShortBlockingStart", hzdArr, 109);
        A00("VideoRecording_EnableMinRecordingDuration", hzdArr, 110);
        A00("VideoRecording_ImprovedStateRestoration", hzdArr, 111);
        A00("VideoRecording_State_StartedOnlyFromStarting", hzdArr, 112);
        A00("VideoRecording_State_AllowDualState", hzdArr, 113);
        A00("OC_CaptureHevcVideo", hzdArr, 114);
        A00("OC_CaptureHevcVideoAllowListed", hzdArr, 115);
        A00("OC_CaptureHevcVideoGHZClassEnabled", hzdArr, 116);
        A00("OC_CaptureAV1Video", hzdArr, 117);
        A00("OC_CaptureAV1Video_AllowSoftwareEncoder", hzdArr, 118);
        A00("OC_VideoRecordPerfStats", hzdArr, 119);
        A00("OC_CaptureAllowMtKHevcHDR", hzdArr, 120);
        A00("OC_CaptureAllowMtKHevcSDR", hzdArr, 121);
        A00("OC_CaptureAllowMtkHevcHardware", hzdArr, 122);
        A00("OC_ARVideoRecordingUseFileOnTimeout", hzdArr, 123);
        A00("OC_ARVideoRecordingUseFileOnMuxerError", hzdArr, 124);
        A00("OC_ARVideoRecordingUseFileOnEncoderError", hzdArr, 125);
        A00("OC_ARVideoRecordingValidateFileWithMediaExtractor", hzdArr, 126);
        A00("OC_UseAudioRecordTimestamp", hzdArr, 127);
        A00("OC_ARVideoRecordingBlockDoubleLatchStop", hzdArr, 128);
        A00("OC_UseTimestampSynchronizer", hzdArr, 129);
        A00("OC_UseOriginalBufferTimestampInMuxer", hzdArr, 130);
        A00("OC_AudioRecordEnableDropInitialBuffers", hzdArr, 131);
        A00("OC_AudioRecordEnableDropUntilValidInterval", hzdArr, 132);
        A00("OC_DelayNotifyingAREngine_StartVideoRecording", hzdArr, 133);
        A00("OneCameraArXLogger", hzdArr, 134);
        A00("WorldTrackerModule_UseUnmodifiedPlatformTrackingState", hzdArr, 135);
        A00("QueryWidthHeightAlignment", hzdArr, 136);
        A00("VideoRecording_AudioEncoder_SkipPassingCodecConfigFlagDownstream", hzdArr, 137);
        A00("Avatars_RecordLog", hzdArr, 138);
        A00("Avatars_RecordPluginMetrics", hzdArr, 139);
        A00("Avatars_DET_UserCalibrationEnabled", hzdArr, 140);
        A00("Avatars_DET_MouthOcclusionHandlingEnabled", hzdArr, 141);
        A00("Avatars_HeadOnlyNeckCollapseEnabled", hzdArr, 142);
        A00("Avatars_CacheBehaviors", hzdArr, 143);
        A00("Avatars_EnableTrackingWithMemoryAssets", hzdArr, 144);
        A00("Avatars_RecordPrefetchMetrics", hzdArr, 145);
        A00("Avatars_DET_HeadPoseEnabled", hzdArr, 146);
        A00("Avatars_ShaderCacheEnabled", hzdArr, 147);
        A00("Avatars_EnableCdlEventFramePolling", hzdArr, 148);
        A00("Avatars_EnableM6Parametrics", hzdArr, 149);
        A00("Avatars_UseSparseMorphTargets", hzdArr, 150);
        A00("Avatars_EnableHalfBodyCollapse", hzdArr, 151);
        A00("Avatars_MergeMeshesPerShader", hzdArr, 152);
        A00("Avatars_EnableBodySolver", hzdArr, 153);
        A00("Avatars_DisableWaitForEntityStatus", hzdArr, 154);
        A00("Avatars_DisableHairSimSwitchOff", hzdArr, 155);
        A00("Avatars_UseEmotesSdk", hzdArr, 156);
        A00("Zeratul_DET_Enabled", hzdArr, 157);
        A00("Felios_ParallelizeLoadLocalAssets", hzdArr, 158);
        A00("VideoCall_StreamUseCase_Enabled", hzdArr, 159);
        A00("Preview_Video_Stabilization_Enabled", hzdArr, 160);
        A00("Using_Swiftshader", hzdArr, 161);
        A00("ShouldUseReducedVideoResolutionFromDeviceSegment", hzdArr, 162);
        A00("ExpressionTracker_OneRunPerRender", hzdArr, 163);
        A00("PersonSegmentation_UnsafeLoad", hzdArr, 164);
        A00("MediaPipeline_Debug_Enabled", hzdArr, 165);
        A00("AREngine_DeSparkifyReactivePlugin", hzdArr, 166);
        A00("AREngine_DeSparkifyComponentsInfra", hzdArr, 167);
        A00("AREngine_DeSparkifyTypeErasurePluginSystem", hzdArr, 168);
        A00("EnableHDRCapture", hzdArr, 169);
        A00("ImageScalingFix", hzdArr, 170);
        A00("AREngine_GetIndexFileOptimization", hzdArr, 171);
        A00 = hzdArr;
    }

    public static void A00(String str, Object[] objArr, int i) {
        objArr[i] = new HZD(str, i, i);
    }

    public static HZD[] values() {
        return (HZD[]) A00.clone();
    }

    public HZD(String str, int i, int i2) {
        this.mCppValue = i2;
    }
}
