package p000X;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

/* loaded from: classes8.dex */
public class JAT implements InterfaceC43720Jny {
    public byte A00;
    public int A02;
    public C0HS A07;
    public C0HU A08;
    public C0HR A09;
    public I15 A0A;
    public C40250HxS A0B;
    public C0HO A0C;
    public InterfaceC44079JvD A0D;
    public Ju8 A0E;
    public InterfaceC43880JrH A0F;
    public HX1 A0G;
    public IE8 A0H;
    public AbstractC40789IHd A0I;
    public AbstractC39321Hhm A0J;
    public JMX A0K;
    public C39337Hi2 A0L;
    public InputStream A0M;
    public OutputStream A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public List A0R;
    public List A0S;
    public List A0T;
    public Map A0U;
    public boolean A0a;
    public boolean A0b;
    public boolean A0d;
    public boolean A0e;
    public boolean A0g;
    public byte[] A0h;
    public byte[] A0i;
    public byte[] A0j;
    public byte[] A0k;
    public byte[] A0l;
    public byte[] A0m;
    public byte[] A0n;
    public boolean A0X = false;
    public boolean A0Y = false;
    public boolean A0Z = false;
    public boolean A0f = false;
    public int A01 = 0;
    public int A03 = 0;
    public short A0V = 0;
    public short A0W = 0;
    public boolean A0c = false;
    public long A04 = 0;
    public long A05 = 0;
    public long A06 = 0;
}
