.class public Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final A3b:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public static final A3c:Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;


# instance fields
.field public A00:J

.field public A01:LX/6kv;

.field public A02:Z

.field public final A03:D

.field public final A04:I

.field public final A05:I

.field public final A06:I

.field public final A07:I

.field public final A08:I

.field public final A09:I

.field public final A0A:I

.field public final A0B:I

.field public final A0C:I

.field public final A0D:I

.field public final A0E:I

.field public final A0F:I

.field public final A0G:I

.field public final A0H:I

.field public final A0I:I

.field public final A0J:I

.field public final A0K:I

.field public final A0L:I

.field public final A0M:I

.field public final A0N:I

.field public final A0O:I

.field public final A0P:I

.field public final A0Q:I

.field public final A0R:I

.field public final A0S:I

.field public final A0T:I

.field public final A0U:I

.field public final A0V:I

.field public final A0W:I

.field public final A0X:I

.field public final A0Y:I

.field public final A0Z:I

.field public final A0a:I

.field public final A0b:I

.field public final A0c:I

.field public final A0d:I

.field public final A0e:I

.field public final A0f:I

.field public final A0g:J

.field public final A0h:J

.field public final A0i:LX/6mi;

.field public final A0j:LX/6mi;

.field public final A0k:LX/6mi;

.field public final A0l:LX/6mi;

.field public final A0m:LX/6mi;

.field public final A0n:LX/6mi;

.field public final A0o:LX/6mi;

.field public final A0p:LX/6mi;

.field public final A0q:LX/6mi;

.field public final A0r:LX/6mp;

.field public final A0s:LX/6mA;

.field public final A0t:LX/6lt;

.field public final A0u:LX/6lo;

.field public final A0v:LX/6ln;

.field public final A0w:LX/6mb;

.field public final A0x:LX/6le;

.field public final A0y:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public final A0z:LX/6mt;

.field public final A10:LX/6li;

.field public final A11:LX/6mm;

.field public final A12:LX/7bi;

.field public final A13:LX/6lg;

.field public final A14:LX/6lg;

.field public final A15:LX/6me;

.field public final A16:Ljava/lang/String;

.field public final A17:Ljava/lang/String;

.field public final A18:Ljava/lang/String;

.field public final A19:Ljava/util/HashSet;

.field public final A1A:Ljava/util/Map;

.field public final A1B:Ljava/util/Set;

.field public final A1C:Ljava/util/Set;

.field public final A1D:Ljava/util/Set;

.field public final A1E:Ljava/util/Set;

.field public final A1F:Ljava/util/Set;

.field public final A1G:Ljava/util/Set;

.field public final A1H:Ljava/util/Set;

.field public final A1I:Ljava/util/Set;

.field public final A1J:Z

.field public final A1K:Z

.field public final A1L:Z

.field public final A1M:Z

.field public final A1N:Z

.field public final A1O:Z

.field public final A1P:Z

.field public final A1Q:Z

.field public final A1R:Z

.field public final A1S:Z

.field public final A1T:Z

.field public final A1U:Z

.field public final A1V:Z

.field public final A1W:Z

.field public final A1X:Z

.field public final A1Y:Z

.field public final A1Z:Z

.field public final A1a:Z

.field public final A1b:Z

.field public final A1c:Z

.field public final A1d:Z

.field public final A1e:Z

.field public final A1f:Z

.field public final A1g:Z

.field public final A1h:Z

.field public final A1i:Z

.field public final A1j:Z

.field public final A1k:Z

.field public final A1l:Z

.field public final A1m:Z

.field public final A1n:Z

.field public final A1o:Z

.field public final A1p:Z

.field public final A1q:Z

.field public final A1r:Z

.field public final A1s:Z

.field public final A1t:Z

.field public final A1u:Z

.field public final A1v:Z

.field public final A1w:Z

.field public final A1x:Z

.field public final A1y:Z

.field public final A1z:Z

.field public final A20:Z

.field public final A21:Z

.field public final A22:Z

.field public final A23:Z

.field public final A24:Z

.field public final A25:Z

.field public final A26:Z

.field public final A27:Z

.field public final A28:Z

.field public final A29:Z

.field public final A2A:Z

.field public final A2B:Z

.field public final A2C:Z

.field public final A2D:Z

.field public final A2E:Z

.field public final A2F:Z

.field public final A2G:Z

.field public final A2H:Z

.field public final A2I:Z

.field public final A2J:Z

.field public final A2K:Z

.field public final A2L:Z

.field public final A2M:Z

.field public final A2N:Z

.field public final A2O:Z

.field public final A2P:Z

.field public final A2Q:Z

.field public final A2R:Z

.field public final A2S:Z

.field public final A2T:Z

.field public final A2U:Z

.field public final A2V:Z

.field public final A2W:Z

.field public final A2X:Z

.field public final A2Y:Z

.field public final A2Z:Z

.field public final A2a:Z

.field public final A2b:Z

.field public final A2c:Z

.field public final A2d:Z

.field public final A2e:Z

.field public final A2f:Z

.field public final A2g:Z

.field public final A2h:Z

.field public final A2i:Z

.field public final A2j:Z

.field public final A2k:Z

.field public final A2l:Z

.field public final A2m:Z

.field public final A2n:Z

.field public final A2o:Z

.field public final A2p:Z

.field public final A2q:Z

.field public final A2r:Z

.field public final A2s:Z

.field public final A2t:Z

.field public final A2u:Z

.field public final A2v:Z

.field public final A2w:Z

.field public final A2x:Z

.field public final A2y:Z

.field public final A2z:Z

.field public final A30:Z

.field public final A31:Z

.field public final A32:Z

.field public final A33:Z

.field public final A34:Z

.field public final A35:Z

.field public final A36:Z

.field public final A37:Z

.field public final A38:Z

.field public final A39:Z

.field public final A3A:Z

.field public final A3B:Z

.field public final A3C:Z

.field public final A3D:Z

.field public final A3E:Z

.field public final A3F:Z

.field public final A3G:Z

.field public final A3H:Z

.field public final A3I:Z

.field public final A3J:Z

.field public final A3K:Z

.field public final A3L:Z

.field public final A3M:Z

.field public final A3N:Z

.field public final A3O:Z

.field public final A3P:Z

.field public final A3Q:Z

.field public final A3R:Z

.field public final A3S:Z

.field public final A3T:Z

.field public final A3U:Z

.field public final A3V:Z

.field public final A3W:Z

.field public final A3X:Z

.field public final A3Y:Z

.field public final A3Z:Z

.field public final A3a:Z


# direct methods
.method public static constructor <clinit>()V
    .locals 2

    .line 0
    new-instance v0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 1
    .line 2
    invoke-direct {v0}, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;-><init>()V

    .line 3
    .line 4
    .line 5
    sput-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3b:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 6
    .line 7
    new-instance v1, LX/6kq;

    .line 8
    .line 9
    invoke-direct {v1}, LX/6kq;-><init>()V

    .line 10
    .line 11
    .line 12
    new-instance v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;

    .line 13
    .line 14
    invoke-direct {v0, v1}, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;-><init>(LX/6kq;)V

    .line 15
    .line 16
    .line 17
    sput-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3c:Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;

    .line 18
    .line 19
    return-void
    .line 20
.end method

.method public constructor <init>(LX/6kq;)V
    .locals 210

    .line 0
    move-object/from16 v1, p0

    .line 1
    .line 2
    invoke-direct {v1}, Ljava/lang/Object;-><init>()V

    .line 3
    .line 4
    .line 5
    move-object/from16 v2, p1

    .line 6
    .line 7
    iget-boolean v0, v2, LX/6kq;->A1m:Z

    .line 8
    .line 9
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1m:Z

    .line 10
    .line 11
    iget-object v0, v2, LX/6kq;->A0y:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 12
    .line 13
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0y:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 14
    .line 15
    iget-boolean v0, v2, LX/6kq;->A2k:Z

    .line 16
    .line 17
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2g:Z

    .line 18
    .line 19
    iget v0, v2, LX/6kq;->A0W:I

    .line 20
    .line 21
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Y:I

    .line 22
    .line 23
    iget-boolean v0, v2, LX/6kq;->A3H:Z

    .line 24
    .line 25
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3F:Z

    .line 26
    .line 27
    iget-object v0, v2, LX/6kq;->A18:Ljava/lang/String;

    .line 28
    .line 29
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A18:Ljava/lang/String;

    .line 30
    .line 31
    iget-boolean v0, v2, LX/6kq;->A2K:Z

    .line 32
    .line 33
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2J:Z

    .line 34
    .line 35
    iget-boolean v0, v2, LX/6kq;->A27:Z

    .line 36
    .line 37
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A25:Z

    .line 38
    .line 39
    iget-boolean v0, v2, LX/6kq;->A3U:Z

    .line 40
    .line 41
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3S:Z

    .line 42
    .line 43
    iget-boolean v0, v2, LX/6kq;->A2l:Z

    .line 44
    .line 45
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2h:Z

    .line 46
    .line 47
    iget-object v0, v2, LX/6kq;->A0w:LX/6le;

    .line 48
    .line 49
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0x:LX/6le;

    .line 50
    .line 51
    iget-boolean v0, v2, LX/6kq;->A2M:Z

    .line 52
    .line 53
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2L:Z

    .line 54
    .line 55
    iget-object v0, v2, LX/6kq;->A13:LX/6lg;

    .line 56
    .line 57
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A13:LX/6lg;

    .line 58
    .line 59
    iget-object v0, v2, LX/6kq;->A14:LX/6lg;

    .line 60
    .line 61
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A14:LX/6lg;

    .line 62
    .line 63
    iget-boolean v0, v2, LX/6kq;->A1U:Z

    .line 64
    .line 65
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1T:Z

    .line 66
    .line 67
    iget-object v0, v2, LX/6kq;->A10:LX/6li;

    .line 68
    .line 69
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A10:LX/6li;

    .line 70
    .line 71
    iget-boolean v0, v2, LX/6kq;->A33:Z

    .line 72
    .line 73
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A31:Z

    .line 74
    .line 75
    iget-boolean v0, v2, LX/6kq;->A37:Z

    .line 76
    .line 77
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A35:Z

    .line 78
    .line 79
    iget-object v0, v2, LX/6kq;->A0u:LX/6ln;

    .line 80
    .line 81
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0v:LX/6ln;

    .line 82
    .line 83
    iget-object v0, v2, LX/6kq;->A0t:LX/6lo;

    .line 84
    .line 85
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0u:LX/6lo;

    .line 86
    .line 87
    iget-object v0, v2, LX/6kq;->A0s:LX/6lt;

    .line 88
    .line 89
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0t:LX/6lt;

    .line 90
    .line 91
    iget-object v0, v2, LX/6kq;->A0r:LX/6mA;

    .line 92
    .line 93
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0s:LX/6mA;

    .line 94
    .line 95
    iget-object v0, v2, LX/6kq;->A12:LX/7bi;

    .line 96
    .line 97
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A12:LX/7bi;

    .line 98
    .line 99
    iget-object v0, v2, LX/6kq;->A0v:LX/6mb;

    .line 100
    .line 101
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0w:LX/6mb;

    .line 102
    .line 103
    iget-boolean v0, v2, LX/6kq;->A29:Z

    .line 104
    .line 105
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A27:Z

    .line 106
    .line 107
    iget-object v0, v2, LX/6kq;->A15:LX/6me;

    .line 108
    .line 109
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A15:LX/6me;

    .line 110
    .line 111
    iget v0, v2, LX/6kq;->A07:I

    .line 112
    .line 113
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0A:I

    .line 114
    .line 115
    iget v0, v2, LX/6kq;->A06:I

    .line 116
    .line 117
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A09:I

    .line 118
    .line 119
    iget-object v0, v2, LX/6kq;->A0i:LX/6mi;

    .line 120
    .line 121
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0j:LX/6mi;

    .line 122
    .line 123
    iget-object v0, v2, LX/6kq;->A0j:LX/6mi;

    .line 124
    .line 125
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0k:LX/6mi;

    .line 126
    .line 127
    iget-object v0, v2, LX/6kq;->A0l:LX/6mi;

    .line 128
    .line 129
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0m:LX/6mi;

    .line 130
    .line 131
    iget-object v0, v2, LX/6kq;->A0m:LX/6mi;

    .line 132
    .line 133
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0n:LX/6mi;

    .line 134
    .line 135
    iget-boolean v0, v2, LX/6kq;->A26:Z

    .line 136
    .line 137
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A24:Z

    .line 138
    .line 139
    iget-object v0, v2, LX/6kq;->A0k:LX/6mi;

    .line 140
    .line 141
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0l:LX/6mi;

    .line 142
    .line 143
    iget-object v0, v2, LX/6kq;->A0o:LX/6mi;

    .line 144
    .line 145
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0p:LX/6mi;

    .line 146
    .line 147
    iget-boolean v0, v2, LX/6kq;->A2a:Z

    .line 148
    .line 149
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Y:Z

    .line 150
    .line 151
    iget v0, v2, LX/6kq;->A0X:I

    .line 152
    .line 153
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Z:I

    .line 154
    .line 155
    iget-boolean v0, v2, LX/6kq;->A1N:Z

    .line 156
    .line 157
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1M:Z

    .line 158
    .line 159
    iget-boolean v0, v2, LX/6kq;->A3L:Z

    .line 160
    .line 161
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3J:Z

    .line 162
    .line 163
    iget-boolean v0, v2, LX/6kq;->A2h:Z

    .line 164
    .line 165
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2d:Z

    .line 166
    .line 167
    iget-wide v3, v2, LX/6kq;->A0g:J

    .line 168
    .line 169
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0h:J

    .line 170
    .line 171
    iget-boolean v0, v2, LX/6kq;->A3G:Z

    .line 172
    .line 173
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3E:Z

    .line 174
    .line 175
    iget-boolean v0, v2, LX/6kq;->A1W:Z

    .line 176
    .line 177
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1V:Z

    .line 178
    .line 179
    iget-object v0, v2, LX/6kq;->A17:Ljava/lang/String;

    .line 180
    .line 181
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A17:Ljava/lang/String;

    .line 182
    .line 183
    iget-boolean v0, v2, LX/6kq;->A1y:Z

    .line 184
    .line 185
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1y:Z

    .line 186
    .line 187
    iget-boolean v0, v2, LX/6kq;->A3A:Z

    .line 188
    .line 189
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A38:Z

    .line 190
    .line 191
    iget-boolean v0, v2, LX/6kq;->A1f:Z

    .line 192
    .line 193
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1e:Z

    .line 194
    .line 195
    iget-boolean v0, v2, LX/6kq;->A1n:Z

    .line 196
    .line 197
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1n:Z

    .line 198
    .line 199
    iget-boolean v0, v2, LX/6kq;->A2r:Z

    .line 200
    .line 201
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2p:Z

    .line 202
    .line 203
    iget-boolean v0, v2, LX/6kq;->A2z:Z

    .line 204
    .line 205
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2x:Z

    .line 206
    .line 207
    iget-boolean v0, v2, LX/6kq;->A2g:Z

    .line 208
    .line 209
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2c:Z

    .line 210
    .line 211
    iget-boolean v0, v2, LX/6kq;->A1K:Z

    .line 212
    .line 213
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1J:Z

    .line 214
    .line 215
    iget-boolean v0, v2, LX/6kq;->A3Y:Z

    .line 216
    .line 217
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3W:Z

    .line 218
    .line 219
    iget-boolean v0, v2, LX/6kq;->A2E:Z

    .line 220
    .line 221
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2C:Z

    .line 222
    .line 223
    iget-boolean v0, v2, LX/6kq;->A2D:Z

    .line 224
    .line 225
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2B:Z

    .line 226
    .line 227
    iget v0, v2, LX/6kq;->A0L:I

    .line 228
    .line 229
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0N:I

    .line 230
    .line 231
    iget-boolean v0, v2, LX/6kq;->A2m:Z

    .line 232
    .line 233
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2i:Z

    .line 234
    .line 235
    iget-boolean v0, v2, LX/6kq;->A2n:Z

    .line 236
    .line 237
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2j:Z

    .line 238
    .line 239
    iget-boolean v0, v2, LX/6kq;->A3T:Z

    .line 240
    .line 241
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3R:Z

    .line 242
    .line 243
    iget-boolean v0, v2, LX/6kq;->A2f:Z

    .line 244
    .line 245
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2m:Z

    .line 246
    .line 247
    iget-boolean v0, v2, LX/6kq;->A2e:Z

    .line 248
    .line 249
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2k:Z

    .line 250
    .line 251
    iget-boolean v0, v2, LX/6kq;->A2t:Z

    .line 252
    .line 253
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2q:Z

    .line 254
    .line 255
    iget-boolean v0, v2, LX/6kq;->A3c:Z

    .line 256
    .line 257
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3a:Z

    .line 258
    .line 259
    iget-boolean v0, v2, LX/6kq;->A3b:Z

    .line 260
    .line 261
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3Z:Z

    .line 262
    .line 263
    iget-boolean v0, v2, LX/6kq;->A2x:Z

    .line 264
    .line 265
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2v:Z

    .line 266
    .line 267
    iget-boolean v0, v2, LX/6kq;->A2p:Z

    .line 268
    .line 269
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2n:Z

    .line 270
    .line 271
    iget-boolean v0, v2, LX/6kq;->A3E:Z

    .line 272
    .line 273
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3C:Z

    .line 274
    .line 275
    iget-boolean v0, v2, LX/6kq;->A2S:Z

    .line 276
    .line 277
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2R:Z

    .line 278
    .line 279
    iget-boolean v0, v2, LX/6kq;->A2Y:Z

    .line 280
    .line 281
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2W:Z

    .line 282
    .line 283
    iget-boolean v0, v2, LX/6kq;->A2P:Z

    .line 284
    .line 285
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2O:Z

    .line 286
    .line 287
    iget-boolean v0, v2, LX/6kq;->A36:Z

    .line 288
    .line 289
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A34:Z

    .line 290
    .line 291
    iget-boolean v0, v2, LX/6kq;->A3Z:Z

    .line 292
    .line 293
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3X:Z

    .line 294
    .line 295
    iget-boolean v0, v2, LX/6kq;->A3S:Z

    .line 296
    .line 297
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3Q:Z

    .line 298
    .line 299
    iget-boolean v0, v2, LX/6kq;->A3O:Z

    .line 300
    .line 301
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3M:Z

    .line 302
    .line 303
    iget v0, v2, LX/6kq;->A0F:I

    .line 304
    .line 305
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0H:I

    .line 306
    .line 307
    iget-boolean v0, v2, LX/6kq;->A3K:Z

    .line 308
    .line 309
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3I:Z

    .line 310
    .line 311
    iget-boolean v0, v2, LX/6kq;->A2o:Z

    .line 312
    .line 313
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2l:Z

    .line 314
    .line 315
    iget-boolean v0, v2, LX/6kq;->A3J:Z

    .line 316
    .line 317
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3H:Z

    .line 318
    .line 319
    iget v0, v2, LX/6kq;->A0a:I

    .line 320
    .line 321
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0c:I

    .line 322
    .line 323
    iget-boolean v0, v2, LX/6kq;->A3W:Z

    .line 324
    .line 325
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3U:Z

    .line 326
    .line 327
    iget-boolean v0, v2, LX/6kq;->A3V:Z

    .line 328
    .line 329
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3T:Z

    .line 330
    .line 331
    iget-boolean v0, v2, LX/6kq;->A2H:Z

    .line 332
    .line 333
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2F:Z

    .line 334
    .line 335
    iget-boolean v0, v2, LX/6kq;->A3P:Z

    .line 336
    .line 337
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3N:Z

    .line 338
    .line 339
    iget v0, v2, LX/6kq;->A0R:I

    .line 340
    .line 341
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0T:I

    .line 342
    .line 343
    iget-boolean v0, v2, LX/6kq;->A1X:Z

    .line 344
    .line 345
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1W:Z

    .line 346
    .line 347
    iget-boolean v0, v2, LX/6kq;->A2s:Z

    .line 348
    .line 349
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2r:Z

    .line 350
    .line 351
    iget v0, v2, LX/6kq;->A0S:I

    .line 352
    .line 353
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0U:I

    .line 354
    .line 355
    iget v0, v2, LX/6kq;->A0G:I

    .line 356
    .line 357
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0I:I

    .line 358
    .line 359
    iget v0, v2, LX/6kq;->A0H:I

    .line 360
    .line 361
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0J:I

    .line 362
    .line 363
    iget-boolean v0, v2, LX/6kq;->A2y:Z

    .line 364
    .line 365
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2w:Z

    .line 366
    .line 367
    iget-boolean v0, v2, LX/6kq;->A1o:Z

    .line 368
    .line 369
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1o:Z

    .line 370
    .line 371
    iget-object v0, v2, LX/6kq;->A16:Ljava/lang/String;

    .line 372
    .line 373
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A16:Ljava/lang/String;

    .line 374
    .line 375
    iget-boolean v0, v2, LX/6kq;->A2c:Z

    .line 376
    .line 377
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2a:Z

    .line 378
    .line 379
    iget v0, v2, LX/6kq;->A0K:I

    .line 380
    .line 381
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0M:I

    .line 382
    .line 383
    iget v0, v2, LX/6kq;->A0J:I

    .line 384
    .line 385
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0L:I

    .line 386
    .line 387
    iget-boolean v0, v2, LX/6kq;->A1R:Z

    .line 388
    .line 389
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Q:Z

    .line 390
    .line 391
    iget-boolean v0, v2, LX/6kq;->A30:Z

    .line 392
    .line 393
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2y:Z

    .line 394
    .line 395
    iget-boolean v0, v2, LX/6kq;->A31:Z

    .line 396
    .line 397
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2z:Z

    .line 398
    .line 399
    iget-object v0, v2, LX/6kq;->A19:Ljava/util/HashSet;

    .line 400
    .line 401
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A19:Ljava/util/HashSet;

    .line 402
    .line 403
    iget-boolean v0, v2, LX/6kq;->A1L:Z

    .line 404
    .line 405
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1K:Z

    .line 406
    .line 407
    iget v0, v2, LX/6kq;->A0B:I

    .line 408
    .line 409
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0E:I

    .line 410
    .line 411
    iget v0, v2, LX/6kq;->A09:I

    .line 412
    .line 413
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0C:I

    .line 414
    .line 415
    iget v0, v2, LX/6kq;->A0A:I

    .line 416
    .line 417
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0D:I

    .line 418
    .line 419
    iget-boolean v0, v2, LX/6kq;->A2R:Z

    .line 420
    .line 421
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Q:Z

    .line 422
    .line 423
    iget-boolean v0, v2, LX/6kq;->A1b:Z

    .line 424
    .line 425
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1a:Z

    .line 426
    .line 427
    iget v0, v2, LX/6kq;->A0T:I

    .line 428
    .line 429
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0V:I

    .line 430
    .line 431
    iget v0, v2, LX/6kq;->A0U:I

    .line 432
    .line 433
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0W:I

    .line 434
    .line 435
    iget v0, v2, LX/6kq;->A0V:I

    .line 436
    .line 437
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0X:I

    .line 438
    .line 439
    iget-boolean v0, v2, LX/6kq;->A2A:Z

    .line 440
    .line 441
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A28:Z

    .line 442
    .line 443
    iget-boolean v0, v2, LX/6kq;->A1j:Z

    .line 444
    .line 445
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1j:Z

    .line 446
    .line 447
    iget-boolean v0, v2, LX/6kq;->A35:Z

    .line 448
    .line 449
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A33:Z

    .line 450
    .line 451
    iget-boolean v0, v2, LX/6kq;->A1i:Z

    .line 452
    .line 453
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1i:Z

    .line 454
    .line 455
    iget-boolean v0, v2, LX/6kq;->A1h:Z

    .line 456
    .line 457
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1h:Z

    .line 458
    .line 459
    iget-boolean v0, v2, LX/6kq;->A3D:Z

    .line 460
    .line 461
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3B:Z

    .line 462
    .line 463
    iget-boolean v0, v2, LX/6kq;->A1M:Z

    .line 464
    .line 465
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1L:Z

    .line 466
    .line 467
    iget v0, v2, LX/6kq;->A0Q:I

    .line 468
    .line 469
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0S:I

    .line 470
    .line 471
    iget-boolean v0, v2, LX/6kq;->A1P:Z

    .line 472
    .line 473
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1O:Z

    .line 474
    .line 475
    iget-wide v3, v2, LX/6kq;->A0e:J

    .line 476
    .line 477
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0g:J

    .line 478
    .line 479
    iget-boolean v0, v2, LX/6kq;->A34:Z

    .line 480
    .line 481
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A32:Z

    .line 482
    .line 483
    iget-boolean v0, v2, LX/6kq;->A32:Z

    .line 484
    .line 485
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A30:Z

    .line 486
    .line 487
    iget-boolean v0, v2, LX/6kq;->A3Q:Z

    .line 488
    .line 489
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3O:Z

    .line 490
    .line 491
    iget v0, v2, LX/6kq;->A0c:I

    .line 492
    .line 493
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0e:I

    .line 494
    .line 495
    iget v0, v2, LX/6kq;->A02:I

    .line 496
    .line 497
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A05:I

    .line 498
    .line 499
    iget-boolean v0, v2, LX/6kq;->A2F:Z

    .line 500
    .line 501
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2D:Z

    .line 502
    .line 503
    iget-boolean v0, v2, LX/6kq;->A2G:Z

    .line 504
    .line 505
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2E:Z

    .line 506
    .line 507
    iget-wide v3, v2, LX/6kq;->A00:D

    .line 508
    .line 509
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A03:D

    .line 510
    .line 511
    iget-boolean v0, v2, LX/6kq;->A3M:Z

    .line 512
    .line 513
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3K:Z

    .line 514
    .line 515
    iget-boolean v0, v2, LX/6kq;->A2w:Z

    .line 516
    .line 517
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2u:Z

    .line 518
    .line 519
    iget v0, v2, LX/6kq;->A0N:I

    .line 520
    .line 521
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0P:I

    .line 522
    .line 523
    iget v0, v2, LX/6kq;->A0Y:I

    .line 524
    .line 525
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0a:I

    .line 526
    .line 527
    iget v0, v2, LX/6kq;->A0Z:I

    .line 528
    .line 529
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0b:I

    .line 530
    .line 531
    iget-boolean v0, v2, LX/6kq;->A2V:Z

    .line 532
    .line 533
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2U:Z

    .line 534
    .line 535
    iget-boolean v0, v2, LX/6kq;->A2U:Z

    .line 536
    .line 537
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2T:Z

    .line 538
    .line 539
    iget-boolean v0, v2, LX/6kq;->A2T:Z

    .line 540
    .line 541
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2S:Z

    .line 542
    .line 543
    iget v0, v2, LX/6kq;->A0M:I

    .line 544
    .line 545
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0O:I

    .line 546
    .line 547
    iget-object v0, v2, LX/6kq;->A1B:Ljava/util/Set;

    .line 548
    .line 549
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1B:Ljava/util/Set;

    .line 550
    .line 551
    iget-boolean v0, v2, LX/6kq;->A2C:Z

    .line 552
    .line 553
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2A:Z

    .line 554
    .line 555
    iget-boolean v0, v2, LX/6kq;->A2J:Z

    .line 556
    .line 557
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2I:Z

    .line 558
    .line 559
    iget-boolean v0, v2, LX/6kq;->A2i:Z

    .line 560
    .line 561
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2e:Z

    .line 562
    .line 563
    iget v0, v2, LX/6kq;->A0P:I

    .line 564
    .line 565
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0R:I

    .line 566
    .line 567
    iget-boolean v0, v2, LX/6kq;->A1s:Z

    .line 568
    .line 569
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1s:Z

    .line 570
    .line 571
    iget-boolean v0, v2, LX/6kq;->A2Q:Z

    .line 572
    .line 573
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2P:Z

    .line 574
    .line 575
    iget-boolean v0, v2, LX/6kq;->A1S:Z

    .line 576
    .line 577
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1R:Z

    .line 578
    .line 579
    iget-boolean v0, v2, LX/6kq;->A2B:Z

    .line 580
    .line 581
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A29:Z

    .line 582
    .line 583
    iget v0, v2, LX/6kq;->A0d:I

    .line 584
    .line 585
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0f:I

    .line 586
    .line 587
    iget-boolean v0, v2, LX/6kq;->A3a:Z

    .line 588
    .line 589
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3Y:Z

    .line 590
    .line 591
    iget-boolean v0, v2, LX/6kq;->A3N:Z

    .line 592
    .line 593
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3L:Z

    .line 594
    .line 595
    iget-object v0, v2, LX/6kq;->A0p:LX/6mi;

    .line 596
    .line 597
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0q:LX/6mi;

    .line 598
    .line 599
    iget-object v0, v2, LX/6kq;->A0h:LX/6mi;

    .line 600
    .line 601
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0i:LX/6mi;

    .line 602
    .line 603
    iget-object v0, v2, LX/6kq;->A0n:LX/6mi;

    .line 604
    .line 605
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0o:LX/6mi;

    .line 606
    .line 607
    iget-boolean v0, v2, LX/6kq;->A3F:Z

    .line 608
    .line 609
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3D:Z

    .line 610
    .line 611
    iget-object v0, v2, LX/6kq;->A1G:Ljava/util/Set;

    .line 612
    .line 613
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1G:Ljava/util/Set;

    .line 614
    .line 615
    iget-object v0, v2, LX/6kq;->A1F:Ljava/util/Set;

    .line 616
    .line 617
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1F:Ljava/util/Set;

    .line 618
    .line 619
    iget-object v0, v2, LX/6kq;->A1H:Ljava/util/Set;

    .line 620
    .line 621
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1H:Ljava/util/Set;

    .line 622
    .line 623
    iget-boolean v0, v2, LX/6kq;->A3C:Z

    .line 624
    .line 625
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3A:Z

    .line 626
    .line 627
    iget v0, v2, LX/6kq;->A0E:I

    .line 628
    .line 629
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0G:I

    .line 630
    .line 631
    iget v0, v2, LX/6kq;->A0b:I

    .line 632
    .line 633
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0d:I

    .line 634
    .line 635
    iget v0, v2, LX/6kq;->A0C:I

    .line 636
    .line 637
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0F:I

    .line 638
    .line 639
    iget v0, v2, LX/6kq;->A01:I

    .line 640
    .line 641
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A04:I

    .line 642
    .line 643
    iget-boolean v0, v2, LX/6kq;->A2q:Z

    .line 644
    .line 645
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2o:Z

    .line 646
    .line 647
    iget-object v0, v2, LX/6kq;->A1C:Ljava/util/Set;

    .line 648
    .line 649
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1C:Ljava/util/Set;

    .line 650
    .line 651
    iget-boolean v0, v2, LX/6kq;->A1J:Z

    .line 652
    .line 653
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1g:Z

    .line 654
    .line 655
    iget-boolean v0, v2, LX/6kq;->A1T:Z

    .line 656
    .line 657
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1S:Z

    .line 658
    .line 659
    iget-boolean v0, v2, LX/6kq;->A2j:Z

    .line 660
    .line 661
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2f:Z

    .line 662
    .line 663
    iget-boolean v0, v2, LX/6kq;->A3I:Z

    .line 664
    .line 665
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3G:Z

    .line 666
    .line 667
    iget-boolean v0, v2, LX/6kq;->A1q:Z

    .line 668
    .line 669
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1q:Z

    .line 670
    .line 671
    iget-boolean v0, v2, LX/6kq;->A1e:Z

    .line 672
    .line 673
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1d:Z

    .line 674
    .line 675
    iget-boolean v0, v2, LX/6kq;->A23:Z

    .line 676
    .line 677
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A21:Z

    .line 678
    .line 679
    iget-boolean v0, v2, LX/6kq;->A25:Z

    .line 680
    .line 681
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A23:Z

    .line 682
    .line 683
    iget-object v0, v2, LX/6kq;->A11:LX/6mm;

    .line 684
    .line 685
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A11:LX/6mm;

    .line 686
    .line 687
    iget-boolean v0, v2, LX/6kq;->A2I:Z

    .line 688
    .line 689
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2H:Z

    .line 690
    .line 691
    iget-object v0, v2, LX/6kq;->A1A:Ljava/util/Map;

    .line 692
    .line 693
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1A:Ljava/util/Map;

    .line 694
    .line 695
    iget-boolean v0, v2, LX/6kq;->A1Y:Z

    .line 696
    .line 697
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1X:Z

    .line 698
    .line 699
    iget-boolean v0, v2, LX/6kq;->A2v:Z

    .line 700
    .line 701
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2t:Z

    .line 702
    .line 703
    iget-boolean v0, v2, LX/6kq;->A2d:Z

    .line 704
    .line 705
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2b:Z

    .line 706
    .line 707
    iget-boolean v0, v2, LX/6kq;->A38:Z

    .line 708
    .line 709
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A36:Z

    .line 710
    .line 711
    iget-boolean v0, v2, LX/6kq;->A1O:Z

    .line 712
    .line 713
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1N:Z

    .line 714
    .line 715
    iget-boolean v0, v2, LX/6kq;->A1r:Z

    .line 716
    .line 717
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1r:Z

    .line 718
    .line 719
    iget v0, v2, LX/6kq;->A05:I

    .line 720
    .line 721
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A08:I

    .line 722
    .line 723
    iget-boolean v0, v2, LX/6kq;->A1z:Z

    .line 724
    .line 725
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1z:Z

    .line 726
    .line 727
    iget v0, v2, LX/6kq;->A0I:I

    .line 728
    .line 729
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0K:I

    .line 730
    .line 731
    iget v0, v2, LX/6kq;->A04:I

    .line 732
    .line 733
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A07:I

    .line 734
    .line 735
    iget-boolean v0, v2, LX/6kq;->A3B:Z

    .line 736
    .line 737
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A39:Z

    .line 738
    .line 739
    iget-boolean v0, v2, LX/6kq;->A1l:Z

    .line 740
    .line 741
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1l:Z

    .line 742
    .line 743
    iget-boolean v0, v2, LX/6kq;->A3R:Z

    .line 744
    .line 745
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3P:Z

    .line 746
    .line 747
    iget-object v0, v2, LX/6kq;->A1E:Ljava/util/Set;

    .line 748
    .line 749
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1E:Ljava/util/Set;

    .line 750
    .line 751
    iget-object v0, v2, LX/6kq;->A1D:Ljava/util/Set;

    .line 752
    .line 753
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1D:Ljava/util/Set;

    .line 754
    .line 755
    iget-object v0, v2, LX/6kq;->A1I:Ljava/util/Set;

    .line 756
    .line 757
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1I:Ljava/util/Set;

    .line 758
    .line 759
    iget-boolean v0, v2, LX/6kq;->A2O:Z

    .line 760
    .line 761
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2N:Z

    .line 762
    .line 763
    iget-boolean v0, v2, LX/6kq;->A2Z:Z

    .line 764
    .line 765
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2X:Z

    .line 766
    .line 767
    iget-boolean v0, v2, LX/6kq;->A2b:Z

    .line 768
    .line 769
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Z:Z

    .line 770
    .line 771
    iget-boolean v0, v2, LX/6kq;->A1w:Z

    .line 772
    .line 773
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1w:Z

    .line 774
    .line 775
    iget-boolean v0, v2, LX/6kq;->A1x:Z

    .line 776
    .line 777
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1x:Z

    .line 778
    .line 779
    iget-boolean v0, v2, LX/6kq;->A1v:Z

    .line 780
    .line 781
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1v:Z

    .line 782
    .line 783
    iget v0, v2, LX/6kq;->A0O:I

    .line 784
    .line 785
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Q:I

    .line 786
    .line 787
    iget-boolean v0, v2, LX/6kq;->A24:Z

    .line 788
    .line 789
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A22:Z

    .line 790
    .line 791
    iget-boolean v0, v2, LX/6kq;->A2N:Z

    .line 792
    .line 793
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2M:Z

    .line 794
    .line 795
    iget-boolean v0, v2, LX/6kq;->A1u:Z

    .line 796
    .line 797
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1u:Z

    .line 798
    .line 799
    iget-boolean v0, v2, LX/6kq;->A20:Z

    .line 800
    .line 801
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A02:Z

    .line 802
    .line 803
    iget-wide v3, v2, LX/6kq;->A0f:J

    .line 804
    .line 805
    iput-wide v3, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A00:J

    .line 806
    .line 807
    iget-boolean v0, v2, LX/6kq;->A1t:Z

    .line 808
    .line 809
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1t:Z

    .line 810
    .line 811
    iget v0, v2, LX/6kq;->A08:I

    .line 812
    .line 813
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0B:I

    .line 814
    .line 815
    iget v0, v2, LX/6kq;->A03:I

    .line 816
    .line 817
    iput v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A06:I

    .line 818
    .line 819
    iget-boolean v0, v2, LX/6kq;->A1a:Z

    .line 820
    .line 821
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Z:Z

    .line 822
    .line 823
    iget-boolean v0, v2, LX/6kq;->A1V:Z

    .line 824
    .line 825
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1U:Z

    .line 826
    .line 827
    iget-boolean v0, v2, LX/6kq;->A39:Z

    .line 828
    .line 829
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A37:Z

    .line 830
    .line 831
    iget-object v0, v2, LX/6kq;->A0x:LX/6kv;

    .line 832
    .line 833
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A01:LX/6kv;

    .line 834
    .line 835
    iget-boolean v0, v2, LX/6kq;->A1g:Z

    .line 836
    .line 837
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1f:Z

    .line 838
    .line 839
    iget-boolean v0, v2, LX/6kq;->A28:Z

    .line 840
    .line 841
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A26:Z

    .line 842
    .line 843
    iget-boolean v0, v2, LX/6kq;->A1d:Z

    .line 844
    .line 845
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1c:Z

    .line 846
    .line 847
    iget-boolean v0, v2, LX/6kq;->A2X:Z

    .line 848
    .line 849
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2V:Z

    .line 850
    .line 851
    iget-boolean v0, v2, LX/6kq;->A1k:Z

    .line 852
    .line 853
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1k:Z

    .line 854
    .line 855
    iget-boolean v0, v2, LX/6kq;->A3X:Z

    .line 856
    .line 857
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3V:Z

    .line 858
    .line 859
    iget-boolean v0, v2, LX/6kq;->A2u:Z

    .line 860
    .line 861
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2s:Z

    .line 862
    .line 863
    iget-boolean v0, v2, LX/6kq;->A1c:Z

    .line 864
    .line 865
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1b:Z

    .line 866
    .line 867
    iget-boolean v0, v2, LX/6kq;->A1Z:Z

    .line 868
    .line 869
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Y:Z

    .line 870
    .line 871
    iget-boolean v0, v2, LX/6kq;->A22:Z

    .line 872
    .line 873
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A20:Z

    .line 874
    .line 875
    iget-boolean v0, v2, LX/6kq;->A2W:Z

    .line 876
    .line 877
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2G:Z

    .line 878
    .line 879
    iget-boolean v0, v2, LX/6kq;->A1Q:Z

    .line 880
    .line 881
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1P:Z

    .line 882
    .line 883
    iget-boolean v0, v2, LX/6kq;->A2L:Z

    .line 884
    .line 885
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2K:Z

    .line 886
    .line 887
    iget-object v0, v2, LX/6kq;->A0q:LX/6mp;

    .line 888
    .line 889
    iput-object v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0r:LX/6mp;

    .line 890
    .line 891
    iget-boolean v0, v2, LX/6kq;->A1p:Z

    .line 892
    .line 893
    iput-boolean v0, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1p:Z

    .line 894
    .line 895
    iget-object v2, v2, LX/6kq;->A0z:LX/6mt;

    .line 896
    .line 897
    if-nez v2, :cond_0

    .line 898
    .line 899
    const/4 v3, 0x0

    .line 900
    const/16 v56, 0x0

    .line 901
    .line 902
    const-wide/16 v22, 0x0

    .line 903
    .line 904
    const-wide/16 v10, 0x0

    .line 905
    .line 906
    new-instance v2, LX/6mt;

    .line 907
    .line 908
    move-object v4, v3

    .line 909
    move-object v5, v3

    .line 910
    move-object v6, v3

    .line 911
    move-object v7, v3

    .line 912
    move-object v8, v3

    .line 913
    move-object v9, v3

    .line 914
    move-wide v12, v10

    .line 915
    move-wide v14, v10

    .line 916
    move-wide/from16 v16, v10

    .line 917
    .line 918
    move-wide/from16 v18, v10

    .line 919
    .line 920
    move-wide/from16 v20, v10

    .line 921
    .line 922
    move-wide/from16 v24, v22

    .line 923
    .line 924
    move-wide/from16 v26, v22

    .line 925
    .line 926
    move-wide/from16 v28, v22

    .line 927
    .line 928
    move-wide/from16 v30, v22

    .line 929
    .line 930
    move-wide/from16 v32, v22

    .line 931
    .line 932
    move-wide/from16 v34, v22

    .line 933
    .line 934
    move-wide/from16 v36, v22

    .line 935
    .line 936
    move-wide/from16 v38, v22

    .line 937
    .line 938
    move-wide/from16 v40, v22

    .line 939
    .line 940
    move-wide/from16 v42, v22

    .line 941
    .line 942
    move-wide/from16 v44, v22

    .line 943
    .line 944
    move-wide/from16 v46, v22

    .line 945
    .line 946
    move-wide/from16 v48, v22

    .line 947
    .line 948
    move-wide/from16 v50, v22

    .line 949
    .line 950
    move-wide/from16 v52, v22

    .line 951
    .line 952
    move-wide/from16 v54, v22

    .line 953
    .line 954
    move/from16 v57, v56

    .line 955
    .line 956
    move/from16 v58, v56

    .line 957
    .line 958
    move/from16 v59, v56

    .line 959
    .line 960
    move/from16 v60, v56

    .line 961
    .line 962
    move/from16 v61, v56

    .line 963
    .line 964
    move/from16 v62, v56

    .line 965
    .line 966
    move/from16 v63, v56

    .line 967
    .line 968
    move/from16 v64, v56

    .line 969
    .line 970
    move/from16 v65, v56

    .line 971
    .line 972
    move/from16 v66, v56

    .line 973
    .line 974
    move/from16 v67, v56

    .line 975
    .line 976
    move/from16 v68, v56

    .line 977
    .line 978
    move/from16 v69, v56

    .line 979
    .line 980
    move/from16 v70, v56

    .line 981
    .line 982
    move/from16 v71, v56

    .line 983
    .line 984
    move/from16 v72, v56

    .line 985
    .line 986
    move/from16 v73, v56

    .line 987
    .line 988
    move/from16 v74, v56

    .line 989
    .line 990
    move/from16 v75, v56

    .line 991
    .line 992
    move/from16 v76, v56

    .line 993
    .line 994
    move/from16 v77, v56

    .line 995
    .line 996
    move/from16 v78, v56

    .line 997
    .line 998
    move/from16 v79, v56

    .line 999
    .line 1000
    move/from16 v80, v56

    .line 1001
    .line 1002
    move/from16 v81, v56

    .line 1003
    .line 1004
    move/from16 v82, v56

    .line 1005
    .line 1006
    move/from16 v83, v56

    .line 1007
    .line 1008
    move/from16 v84, v56

    .line 1009
    .line 1010
    move/from16 v85, v56

    .line 1011
    .line 1012
    move/from16 v86, v56

    .line 1013
    .line 1014
    move/from16 v87, v56

    .line 1015
    .line 1016
    move/from16 v88, v56

    .line 1017
    .line 1018
    move/from16 v89, v56

    .line 1019
    .line 1020
    move/from16 v90, v56

    .line 1021
    .line 1022
    move/from16 v91, v56

    .line 1023
    .line 1024
    move/from16 v92, v56

    .line 1025
    .line 1026
    move/from16 v93, v56

    .line 1027
    .line 1028
    move/from16 v94, v56

    .line 1029
    .line 1030
    move/from16 v95, v56

    .line 1031
    .line 1032
    move/from16 v96, v56

    .line 1033
    .line 1034
    move/from16 v97, v56

    .line 1035
    .line 1036
    move/from16 v98, v56

    .line 1037
    .line 1038
    move/from16 v99, v56

    .line 1039
    .line 1040
    move/from16 v100, v56

    .line 1041
    .line 1042
    move/from16 v101, v56

    .line 1043
    .line 1044
    move/from16 v102, v56

    .line 1045
    .line 1046
    move/from16 v103, v56

    .line 1047
    .line 1048
    move/from16 v104, v56

    .line 1049
    .line 1050
    move/from16 v105, v56

    .line 1051
    .line 1052
    move/from16 v106, v56

    .line 1053
    .line 1054
    move/from16 v107, v56

    .line 1055
    .line 1056
    move/from16 v108, v56

    .line 1057
    .line 1058
    move/from16 v109, v56

    .line 1059
    .line 1060
    move/from16 v110, v56

    .line 1061
    .line 1062
    move/from16 v111, v56

    .line 1063
    .line 1064
    move/from16 v112, v56

    .line 1065
    .line 1066
    move/from16 v113, v56

    .line 1067
    .line 1068
    move/from16 v114, v56

    .line 1069
    .line 1070
    move/from16 v115, v56

    .line 1071
    .line 1072
    move/from16 v116, v56

    .line 1073
    .line 1074
    move/from16 v117, v56

    .line 1075
    .line 1076
    move/from16 v118, v56

    .line 1077
    .line 1078
    move/from16 v119, v56

    .line 1079
    .line 1080
    move/from16 v120, v56

    .line 1081
    .line 1082
    move/from16 v121, v56

    .line 1083
    .line 1084
    move/from16 v122, v56

    .line 1085
    .line 1086
    move/from16 v123, v56

    .line 1087
    .line 1088
    move/from16 v124, v56

    .line 1089
    .line 1090
    move/from16 v125, v56

    .line 1091
    .line 1092
    move/from16 v126, v56

    .line 1093
    .line 1094
    move/from16 v127, v56

    .line 1095
    .line 1096
    move/from16 v128, v56

    .line 1097
    .line 1098
    move/from16 v129, v56

    .line 1099
    .line 1100
    move/from16 v130, v56

    .line 1101
    .line 1102
    move/from16 v131, v56

    .line 1103
    .line 1104
    move/from16 v132, v56

    .line 1105
    .line 1106
    move/from16 v133, v56

    .line 1107
    .line 1108
    move/from16 v134, v56

    .line 1109
    .line 1110
    move/from16 v135, v56

    .line 1111
    .line 1112
    move/from16 v136, v56

    .line 1113
    .line 1114
    move/from16 v137, v56

    .line 1115
    .line 1116
    move/from16 v138, v56

    .line 1117
    .line 1118
    move/from16 v139, v56

    .line 1119
    .line 1120
    move/from16 v140, v56

    .line 1121
    .line 1122
    move/from16 v141, v56

    .line 1123
    .line 1124
    move/from16 v142, v56

    .line 1125
    .line 1126
    move/from16 v143, v56

    .line 1127
    .line 1128
    move/from16 v144, v56

    .line 1129
    .line 1130
    move/from16 v145, v56

    .line 1131
    .line 1132
    move/from16 v146, v56

    .line 1133
    .line 1134
    move/from16 v147, v56

    .line 1135
    .line 1136
    move/from16 v148, v56

    .line 1137
    .line 1138
    move/from16 v149, v56

    .line 1139
    .line 1140
    move/from16 v150, v56

    .line 1141
    .line 1142
    move/from16 v151, v56

    .line 1143
    .line 1144
    move/from16 v152, v56

    .line 1145
    .line 1146
    move/from16 v153, v56

    .line 1147
    .line 1148
    move/from16 v154, v56

    .line 1149
    .line 1150
    move/from16 v155, v56

    .line 1151
    .line 1152
    move/from16 v156, v56

    .line 1153
    .line 1154
    move/from16 v157, v56

    .line 1155
    .line 1156
    move/from16 v158, v56

    .line 1157
    .line 1158
    move/from16 v159, v56

    .line 1159
    .line 1160
    move/from16 v160, v56

    .line 1161
    .line 1162
    move/from16 v161, v56

    .line 1163
    .line 1164
    move/from16 v162, v56

    .line 1165
    .line 1166
    move/from16 v163, v56

    .line 1167
    .line 1168
    move/from16 v164, v56

    .line 1169
    .line 1170
    move/from16 v165, v56

    .line 1171
    .line 1172
    move/from16 v166, v56

    .line 1173
    .line 1174
    move/from16 v167, v56

    .line 1175
    .line 1176
    move/from16 v168, v56

    .line 1177
    .line 1178
    move/from16 v169, v56

    .line 1179
    .line 1180
    move/from16 v170, v56

    .line 1181
    .line 1182
    move/from16 v171, v56

    .line 1183
    .line 1184
    move/from16 v172, v56

    .line 1185
    .line 1186
    move/from16 v173, v56

    .line 1187
    .line 1188
    move/from16 v174, v56

    .line 1189
    .line 1190
    move/from16 v175, v56

    .line 1191
    .line 1192
    move/from16 v176, v56

    .line 1193
    .line 1194
    move/from16 v177, v56

    .line 1195
    .line 1196
    move/from16 v178, v56

    .line 1197
    .line 1198
    move/from16 v179, v56

    .line 1199
    .line 1200
    move/from16 v180, v56

    .line 1201
    .line 1202
    move/from16 v181, v56

    .line 1203
    .line 1204
    move/from16 v182, v56

    .line 1205
    .line 1206
    move/from16 v183, v56

    .line 1207
    .line 1208
    move/from16 v184, v56

    .line 1209
    .line 1210
    move/from16 v185, v56

    .line 1211
    .line 1212
    move/from16 v186, v56

    .line 1213
    .line 1214
    move/from16 v187, v56

    .line 1215
    .line 1216
    move/from16 v188, v56

    .line 1217
    .line 1218
    move/from16 v189, v56

    .line 1219
    .line 1220
    move/from16 v190, v56

    .line 1221
    .line 1222
    move/from16 v191, v56

    .line 1223
    .line 1224
    move/from16 v192, v56

    .line 1225
    .line 1226
    move/from16 v193, v56

    .line 1227
    .line 1228
    move/from16 v194, v56

    .line 1229
    .line 1230
    move/from16 v195, v56

    .line 1231
    .line 1232
    move/from16 v196, v56

    .line 1233
    .line 1234
    move/from16 v197, v56

    .line 1235
    .line 1236
    move/from16 v198, v56

    .line 1237
    .line 1238
    move/from16 v199, v56

    .line 1239
    .line 1240
    move/from16 v200, v56

    .line 1241
    .line 1242
    move/from16 v201, v56

    .line 1243
    .line 1244
    move/from16 v202, v56

    .line 1245
    .line 1246
    move/from16 v203, v56

    .line 1247
    .line 1248
    move/from16 v204, v56

    .line 1249
    .line 1250
    move/from16 v205, v56

    .line 1251
    .line 1252
    move/from16 v206, v56

    .line 1253
    .line 1254
    move/from16 v207, v56

    .line 1255
    .line 1256
    move/from16 v208, v56

    .line 1257
    .line 1258
    move/from16 v209, v56

    .line 1259
    .line 1260
    invoke-direct/range {v2 .. v209}, LX/6mt;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DDDDDDJJJJJJJJJJJJJJJJJZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ)V

    .line 1261
    .line 1262
    .line 1263
    :cond_0
    iput-object v2, v1, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0z:LX/6mt;

    .line 1264
    .line 1265
    return-void
.end method
