services:
  patcher:
    build: .
    volumes:
      - ./:/data
      - ./main.py:/app/main.py
      - ./artifactory_generator:/app/artifactory_generator
      - ./smali_generator:/app/smali_generator
    command: -p /data/Whatsapp.apk -o /data/PatchedWhatsApp.apk -t /tmp/whatsapp-temp
