package com.crossapp.graphql.facebook.enums.stringdefs;

import java.util.Set;
import p000X.C8I;

/* loaded from: classes18.dex */
public final class GraphQLPaymentCredentialTypeEnumSet {
    public static final Set A00;

    static {
        String[] strArr = new String[102];
        System.arraycopy(new String[]{"ADS_STORED_BALANCE", "AFFIRM", "ALIPAY", "ALIPAY_HK", "ALT_PAY", "APPLE_IAP", "APPLE_PAY", "BLIK", "BPI", "CAPITEC_PAY", "CLABE", "CREDIT_CARD", "CREDIT_CARD_AMERICANEXPRESS", "CREDIT_CARD_CUP", "CREDIT_CARD_DINERSCLUB", "CREDIT_CARD_DISCOVER", "CREDIT_CARD_ELO", "CREDIT_CARD_INTERAC", "CREDIT_CARD_JCB", "CREDIT_CARD_MAESTRO", "CREDIT_CARD_MASTERCARD", "CREDIT_CARD_PIN_ONLY", "CREDIT_CARD_RUPAY", "CREDIT_CARD_VISA", "DANA", "DEBIT_CARD_PAYOUT", "DIRECT_DEBIT"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"DUMMY", "EARNINGS_PAYOUT", "EXTENDED_CREDIT", "EXTERNAL_CREDENTIAL", "EXTERNAL_UPI", "EXTERNAL_WALLET", "FACEBOOK_PAY", "FB_GIFTCARD", "FB_TOKEN", "FORM_FILL_TOKEN", "GCASH", "GIFTCARD", "GIFTCARD_BALANCE", "GOOGLE_PAY", "HPP_PAYMENT_LINK", "ID_PAYMENT_ACCOUNT", "INCENTIVE_FUNDING", "INCENTIVE_MOR_OMNIPE_MIGRATION", "INCENTIVE_MOR_OMNIPE_MIGRATION_MERCHANT_FUNDED", "INCENTIVE_NMOR_OMNIPE_MIGRATION", "KAKAOPAY", "KBANK", "MB_WAY", "META_DUMMY", "META_PAY", "META_REWARD_DONATION", "MOBILE_MONEY"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"MOCK_OPAQUE_REDIRECT_LPM", "MOMO", "NETWORK_TOKEN", "NET_BANKING", "NET_BANKING_BUALUANG", "NET_BANKING_KMA", "NET_BANKING_KRUNGTHAI_NEXT", "NET_BANKING_K_PLUS", "NET_BANKING_SCB", "NEW_BUSINESS_STORED_BALANCE", "NEW_CREDENTIAL_NUX", "NEW_CREDIT_CARD", "NEW_EXTENDED_CREDIT", "NEW_EXTERNAL_WALLET", "NEW_PAYPAL_BA", "NEW_PAYPAL_BNPL_CHECKOUT", "NEW_PAYPAL_CHECKOUT", "NEW_SHOP_PAY", "NEW_WA_EXTERNAL_WALLET", "OFFER", "PAYMAYA", "PAYONEER", "PAYOUT_CONSUMER_EARNING", "PAYPAL_BA", "PAYPAL_PAYMENT_LINK", "PAYPAL_PAYOUT", "PAYPAL_TOKEN"}, 0, strArr, 54, 27);
        A00 = C8I.A0W(new String[]{"PAYPAY", "PAY_ON_DELIVERY", "PIX", "PIX_KEY", "QR_CODE", "QUEST_CASH", "REWARD", "SHOPIFY_BNPL", "SHOPIFY_OTC", "SHOP_PAY", "SOFORT", "STABLECOIN", "STORED_CREDIT", "STORED_VALUE", "TOSS", "TOUCH_N_GO", "TRUEMONEY", "UPI", "UPI_WA", "VIRTUAL_CARD_KLARNA_BNPL", "WA_EXTERNAL_WALLET"}, strArr, 0, 81, 21);
    }

    public static final Set getSet() {
        return A00;
    }
}
