package com.crossapp.graphql.facebook.enums.stringdefs;

import java.util.Set;
import p000X.C8I;

/* loaded from: classes18.dex */
public final class GraphQLPaymentProviderSet {
    public static final Set A00;

    static {
        String[] strArr = new String[168];
        System.arraycopy(new String[]{"ADS", "ADYEN_ALTPAY", "ADYEN_AMEX", "ADYEN_CC", "ADYEN_CHECKOUT", "ADYEN_INTERCOMPANY", "ADYEN_LOCAL", "AFFIRM", "AMEX", "ANT_FINANCIAL", "APPLE_PAY", "ARVATO_DD", "ASYNC_DUMMY", "AXIS", "BANGO", "BANK_ADYEN", "BANK_OF_AMERICA_DD", "BBVA", "BILLDESK", "BOF_API", "BOKU", "BOKU_DIRECT", "BOKU_WALLET", "BRAINTREE_AMEX", "BRAINTREE_GRAPH", "BRAINTREE_PAYMENTECH", "BT"}, 0, strArr, 0, 27);
        System.arraycopy(new String[]{"BUNDLE", "BYOG_HPP_CIELO", "BYOG_PAYPAL", "BYOG_PAYPAL_MARKETPLACE", "BYOG_STRIPE", "BYOG_STRIPE_LITE", "CARDINAL", "CASHFREE", "CC_AVENUE", "CHASE", "CHASE_AMEX", "CHECKOUT_COM", "CIELO", "CIELO_CONSUMER", "CIELO_ECOMMERCE", "CIELO_MERCHANT_V1", "CITI_DD", "CONTACT_MERCHANT", "COURTESY_CREDITS", "CREDIT_CARD", "CYBERSOURCE_AMEX", "CYBERSOURCE_PAYMENTECH", "DCP_APPLE", "DCP_GOOGLE", "DIRECT_DEBIT", "DLOCAL", "DUMMY"}, 0, strArr, 27, 27);
        System.arraycopy(new String[]{"EBANX", "EBANX_DIRECT", "ECOBANK", "EKATA", "ETHOCA", "FB", "FB_SPEC_MOCK", "FISERV", "FLUTTERWAVE", "FONOA", "GETNET", "GMG", "GO", "HDFC", "HYPERWALLET", "ICICI", "INICIADOR", "JIO", "JUSPAY_CONSUMER", "KBANK", "LIVEGAMER", "LPM_DUMMY_REVERSE", "MANAGED_STRIPE", "MASTERCARD", "MASTERCARD_CHECKOUT_SOLUTIONS", "MASTERCARD_OFFERS", "MASTERCARD_SCOF"}, 0, strArr, 54, 27);
        System.arraycopy(new String[]{"MERCADO_PAGO", "MERCADO_PAGO_DIRECT", "META_HPP_MOCK", "META_PLATFORM", "MINDGATE_CONSUMER", "MOCK_BRAINTREE_GRAPH", "MOCK_CC", "MOCK_CC_AUTHENTICATE", "MOCK_CHAINING", "MOCK_GENERIC_HTTP", "MOCK_LPM", "MOCK_RETRY", "MOCK_UPI", "MOCK_WALLET", "MOCK_WITH_PREDEFINED_CCS", "NMOR_PAYPAL", "NMOR_SHOPIFY_DIRECT", "O3P_KBANK", "O3P_STRIPE_P4P", "OAUTH", "OFFSITE_LINK", "OPG_PAYPAL", "OTTO", "OVO", "P2M_INDIA_NOT_APPLICABLE", "PAGSEGURO", "PAYMAYA"}, 0, strArr, 81, 27);
        System.arraycopy(new String[]{"PAYMENTECH", "PAYMENTWALL", "PAYONEER", "PAYOUT", "PAYPAL", "PAYPAL_ACP", "PAYPAL_COMMERCE", "PAYPAL_MARKETPLACE", "PAYPAL_NVP", "PAYPAL_OFFSITE", "PAYPAL_USER_REVERIFY", "PAYU", "PAYU_INDIA", "PAYU_INDIA_MERCHANT", "PAY_WITH_MY_BANK_DD", "PB", "PE_TEST", "PINGPONG", "PLATFORMIZED_ADYEN_CHECKOUT", "PLATFORMIZED_BRAINTREE", "PLATFORMIZED_CYBERSOURCE", "PLATFORMIZED_KBANK", "PLATFORMIZED_PAYPAL", "PLATFORMIZED_PAYU", "PLATFORMIZED_STRIPE", "PLAYSPAN", "QRC_PAYPAL"}, 0, strArr, 108, 27);
        System.arraycopy(new String[]{"RAKUTEN", "RAZORPAY", "REDE", "RISKIFIED", "SAFECHARGE", "SBI", "SERASA", "SHOPIFY", "SHOPIFY_DIRECT", "SMARTPAY", "STONE", "STRIPE", "STRIPE_ACP", "STRIPE_AMEX", "STRIPE_OFFSITE", "STRIPE_PAYOUTS", "SUMUP", "TINCHECKER", "TOPPS", "TRUSTLY", "TRUSTLY_GACH", "TSP_PAYPAL", "TWO_C_TWO_P", "UNKNOWN", "UPI", "USER_STORED_BALANCE", "VISA"}, 0, strArr, 135, 27);
        A00 = C8I.A0W(new String[]{"WITHDRAW", "WORLDLINE_CC", "WORLD_PAY", "XENDIT", "ZAAKPAY", "ZONG"}, strArr, 0, 162, 6);
    }

    public static final Set getSet() {
        return A00;
    }
}
