package com.facebook.distribgw.client;

import p000X.AbstractC27914AsI;
import p000X.C0IP;
import p000X.InterfaceC29561Bdl;

/* loaded from: classes2.dex */
public class DGWClientConfig {
    public static final String FB_GATEWAY_DOMAIN = "gateway.facebook.com";
    public static final String WP_GATEWAY_DOMAIN = "gateway.workplace.com";
    public boolean allowRetriableWithConnectivityAwareLayer;
    public final String appId;
    public final String appVersion;
    public final boolean avoidCopyingBuffer;
    public final String certificateRevocationListJSON;
    public final boolean closeConnectionWhenNoRequests;
    public final long closeMnsConnectionThrottlingMs;
    public final boolean closeNetworkConnectionOnTimeout;
    public boolean closeNetworkRequestOnTunnelStreamDestruct;
    public final int connectionTrafficTracingSamplingRate;
    public final ConnectivityManagerOptions connectivityManagerOptions;
    public final String deviceId;
    public final String deviceOS;
    public final boolean disableCancellationForTigonRequests;
    public final boolean disableRetriableLayer;
    public final boolean eagerStreamGroupEnabled;
    public final boolean enableCallingSgErrorOnlyOnceInSgt;
    public final boolean enableCertificateRevocation;
    public final boolean enableEarlyData;
    public final boolean enableEligibilityHashHeader;
    public final boolean enableFetchRegionHintFromWww;
    public final boolean enableHTTP3;
    public final boolean enableHttpVersionCache;
    public final boolean enableLogoutOnAuthFailure;
    public final boolean enableQlog;
    public final boolean enableSeparateHTTPClientForTunnel;
    public final boolean enableStreamGroupLoadShedding;
    public final boolean enableTunnelRetriableLayer;
    public final long evLoopThreadPriority;
    public final DGWFallbackConfig fallbackConfig;
    public final String familyDeviceId;
    public final boolean forceHTTP2ForTunnel;
    public String gatewayDomain;
    public final long h2MaxRequestsPerConnection;
    public final long h2PingIntervalSeconds;
    public final boolean highPriorityEvLoopThread;
    public final boolean isWorkBuild;
    public final boolean keepStreamGroupAliveAfterLastStream;
    public final boolean matchMqttWakeup;
    public final long maxQlogLines;
    public final String mid;
    public boolean msysBufferRequestWhileNoConnectivity;
    public boolean msysNotifyStreamGroupOnPubAckTimeout;
    public int msysStreamGroupTransportSampleRate;
    public int msysStreamLifecycleSampleRate;
    public final long mvfstKeepAliveTimeoutSeconds;
    public final Long mvfstMaximumPTOs;
    public final boolean mvfstUseHandshakeTimeout;
    public final boolean mvfstUseUDPSocketConnect;
    public final DGWPersonalizationConfig personalizationConfig;
    public final boolean preferIPv6ForBothTCPAndQUIC;
    public final long qlogSamplingRate;
    public final long quicIdleTimeoutSec;
    public final long quicKeepaliveTimeoutSec;
    public final String quicKnobs;
    public final boolean quicUseMvfstMobileLibrary;
    public final long regionHintCacheTtlHours;
    public final boolean removeAsyncExecutorFromTunnelNetworkCallbacks;
    public final int requestCompressionLevel;
    public final String responseCompression;
    public final int responseCompressionLevel;
    public final DGWStreamGroupRetryableLayerConfig retryableLayerConfig;
    public final long secureTcpReadTimeoutSec;
    public final long secureTcpWriteTimeoutSec;
    public final boolean sendHeadersImmediately;
    public final long streamGroupPingPeriod;
    public final long streamGroupPingTimeout;
    public final long streamGroupStopBgPingDelay;
    public final int streamGroupTrafficTracingSamplingRate;
    public final long streamIdleTimeoutMs;
    public final boolean subscribeSgPingertoAppStatusCallbacks;
    public final long tcpConnectTimeoutSec;
    public final long tcpDelayMs;
    public final boolean triggerMsysHighSignalSyncOnAllConnections;
    public final boolean tunnelConnectAckDisableConnectionClosure;
    public final boolean tunnelDeferReadyStateCleanup;
    public final boolean useCachedStreamGroupsStatus;
    public final boolean useExecutorProxies;
    public final boolean useExecutorProxiesPhaseTwo;
    public boolean useTigon;
    public boolean useTigonInDeprecatedMNSClient;
    public final boolean useTunnelExecutor;
    public final String userAgent;
    public final InterfaceC29561Bdl zeroRatingCachingEnabled;
    public final InterfaceC29561Bdl zeroRatingEnabled;
    public final InterfaceC29561Bdl zeroUrlRewritingV2Enabled;

    public DGWClientConfig(int i, int i2, String str, String str2, String str3, String str4, ConnectivityManagerOptions connectivityManagerOptions, boolean z, String str5, String str6, long j, String str7, int i3, int i4, boolean z2, InterfaceC29561Bdl interfaceC29561Bdl, InterfaceC29561Bdl interfaceC29561Bdl2, InterfaceC29561Bdl interfaceC29561Bdl3, String str8, long j2, long j3, long j4, boolean z3, DGWPersonalizationConfig dGWPersonalizationConfig, DGWStreamGroupRetryableLayerConfig dGWStreamGroupRetryableLayerConfig, boolean z4, boolean z5, boolean z6, long j5, long j6, boolean z7, boolean z8, boolean z9, long j7, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, DGWFallbackConfig dGWFallbackConfig, boolean z15, String str9, boolean z16, boolean z17, int i5, int i6, boolean z18, boolean z19, boolean z20, boolean z21, boolean z22, boolean z23, long j8, long j9, boolean z24, long j10, long j11, long j12, long j13, boolean z25, long j14, long j15, boolean z26, String str10, boolean z27, boolean z28, boolean z29, boolean z30, long j16, boolean z31, boolean z32, boolean z33, boolean z34, long j17, boolean z35, boolean z36, boolean z37, boolean z38, boolean z39, boolean z40, long j18, boolean z41, boolean z42, boolean z43, String str11, long j19) {
        this.streamGroupTrafficTracingSamplingRate = i;
        this.connectionTrafficTracingSamplingRate = i2;
        this.deviceOS = str4;
        this.deviceId = str;
        this.familyDeviceId = str2;
        this.mid = str3;
        this.connectivityManagerOptions = connectivityManagerOptions;
        this.isWorkBuild = z;
        this.appId = str5;
        this.appVersion = str6;
        this.streamIdleTimeoutMs = j;
        this.responseCompression = str7;
        this.requestCompressionLevel = i3;
        this.responseCompressionLevel = i4;
        this.enableHTTP3 = z2;
        this.zeroRatingEnabled = interfaceC29561Bdl;
        this.zeroUrlRewritingV2Enabled = interfaceC29561Bdl2;
        this.zeroRatingCachingEnabled = interfaceC29561Bdl3;
        this.gatewayDomain = str8;
        this.streamGroupPingPeriod = j2;
        this.streamGroupPingTimeout = j3;
        this.streamGroupStopBgPingDelay = j4;
        this.enableStreamGroupLoadShedding = z3;
        this.personalizationConfig = dGWPersonalizationConfig;
        this.retryableLayerConfig = dGWStreamGroupRetryableLayerConfig;
        this.useCachedStreamGroupsStatus = z4;
        this.closeNetworkConnectionOnTimeout = z5;
        this.enableQlog = z6;
        this.qlogSamplingRate = j5;
        this.maxQlogLines = j6;
        this.eagerStreamGroupEnabled = z7;
        this.keepStreamGroupAliveAfterLastStream = z8;
        this.enableFetchRegionHintFromWww = z9;
        this.regionHintCacheTtlHours = j7;
        this.matchMqttWakeup = z10;
        this.enableTunnelRetriableLayer = z11;
        this.useExecutorProxies = z12;
        this.useExecutorProxiesPhaseTwo = z13;
        this.avoidCopyingBuffer = z14;
        this.fallbackConfig = dGWFallbackConfig;
        this.enableEligibilityHashHeader = z15;
        this.userAgent = str9;
        this.removeAsyncExecutorFromTunnelNetworkCallbacks = z16;
        this.enableCallingSgErrorOnlyOnceInSgt = z17;
        this.msysStreamGroupTransportSampleRate = i5;
        this.msysStreamLifecycleSampleRate = i6;
        this.msysNotifyStreamGroupOnPubAckTimeout = z18;
        this.closeNetworkRequestOnTunnelStreamDestruct = z19;
        this.useTigon = z20;
        this.useTigonInDeprecatedMNSClient = z21;
        this.allowRetriableWithConnectivityAwareLayer = z22;
        this.msysBufferRequestWhileNoConnectivity = z23;
        this.quicIdleTimeoutSec = j8;
        this.quicKeepaliveTimeoutSec = j9;
        this.enableEarlyData = z24;
        this.tcpDelayMs = j10;
        this.tcpConnectTimeoutSec = j11;
        this.secureTcpReadTimeoutSec = j12;
        this.secureTcpWriteTimeoutSec = j13;
        this.highPriorityEvLoopThread = z25;
        this.evLoopThreadPriority = j14;
        this.h2PingIntervalSeconds = j15;
        this.enableHttpVersionCache = z26;
        this.quicKnobs = str10;
        this.quicUseMvfstMobileLibrary = z27;
        this.mvfstUseHandshakeTimeout = z28;
        this.preferIPv6ForBothTCPAndQUIC = z29;
        this.closeConnectionWhenNoRequests = z30;
        this.closeMnsConnectionThrottlingMs = j16;
        this.disableRetriableLayer = z31;
        this.disableCancellationForTigonRequests = z32;
        this.subscribeSgPingertoAppStatusCallbacks = z33;
        this.triggerMsysHighSignalSyncOnAllConnections = z34;
        this.h2MaxRequestsPerConnection = j17;
        this.mvfstUseUDPSocketConnect = z35;
        this.enableLogoutOnAuthFailure = z36;
        this.useTunnelExecutor = z37;
        this.tunnelConnectAckDisableConnectionClosure = z38;
        this.tunnelDeferReadyStateCleanup = z39;
        this.sendHeadersImmediately = z40;
        this.mvfstKeepAliveTimeoutSeconds = j18;
        this.enableSeparateHTTPClientForTunnel = z41;
        this.forceHTTP2ForTunnel = z42;
        this.enableCertificateRevocation = z43;
        this.certificateRevocationListJSON = str11;
        this.mvfstMaximumPTOs = Long.valueOf(j19);
    }

    public static C0IP newBuilder() {
        return new C0IP();
    }

    public String getDeviceOS(String str) {
        String str2 = this.deviceOS;
        return str2 == null ? str : str2;
    }

    public DGWFallbackConfig getFallbackConfig() {
        DGWFallbackConfig dGWFallbackConfig = this.fallbackConfig;
        return dGWFallbackConfig == null ? new DGWFallbackConfig(false, "", 0, "") : dGWFallbackConfig;
    }

    public String getGatewayDomain() {
        String str = this.gatewayDomain;
        return str == null ? this.isWorkBuild ? "gateway.workplace.com" : "gateway.facebook.com" : str;
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        AbstractC27914AsI.A0I("{deviceOS:", sb);
        AbstractC27914AsI.A0I(this.deviceOS, sb);
        AbstractC27914AsI.A0I(",isWorkBuild:", sb);
        sb.append(this.isWorkBuild);
        AbstractC27914AsI.A0I(",appVersion:", sb);
        AbstractC27914AsI.A0I(this.appVersion, sb);
        AbstractC27914AsI.A0I(",appId:", sb);
        AbstractC27914AsI.A0I(this.appId, sb);
        AbstractC27914AsI.A0I(",streamIdleTimeoutMs:", sb);
        sb.append(this.streamIdleTimeoutMs);
        AbstractC27914AsI.A0I(",responseCompression:", sb);
        AbstractC27914AsI.A0I(this.responseCompression, sb);
        AbstractC27914AsI.A0I(",enableHTTP3:", sb);
        sb.append(this.enableHTTP3);
        AbstractC27914AsI.A0I(",zeroRatingEnabled:", sb);
        sb.append((Object) false);
        AbstractC27914AsI.A0I(",zeroUrlRewritingV2Enabled:", sb);
        sb.append((Object) false);
        AbstractC27914AsI.A0I(",zeroRatingCachingEnabled:", sb);
        sb.append((Object) false);
        AbstractC27914AsI.A0I(",gatewayDomain:", sb);
        AbstractC27914AsI.A0I(this.gatewayDomain, sb);
        AbstractC27914AsI.A0I(",streamGroupPingPeriod:", sb);
        sb.append(this.streamGroupPingPeriod);
        AbstractC27914AsI.A0I(",streamGroupPingTimeout:", sb);
        sb.append(this.streamGroupPingTimeout);
        AbstractC27914AsI.A0I(",streamGroupStopBgPingDelay:", sb);
        sb.append(this.streamGroupStopBgPingDelay);
        AbstractC27914AsI.A0I(",useCachedStreamGroupsStatus:", sb);
        sb.append(this.useCachedStreamGroupsStatus);
        AbstractC27914AsI.A0I(",closeNetworkConnectionOnTimeout:", sb);
        sb.append(this.closeNetworkConnectionOnTimeout);
        AbstractC27914AsI.A0I(",connectivityManagerOptions:", sb);
        sb.append(this.connectivityManagerOptions);
        AbstractC27914AsI.A0I(",personalizationConfig:", sb);
        sb.append(this.personalizationConfig);
        AbstractC27914AsI.A0I(",eagerStreamGroupEnabled:", sb);
        sb.append(this.eagerStreamGroupEnabled);
        AbstractC27914AsI.A0I(",keepStreamGroupAliveAfterLastStream:", sb);
        sb.append(this.keepStreamGroupAliveAfterLastStream);
        AbstractC27914AsI.A0I(",enableFetchRegionHintFromWww:", sb);
        sb.append(this.enableFetchRegionHintFromWww);
        AbstractC27914AsI.A0I(",regionHintCacheTtlHours:", sb);
        sb.append(this.regionHintCacheTtlHours);
        AbstractC27914AsI.A0I(",matchMqttWakeup:", sb);
        sb.append(this.matchMqttWakeup);
        AbstractC27914AsI.A0I(",enableTunnelRetriableLayer:", sb);
        sb.append(this.enableTunnelRetriableLayer);
        AbstractC27914AsI.A0I(",useExecutorProxies:", sb);
        sb.append(this.useExecutorProxies);
        AbstractC27914AsI.A0I(",useExecutorProxiesPhaseTwo:", sb);
        sb.append(this.useExecutorProxiesPhaseTwo);
        AbstractC27914AsI.A0I(",avoidCopyingBuffer:", sb);
        sb.append(this.avoidCopyingBuffer);
        AbstractC27914AsI.A0I(",fallbackConfig:", sb);
        sb.append(this.fallbackConfig);
        AbstractC27914AsI.A0I(",retryableLayerConfig:", sb);
        sb.append(this.retryableLayerConfig);
        AbstractC27914AsI.A0I(",enableEligibilityHashHeader:", sb);
        sb.append(this.enableEligibilityHashHeader);
        AbstractC27914AsI.A0I(",userAgent:", sb);
        AbstractC27914AsI.A0I(this.userAgent, sb);
        AbstractC27914AsI.A0I(",removeAsyncExecutorFromTunnelNetworkCallbacks:", sb);
        sb.append(this.removeAsyncExecutorFromTunnelNetworkCallbacks);
        AbstractC27914AsI.A0I(",enableCallingSgErrorOnlyOnceInSgt:", sb);
        sb.append(this.enableCallingSgErrorOnlyOnceInSgt);
        AbstractC27914AsI.A0I(",msysStreamGroupTransportSampleRate:", sb);
        sb.append(this.msysStreamGroupTransportSampleRate);
        AbstractC27914AsI.A0I(",msysStreamLifecycleSampleRate:", sb);
        sb.append(this.msysStreamLifecycleSampleRate);
        AbstractC27914AsI.A0I(",msysNotifyStreamGroupOnPubAckTimeout:", sb);
        sb.append(this.msysNotifyStreamGroupOnPubAckTimeout);
        AbstractC27914AsI.A0I(",closeNetworkRequestOnTunnelStreamDestruct:", sb);
        sb.append(this.closeNetworkRequestOnTunnelStreamDestruct);
        AbstractC27914AsI.A0I(",useTigon:", sb);
        sb.append(this.useTigon);
        AbstractC27914AsI.A0I(",useTigonInDeprecatedMNSClient:", sb);
        sb.append(this.useTigonInDeprecatedMNSClient);
        AbstractC27914AsI.A0I(",allowRetriableWithConnectivityAwareLayer:", sb);
        sb.append(this.allowRetriableWithConnectivityAwareLayer);
        AbstractC27914AsI.A0I(",msysBufferRequestWhileNoConnectivity:", sb);
        sb.append(this.msysBufferRequestWhileNoConnectivity);
        AbstractC27914AsI.A0I(", disableRetriableLayer:", sb);
        sb.append(this.disableRetriableLayer);
        AbstractC27914AsI.A0I(", disableCancellationForTigonRequests:", sb);
        sb.append(this.disableCancellationForTigonRequests);
        AbstractC27914AsI.A0I(", subscribeSgPingertoAppStatusCallbacks:", sb);
        sb.append(this.subscribeSgPingertoAppStatusCallbacks);
        AbstractC27914AsI.A0I(", triggerMsysHighSignalSyncOnAllConnections:", sb);
        sb.append(this.triggerMsysHighSignalSyncOnAllConnections);
        AbstractC27914AsI.A0I(", h2MaxRequestsPerConnection:", sb);
        sb.append(this.h2MaxRequestsPerConnection);
        AbstractC27914AsI.A0I(", mvfstUseUDPSocketConnect:", sb);
        sb.append(this.mvfstUseUDPSocketConnect);
        AbstractC27914AsI.A0I(", enableLogoutOnAuthFailure:", sb);
        sb.append(this.enableLogoutOnAuthFailure);
        AbstractC27914AsI.A0I(", useTunnelExecutor:", sb);
        sb.append(this.useTunnelExecutor);
        AbstractC27914AsI.A0I(", tunnelConnectAckDisableConnectionClosure:", sb);
        sb.append(this.tunnelConnectAckDisableConnectionClosure);
        AbstractC27914AsI.A0I(", mvfstKeepAliveTimeoutSeconds:", sb);
        sb.append(this.mvfstKeepAliveTimeoutSeconds);
        AbstractC27914AsI.A0I(", enableSeparateHTTPClientForTunnel:", sb);
        sb.append(this.enableSeparateHTTPClientForTunnel);
        AbstractC27914AsI.A0I(", forceHTTP2ForTunnel:", sb);
        sb.append(this.forceHTTP2ForTunnel);
        AbstractC27914AsI.A0I(", enableCertificateRevocation:", sb);
        sb.append(this.enableCertificateRevocation);
        AbstractC27914AsI.A0I(", certificateRevocationListJSON:", sb);
        AbstractC27914AsI.A0I(this.certificateRevocationListJSON, sb);
        AbstractC27914AsI.A0I(", mvfstMaximumPTOs", sb);
        sb.append(this.mvfstMaximumPTOs);
        AbstractC27914AsI.A0I("}", sb);
        return sb.toString();
    }
}
